🗃️ Committing everything that changed 🗃️
bin/acme-cli

diff --git a/bin/acme-cli b/bin/acme-cli
--- a/bin/acme-cli
+++ b/bin/acme-cli
@@ -347,6 +347,7 @@ __certbot_test() {
   retVal=$?
   if [ $retVal -ne 0 ]; then
     printf_red "Log saved to /var/log/letsencrypt/letsencrypt.log"
+    ACME_CLI_EXIT_STATUS=$((ACME_CLI_EXIT_STATUS + retVal))
   fi
   return $retval
 }
@@ -358,6 +359,7 @@ __certbot_renew() {
   retVal=$?
   if [ $retVal -ne 0 ]; then
     printf_red "Log saved to /var/log/letsencrypt/letsencrypt.log"
+    ACME_CLI_EXIT_STATUS=$((ACME_CLI_EXIT_STATUS + retVal))
   fi
   return $retval
 }
@@ -369,6 +371,7 @@ __certbot_new() {
   retVal=$?
   if [ $retVal -ne 0 ]; then
     printf_red "Log saved to /var/log/letsencrypt/letsencrypt.log"
+    ACME_CLI_EXIT_STATUS=$((ACME_CLI_EXIT_STATUS + retVal))
   fi
   return $retval
 }
@@ -429,6 +432,8 @@ __reload_services() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __update_certs() {
   local ip
+  local retVal=0
+  local prevExit=${1:-0}
   [ "$ACME_CLI_RYSNC" = "false" ] && printf '%s\n' "rsync is disabled" >&2 && return ${1:-2}
   [ -z "$ACME_CLI_UPDATE_CERTS_IPS" ] && printf '%s\n' "ACME_CLI_UPDATE_CERTS_IPS var is unset" >&2 && return 1
   printf '%s\n' "Attempting to copy the certs to your other servers via rsync"
@@ -445,13 +450,16 @@ __update_certs() {
         for service in $ACME_CLI_SERVICE_RESTART; do
           printf '%s' "Restarting $service on $ip"
           ssh -t -q root@$ip -p $port "systemctl restart $service" >/dev/null
-          [ $? = 0 ] && printf ': %s\n' 'OK' || printf ': %s\n' "Failed"
+          retVal=$?
+          prevExit=$((prevExit + retVal))
+          [ $retVal = 0 ] && printf ': %s\n' 'OK' || printf ': %s\n' "Failed"
         done
       else
         printf '%s\n' "The IP matches dns server"
       fi
     fi
   done
+  return $prevExit
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __gen_dns_conf() {
@@ -773,9 +781,9 @@ renew)
   __gen_config &>/dev/null
   __generate_domain_list
   __certbot_renew
-  __reload_services
-  __update_certs 0
-  exit $?
+  __reload_services $ACME_CLI_EXIT_STATUS
+  __update_certs $ACME_CLI_EXIT_STATUS
+  exit $ACME_CLI_EXIT_STATUS
   ;;
 *)
   [ "$1" = "new" ] && shift 1
@@ -784,9 +792,9 @@ renew)
   __gen_config &>/dev/null
   __generate_domain_list
   __certbot_new
-  __reload_services
-  __update_certs
-  exit $?
+  __reload_services $ACME_CLI_EXIT_STATUS
+  __update_certs $ACME_CLI_EXIT_STATUS
+  exit $ACME_CLI_EXIT_STATUS
   ;;
 esac
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
