🗃️ Committing everything that changed 🗃️
bin/acme-cli

diff --git a/bin/acme-cli b/bin/acme-cli
--- a/bin/acme-cli
+++ b/bin/acme-cli
@@ -433,6 +433,7 @@ __reload_services() {
 __update_certs() {
   local ip
   local retVal=0
+  local preVal=0
   local prevExit=${1:-0}
   if [ $prevExit -ne 0 ]; then
     ACME_CLI_EXIT_STATUS=$prevExit
@@ -448,16 +449,18 @@ __update_certs() {
       if [ "$ip" != "$ACME_CLI_PRIMARY_DNS_IP" ]; then
         ssh -q -l root -p $port $ip 'exit' && echo "connection to $ip successfully made..."
         printf '%s%s' "Sending files to $ip:$port" " "
-        timeout 30 ssh -t root@$ip -p $port "mkdir -p /etc/letsencrypt"
-        timeout 30 rsync -qavhP -e "ssh -p $port" /etc/letsencrypt/* root@$ip:/etc/letsencrypt/ --delete &>/dev/null
-        [ $? -eq 0 ] && printf '%s\n' "has completed" || printf '%s\n' "has failed" >&2
-        for service in $ACME_CLI_SERVICE_RESTART; do
-          printf '%s' "Restarting $service on $ip"
-          ssh -t -q root@$ip -p $port "systemctl restart $service" >/dev/null
-          retVal=$?
-          prevExit=$((prevExit + retVal))
-          [ $retVal = 0 ] && printf ': %s\n' 'OK' || printf ': %s\n' "Failed"
-        done
+        timeout 30 ssh -t root@$ip -p $port "mkdir -p /etc/letsencrypt" && timeout 30 rsync -qavhP -e "ssh -p $port" /etc/letsencrypt/* root@$ip:/etc/letsencrypt/ --delete &>/dev/null
+        preVal=$?
+        if [ $preVal -eq 0 ]; then
+          printf '%s\n' "has completed" || printf '%s\n' "has failed" >&2
+          for service in $ACME_CLI_SERVICE_RESTART; do
+            printf '%s' "Restarting $service on $ip"
+            ssh -t -q root@$ip -p $port "systemctl restart $service" >/dev/null
+            retVal=$?
+            prevExit=$((prevExit + retVal))
+            [ $retVal = 0 ] && printf ': %s\n' 'OK' || printf ': %s\n' "Failed"
+          done
+        fi
       else
         printf '%s\n' "The IP matches dns server"
       fi
