🐛 FIXED: bin/ask_for_password 🐛

diff --git a/bin/ask_for_password b/bin/ask_for_password
--- a/bin/ask_for_password
+++ b/bin/ask_for_password
@@ -65,55 +65,65 @@ EOF
     false
   fi
 }
-
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __set_pass() {
-  PASS_WORD="${PASS_WORD:-}"
   __ask_pass
-  sudo -kSp ' ' true <<<$PASS_WORD 2>&1 | grep -vq 'try again' &>/dev/null && return 0 || return 1
+  sudo -kSp ' ' true <<<$PASS_WORD 2>&1 | grep -vq 'try again' &>/dev/null && return 1 || { PASS_WORD="" && return 0; }
 }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __get_pass() {
-  local retries=3
+  local retries=2
   local exitCode=1
   local SHELL=/bin/bash
-  local PASS_APP="" PASS_WORD="" SUDO_PROMPT="" SUDO_ASKPASS=""
+  local PASS_APP=""
+  PASS_WORD="Not Set"
+  SUDO_PROMPT=""
+  SUDO_ASKPASS=""
+  # Check if password is needed
   if ! builtin command sudo -n true &>/dev/null; then
+    # Check for displays
     if [ -n "$DISPLAY" ] && [ -z "$SSH_CONNECT" ]; then
+      # command check and set ask_pass
       if cmd_exists zenity; then
         PASS_APP="zenity"
-        __ask_pass() { export PASS_WORD="$(zenity --password --title="Please enter your password: " --timeout=20 2>/dev/null)"; }
+        __ask_pass() { PASS_WORD="$(zenity --password --title="Please enter your password: " --timeout=20 2>/dev/null)"; }
       elif cmd_exists kdialog; then
         PASS_APP="kdialog"
-        __ask_pass() { export PASS_WORD="$(kdialog --password "Please enter your password: " 2>/dev/null)"; }
+        __ask_pass() { PASS_WORD="$(kdialog --password "Please enter your password: " 2>/dev/null)"; }
       elif cmd_exists rofi; then
         PASS_APP="rofi"
-        __ask_pass() { export PASS_WORD="$(rofi -theme /home/jason/.config/rofi/themes/purple.rasi -dmenu -password -i -no-fixed-num-lines -p "Please enter your password: " 2>/dev/null)"; }
+        __ask_pass() { PASS_WORD="$(rofi -theme /home/jason/.config/rofi/themes/purple.rasi -dmenu -password -i -no-fixed-num-lines -p "Please enter your password: " 2>/dev/null)"; }
       elif cmd_exists dmenupass; then
         PASS_APP="dmenupass"
-        __ask_pass() { export PASS_WORD="$(dmenupass "Please enter your password: " 2>/dev/null)"; }
+        __ask_pass() { PASS_WORD="$(dmenupass "Please enter your password: " 2>/dev/null)"; }
       elif cmd_exists gksudo; then
         PASS_APP="gksudo"
-        __ask_pass() { export PASS_WORD="$(gksudo --print-pass --message "Please enter your password: " 2>/dev/null)"; }
+        __ask_pass() { PASS_WORD="$(gksudo --print-pass --message "Please enter your password: " 2>/dev/null)"; }
       elif [ $(uname -s) = MacOS ]; then
         PASS_APP="osascript"
-        __ask_pass() { export PASS_WORD="$(osascript -e 'Tell application "System Events" to display dialog "Please enter your password: " default answer ""' -e 'text returned of result' 2>/dev/null)"; }
+        __ask_pass() { PASS_WORD="$(osascript -e 'Tell application "System Events" to display dialog "Please enter your password: " default answer ""' -e 'text returned of result' 2>/dev/null)"; }
       else
         PASS_APP="terminal"
-        __ask_pass() { export SUDO_PROMPT="$(printf "\t\t\033[1;31m")[sudo]$(printf "\033[1;36m") password for $(printf "\033[1;32m")%p: $(printf "\033[0m")"; }
+        __ask_pass() { SUDO_PROMPT="$(printf "\t\t\033[1;31m")[sudo]$(printf "\033[1;36m") password for $(printf "\033[1;32m")%p: $(printf "\033[0m")"; }
       fi
+      # If no display
     else
       PASS_APP="terminal"
-      __ask_pass() { export SUDO_PROMPT="$(printf "\t\t\033[1;31m")[sudo]$(printf "\033[1;36m") password for $(printf "\033[1;32m")%p: $(printf "\033[0m")"; }
+      __ask_pass() { SUDO_PROMPT="$(printf "\t\t\033[1;31m")[sudo]$(printf "\033[1;36m") password for $(printf "\033[1;32m")%p: $(printf "\033[0m")"; }
     fi
+    # trye to get the password
     __notifications "Attempting to get password from $PASS_APP"
-    __set_pass
-    if [ -n "$PASS_APP" ] && [ -n "$PASS_WORD" ]; then
+    __set_pass && true || false
+    # Sanity check
+    if [ -n "$PASS_APP" ]; then
+      # Debugger
       if [ -n "$DEBUGGER" ]; then
         __notifications "Retrieved password for $SUDO_USER"
         printf_green "With password helper being $PASS_APP"
       fi
-      retries="${retries:-3}"
-      while [[ $retries -lt 3 ]] && [[ "$PASS_WORD" != "true" ]]; do
-        PASS_WORD=""
+      # If password fails retry 2 more times
+      retries="${retries:-2}"
+      while [[ $retries -lt 2 ]] && [[ -n "$PASS_WORD" ]]; do
         if __ask_pass; then
           exitCode=0
           break
@@ -123,15 +133,18 @@ __get_pass() {
         fi
         ((retries++))
       done
+      # Error was encountered
     else
       message="No password seems to be present. Did you cancel?"
       printf_red "No password seems to be present. Did you cancel?"
       exitCode=1
     fi
+    # sudo says no password needed
   else
     mesage="Your password seems to be cached"
     exitCode=0
   fi
+  # Clean up
   sleep 1
   unset PASS_APP PASS_WORD
   return ${exitCode:-$?}
