🗃️  Committing everything that changed 🗃️
bin/buildx

diff --git a/bin/buildx b/bin/buildx
--- a/bin/buildx
+++ b/bin/buildx
@@ -539,7 +539,6 @@ __is_buildx_installed() {
   local buildx_installed=""
   buildx_installed="$(__docker_init buildx ls 2>&1 | grep -A3 'NAME/NODE' | grep 'running.*[0-9] ' | grep -q '^' && echo 'yes' || echo 'no')"
   if [ "$buildx_installed" = "yes" ]; then
-    export BUILDX_INSTALLED="yes"
     return 0
   else
     export BUILDX_INSTALLED="no"
@@ -644,7 +643,7 @@ __reinit_buildx() {
   name="${name:-init}"
   local force_install="${BUILDX_FORCE:-$BUILDX_FORCE_REINSTALL}"
   __buildx_vars "${BUILDX_BUILDER_NAME:-}"
-  [ "$BUILDX_INSTALLED" != "yes" ] || [ "$BUILDX_INIT_RAN" != "true" ] || return 0
+  ! __is_buildx_installed || [ "$BUILDX_INIT_RAN" != "true" ] || return 0
   [ "$force_install" = "yes" ] || [ -z "$builder_id" ] || [ -z "$binfmt_id" ] || [ -z "$qemu_id" ] || return 0
   printf_cyan "Reinitializing buildx $name on $(date)"
   echo "Reinitializing buildx $name on $(date)" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
@@ -659,7 +658,7 @@ __reinit_buildx() {
   __docker_init buildx inspect --bootstrap |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
   __buildx_vars "${BUILDX_BUILDER_NAME:-}"
   __create_update_docker_daemon_config
-  [ -n "$builder_id" ] && BUILDX_INSTALLED="yes" && BUILDX_FORCE_REINSTALL="" BUILDX_FORCE="" BUILDX_INIT_RAN="true" || { echo "Initializing of buildx failed" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null && printf_yellow "Initializing of buildx failed"; }
+  [ -n "$builder_id" ] && __is_buildx_installed && BUILDX_FORCE_REINSTALL="" BUILDX_FORCE="" BUILDX_INIT_RAN="true" || { echo "Initializing of buildx failed" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null && printf_yellow "Initializing of buildx failed"; }
   return 0
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -988,7 +987,7 @@ __build_cmd() {
     BUILDX_IS_RUNNING="true"
     echo "$BUILDX_PID_NUMBER" >"$BUILDX_PID_FILE"
   fi
-  if [ "$BUILDX_INSTALLED" = "false" ]; then
+  if [ "$BUILDX_INSTALLED" = "no" ]; then
     printf_yellow "💔 buildx is not installed - Using 'docker build' instead. 💔"
   fi
   __run_docker_build
@@ -1510,9 +1509,9 @@ export DOCKER_CLI_EXPERIMENTAL="$BUILDX_DOCKER_CLI_EXPERIMENTAL"
 [ -n "$BUILDX_SET_REPO" ] && export BUILDX_SET_REPO BUILDX_DEFAULT_REPO="$BUILDX_SET_REPO"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Actions based on env
-__create_log_files
 __is_docker_installed
-__is_buildx_installed && BUILDX_INSTALLED="yes"
+__is_buildx_installed
+__create_log_files
 [ -f "$BUILDX_PID_FILE" ] && BUILDX_CLEANUP=""
 [ "$1" = "init" ] || [ -d "$HOME/.docker/buildx" ] || __buildx_init
 [ -d "$HOME/.local/run/$APPNAME" ] || mkdir -p "$HOME/.local/run/$APPNAME"
