🗃️ Committing everything that changed 🗃️
bin/buildx

diff --git a/bin/buildx b/bin/buildx
--- a/bin/buildx
+++ b/bin/buildx
@@ -580,7 +580,7 @@ __buildx_run() {
   __reinit_buildx
   __run_git_pull "$BUILDX_CWD"
   if [ $# -ne 0 ]; then
-    __execute_buildx "$@"
+    __execute_buildx "$i"
     exitCode=$?
   elif [ -f "$BUILDX_CWD/Dockerfile" ]; then
     __execute_buildx "$BUILDX_CWD/Dockerfile"
@@ -612,7 +612,8 @@ __wait_for_previous_build() {
     done
     [ -f "$BUILDX_PID_FILE" ] && rm -Rf "$BUILDX_PID_FILE"
     buildx init &>/dev/null
-    BUILDX_CLEANUP="false"
+    #BUILDX_CLEANUP="false"
+    sleep 60
   fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -1794,10 +1795,20 @@ run)
 
 build)
   shift 1
-  __buildx_run "$@"
+  runAllCode=0
+  for i in "${@:-BUILDX_CWD}"; do
+    __buildx_run "$i"
+    runAllCode=$(($? + $runAllCode))
+  done
+  exitCode="$runAllCode"
   ;;
 *)
-  __buildx_run "$@"
+  runAllCode=0
+  for i in "${@:-BUILDX_CWD}"; do
+    __buildx_run "$i"
+    runAllCode=$(($? + $runAllCode))
+  done
+  exitCode="$runAllCode"
   ;;
 esac
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
