🗃️ Committing everything that changed 🗃️
bin/buildx
completions/_buildx_completions

diff --git a/bin/buildx b/bin/buildx
--- a/bin/buildx
+++ b/bin/buildx
@@ -1302,19 +1302,21 @@ __execute_buildx() {
   if __build_cmd "$FULL_DIR_PATH"; then
     notify_message+="Successfully built $set_tag $ADDITIONAL_PRETTY|"
     printf_green "Successfully built container: $set_tag $ADDITIONAL_PRETTY"
-    printf '%b: ' "$(printf_green "Pulling the updated image")"
-    if __docker pull "$push_tag" &>/dev/null; then
-      printf_green "Successfully pulled $push_tag"
-      notify_message+="Successfully pulled $push_tag|"
-      printf '\n%s\n' "# Successfully pulled $push_tag on : $(date +'%Y-%m-%d at %H:%M')" | tee -p -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-      __docker rmi "$push_tag" &>/dev/null
-      __docker rmi "$pretty_name" &>/dev/null
-      buildxexitCode=1
-    else
-      printf_red "Failed to pull $push_tag" >&2
-      notify_message+="Failed to pull $push_tag|"
-      printf '\n%s\n' "# Failed to pull $push_tag on : $(date +'%Y-%m-%d at %H:%M')" | tee -p -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-      buildxexitCode=2
+    if [ "$BUILDX_NO_PULL" != "no" ]; then
+      printf '%b: ' "$(printf_green "Pulling the updated image")"
+      if __docker pull "$push_tag" &>/dev/null; then
+        printf_green "Successfully pulled $push_tag"
+        notify_message+="Successfully pulled $push_tag|"
+        printf '\n%s\n' "# Successfully pulled $push_tag on : $(date +'%Y-%m-%d at %H:%M')" | tee -p -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+        __docker rmi "$push_tag" &>/dev/null
+        __docker rmi "$pretty_name" &>/dev/null
+        buildxexitCode=1
+      else
+        printf_red "Failed to pull $push_tag" >&2
+        notify_message+="Failed to pull $push_tag|"
+        printf '\n%s\n' "# Failed to pull $push_tag on : $(date +'%Y-%m-%d at %H:%M')" | tee -p -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+        buildxexitCode=2
+      fi
     fi
   else
     printf_red "Failed to build $name" >&2
@@ -1532,7 +1534,7 @@ SETARGS=("$@")
 SHORTOPTS=""
 SHORTOPTS+=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-LONGOPTS="completions:,config,debug,dir:,help,options,raw,version,silent"
+LONGOPTS="completions:,config,debug,dir:,help,options,raw,version,silent,no-pull"
 LONGOPTS+=",force,cleanup,add-registry:,repo:,no-registry,no-repo,cron,platform:"
 LONGOPTS+=",gen-script,tag:,add-tag:,all,build,url:,script,init,user:,image:,registry:"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -1726,6 +1728,10 @@ while :; do
   --registry)
     BUILDX_SET_REGISTRY="$2"
     shift 2
+    ;;
+  --no-pull)
+    shift 1
+    BUILDX_NO_PULL="true"
     ;;
   --)
     shift 1
