🗃️ Committing everything that changed 🗃️

diff --git a/bin/buildx b/bin/buildx
--- a/bin/buildx
+++ b/bin/buildx
@@ -351,10 +351,12 @@ __get_dockerfile_ver() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __buildx_run() {
   if [ $# -ne 0 ]; then
-    __reinit_buildx && __execute_buildx "$@"
+    __reinit_buildx
+    __execute_buildx "$@"
     exitCode=$?
   elif [ -f "$BUILDX_CWD/Dockerfile" ]; then
-    __reinit_buildx && __execute_buildx "$BUILDX_CWD/Dockerfile"
+    __reinit_buildx
+    __execute_buildx "$BUILDX_CWD/Dockerfile"
     exitCode=$?
   else
     printf_red "Can not find a Dockerfile in ${BUILDX_CWD}"
@@ -471,10 +473,10 @@ __builder_init() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __reinit_buildx() {
   [ "$BUILDX_INIT_RAN" = "true" ] && return
-  [ "$BUILDX_FORCE_REINSTALL" = "yes" ] || __is_buildx_installed || return 0
-  local force="${BUILDX_FORCE_REINSTALL:-$BUILDX_CLEAN_FORCE}"
+  [ "$BUILDX_FORCE_REINSTALL" = "yes" ] || __is_buildx_installed || return 1
   printf_cyan "Reinitializing buildx $name on $(date)"
   echo "Reinitializing buildx $name on $(date)" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+  local force="${BUILDX_FORCE_REINSTALL:-$BUILDX_CLEAN_FORCE}"
   [ "$force" = "true" ] || __docker_init rm -f $builder_id |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
   [ "$force" = "true" ] || __docker_init rm -f "$qemu_imagename" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
   [ "$force" = "true" ] || __docker_init rm -f "$binfmt_imagename" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
@@ -483,7 +485,7 @@ __reinit_buildx() {
   __docker_init buildx create --driver docker-container --driver-opt network=host --driver-opt image=moby/buildkit:master --name ${name:-mybuilder} --use |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
   __docker_init buildx use "$name" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
   __docker_init buildx inspect --bootstrap |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
-  __is_initialized && BUILDX_INSTALLED="true" && BUILDX_FORCE_REINSTALL="" BUILDX_FORCE="" BUILDX_INIT_RAN="true"
+  __is_initialized && BUILDX_INSTALLED="true" && BUILDX_FORCE_REINSTALL="" BUILDX_FORCE="" BUILDX_INIT_RAN="true" || { echo "Initializing of buildx failed" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null && printf_yellow "Initializing of buildx failed"; }
   return 0
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -1286,7 +1288,7 @@ __is_docker_installed
 [ -d "$HOME/.docker/buildx" ] || [ "$1" = "init" ] || __buildx_init
 [ -d "$HOME/.local/run/$APPNAME" ] || mkdir -p "$HOME/.local/run/$APPNAME"
 [ -d "$BUILDX_CONFIG_DIR/scripts" ] && mkdir -p "$BUILDX_CONFIG_DIR/scripts"
-__is_buildx_installed && { __reinit_buildx && BUILDX_INSTALLED="true"; } || BUILDX_INSTALLED="false"
+__reinit_buildx && BUILDX_INSTALLED="true" || BUILDX_INSTALLED="false"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # begin main app
 case "$1" in
