🗃️ Committing everything that changed 🗃️
bin/buildx
.claude/settings.local.json
version.txt

diff --git a/bin/buildx b/bin/buildx
--- a/bin/buildx
+++ b/bin/buildx
@@ -513,11 +513,11 @@ __create_update_docker_daemon_config() {
     __sudo true
     sudo mkdir -p "/etc/docker"
     if [ ! -f "/etc/docker/daemon.json" ]; then
-      printf '{\n  %s\n}' "\"experimental\": true" | sudo tee-a "/etc/docker/daemon.json" &>/dev/null
+      printf '{\n  %s\n}' "\"experimental\": true" | sudo tee -a "/etc/docker/daemon.json" &>/dev/null
     elif grep -shq "experimental" "/etc/docker/daemon.json"; then
       sudo sed -i 's|experimental.*e|experimental": true|g' "/etc/docker/daemon.json"
     else
-      echo "{\"experimental\": true}," | sudo tee-a "/etc/docker/daemon.json" &>/dev/null
+      echo "{\"experimental\": true}," | sudo tee -a "/etc/docker/daemon.json" &>/dev/null
     fi
   fi
 }
@@ -912,9 +912,9 @@ __docker_init() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __docker_push() {
-  __docker push "$tagged_name" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null ||
-    __docker push "$tagged_name" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null ||
-    __docker push "$tagged_name" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null && true
+  __docker push "$tagged_name" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null ||
+    __docker push "$tagged_name" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null ||
+    __docker push "$tagged_name" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null && true
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -976,16 +976,16 @@ __reinit_buildx() {
   [ "$BUILDX_INIT_RAN" != "true" ] || return 0
   [ "$force_install" = "yes" ] || [ -z "$builder_id" ] || [ -z "$binfmt_id" ] || [ -z "$qemu_id" ] || return 0
   printf_cyan "Reinitializing buildx: $BUILDX_BUILDER_NAME on: $(date)"
-  echo "Reinitializing buildx: $BUILDX_BUILDER_NAME on: $(date)" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  echo "Reinitializing buildx: $BUILDX_BUILDER_NAME on: $(date)" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
   local force="${force_install:-$BUILDX_CLEAN_FORCE}"
-  [ -z "$builder_id" ] || __docker_init rm -f --volumes $builder_id |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-  [ -z "$binfmt_id" ] || __docker_init rm -f --volumes "$qemu_imagename" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-  [ -z "$qemu_id" ] || __docker_init rm -f --volumes "$binfmt_imagename" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-  __docker_init run -d --name "$qemu_imagename" --privileged multiarch/qemu-user-static --reset -p yes --credential yes |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-  __docker_init run -d --name "$binfmt_imagename" --privileged tonistiigi/binfmt --install all |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-  __docker_init buildx create --driver docker-container --driver-opt network=host --driver-opt image=moby/buildkit:master --name ${BUILDX_BUILDER_NAME:-mybuilder} --use |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-  __docker_init buildx use "$BUILDX_BUILDER_NAME" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-  __docker_init buildx inspect --bootstrap |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  [ -z "$builder_id" ] || __docker_init rm -f --volumes $builder_id |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  [ -z "$binfmt_id" ] || __docker_init rm -f --volumes "$qemu_imagename" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  [ -z "$qemu_id" ] || __docker_init rm -f --volumes "$binfmt_imagename" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  __docker_init run -d --name "$qemu_imagename" --privileged multiarch/qemu-user-static --reset -p yes --credential yes |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  __docker_init run -d --name "$binfmt_imagename" --privileged tonistiigi/binfmt --install all |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  __docker_init buildx create --driver docker-container --driver-opt network=host --driver-opt image=moby/buildkit:master --name ${BUILDX_BUILDER_NAME:-mybuilder} --use |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  __docker_init buildx use "$BUILDX_BUILDER_NAME" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  __docker_init buildx inspect --bootstrap |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
   __buildx_vars "${BUILDX_BUILDER_NAME:-}"
   __create_update_docker_daemon_config
   if [ -n "$builder_id" ] && __is_buildx_installed; then
@@ -993,10 +993,10 @@ __reinit_buildx() {
     BUILDX_INIT_RAN="true"
     BUILDX_FORCE_REINSTALL=""
     printf_cyan "Building for platforms: $BUILDX_DOCKER_PLATFORMS"
-    printf '%s\n' " # Building for platforms: $BUILDX_DOCKER_PLATFORMS" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+    printf '%s\n' " # Building for platforms: $BUILDX_DOCKER_PLATFORMS" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
     return 0
   else
-    echo "Initializing of buildx failed" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+    echo "Initializing of buildx failed" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
     printf_yellow "Initializing of buildx failed"
     return 1
   fi
@@ -1076,23 +1076,23 @@ __buildx_init() {
     printf_cyan "Setting logfile to: $buildx_log_file"
     if [ "$BUILDX_CLEANUP" = "true" ] || { [ -n "$binfmt_id" ] && [ -n "$qemu_id" ]; }; then
       printf_yellow "Removing old containers: $qemu_imagename,$binfmt_imagename"
-      __docker_init rm -f --volumes "$qemu_imagename" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-      __docker_init rm -f --volumes "$binfmt_imagename" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+      __docker_init rm -f --volumes "$qemu_imagename" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+      __docker_init rm -f --volumes "$binfmt_imagename" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
     fi
     __install_buildx
     if [ "$(uname -m)" = "x86_64" ]; then
       # Setup qemu
       printf_yellow "Setting up the qemu image - multiarch/qemu-user-static as $qemu_imagename"
-      __docker_init run -d --name "$qemu_imagename" --privileged multiarch/qemu-user-static --reset -p yes --credential yes |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+      __docker_init run -d --name "$qemu_imagename" --privileged multiarch/qemu-user-static --reset -p yes --credential yes |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
       # Setup binfmt
       printf_yellow "Setting up the binfmt image - tonistiigi/binfmt as $binfmt_imagename"
-      __docker_init run -d --name "$binfmt_imagename" --privileged tonistiigi/binfmt --install all |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+      __docker_init run -d --name "$binfmt_imagename" --privileged tonistiigi/binfmt --install all |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
       # setup buildx
       printf_blue "Setting up docker build to use buildx"
-      #__docker_init buildx create --buildkitd-flags '--allow-insecure-entitlement security.insecure' --name "$name" --use |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-      __docker_init buildx create --driver docker-container --driver-opt network=host --driver-opt image=moby/buildkit:master --name ${name:-mybuilder} --use |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-      __docker_init buildx use "$name" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-      __docker_init buildx inspect --bootstrap |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+      #__docker_init buildx create --buildkitd-flags '--allow-insecure-entitlement security.insecure' --name "$name" --use |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+      __docker_init buildx create --driver docker-container --driver-opt network=host --driver-opt image=moby/buildkit:master --name ${name:-mybuilder} --use |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+      __docker_init buildx use "$name" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+      __docker_init buildx inspect --bootstrap |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
     fi
     if [ "$BUILDX_INIT_RAN" != "yes" ]; then
       # create docker daemon file
@@ -1173,7 +1173,7 @@ __run_docker_script() {
   build_command="$(echo "$set_build_command" | grep '^' | grep -v '^$' | sed 's|,,| \\\n|g')"
   set_build_command="${set_build_command//,,/}"
   printf '%b%s: %b%s%b\n' "$GREEN" "Saving the build command to" "$CYAN" "$logscript_file" "$NC"
-  printf 'Saving the build command to: %s\n' "$logscript_file" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  printf 'Saving the build command to: %s\n' "$logscript_file" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
   __save_build_script
   printf_blue "Setting default tag to: $set_tag"
   if [ -n "$ADDITIONAL_PRETTY" ]; then
@@ -1181,14 +1181,14 @@ __run_docker_script() {
       printf_cyan "Added tag: $reg"
     done
   fi
-  echo "$BUILDX_GET_VERSION_MESSAGE" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  echo "$BUILDX_GET_VERSION_MESSAGE" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
   if [ "$BUILDX_ADD_TAG" = "true" ] || [ -n "$REGISTRY_TAG" ] && [ -n "$ADDITIONAL_PRETTY" ]; then
     printf_blue "Adding tags: $ADDITIONAL_PRETTY"
-    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
   fi
   sleep 2
-  printf 'Executing: %s\n' "$set_build_command" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-  eval "$set_build_command" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null || false
+  printf 'Executing: %s\n' "$set_build_command" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  eval "$set_build_command" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null || false
   return $?
 
 }
@@ -1203,16 +1203,16 @@ __run_dockermgr_script() {
   build_command="$(echo "$set_build_command" | grep '^' | grep -v '^$' | sed 's|,,| \\\n|g')"
   set_build_command="${set_build_command//,,/}"
   printf '%b%s: %b%s%b\n' "$GREEN" "Saving the build command to" "$CYAN" "$logscript_file" "$NC"
-  printf 'Saving the build command to: %s\n' "$logscript_file" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  printf 'Saving the build command to: %s\n' "$logscript_file" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
   __save_build_script
   printf_blue "Setting default tag to: $set_tag"
   if [ "$BUILDX_ADD_TAG" = "true" ] || [ -n "$REGISTRY_TAG" ] && [ -n "$ADDITIONAL_PRETTY" ]; then
     printf_blue "Adding tags: $ADDITIONAL_PRETTY"
-    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
   fi
   sleep 2
-  printf 'Executing: %s\n' "$build_command" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-  eval "$set_build_command" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null || false
+  printf 'Executing: %s\n' "$build_command" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  eval "$set_build_command" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null || false
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -1227,16 +1227,16 @@ __run_buildx_script() {
   build_command="$(echo "$set_build_command" | grep '^' | grep -v '^$' | sed 's|,,| \\\n|g')"
   set_build_command="${set_build_command//,,/}"
   printf '%b%s: %b%s%b\n' "$GREEN" "Saving the build command to" "$CYAN" "$logscript_file" "$NC"
-  printf 'Saving the build command to: %s\n' "$logscript_file" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  printf 'Saving the build command to: %s\n' "$logscript_file" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
   __save_build_script
   printf_blue "Setting default tag to: $set_tag"
   if [ "$BUILDX_ADD_TAG" = "true" ] || [ -n "$REGISTRY_TAG" ] && [ -n "$ADDITIONAL_PRETTY" ]; then
     printf_blue "Adding tags: $ADDITIONAL_PRETTY"
-    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
   fi
   sleep 2
-  printf 'Executing: %s\n' "$set_build_command" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-  eval "$set_build_command" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null || false
+  printf 'Executing: %s\n' "$set_build_command" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  eval "$set_build_command" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null || false
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -1246,16 +1246,16 @@ __run_build_script() {
   build_command="$(echo "$set_build_command" | grep '^' | grep -v '^$' | sed 's|,,| \\\n|g')"
   set_build_command="${set_build_command//,,/}"
   printf '%b%s: %b%s%b\n' "$GREEN" "Saving the build command to" "$CYAN" "$logscript_file" "$NC"
-  printf 'Saving the build command to: %s\n' "$logscript_file" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  printf 'Saving the build command to: %s\n' "$logscript_file" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
   __save_build_script
   printf_blue "Setting default tag to: $set_tag"
   if [ "$BUILDX_ADD_TAG" = "true" ] || [ -n "$REGISTRY_TAG" ] && [ -n "$ADDITIONAL_PRETTY" ]; then
     printf_blue "Adding tags: $ADDITIONAL_PRETTY"
-    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
   fi
   sleep 2
-  printf 'Executing: %s\n' "$set_build_command" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-  eval "$set_build_command" |& tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null || false
+  printf 'Executing: %s\n' "$set_build_command" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  eval "$set_build_command" |& tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null || false
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -1274,10 +1274,10 @@ EOF
   if [ "$BUILDX_GEN_SCRIPT" = "true" ]; then
     if [ -x "$logscript_file" ]; then
       printf_yellow "Your script has been saved: exiting"
-      echo "Your script has been saved: exiting" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+      echo "Your script has been saved: exiting" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
       exit 0
     else
-      printf_red "Your script failed to save: exiting" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+      printf_red "Your script failed to save: exiting" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
       exit 1
     fi
   else
@@ -1323,35 +1323,35 @@ __run_docker_build() {
   [ -n "$image_name" ] && tagged_name="$image_name" || tagged_name="$push_tag"
   if [ "$BUILDX_RUN_SCRIPT" = "true" ] && [ -f "$BUILDX_CWD/build.sh" ]; then
     printf_blue "Using $BUILDX_CWD/build.sh to build $tagged_name"
-    printf '%s\n' "# Using Using $BUILDX_CWD/build.sh to build $tagged_name" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+    printf '%s\n' "# Using Using $BUILDX_CWD/build.sh to build $tagged_name" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
     __run_docker_script
     buildx_status=$?
   elif __is_buildx_installed; then
     printf_blue "Using docker buildx to build $tagged_name"
-    printf '%s\n' "# Using docker buildx to build $tagged_name" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+    printf '%s\n' "# Using docker buildx to build $tagged_name" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
     __run_buildx_script
     buildx_status=$?
   else
     printf_blue "Using docker build to build $tagged_name"
-    printf '%s\n' "# Using docker build to build $tagged_name" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+    printf '%s\n' "# Using docker build to build $tagged_name" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
     __run_build_script
     buildx_status=$?
     if [ "$buildx_status" = 0 ]; then
       if __docker_push; then
-        printf '%s\n' "# Pushing of $tagged_name completed on : $(date +'%Y-%m-%d at %H:%M')" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+        printf '%s\n' "# Pushing of $tagged_name completed on : $(date +'%Y-%m-%d at %H:%M')" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
       else
-        printf '%s\n' "# Pushing of $tagged_name failed on : $(date +'%Y-%m-%d at %H:%M')" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+        printf '%s\n' "# Pushing of $tagged_name failed on : $(date +'%Y-%m-%d at %H:%M')" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
       fi
     fi
   fi
   if [ $buildx_status = 0 ]; then
-    printf '%s\n' "# Finished building $tagged_name $ADDITIONAL_PRETTY" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+    printf '%s\n' "# Finished building $tagged_name $ADDITIONAL_PRETTY" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
     buildx_status=0
   else
-    printf '%s\n' "# Building of $tagged_name has failed" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+    printf '%s\n' "# Building of $tagged_name has failed" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
     buildx_status="${buildx_status:-10}"
   fi
-  printf '\n%s\n' "buildx has Finished on: $(date +'%Y-%m-%d at %H:%M')" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  printf '\n%s\n' "buildx has Finished on: $(date +'%Y-%m-%d at %H:%M')" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
   __remove_pid
   return $buildx_status
 }
@@ -1506,14 +1506,14 @@ __execute_buildx() {
       if __docker pull "$push_tag" &>/dev/null; then
         printf_green "Successfully pulled $push_tag"
         notify_message+="Successfully pulled $push_tag|"
-        printf '\n%s\n' "# Successfully pulled $push_tag on : $(date +'%Y-%m-%d at %H:%M')" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+        printf '\n%s\n' "# Successfully pulled $push_tag on : $(date +'%Y-%m-%d at %H:%M')" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
         __docker rmi "$push_tag" &>/dev/null
         __docker rmi "$pretty_name" &>/dev/null
         buildxexitCode=0
       else
         printf_red "Failed to pull $push_tag" >&2
         notify_message+="Failed to pull $push_tag|"
-        printf '\n%s\n' "# Failed to pull $push_tag on : $(date +'%Y-%m-%d at %H:%M')" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+        printf '\n%s\n' "# Failed to pull $push_tag on : $(date +'%Y-%m-%d at %H:%M')" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
         buildxexitCode=2
       fi
     fi
@@ -1525,8 +1525,8 @@ __execute_buildx() {
   notify_message="$(printf '%b\n\n' "$notify_message")"
   __notifications "${notify_message[@]}" &>/dev/null &
   [ "$BUILDX_REMOTE_NOTIFY_ENABLED" = "yes" ] && [ -n "$BUILDX_REMOTE_NOTIFY_COMMAND" ] && eval "$BUILDX_REMOTE_NOTIFY_COMMAND" "${notify_message[@]}" &>/dev/null &
-  printf "# Exit status: %s\n" "$buildxexitCode" | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
-  printf '###############################################################################\n\n' | tee-a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  printf "# Exit status: %s\n" "$buildxexitCode" | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
+  printf '###############################################################################\n\n' | tee -a "$BUILDX_CUSTOM_LOG_FILE" &>/dev/null
   [ -f "$BUILDX_PID_FILE" ] && rm -Rf "$BUILDX_PID_FILE"
   [ "$buildxexitCode" = "1" ] && exitCode=0 || exitCode=$buildxexitCode
   if [ $exitCode -ne 0 ] && [ -f "$BUILDX_FAILED_LOG" ] && __cmd_exists sendemail-to; then
@@ -1805,7 +1805,7 @@ while :; do
     export SCRIPT_OPTS="--debug"
     export _DEBUG="on"
     __devnull() { tee || return 1; }
-    __devnull2() { eval "$@" |& tee|| return 1; }
+    __devnull2() { eval "$@" |& tee || return 1; }
     ;;
   --completions)
     if [ "$2" = "short" ]; then
