🗃️ Committing everything that changed 🗃️

diff --git a/bin/buildx b/bin/buildx
--- a/bin/buildx
+++ b/bin/buildx
@@ -277,6 +277,22 @@ __trap_exit_local() {
   return 0
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__curl_docker_api_tags() {
+  [ $# -ne 3 ] || return 1
+  curl -q -LSsf "$1/$2/$3/tags?page_size=1000" | jq -r ".results[].name" | sort --version-sort | grep -v '[0-9]' ||
+    curl -q -LSsf "$1/$2/$3/tags?page_size=1000" | jq -r ".results[].name" | sort --version-sort | grep -v '[0-9]' ||
+    return 1
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__get_tags() {
+  local results="" registry="${3:-$2}" repo="${2:-}" image="${1:-}"
+  local registry="https://registry.hub.docker.com"
+  echo "$image" | grep -q '/' && repo="${image//\/*/}" && image="${image//*\//}"
+  results="$(__curl_docker_api_tags "$registry/v2/repositories" "$repo" "$image")"
+  [ -n "$results" ] && echo "$results" | printf_column "$BUILDX_OUTPUT_COLOR_GOOD" || printf_exit "Failed to get tags from $registry/$repo/$image"
+  return $?
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __get_dockerfile_ver() {
   local gver="" ver="" filename="" fileloc="" exitC=0
   [ "$BUILDX_AUTO_VERSION" = "false" ] && return 1
@@ -1152,6 +1168,12 @@ version)
 api)
   shift 1
   case "$1" in
+  tags)
+    shift 1
+    [ "$1" = "help" ] && printf_help "usage: $APPNAME api tags repo/image"
+    __get_tags "$@"
+    exit $?
+    ;;
   list)
     shift 1
     [ "$1" = "help" ] && printf_help "usage: $APPNAME api list repo"
