🗃️ Committing everything that changed 🗃️
bin/buildx

diff --git a/bin/buildx b/bin/buildx
--- a/bin/buildx
+++ b/bin/buildx
@@ -1088,7 +1088,7 @@ __build_cmd() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __execute_buildx() {
   local exitCode=0
-  local buildxexitCode=0
+  local buildxexitCode=1
   if [ -f "$BUILDX_PID_FILE" ]; then
     printf_exit "$APPNAME is already running"
   else
@@ -1188,25 +1188,24 @@ __execute_buildx() {
       printf '\n%s\n' "# Successfully pulled $push_tag on : $(date +'%Y-%m-%d at %H:%M')" | tee -a "$logfile" &>/dev/null
       __docker rmi "$push_tag" &>/dev/null
       __docker rmi "$pretty_name" &>/dev/null
-      buildxexitCode=0
+      buildxexitCode=1
     else
       printf_red "Failed to pull $push_tag" >&2
       notify_message+="Failed to pull $push_tag|"
       printf '\n%s\n' "# Failed to pull $push_tag on : $(date +'%Y-%m-%d at %H:%M')" | tee -a "$logfile" &>/dev/null
-      buildxexitCode=1
+      buildxexitCode=2
     fi
   else
     printf_red "Failed to build $name" >&2
     notify_message+="Failed to build $name|"
-    buildxexitCode=1
+    buildxexitCode=10
   fi
   notify_message="$(echo "$notify_message" | tr '|' '\n')"
   __notifications "${notify_message[@]}" &>/dev/null &
-  exitCode="${buildxexitCode:-$?}"
-  printf "# Exit status: %s\n" "$exitCode" | tee -a "$logfile" &>/dev/null
+  printf "# Exit status: %s\n" "$buildxexitCode" | tee -a "$logfile" &>/dev/null
   printf '###############################################################################\n\n' | tee -a "$logfile" &>/dev/null
   [ -f "$BUILDX_PID_FILE" ] && rm -Rf "$BUILDX_PID_FILE"
-  [ "$buildxexitCode" = 0 ] && exitCode=0 || exitCode=$buildxexitCode
+  [ "$buildxexitCode" = "1" ] && exitCode=0 || exitCode=$buildxexitCode
   return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
