🗃️ Committing everything that changed 🗃️

diff --git a/bin/buildx b/bin/buildx
--- a/bin/buildx
+++ b/bin/buildx
@@ -278,6 +278,102 @@ __trap_exit_local() {
   return 0
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__orgs_api_delete() {
+  if echo "$1" | grep -q '/'; then
+    user="${1//\/*/}"
+    image="${1//*\//}"
+  elif [ $# -eq 1 ]; then
+    user="$BUILDX_DEFAULT_REPO"
+    image="$1"
+  else
+    user="$1"
+    image="$2"
+  fi
+  [ -n "$user" ] || printf_exit "Please provide a organization name"
+  [ -n "$image" ] || printf_exit "Please provide a repository name"
+  repo="$user/$image"
+  if [ -f "$BUILDX_CACHE_DIR/token" ]; then
+    local TOKEN="$(<"$BUILDX_CACHE_DIR/token")"
+    printf_cyan "Attempting to delete $image from: $BUILDX_REGISTRY_URL/v2/repositories/$repo"
+    curl -q -LSsfi -H "Authorization: Bearer $TOKEN" -X DELETE "$BUILDX_REGISTRY_URL/v2/repositories/$repo" &>"$BUILDX_CACHE_DIR/delete.log"
+    if grep -qis '405 Not Allowed' "$BUILDX_CACHE_DIR/delete.log"; then
+      __api_auth_error
+    elif grep -qis '404.*Not.*Found' "$BUILDX_CACHE_DIR/delete.log"; then
+      printf_green "Repository does not exist"
+    elif grep -qis 'HTTP.*404.NO.*Content' "$BUILDX_CACHE_DIR/delete.log"; then
+      printf_green "Repository does not exist"
+    elif grep -qis 'HTTP.*204.NO.*Content' "$BUILDX_CACHE_DIR/delete.log"; then
+      printf_green "Repository does not exist"
+    elif grep -qis 'HTTP.*202.*Accepted' "$BUILDX_CACHE_DIR/delete.log"; then
+      printf_green "Successfully deleted the repository"
+    else
+      printf_exit "Failed to delete the repository"
+      grep -i 'HTTP/.*' "$BUILDX_CACHE_DIR/delete.log" | printf_readline 1
+      grep -i 'URL returned error' "$BUILDX_CACHE_DIR/delete.log" | sed 's|*.The requested URL returned error: ||g' | printf_readline 1
+    fi
+  else
+    printf_exit 1 1 "token not set: $APPNAME api auth [username] [password]"
+  fi
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__orgs_api_update() {
+  # TODO figure out how to make this work
+  printf_exit "This is not working for me!"
+  if echo "$1" | grep -q '/'; then
+    user="${1//\/*/}"
+    image="${1//*\//}"
+  elif [ $# -eq 1 ]; then
+    user="$BUILDX_DEFAULT_REPO"
+    image="$1"
+  else
+    user="$1"
+    image="$2"
+  fi
+  repo="$user/$image"
+  [ -n "$user" ] || printf_exit "Please provide a organization name"
+  [ -n "$image" ] || printf_exit "Please provide a repository name"
+  [ -n "$3" ] && field="$3" || printf_exit "Please provide a field to update [description,full_description,is_private]"
+  [ -n "$4" ] && field_value="$4" || printf_exit "Please provide a value to field"
+  # [ -n "$4" ] && full_description="$4" || printf_exit "Please provide full description"
+  # [ -n "$5" ] && is_private="$5" || printf_exit "private repo true/false"
+  # [ -n "$6" ] && can_edit="$6" || printf_exit "can edit true/false"
+  #-d "{\"description\": \"$description\", \"is_private\": \"$is_private\", \"can_edit\": \"$can_edit\", \"full_description\": \"$full_description\"}" \
+  if [ -f "$BUILDX_CACHE_DIR/token" ]; then
+    local TOKEN="$(<"$BUILDX_CACHE_DIR/token")"
+    printf_cyan "Attempting to update $image from:"
+    printf_cyan "$BUILDX_REGISTRY_URL/v2/repositories/$repo"
+    curl -q -LSsfi -H "Content-Type: application/json" \
+      -H "Authorization: Bearer $TOKEN" -X PATCH \
+      -d "{\"$field\": \"$field_value\"}" \
+      "$BUILDX_REGISTRY_URL/v2/repositories/$repo/" &>"$BUILDX_CACHE_DIR/update.log"
+    if grep -qis '405 Not Allowed' "$BUILDX_CACHE_DIR/update.log"; then
+      __api_auth_error
+    elif grep -qis '404.*Not.*Found' "$BUILDX_CACHE_DIR/update.log"; then
+      printf_green "Repository does not exist"
+    elif grep -qis '403.*FORBIDDEN' "$BUILDX_CACHE_DIR/update.log"; then
+      printf_green "You are not authorized to make this request"
+    elif grep -qis 'HTTP.*404.NO.*Content' "$BUILDX_CACHE_DIR/update.log"; then
+      printf_green "Repository does not exist"
+    elif grep -qis 'HTTP.*204.NO.*Content' "$BUILDX_CACHE_DIR/update.log"; then
+      printf_green "Repository does not exist"
+    elif grep -qis 'HTTP.*202.*Accepted' "$BUILDX_CACHE_DIR/update.log"; then
+      printf_green "Successfully updated the repository"
+    else
+      printf_exit "Failed to update the repository"
+      grep -i 'HTTP/.*' "$BUILDX_CACHE_DIR/update.log" | printf_readline 1
+      grep -i 'URL returned error' "$BUILDX_CACHE_DIR/update.log" | sed 's|*.The requested URL returned error: ||g' | printf_readline 1
+    fi
+  else
+    printf_exit 1 1 "Well something went terribly wrong"
+  fi
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__api_auth_error() {
+  printf_exit "Please authenticate with the command:"
+  printf_yellow "dockermgr api auth username password/key"
+  exit 1
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __curl_docker_api_tags() {
   [ -n "$DEBUGGER" ] && set -x
   local tags="" latest="" words="" numbers=""
@@ -314,6 +410,7 @@ __get_tags() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __get_dockerfile_ver() {
+  # TODO: rewrite this function
   [ -n "$DEBUGGER" ] && set -x
   local dver="" iver="" filename="" fileloc="" exitC=0
   local buildx_enable_tag="$BUILDX_ADD_TAG"
@@ -1126,7 +1223,7 @@ LONGOPTS="completions:,config,debug,dir:,help,options,raw,version,silent"
 LONGOPTS+=",force,cleanup,registry:,repo:,no-registry,no-repo,platform:"
 LONGOPTS+=",tag:,add-tag:,all,build,url:,no-script,init"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-ARRAY="run[Dockerfile] init status version api[tags,list,search,sources,clone] "
+ARRAY="all run[Dockerfile] init status version api[tags,list,search,sources,clone,delete,update] "
 ARRAY+=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 LIST=""
@@ -1388,6 +1485,15 @@ api)
     [ "$1" = "help" ] && printf_help "usage: $APPNAME api clone repo [Base user repo]"
     __api_clone "${@:-all}"
     exit $?
+    ;;
+  delete)
+    shift 1
+    __orgs_api_delete "$@"
+    exit $?
+    ;;
+  update)
+    shift 1
+    __orgs_api_update "$@"
     ;;
   *)
     printf_help "usage: $APPNAME api [list,search,sources,clone] [query]"
