🗃️ Committing everything that changed 🗃️
bin/buildx
bin/gitignore
.gitignore

diff --git a/bin/buildx b/bin/buildx
--- a/bin/buildx
+++ b/bin/buildx
@@ -292,7 +292,7 @@ __trap_exit_local() {
   [ "$_DEBUG" != "on" ] || { [ -n "$exitCode" ] && echo $exitCode; }
   __buildx_cleanup && exitCode=0
   __remove_pid
-  [ -f "$BUILD_FAILED_LOG" ] && [ "$exitCode" -ne 0 ] || exitCode=0
+  [ -f "$BUILDX_FAILED_LOG" ] && [ "$exitCode" -ne 0 ] || exitCode=0
   return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -329,12 +329,10 @@ __create_update_docker_daemon_config() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __last_build_check() {
-  local version="$(echo "$Dockerfile" | sed 's|[a-zA-Z]||g;s| ||g')"
-  [ -n "$version" ] && BUILD_FAILED_LOG="build_failed$version" || BUILD_FAILED_LOG="build_failed"
-  if [ -f "${1:-$BUILDX_CWD}/.$BUILD_FAILED_LOG" ]; then
+  if [ -f "${1:-$BUILDX_CWD}/$BUILDX_FAILED_LOG" ]; then
     printf_red "Please note the last build had failed!!"
     printf_red "Please check the error log and fix all problems"
-    printf_yellow "To remove this warning delete ${1:-$BUILDX_CWD}/.$BUILD_FAILED_LOG"
+    printf_yellow "To remove this warning delete ${1:-$BUILDX_CWD}/$BUILDX_FAILED_LOG"
     return 20
   fi
 }
@@ -1089,8 +1087,6 @@ __run_docker_build() {
 __build_cmd() {
   local exitCodeS="1"
   local dir="${1:-$FULL_DIR_PATH}"
-  local version="$(echo "$Dockerfile" | sed 's|[a-zA-Z]||g;s| ||g')"
-  [ -n "$version" ] && BUILD_FAILED_LOG="build_failed$version" || BUILD_FAILED_LOG="build_failed"
   __last_build_check "$dir"
   if ! __is_buildx_installed; then
     printf_yellow "💔 buildx is not installed - Using 'docker build' instead. 💔"
@@ -1099,12 +1095,12 @@ __build_cmd() {
   exitCodeS=$?
   if [ "$exitCodeS" -ne 0 ]; then
     printf_yellow "The last 50 lines of the log are in:"
-    printf_cyan "$BUILDX_CWD/.$BUILD_FAILED_LOG"
+    printf_cyan "$BUILDX_CWD/$BUILDX_FAILED_LOG"
     printf_blue "Full log is in the logfile"
-    echo "build failed on $(date +'%Y-%m-%d at %H:%M')" >"$BUILDX_CWD/.$BUILD_FAILED_LOG"
-    tail -n75 "$logfile" >>"$BUILDX_CWD/.$BUILD_FAILED_LOG"
+    echo "build failed on $(date +'%Y-%m-%d at %H:%M')" >"$BUILDX_CWD/$BUILDX_FAILED_LOG"
+    tail -n75 "$logfile" >>"$BUILDX_CWD/$BUILDX_FAILED_LOG"
   fi
-  BUILD_FAILED_LOG="${BUILD_FAILED_LOG:-}"
+  BUILDX_FAILED_LOG="${BUILDX_FAILED_LOG:-}"
   return ${exitCodeS:-$?}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -1162,6 +1158,8 @@ __execute_buildx() {
     printf_red "Can not find a Dockerfile in $FULL_DIR_PATH"
     echo "" && exit 1
   fi
+  BUILDX_DOCKERFILE_VERSION="${BUILDX_DOCKERFILE_VERSION:-$(echo "$Dockerfile" | sed 's|[a-zA-Z]||g;s| ||g')}"
+  [ -n "$BUILDX_DOCKERFILE_VERSION" ] && BUILDX_FAILED_LOG="${BUILDX_FAILED_LOG:-.build_failed$BUILDX_DOCKERFILE_VERSION}" || BUILDX_FAILED_LOG="${BUILDX_FAILED_LOG:-.build_failed}"
   #
   image_name="$(grep -s 'ARG.*IMAGE_NAME=' "$Dockerfile" | awk -F'=' '{print $2}' | sed 's|"||g' | grep '^' || echo "$default_name")"
   #
diff --git a/bin/gitignore b/bin/gitignore
--- a/bin/gitignore
+++ b/bin/gitignore
@@ -277,8 +277,9 @@ __dirignore() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __failedignore() {
-  if grep -qvs "ignore .build_failed" "$GITIGNORE_CWD/.gitignore"; then
-    printf '# ignore .build_failed files\**/.build_failed\n\n'
+  grep -qs '\*\*/.build_failed\*' "$GITIGNORE_CWD/.gitignore" || sed -i 's|.*/.build_failed.*|**/.build_failed*|g' "$GITIGNORE_CWD/.gitignore"
+  if ! grep -qs "# ignore .build_failed" "$GITIGNORE_CWD/.gitignore"; then
+    printf '# ignore .build_failed files\n**/.build_failed*\n\n'
   fi
   if grep -qs '# ignore .build_failed' "$GITIGNORE_CWD/.gitignore"; then
     return 0
@@ -368,8 +369,9 @@ $RECYCLE.BIN/
 # ignore commit message
 **/.gitcommit
 
-#ignore .failed
-**/.build_failed
+# ignore .build_failed files
+**/.build_failed*
+
 
 # ignore .bak files
 **/*.bak
@@ -726,14 +728,13 @@ save)
 add)
   shift 1
   ignore_list "$@"
-  printf_green "Adding $IGNORELIST to:"
-  printf_green "$GITIGNORE_CWD/.gitignore"
+  printf_green "Adding $IGNORELIST to: ${GITIGNORE_CWD//$PWD/.}/.gitignore"
   fetch_ignore >>"$GITIGNORE_CWD/.gitignore" && true || false
   exit $?
   ;;
 
 *)
-  [ -n "$1" ] || __update_files
+  [ $# -ne 0 ] || __update_files
   ignore_overwrite "$@"
   [ $# -ne 0 ] && create_gitignore "$@" && true || false
   ;;
