🗃️  modified: bin/buildx 🗃️

diff --git a/bin/buildx b/bin/buildx
--- a/bin/buildx
+++ b/bin/buildx
@@ -183,23 +183,34 @@ __buildx_status() {
 __build_cmd() {
   set -e -o pipefail
   local exitCodeS=1
+  local dir="${1:-$REALPATH}"
   local logfolder="$(dirname "$tagged_name" | sed 's|.*://||g')"
   local logfile="$BUILDX_LOG_DIR/$(echo "$tagged_name" | awk -F':' '{print $1}').log"
+  local date="$(date +'%Y-%m-%d at %H:%M')"
+  if [[ -f "$dir/.build_failed" ]]; then
+    printf_red "Last build failed on $(cat "$dir/.build_failed")"
+    printf_red "Please check the error log and fix all problems"
+    printf_red "Then remove $dir/.build_failed and retry"
+    exit 20
+  fi
   printf_blue "Log is being written to:"
   printf_cyan "${logfile//$HOME/~}"
   mkdir -p "$BUILDX_LOG_DIR/$logfolder"
-  printf '%s\n' "Building $tagged_name on : $(date +'%Y-%m-%d at %H:%M')" >>"$logfile"
+  printf '%s\n' "Building $tagged_name on : $date" >>"$logfile"
   sudo docker buildx build ${BUILDX_REMOVE_BUILD:-} \
     --platform "${DOCKER_PLATFORMS// /,}" \
     --push \
     --output type=registry \
     --progress auto \
     -f ${Dockerfile:-Dockerfile} \
-    -t "$tagged_name" "${@:-$PWD}" 2>&1 |
+    -t "$tagged_name" "${dir:-$PWD}" 2>&1 |
     tee -a "$logfile" &>/dev/null &&
     exitCodeS=0 || exitCodeS=1
   printf "Exit status: %s\n" "$exitCodeS" >>"$logfile"
   printf '###############################################################################\n\n' >>"$logfile"
+  if [[ "$exitCodeS" -ne 0 ]]; then
+    echo "build failed on $date" >"$dir/.build_failed"
+  fi
   return ${exitCodeS:-$?}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -239,7 +250,7 @@ __buildx_exec() {
   else
     printf_cyan "Building $tagged_name"
   fi
-  __build_cmd &&
+  __build_cmd "$REALPATH" &&
     {
       __notifications "Successfully built $name"
       printf_green "Successfully built $name"
