🗃️ Committing everything that changed 🗃️

diff --git a/bin/buildx b/bin/buildx
--- a/bin/buildx
+++ b/bin/buildx
@@ -465,16 +465,16 @@ __run_docker_build() {
       --pull \
       --force-rm \
       --no-cache \
-      -t "$tagged_name" "${dir:-$PWD}" |& tee -a "$logfile" &>/dev/null &&
+      -t "$push_tag" "${dir:-$PWD}" |& tee -a "$logfile" &>/dev/null &&
       buildx_status=0 || buildx_status=1
   fi
   if [ $buildx_status = 0 ]; then
     printf '\n%s\n' "# Finished building $tagged_name on : $(date +'%Y-%m-%d at %H:%M')" >>"$logfile"
-    printf '\n%s\n' "# Pushing $tagged_name on : $(date +'%Y-%m-%d at %H:%M')" >>"$logfile"
+    printf '\n%s\n' "# Pushing $push_tag on : $(date +'%Y-%m-%d at %H:%M')" >>"$logfile"
     if __docker_push; then
-      printf '\n%s\n' "# Pushing of $tagged_name completed on : $(date +'%Y-%m-%d at %H:%M')" >>"$logfile"
+      printf '\n%s\n' "# Pushing of $push_tag completed on : $(date +'%Y-%m-%d at %H:%M')" >>"$logfile"
     else
-      printf '\n%s\n' "# Pushing of $tagged_name failed on : $(date +'%Y-%m-%d at %H:%M')" >>"$logfile"
+      printf '\n%s\n' "# Pushing of $push_tag failed on : $(date +'%Y-%m-%d at %H:%M')" >>"$logfile"
     fi
   else
     printf '\n%s\n' "# Building of $tagged_name has failed on : $(date +'%Y-%m-%d at %H:%M')" >>"$logfile"
@@ -571,21 +571,22 @@ __execute_buildx() {
   fi
   logfolder="$(dirname "$tagged_name" | sed 's|.*://||g')"
   logfile="$BUILDX_LOG_DIR/$(echo "$tagged_name" | awk -F':' '{print $1}').log"
+  push_tag="$tagged_name:${BUILDX_DEFAULT_TAG:-latest}"
   [ -d "$BUILDX_LOG_DIR/$logfolder" ] || mkdir -p "$BUILDX_LOG_DIR/$logfolder"
   if __build_cmd "$REALPATH"; then
     __notifications "Successfully built $name"
     printf_green "Successfully built $name"
     __notifications "Pulling the updated image"
     printf_green "Pulling the updated image"
-    if __docker pull "$tagged_name" &>/dev/null; then
-      echo "# Successfully pulled $tagged_name" | tee -a "$logfile" &>/dev/null
-      __notifications "Successfully pulled $tagged_name"
-      printf_green "Successfully pulled $tagged_name"
+    if __docker pull "$push_tag" &>/dev/null; then
+      echo "# Successfully pulled $push_tag" | tee -a "$logfile" &>/dev/null
+      __notifications "Successfully pulled $push_tag"
+      printf_green "Successfully pulled $push_tag"
       exitCode=0
     else
-      echo "# Failed to pull $tagged_name" | tee -a "$logfile" &>/dev/null
-      __notifications "Failed to pull $tagged_name"
-      printf_red "Failed to pull $tagged_name" 1>&2
+      echo "# Failed to pull $push_tag" | tee -a "$logfile" &>/dev/null
+      __notifications "Failed to pull $push_tag"
+      printf_red "Failed to pull $push_tag" 1>&2
       exitCode+=1
     fi
   else
