🗃️ Committing everything that changed 🗃️

diff --git a/bin/cdd b/bin/cdd
--- a/bin/cdd
+++ b/bin/cdd
@@ -430,7 +430,7 @@ cd_goto() {
   if [ "$CDD_JUST_CD" = "true" ]; then
     printf_cyan "Setting working directory to: $dir"
     unset -f cd_cdd &>/dev/null
-    cd_cdd() { [ -d "$1" ] && builtin cd "$1" || { echo "Failed to cd into $1" && return 1; }; }
+    cd_cdd() { { [ -d "$1" ] && builtin cd "$1"; } || { [ $# -eq 0 ] && builtin cd "$CDD_CWD_DIR"; } || { echo "Failed to cd into $1" && return 1; }; }
   else
     printf_yellow "cd out of $dir is not"
     printf_yellow "allowed while using cdd which will cause issues with applications"
