🗃️ Committing everything that changed 🗃️

diff --git a/bin/cdd b/bin/cdd
--- a/bin/cdd
+++ b/bin/cdd
@@ -428,17 +428,18 @@ cd_goto() {
   [ -n "$message" ] && printf_green "$message using $(basename "$SHELL" 2>/dev/null)"
   [ -n "$message_add" ] && printf_blue "$message_add"
   if [ "$CDD_JUST_CD" = "true" ]; then
-    unset -f cd_cdd cd &>/dev/null
-    cd_cdd() { builtin cd "$1" || return 1; }
+    printf_cyan "Setting working directory to: $dir"
+    unset -f cd_cdd &>/dev/null
+    cd_cdd() { [ -d "$1" ] && builtin cd "$1" || { echo "Failed to cd into $1" && return 1; }; }
   else
     printf_yellow "cd out of $dir is not"
     printf_yellow "allowed while using cdd which will cause issues with applications"
     printf_cyan "Type quit to return to your previous directory/shell"
-    export -f _cd cd_cdd
   fi
-  export -f quit __git_top_dir printf_red
+  export -f _cd cd_cdd quit __git_top_dir printf_red
   export SHELL GREP_COLORS CDD_CWD_DIR="$PWD" PS1_ADD="$PS1_ADD_CDD" CDD_STATUS="$STATUS"
   export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:."
+  printf '\n'
   eval "$SHELL"
   exitCode=$?
   sleep .5
