🗃️ Committing everything that changed 🗃️
bin/cloudflare
completions/_cloudflare_completions

diff --git a/bin/cloudflare b/bin/cloudflare
--- a/bin/cloudflare
+++ b/bin/cloudflare
@@ -311,15 +311,20 @@ __get_ip6() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __message() {
+  exitStatus=1
   if grep 'success' "$CLOUDFLARE_TEMP_FILE" | grep -q 'true'; then
     printf_green "${1:-Successfully created $CLOUDFLARE_HOSTNAME}"
-    return 0
+    exitStatus=0
   else
+    printf '# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n# %s\n' "$(date)" >>"$CLOUDFLARE_LOG_DIR/errors.log"
+    cat "$CLOUDFLARE_TEMP_FILE" >>"$CLOUDFLARE_LOG_DIR/errors.log"
+    printf '# %s\n# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n' "End Log" >>"$CLOUDFLARE_LOG_DIR/errors.log"
     err_mess="$(__devnull2 cat "$CLOUDFLARE_TEMP_FILE" | jq -rc '.errors | .[].message' 2>/dev/null | grep '^')"
     [ -z "$err_mess" ] && err_mess="Well something went horribly wrong" || err_mess="Error: $err_mess"
     printf_yellow "${err_mess}"
-    return 1
+    exitStatus=1
   fi
+  return $exitStatus
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __tunnel() {
@@ -334,17 +339,17 @@ __tunnel() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __api_verify() {
-  curl -q -LSs -X GET -H 'Authorization: Bearer '$CLOUDFLARE_API_KEY'' -H "Content-Type: application/json" "$CLOUDFLARE_API_URL/user/tokens/verify" 2>/dev/null | jq -r '.messages | .[] | .message' | grep 'valid and active' || return 1
+  curl -q -LSs -X GET -H 'X-Auth-Key: '$CLOUDFLARE_API_KEY'' -H 'X-auth-email: '$CLOUDFLARE_EMAIL'' -H "Content-Type: application/json" "$CLOUDFLARE_API_URL/user/tokens/verify" 2>/dev/null | jq -r '.messages | .[] | .message' | grep 'valid and active' || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __zone_identifier() {
   local results=""
   CLOUDFLARE_ZONE="${1:-$CLOUDFLARE_ZONE}"
-  results="$(curl -q -LSs -X GET -H 'Authorization: Bearer '$CLOUDFLARE_API_KEY'' -H "Content-Type: application/json" "$CLOUDFLARE_API_URL/zones?per_page=1000&name=$CLOUDFLARE_ZONE" 2>/dev/null || echo '')"
-  if echo "$results" | jq '.success' 2>/dev/null | grep -q 'false'; then
+  results="$(curl -q -LSs -X GET -H 'X-Auth-Key: '$CLOUDFLARE_API_KEY'' -H 'X-auth-email: '$CLOUDFLARE_EMAIL'' -H "Content-Type: application/json" "$CLOUDFLARE_API_URL/zones?per_page=1000&name=$CLOUDFLARE_ZONE" 2>/dev/null || echo '')"
+  if [ -z "$results" ] && echo "$results" | jq '.success' 2>/dev/null | grep -q 'false'; then
     exitCode="1"
   else
-    echo "$results" | grep -Po '(?<="id":")[^"]*' | head -1
+    echo "$results" | grep -Po '(?<="id":")[^"]*' | head -n1
   fi
   return ${exitCode:-0}
 }
@@ -352,7 +357,7 @@ __zone_identifier() {
 __record_identifier() {
   local results="" id=""
   local CLOUDFLARE_HOSTNAME="${1:-$CLOUDFLARE_HOSTNAME}"
-  results="$(curl -q -LSs -X GET -H 'Authorization: Bearer '$CLOUDFLARE_API_KEY'' -H "Content-Type: application/json" "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records" 2>/dev/null || echo '')"
+  results="$(curl -q -LSs -X GET -H 'X-Auth-Key: '$CLOUDFLARE_API_KEY'' -H 'X-auth-email: '$CLOUDFLARE_EMAIL'' -H "Content-Type: application/json" "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records" 2>/dev/null || echo '')"
   if echo "$results" | jq '.success' 2>/dev/null | grep -q 'false'; then
     exitCode="1"
   else
@@ -365,7 +370,7 @@ __record_identifier() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __api() {
   local results=""
-  results="$(curl -q -LSs -X GET -H 'Authorization: Bearer '$CLOUDFLARE_API_KEY'' -H "Content-Type: application/json" "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records" 2>/dev/null || echo '')"
+  results="$(curl -q -LSs -X GET -H "Content-Type: application/json" -H 'X-Auth-Key: '$CLOUDFLARE_API_KEY'' -H 'X-auth-email: '$CLOUDFLARE_EMAIL'' "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records" 2>/dev/null || echo '')"
   if echo "$results" | jq '.success' 2>/dev/null | grep -q 'false'; then
     exitCode=1
   else
@@ -376,30 +381,30 @@ __api() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __api_full() {
   local results=""
-  results="$(curl -q -LSs -X GET -H 'Authorization: Bearer '$CLOUDFLARE_API_KEY'' -H "Content-Type: application/json" "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records" 2>/dev/null || echo '')"
+  results="$(curl -q -LSs -X GET -H "Content-Type: application/json" -H 'X-Auth-Key: '$CLOUDFLARE_API_KEY'' -H 'X-auth-email: '$CLOUDFLARE_EMAIL'' "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records" 2>/dev/null || echo '')"
   #echo "$results" | jq '.result|.[]'|jq -rc '{name:.name,type:.type,content:.content,proxiable:.proxiable,proxied:.proxied}
   echo "$results" | jq '.result|.[]'
   return ${exitCode:-0}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __delete_record() {
-  local results=""
+  local exitStatus=0 results=""
   printf_blue "Attempting to delete host"
-  results="$(curl -q -LSs -X DELETE -H "Authorization: Bearer '$CLOUDFLARE_API_KEY" -H "Content-Type: application/json" "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records/$RECORD_ID" 2>/dev/null || echo '')"
+  results="$(curl -q -LSs -X DELETE -H "Content-Type: application/json" -H 'X-Auth-Key: '$CLOUDFLARE_API_KEY'' -H 'X-auth-email: '$CLOUDFLARE_EMAIL'' "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records/$RECORD_ID" 2>/dev/null || echo '')"
   echo "$results" >"$CLOUDFLARE_TEMP_FILE"
   __message "Successfully deleted $CLOUDFLARE_HOSTNAME"
-  return ${exitCode:-0}
+  return $exitStatus
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __bulk_delete() {
   local exitStatus=0 results="" name=""
   printf_cyan "Getting data for $CLOUDFLARE_ZONE"
-  results="$(curl -q -LSs -X GET -H 'Authorization: Bearer '$CLOUDFLARE_API_KEY'' -H "Content-Type: application/json" "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records?per_page=1000" 2>/dev/null | jq '.result| .[]' | jq -rc '{ "name":.name,"id":.id }' || echo '')"
+  results="$(curl -q -LSs -X GET -H "Content-Type: application/json" -H 'X-Auth-Key: '$CLOUDFLARE_API_KEY'' -H 'X-auth-email: '$CLOUDFLARE_EMAIL'' "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records?per_page=1000" 2>/dev/null | jq '.result| .[]' | jq -rc '{ "name":.name,"id":.id }' | grep "${1:-^}" || echo '')"
   [ -n "$results" ] || printf_exit 2 0 "There doesn't seem to be any records for zone: $CLOUDFLARE_ZONE"
   for dns_record in $(echo "$results" | jq -rc '.id'); do
     name="$(echo "$results" | grep "$dns_record" | jq -rc '.name')"
     printf_blue "Attempting to delete host: $name"
-    curl -q -LSs -X DELETE -H "Content-Type: application/json" -H 'Authorization: Bearer '$CLOUDFLARE_API_KEY'' "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records/$dns_record" >"$CLOUDFLARE_TEMP_FILE" || exitStatus=$((1 + exitStatus))
+    curl -q -LSs -X DELETE -H "Content-Type: application/json" -H 'X-Auth-Key: '$CLOUDFLARE_API_KEY'' -H 'X-auth-email: '$CLOUDFLARE_EMAIL'' "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records/$dns_record" >"$CLOUDFLARE_TEMP_FILE" || exitStatus=$((1 + exitStatus))
     __message "Successfully deleted id: $dns_record"
     [ -f "$CLOUDFLARE_TEMP_FILE" ] && rm -Rf "$CLOUDFLARE_TEMP_FILE"
   done
@@ -411,32 +416,37 @@ __create_record() {
   CLOUDFLARE_DNS_TYPE="${2:-$CLOUDFLARE_DNS_TYPE}"
   CLOUDFLARE_PROXY="${3:-$CLOUDFLARE_PROXY}"
   [ "$CLOUDFLARE_PROXY" = "yes" ] && CLOUDFLARE_PROXY=true
+  [ "$CLOUDFLARE_PROXY" = "no" ] && CLOUDFLARE_PROXY=false
   printf_blue "Attempting to create a new host"
-  curl -q -LSs -X POST -H "Content-Type: application/json" -H 'Authorization: Bearer '$CLOUDFLARE_API_KEY'' --data "{\"type\":\"${CLOUDFLARE_DNS_TYPE}\",\"name\":\"${CLOUDFLARE_HOSTNAME}\",\"content\":\"${CLOUDFLARE_IP_ADDR}\",\"ttl\":120,\"priority\":0,\"proxied\":${CLOUDFLARE_PROXY}}" "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records" 2>/dev/null >"$CLOUDFLARE_TEMP_FILE"
+  curl -q -LSs -X POST -H "Content-Type: application/json" -H 'X-Auth-Key: '$CLOUDFLARE_API_KEY'' -H 'X-auth-email: '$CLOUDFLARE_EMAIL'' --data "{\"type\":\"${CLOUDFLARE_DNS_TYPE}\",\"name\":\"${CLOUDFLARE_HOSTNAME}\",\"content\":\"${CLOUDFLARE_IP_ADDR}\",\"ttl\":1200,\"priority\":0,\"proxied\":${CLOUDFLARE_PROXY}}" "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records" 2>/dev/null >"$CLOUDFLARE_TEMP_FILE"
   __message "Successfully created ${CLOUDFLARE_HOSTNAME}"
   return ${exitCode:-0}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __update_record() {
+  local exitStatus=0
   CLOUDFLARE_HOSTNAME="${1:-$CLOUDFLARE_HOSTNAME}"
-  CLOUDFLARE_ZONE="${2:-$CLOUDFLARE_ZONE}"
-  CLOUDFLARE_PROXY="${3:-$CLOUDFLARE_PROXY}"
+  CLOUDFLARE_PROXY="${2:-$CLOUDFLARE_PROXY}"
   [ "$CLOUDFLARE_PROXY" = "yes" ] && CLOUDFLARE_PROXY=true
+  [ "$CLOUDFLARE_PROXY" = "no" ] && CLOUDFLARE_PROXY=false
+  [ -n "$RECORD_ID" ] || printf_exit "Failed to get record is for $CLOUDFLARE_HOSTNAME"
   printf_blue "Attempting to update host"
-  curl -q -LSs -X PATCH -H 'Authorization: Bearer '$CLOUDFLARE_API_KEY'' -H "Content-Type: application/json" --data "{\"id\":\"${CLOUDFLARE_HOSTNAME}\",\"type\":\"${CLOUDFLARE_DNS_TYPE}\",\"proxied\":${CLOUDFLARE_PROXY},\"name\":\"${CLOUDFLARE_HOSTNAME}\",\"content\":\"${CLOUDFLARE_IP_ADDR}\"}" "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records/$RECORD_ID" 2>/dev/null >"$CLOUDFLARE_TEMP_FILE"
+  curl -q -LSs -X PUT -H 'X-Auth-Key: '$CLOUDFLARE_API_KEY'' -H 'X-auth-email: '$CLOUDFLARE_EMAIL'' -H "Content-Type: application/json" --data "{\"name\":\"${CLOUDFLARE_HOSTNAME}\",\"ttl\":1200,\"type\":\"${CLOUDFLARE_DNS_TYPE}\",\"proxied\":${CLOUDFLARE_PROXY},\"content\":\"${CLOUDFLARE_IP_ADDR}\"}" "$CLOUDFLARE_API_URL/zones/$ZONE_ID/dns_records/$RECORD_ID" 2>/dev/null >"$CLOUDFLARE_TEMP_FILE"
   __message "Successfully Updated ${CLOUDFLARE_HOSTNAME}"
-  return ${exitCode:-0}
+  return $exitStatus
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __cloudflare_zone() {
+  set -x
   CLOUDFLARE_ZONE="${1:-$CLOUDFLARE_ZONE}"
   CLOUDFLARE_HOSTNAME="${2:-$CLOUDFLARE_HOSTNAME}"
   CLOUDFLARE_DNS_TYPE="${3:-$CLOUDFLARE_DNS_TYPE}"
   CLOUDFLARE_PROXY="${4:-$CLOUDFLARE_PROXY}"
   CLOUDFLARE_HOSTNAME="${CLOUDFLARE_HOSTNAME:-$CLOUDFLARE_ZONE}"
+  ZONE_ID="${ZONE_ID_KEY:-$(__zone_identifier "$CLOUDFLARE_ZONE")}"
+  RECORD_ID="${RECORD_ID_KEY:-$(__record_identifier "$CLOUDFLARE_HOSTNAME")}"
   [ "$CLOUDFLARE_PROXY" = "yes" ] && CLOUDFLARE_PROXY=true
-  [ -z "$CLOUDFLARE_ZONE" ] || ZONE_ID="${ZONE_ID_KEY:-$(__zone_identifier "$CLOUDFLARE_ZONE")}"
-  [ -z "$CLOUDFLARE_HOSTNAME" ] || RECORD_ID="${RECORD_ID_KEY:-$(__record_identifier "$CLOUDFLARE_HOSTNAME")}"
+  [ "$CLOUDFLARE_PROXY" = "no" ] && CLOUDFLARE_PROXY=false
   if [ "$CLOUDFLARE_DNS_TYPE" == "CNAME" ]; then
     CLOUDFLARE_IP_ADDR="$CLOUDFLARE_ZONE"
   elif [ "$CLOUDFLARE_DNS_TYPE" == "AAAA" ]; then
@@ -447,6 +457,7 @@ __cloudflare_zone() {
   [ -n "$CLOUDFLARE_IP_ADDR" ] || CLOUDFLARE_IP_ADDR=${IP_ADDR:-$(__get_ip4)}
   [ -n "$CLOUDFLARE_PROXY" ] || CLOUDFLARE_PROXY="true"
   [ -n "$CLOUDFLARE_ZONE" ] || __usage $CLOUDFLARE_ZONE || exit 1
+  set +x
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __usage() {
@@ -545,7 +556,7 @@ SHORTOPTS=""
 SHORTOPTS+=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 LONGOPTS="completions:,config,debug,help,options,raw,version,silent,"
-LONGOPTS+=",ip:,zone:,proxy:,record:,api,key:,delete-all,id:"
+LONGOPTS+=",ip:,zone:,proxy:,record:,api,key:,delete-all,id:,bulk"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ARRAY="create update delete list verify tunnel"
 ARRAY+=""
@@ -639,6 +650,10 @@ while :; do
     SET_API="full"
     ;;
   --delete-all)
+    shift 1
+    CLOUDFLARE_BULK_DELETE="true"
+    ;;
+  --bulk)
     shift 1
     CLOUDFLARE_BULK_DELETE="true"
     ;;
@@ -752,7 +767,7 @@ create)
 update)
   shift 1
   __cloudflare_zone "$@"
-  __update_record "$CLOUDFLARE_HOSTNAME" "$CLOUDFLARE_ZONE"
+  __update_record "$CLOUDFLARE_HOSTNAME" "$CLOUDFLARE_PROXY"
   exit $?
   ;;
 
@@ -760,7 +775,7 @@ delete)
   shift 1
   __cloudflare_zone "$@"
   if [ "$CLOUDFLARE_BULK_DELETE" = "true" ]; then
-    __bulk_delete
+    __bulk_delete "$CLOUDFLARE_HOSTNAME"
   else
     __delete_record "$CLOUDFLARE_HOSTNAME"
   fi
@@ -772,9 +787,9 @@ verify)
   printf_cyan "Fetching data from: $CLOUDFLARE_API_URL"
   if [ "$1" = "id" ]; then
     shift 1
-    __cloudflare_zone "$2"
-    results="$(__record_identifier "$1")"
-    [ -n "$results" ] && printf_green "ID for $1 should be: $results" || printf_exit 2 5 "Failed to get ID for $1"
+    __cloudflare_zone "$1"
+    results="$(__record_identifier "$CLOUDFLARE_HOSTNAME")"
+    [ -n "$results" ] && printf_green "ID for $CLOUDFLARE_HOSTNAME should be: $results" || printf_exit 2 5 "Failed to get ID for $CLOUDFLARE_HOSTNAME"
   else
     __cloudflare_zone "$@"
     results="$(__api_verify)"
