🐛 FIXED: bin/corona-virus 🐛

diff --git a/bin/corona-virus b/bin/corona-virus
--- a/bin/corona-virus
+++ b/bin/corona-virus
@@ -1,20 +1,23 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 APPNAME="$(basename "$0")"
+VERSION="202108220554-git"
+RUN_USER="${SUDO_USER:-${USER}}"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-#set opts
+# Set bash options
+trap 'exitCode=${exitCode:-$?};[ -f "$CORONA_VIRUS_TEMP_FILE" ] && rm -Rf "$CORONA_VIRUS_TEMP_FILE" &>/dev/null' EXIT
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 202103200620-git
+##@Version       : 202108220554-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
 # @License       : WTFPL
 # @ReadME        : corona-virus --help
-# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Saturday, Mar 20, 2021 06:20 EDT
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, Casjays Developments
+# @Created       : Sunday, Aug 22, 2021 05:54 EDT
 # @File          : corona-virus
 # @Description   : corona-virus local stats
 # @TODO          :
@@ -40,33 +43,178 @@ fi
 user_install
 __options "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-am_i_online --error || exit 1
-__requires curl || exit 1
+# Set functions
+__list_options() { printf_custom "$1" "$2: $(echo ${3:-$ARRAY} | __sed 's|:||g;s|'$4'| '$5'|g')" 2>/dev/null; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [[ $1 = --force ]]; then
-  shift 1
-  __rm_rf "$HOME/.cache/corona-virus"
-  __curl_download https://corona-stats.online/us "$HOME/.cache/corona-virus"
-  if [ ! -f "$HOME/.cache/corona-virus" ]; then
+__gen_config() {
+  printf_green "Generating the config file in"
+  printf_green "$CORONA_VIRUS_CONFIG_DIR/$CORONA_VIRUS_CONFIG_FILE"
+  [ -d "$CORONA_VIRUS_CONFIG_DIR" ] || mkdir -p "$CORONA_VIRUS_CONFIG_DIR"
+  [ -d "$CORONA_VIRUS_CONFIG_BACKUP_DIR" ] || mkdir -p "$CORONA_VIRUS_CONFIG_BACKUP_DIR"
+  [ -f "$CORONA_VIRUS_CONFIG_DIR/$CORONA_VIRUS_CONFIG_FILE" ] &&
+    cp -Rf "$CORONA_VIRUS_CONFIG_DIR/$CORONA_VIRUS_CONFIG_FILE" "$CORONA_VIRUS_CONFIG_BACKUP_DIR/$CORONA_VIRUS_CONFIG_FILE.$$"
+  cat <<EOF >"$CORONA_VIRUS_CONFIG_DIR/$CORONA_VIRUS_CONFIG_FILE"
+# Settings for corona-virus
+CORONA_VIRUS_COUNTRY="${CORONA_VIRUS_COUNTRY:-USA}"
+CORONA_VIRUS_API_URL="${CORONA_VIRUS_API_URL:-https://corona-stats.online}"
+
+# Notification settings
+CORONA_VIRUS_GOOD_MESSAGE="${CORONA_VIRUS_GOOD_MESSAGE:-Everything Went OK}"
+CORONA_VIRUS_ERROR_MESSAGE="${CORONA_VIRUS_ERROR_MESSAGE:-Well that didn\'t work}"
+CORONA_VIRUS_NOTIFY_ENABLED="${CORONA_VIRUS_NOTIFY_ENABLED:-yes}"
+CORONA_VIRUS_NOTIFY_CLIENT_NAME="${NOTIFY_CLIENT_NAME:-$APPNAME}"
+CORONA_VIRUS_NOTIFY_CLIENT_ICON="${NOTIFY_CLIENT_ICON:-$CORONA_VIRUS_NOTIFY_CLIENT_ICON}"
+
+# Colorization settings
+CORONA_VIRUS_OUTPUT_COLOR="${CORONA_VIRUS_OUTPUT_COLOR:-5}"
+CORONA_VIRUS_OUTPUT_COLOR_GOOD="${CORONA_VIRUS_OUTPUT_COLOR_GOOD:-2}"
+CORONA_VIRUS_OUTPUT_COLOR_ERROR="${CORONA_VIRUS_OUTPUT_COLOR_ERROR:-1}"
+
+EOF
+  if [ -f "$CORONA_VIRUS_CONFIG_DIR/$CORONA_VIRUS_CONFIG_FILE" ]; then
+    printf_green "Your config file for corona-virus has been created"
+    true
+  else
+    printf_red "Failed to create the config file"
+    false
+  fi
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Additional functions
+__print_results() {
+  grep "$LOCATION" "$CORONA_VIRUS_CACHE_DIR/corona-virus" | sed "s/\x1b\[[0-9;]*m//g" |
+    sed "s/\s*//g ; s/║//g ; s/│/;/g" | awk -F';' '{print "😷" $3 " (" $9") 💀" $5 " 🏠("$7"%)"}'
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Default variables
+exitCode="0"
+CORONA_VIRUS_CACHE_DIR="${CORONA_VIRUS_CACHE_DIR:-$HOME/.cache/corona-virus}"
+CORONA_VIRUS_CONFIG_DIR="${CORONA_VIRUS_CONFIG_DIR:-$HOME/.config/myscripts/corona-virus}"
+CORONA_VIRUS_OPTIONS_DIR="${CORONA_VIRUS_OPTIONS_DIR:-$HOME/.local/share/myscripts/corona-virus/options}"
+CORONA_VIRUS_CONFIG_BACKUP_DIR="${CORONA_VIRUS_CONFIG_BACKUP_DIR:-$HOME/.local/share/myscripts/corona-virus/backups}"
+CORONA_VIRUS_TEMP_DIR="${CORONA_VIRUS_TEMP_DIR:-$HOME/.local/tmp/system_scripts/corona-virus}"
+CORONA_VIRUS_TEMP_FILE="${CORONA_VIRUS_TEMP_FILE:-$(mktemp $CORONA_VIRUS_TEMP_DIR/XXXXXX 2>/dev/null)}"
+CORONA_VIRUS_CONFIG_FILE="${CORONA_VIRUS_CONFIG_FILE:-settings.conf}"
+CORONA_VIRUS_GOOD_MESSAGE="${CORONA_VIRUS_GOOD_MESSAGE:-Everything Went OK}"
+CORONA_VIRUS_ERROR_MESSAGE="${CORONA_VIRUS_ERROR_MESSAGE:-Well that didn\'t work}"
+CORONA_VIRUS_NOTIFY_ENABLED="${CORONA_VIRUS_NOTIFY_ENABLED:-yes}"
+CORONA_VIRUS_NOTIFY_CLIENT_NAME="${NOTIFY_CLIENT_NAME:-$APPNAME}"
+CORONA_VIRUS_NOTIFY_CLIENT_ICON="${NOTIFY_CLIENT_ICON:-$CORONA_VIRUS_NOTIFY_CLIENT_ICON}"
+CORONA_VIRUS_OUTPUT_COLOR="${CORONA_VIRUS_OUTPUT_COLOR:-5}"
+CORONA_VIRUS_OUTPUT_COLOR_GOOD="${CORONA_VIRUS_OUTPUT_COLOR_GOOD:-2}"
+CORONA_VIRUS_OUTPUT_COLOR_ERROR="${CORONA_VIRUS_OUTPUT_COLOR_ERROR:-1}"
+CORONA_VIRUS_COUNTRY="${CORONA_VIRUS_COUNTRY:-USA}"
+CORONA_VIRUS_API_URL="${CORONA_VIRUS_API_URL:-https://corona-stats.online}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Ensure Directories exist
+[ -d "$CORONA_VIRUS_TEMP_DIR" ] || mkdir -p "$CORONA_VIRUS_TEMP_DIR" &>/dev/null
+[ -d "$CORONA_VIRUS_CACHE_DIR" ] || mkdir -p "$CORONA_VIRUS_CACHE_DIR" &>/dev/null
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Generate config files
+[ -f "$CORONA_VIRUS_CONFIG_DIR/$CORONA_VIRUS_CONFIG_FILE" ] ||
+  __gen_config &>/dev/null
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Import config
+[ -f "$CORONA_VIRUS_CONFIG_DIR/$CORONA_VIRUS_CONFIG_FILE" ] &&
+  . "$CORONA_VIRUS_CONFIG_DIR/$CORONA_VIRUS_CONFIG_FILE"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Show warn message if variables are missing
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set additional variables/Argument/Option settings
+SETARGS="$*"
+SHORTOPTS="z:"
+LONGOPTS="options,config,version,help,dir:,force"
+ARRAY=""
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -a -n "$PROG" -- "$@" 2>/dev/null)
+eval set -- "${setopts[@]}" 2>/dev/null
+while :; do
+  case $1 in
+  --options)
+    shift 1
+    [ -n "$1" ] || printf_blue "Current options for ${PROG:-$APPNAME}"
+    [ -z "$SHORTOPTS" ] || __list_options "5" "Short Options" "-$SHORTOPTS" ',' '-'
+    [ -z "$LONGOPTS" ] || __list_options "5" "Long Options" "--$LONGOPTS" ',' '--'
+    [ -z "$ARRAY" ] || __list_options "5" "Base Options" "$ARRAY" ',' ''
+    exit $?
+    ;;
+  --version)
+    shift 1
+    __version
+    exit $?
+    ;;
+  --help)
+    shift 1
+    __help
+    exit $?
+    ;;
+  --config)
+    shift 1
+    __gen_config
+    exit $?
+    ;;
+  -z | --dir)
+    CORONA_VIRUS_CWD="$2"
+    shift 2
+    ;;
+  --force)
+    shift 1
+    FORCE=true
+    ;;
+  --)
+    shift 1
+    break
+    ;;
+  esac
+done
+#set -- "$SETARGS"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Actions based on env
+if [ "$CORONA_VIRUS_NOTIFY_ENABLED" = "yes" ]; then
+  __notifications() {
+    export NOTIFY_GOOD_MESSAGE="${CORONA_VIRUS_GOOD_MESSAGE}"
+    export NOTIFY_ERROR_MESSAGE="${CORONA_VIRUS_ERROR_MESSAGE}"
+    export NOTIFY_CLIENT_NAME="${CORONA_VIRUS_NOTIFY_CLIENT_NAME}"
+    export NOTIFY_CLIENT_ICON="${CORONA_VIRUS_NOTIFY_CLIENT_ICON}"
+    notifications "$*" || return 1
+  }
+else
+  __notifications() { false; }
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Check for required applications/Network check
+cmd_exists --error --ask bash curl || exit 1 # exit 1 if not found
+#am_i_online --error || exit 1     # exit 1 if no internet
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# APP Variables overrides
+LOCATION="${1:-$CORONA_VIRUS_COUNTRY}"
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# begin main app
+if [[ "$FORCE" = "true" ]]; then
+  __rm_rf "$CORONA_VIRUS_CACHE_DIR/corona-virus"
+  __curl_download "$CORONA_VIRUS_API_URL" "$CORONA_VIRUS_CACHE_DIR/corona-virus"
+  if [ ! -f "$CORONA_VIRUS_CACHE_DIR/corona-virus" ]; then
     printf_exit "Download unsuccessful"
   fi
 fi
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [ "$(__devnull find "$HOME/.cache/corona-virus" -type f -mmin +120 -delete)" ] || [ ! -f "$HOME/.cache/corona-virus" ]; then
-  __curl_download https://corona-stats.online/us "$HOME/.cache/corona-virus"
-  if [ ! -f "$HOME/.cache/corona-virus" ]; then
+if [ "$(find "$CORONA_VIRUS_CACHE_DIR/corona-virus" -type f -mmin +120 -delete &>/dev/null)" ] || [ ! -f "$CORONA_VIRUS_CACHE_DIR/corona-virus" ]; then
+  __curl_download "$CORONA_VIRUS_API_URL" "$CORONA_VIRUS_CACHE_DIR/corona-virus"
+  if [ ! -f "$CORONA_VIRUS_CACHE_DIR/corona-virus" ]; then
     printf_exit "Download unsuccessful"
   fi
 fi
+
+results="$(__print_results)"
+if [[ -n "$results" ]]; then
+  printf_color "$LOCATION: $results\n" 8
+  __notifications "$results"
+else
+  echo "Error"
+fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-[ -n "$1" ] && LOCATION="$1" || LOCATION=USA
+# End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-printf_color "4" "$LOCATION: "
-grep "$LOCATION" "$HOME/.cache/corona-virus" |
-  sed "s/\x1b\[[0-9;]*m//g" |
-  sed "s/\s*//g ; s/║//g ; s/│/;/g" |
-  awk -F';' '{print "😷" $3 " (" $9") 💀" $5 " 🏠("$7"%)"}'
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# end
+# lets exit with code
+exit ${exitCode:-$?}
