🗃️ Committing everything that changed 🗃️
bin/desktopmgr

diff --git a/bin/desktopmgr b/bin/desktopmgr
--- a/bin/desktopmgr
+++ b/bin/desktopmgr
@@ -825,44 +825,48 @@ qemu)
     shift 1
     VERSION="${1:-https://repo.almalinux.org/almalinux/9/isos/x86_64/AlmaLinux-9-latest-x86_64-boot.iso}"
     VM_NAME="linux"
+    PORT="65301"
     echo "initializing qemu-$VM_NAME"
     if ! docker ps -a 2>%1 | grep -q qemu-$VM_NAME; then
-      docker run --quiet --detach --memory=4G -it --privileged --name qemu-$VM_NAME --publish 65301:8006 --device=/dev/kvm --volume "$HOME/.local/share/qemu/$VM_NAME":/storage --cap-add NET_ADMIN --stop-timeout 120 --env BOOT="${VERSION}" --env DISK_SIZE="100G" --env RAM_SIZE="4G" --env CPU_CORES="2" qemux/qemu-docker
-      [ $? -eq 0 ] || docker rm -f "$VM_NAME" >/dev/null 2>&1
+      docker run --quiet --detach --memory=4G -it --privileged --name qemu-$VM_NAME --publish $PORT:8006 --device=/dev/kvm --volume "$HOME/.local/share/qemu/$VM_NAME":/storage --cap-add NET_ADMIN --stop-timeout 120 --env BOOT="${VERSION}" --env DISK_SIZE="100G" --env RAM_SIZE="4G" --env CPU_CORES="2" qemux/qemu-docker
+      retVal=$?
     fi
-    echo "Go to http://$CURRENT_IP_4:65301 and open docker logs --follow qemu-$VM_NAME"
+    [ $retVal -eq 0 ] && echo "Go to http://$CURRENT_IP_4:$PORT and open docker logs --follow qemu-$VM_NAME" || { echo "Failed to create $VM_NAME" && docker rm -f "$VM_NAME" >/dev/null 2>&1; }
     ;;
   win | windows)
     shfit 1
     VERSION="${1:-ventura}"
     VM_NAME="windows"
+    PORT="65302"
     echo "initializing qemu-$VM_NAME"
     if ! docker ps -a 2>%1 | grep -q qemu-$VM_NAME; then
-      docker run --quiet --detach --memory=4G -it --privileged --name qemu-$VM_NAME --publish 65302:8006 --device=/dev/kvm --cap-add NET_ADMIN --volume "$HOME/.local/share/qemu/$VM_NAME":/storage --stop-timeout 120 --env VERSION="${VERSION}" --env DISK_SIZE="100G" --env RAM_SIZE="4G" --env CPU_CORES="2" dockurr/windows
-      [ $? -eq 0 ] || docker rm -f "$VM_NAME" >/dev/null 2>&1
+      docker run --quiet --detach --memory=4G -it --privileged --name qemu-$VM_NAME --publish $PORT:8006 --device=/dev/kvm --cap-add NET_ADMIN --volume "$HOME/.local/share/qemu/$VM_NAME":/storage --stop-timeout 120 --env VERSION="${VERSION}" --env DISK_SIZE="100G" --env RAM_SIZE="4G" --env CPU_CORES="2" dockurr/windows
+      retVal=$?
     fi
-    echo "Go to http://$CURRENT_IP_4:65302 and open docker logs --follow qemu-$VM_NAME"
+    [ $retVal -eq 0 ] && echo "Go to http://$CURRENT_IP_4:$PORT and open docker logs --follow qemu-$VM_NAME" || { echo "Failed to create $VM_NAME" && docker rm -f "$VM_NAME" >/dev/null 2>&1; }
     ;;
   mac | macos)
     shfit 1
     VERSION="${1:-10}"
     VM_NAME="macos"
+    PORT="65303"
     echo "initializing qemu-$VM_NAME"
     if ! docker ps -a 2>%1 | grep -q qemu-$VM_NAME; then
-      docker run --quiet --detach --memory=4G -it --privileged --name qemu-$VM_NAME --publish 65303:8006 --device=/dev/kvm --cap-add NET_ADMIN --volume "$HOME/.local/share/qemu/$VM_NAME":/storage --stop-timeout 120 --env VERSION="${VERSION}" --env DISK_SIZE="100G" --env RAM_SIZE="4G" --env CPU_CORES="2" dockurr/macos
-      [ $? -eq 0 ] || docker rm -f "$VM_NAME" >/dev/null 2>&1
+      docker run --quiet --detach --memory=4G -it --privileged --name qemu-$VM_NAME --publish $PORT:8006 --device=/dev/kvm --cap-add NET_ADMIN --volume "$HOME/.local/share/qemu/$VM_NAME":/storage --stop-timeout 120 --env VERSION="${VERSION}" --env DISK_SIZE="100G" --env RAM_SIZE="4G" --env CPU_CORES="2" dockurr/macos
+      retVal=$?
     fi
-    echo "Go to http://$CURRENT_IP_4:65303 and open docker logs --follow qemu-$VM_NAME"
+    [ $retVal -eq 0 ] && echo "Go to http://$CURRENT_IP_4:$PORT and open docker logs --follow qemu-$VM_NAME" || { echo "Failed to create $VM_NAME" && docker rm -f "$VM_NAME" >/dev/null 2>&1; }
     ;;
   arm | arm64)
     VERSION="${1:-https://downloads.raspberrypi.com/raspios_full_armhf/images/raspios_full_armhf-2024-07-04/2024-07-04-raspios-bookworm-armhf-full.img.xz}"
     VM_NAME="arm"
+    PORT="65304"
     echo "initializing qemu-$VM_NAME"
     if ! docker ps -a 2>%1 | grep -q qemu-$VM_NAME; then
-      docker run --quiet --detach --memory=4G -it --privileged --name qemu-$VM_NAME --publish 65304:8006 --device=/dev/kvm --volume "$HOME/.local/share/qemu/$VM_NAME":/storage --cap-add NET_ADMIN --stop-timeout 120 --env BOOT="${VERSION}" --env DISK_SIZE="100G" --env RAM_SIZE="4G" --env CPU_CORES="2" qemux/qemu-arm
-      [ $? -eq 0 ] || docker rm -f "$VM_NAME" >/dev/null 2>&1
+      docker run --quiet --detach --memory=4G -it --privileged --name qemu-$VM_NAME --publish $PORT:8006 --device=/dev/kvm --volume "$HOME/.local/share/qemu/$VM_NAME":/storage --cap-add NET_ADMIN --stop-timeout 120 --env BOOT="${VERSION}" --env DISK_SIZE="100G" --env RAM_SIZE="4G" --env CPU_CORES="2" qemux/qemu-arm
+      retVal=$?
     fi
-    echo "Go to http://$CURRENT_IP_4:65304 and open docker logs --follow qemu-$VM_NAME"
+    [ $retVal -eq 0 ] && echo "Go to http://$CURRENT_IP_4:$PORT and open docker logs --follow qemu-$VM_NAME" || { echo "Failed to create $VM_NAME" && docker rm -f "$VM_NAME" >/dev/null 2>&1; }
     ;;
   esac
   ;;
