🗃️ Committing everything that changed 🗃️
bin/dockermgr

diff --git a/bin/dockermgr b/bin/dockermgr
--- a/bin/dockermgr
+++ b/bin/dockermgr
@@ -160,6 +160,7 @@ __container_is_running() { __docker ps -a -q -f status=running -f name=^/$1$ | g
 __swap_status() { swapon -s 2>&1 | grep -q "$1" && echo 'enabled' || false; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __container_name() { docker ps -a 2>&1 | grep -Ew ''$1'|'$1'-*' | awk '{print $NF}' | grep '^' || return 1; }
+__docker_manifest_log() { [ $1 -eq 0 ] && rm -Rf "$DOCKERMGR_LOG_DIR/$2.log" || { [ -f "$DOCKERMGR_LOG_DIR/$2.log" ] && cat "$DOCKERMGR_LOG_DIR/$2.log" | printf_readline && false; } || exit 1; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __get_arch() {
   local uname="$(uname -s)"
@@ -175,7 +176,24 @@ __get_arch() {
   [ -n "$arch" ] && [ -n "$osname" ] && export arch osname || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__docker_manifest_log() { [ $1 -eq 0 ] && rm -Rf "$DOCKERMGR_LOG_DIR/$2.log" || { [ -f "$DOCKERMGR_LOG_DIR/$2.log" ] && cat "$DOCKERMGR_LOG_DIR/$2.log" | printf_readline && false; } || exit 1; }
+__update_repo_info() {
+  local image="${1}" && shift
+  local token="$(<"$DOCKERMGR_CACHE_DIR/token")"
+  local info=("${@:-From ${set_push:-$image}}")
+  local code=$(jq -n --arg msg "${info[@]}" \
+    '{"registry":"registry-1.docker.io","full_description": $msg }' |
+    curl -s -o /dev/null -L -w "%{http_code}" \
+      https://cloud.docker.com/v2/repositories/"${image}"/ \
+      -d @- -X PATCH \
+      -H "Content-Type: application/json" \
+      -H "Authorization: JWT ${token}")
+  if [[ "${code}" = "200" ]]; then
+    printf "Successfully pushed README to Docker Hub"
+  else
+    printf "Unable to push README to Docker Hub, response code: %s\n" "${code}"
+    return 1
+  fi
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __registry_delete_tag() {
   if [ -f "$DOCKERMGR_CACHE_DIR/token" ]; then
@@ -239,7 +257,7 @@ __create_manifest() {
   for platform in $platforms; do
     local set_tag="$tag"
     local new_tag="$set_tag-$platform"
-    local set_push="${push//:*/}:${tag_push//*:/}-$platform"
+    set_push="${push//:*/}:${tag_push//*:/}-$platform"
     printf_cyan "Attempting to build $image$tag for platform: $platform"
     echo "FROM --platform="linux/$platform" $image$tag" | docker build --pull -t $set_push - 2>"$DOCKERMGR_LOG_DIR/$manifest_log_file.log" >/dev/null && amend+="--amend $set_push " delete_tag+="$set_push " || code=1
     [ $code -ne 0 ] && printf_red "Failed to build $set_push" && __docker_manifest_log $code "$name"
@@ -266,7 +284,7 @@ __create_manifest() {
     fi
     [ -n "$local_name" ] && docker rmi $local_name >/dev/null 2>>"$DOCKERMGR_LOG_DIR/$manifest_log_file.log" && printf_cyan "🦄 Deleted local image $push:$tag with id: $local_name 🦄"
   done
-
+  __update_repo_info "$push"
   [ $code -eq 0 ] && printf_green "😸 Successfully created/updated $push 😸" || printf_red "😿 Failed to create/update $push 😿"
   return $code
 }
