🗃️  Committing everything that changed 🗃️
bin/bin/dockerrun
bin/dockerrun

diff --git a/bin/dockerrun b/bin/dockerrun
--- a/bin/dockerrun
+++ b/bin/dockerrun
@@ -1,13 +1,14 @@
 #!/usr/bin/env bash
 # shellcheck shell=bash
+# shellcheck disable=SC2317
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version           :  202208052209-git
+##@Version           :  202304191255-git
 # @@Author           :  Jason Hempstead
 # @@Contact          :  jason@casjaysdev.com
 # @@License          :  WTFPL
 # @@ReadME           :  dockerrun --help
-# @@Copyright        :  Copyright: (c) 2022 Jason Hempstead, Casjays Developments
-# @@Created          :  Friday, Aug 05, 2022 22:09 EDT
+# @@Copyright        :  Copyright: (c) 2023 Jason Hempstead, Casjays Developments
+# @@Created          :  Wednesday, Apr 19, 2023 12:55 EDT
 # @@File             :  dockerrun
 # @@Description      :  run docker image
 # @@Changelog        :  New script
@@ -19,7 +20,7 @@
 # @@Template         :  bash/system
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 APPNAME="$(basename "$0" 2>/dev/null)"
-VERSION="202208052209-git"
+VERSION="202304191255-git"
 HOME="${USER_HOME:-$HOME}"
 USER="${SUDO_USER:-$USER}"
 RUN_USER="${SUDO_USER:-$USER}"
@@ -60,33 +61,33 @@ user_install && __options "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Send all output to /dev/null
 __devnull() {
-  tee &>/dev/null && exitCode=0 || exitCode=1
-  return ${exitCode:-0}
+  tee &>/dev/null && DOCKERRUN_EXIT_STATUS=0 || DOCKERRUN_EXIT_STATUS=1
+  return ${DOCKERRUN_EXIT_STATUS:-0}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
 # Send errors to /dev/null
 __devnull2() {
   [ -n "$1" ] && local cmd="$1" && shift 1 || return 1
-  eval $cmd "$*" 2>/dev/null && exitCode=0 || exitCode=1
-  return ${exitCode:-0}
+  eval $cmd "$*" 2>/dev/null && DOCKERRUN_EXIT_STATUS=0 || DOCKERRUN_EXIT_STATUS=1
+  return ${DOCKERRUN_EXIT_STATUS:-0}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
 # See if the executable exists
 __cmd_exists() {
-  exitCode=0
-  [ -n "$1" ] && local exitCode="" || return 0
+  DOCKERRUN_EXIT_STATUS=0
+  [ -n "$1" ] && local DOCKERRUN_EXIT_STATUS="" || return 0
   for cmd in "$@"; do
-    builtin command -v "$cmd" &>/dev/null && exitCode+=$(($exitCode + 0)) || exitCode+=$(($exitCode + 1))
+    builtin command -v "$cmd" &>/dev/null && DOCKERRUN_EXIT_STATUS+=$(($DOCKERRUN_EXIT_STATUS + 0)) || DOCKERRUN_EXIT_STATUS+=$(($DOCKERRUN_EXIT_STATUS + 1))
   done
-  [ $exitCode -eq 0 ] || exitCode=3
-  return ${exitCode:-0}
+  [ $DOCKERRUN_EXIT_STATUS -eq 0 ] || DOCKERRUN_EXIT_STATUS=3
+  return ${DOCKERRUN_EXIT_STATUS:-0}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Check for a valid internet connection
 __am_i_online() {
-  local exitCode=0
-  curl -q -LSsfI --max-time 2 --retry 1 "${1:-http://1.1.1.1}" 2>&1 | grep -qi 'server:.*cloudflare' || exitCode=4
-  return ${exitCode:-0}
+  local DOCKERRUN_EXIT_STATUS=0
+  curl -q -LSsfI --max-time 1 --retry 0 "${1:-http://1.1.1.1}" 2>&1 | grep -qi 'server:.*cloudflare' || DOCKERRUN_EXIT_STATUS=4
+  return ${DOCKERRUN_EXIT_STATUS:-0}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # colorization
@@ -124,7 +125,8 @@ __gen_config() {
     cp -Rf "$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE" "$DOCKERRUN_CONFIG_BACKUP_DIR/$DOCKERRUN_CONFIG_FILE.$$"
   cat <<EOF >"$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE"
 # Settings for dockerrun
-DOCKERRUN_DOCKER_BIN="${DOCKERRUN_DOCKER_BIN:-}"
+DOCKER_RUN_DOCKER_BIN="${DOCKER_RUN_DOCKER_BIN:-}"
+DOCKER_RUN_DEFAULT_IMAGE="${DOCKER_RUN_DEFAULT_IMAGE:-}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Color Settings
 DOCKERRUN_OUTPUT_COLOR_1="${DOCKERRUN_OUTPUT_COLOR_1:-}"
@@ -147,12 +149,12 @@ EOF
   if [ -f "$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE" ]; then
     [ "$INIT_CONFIG" = "TRUE" ] || printf_green "Your config file for $APPNAME has been created"
     . "$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE"
-    exitCode=0
+    DOCKERRUN_EXIT_STATUS=0
   else
     printf_red "Failed to create the config file"
-    exitCode=1
+    DOCKERRUN_EXIT_STATUS=1
   fi
-  return ${exitCode:-0}
+  return ${DOCKERRUN_EXIT_STATUS:-0}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Help function - Align to 50
@@ -162,6 +164,7 @@ __help() {
   __printf_head "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
   __printf_line "Usage: dockerrun [containerID,containerName] [commands] [image]"
   __printf_line "alpine /bin/sh alpine           - Runs the alpine container with sh"
+  __printf_line "--dir                           - Sets the working directory"
   __printf_head "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
   __printf_opts "Other Options"
   __printf_head "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
@@ -173,6 +176,8 @@ __help() {
   __printf_line "--raw                           - Removes all formatting on output"
   __printf_head "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
 }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__grep() { grep "$@" 2>/dev/null; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Is current user root
 __user_is_root() {
@@ -234,58 +239,58 @@ __sudo() {
   if __sudoif; then
     export PATH="$PATH"
     $SUDO ${OPTS:-} $CMD $CMD_ARGS && true || false
-    exitCode=$?
+    DOCKERRUN_EXIT_STATUS=$?
   else
     printf '%s\n' "This requires root to run"
-    exitCode=1
+    DOCKERRUN_EXIT_STATUS=1
   fi
-  return ${exitCode:-1}
+  return ${DOCKERRUN_EXIT_STATUS:-0}
 }
 # End of sudo functions
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __trap_exit() {
-  exitCode=${exitCode:-0}
+  DOCKERRUN_EXIT_STATUS=${DOCKERRUN_EXIT_STATUS:-0}
   [ -f "$DOCKERRUN_TEMP_FILE" ] && rm -Rf "$DOCKERRUN_TEMP_FILE" &>/dev/null
   if builtin type -t __trap_exit_local | grep -q 'function'; then __trap_exit_local; fi
-  return $exitCode
+  return $DOCKERRUN_EXIT_STATUS
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # User defined functions
-__docker() {
-  eval $DOCKERRUN_DOCKER_BIN "$*"
-  return $?
-}
+__docker_exec() { $DOCKER_RUN_DOCKER_BIN exec --tty --interactive "$DOCKER_RUN_NAME" $DOCKER_RUN_EXEC || return 1; }
+__docker_run() { $DOCKER_RUN_DOCKER_BIN run -d --restart always --network $DOCKER_RUN_NETWORK -it --name "$DOCKER_RUN_NAME" $DOCKER_RUN_OPTS $DOCKER_RUN_MOUNTS $DOCKER_RUN_PORTS "$DOCKER_RUN_IMAGE" >/dev/null 2>"$DOCKERRUN_TEMP_FILE" && sleep 10 || return 1; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__execute_dockerrun() {
-  NAME="$(echo "$1" | sed 's/[!@#\$%^&*():]//g')"
-  [ -n "${NAME:-$1}" ] && shift 1 || printf_exit "Please provide the container name or ID"
-  [ -n "$1" ] && COMMAND="$1" || COMMAND="/bin/bash"
-  [ -n "$2" ] && IMAGE="$2" || IMAGE="casjaysdevdocker/alpine"
-  if [ "$(__docker ps -q -f status=running -f name=^/${NAME}$)" ]; then
-    __docker container exec -it "$NAME" "${COMMAND}"
-  elif [ $# -eq 2 ]; then
-    __docker run -d --network host -it --name "$NAME" --restart always "$IMAGE" &&
-      __docker container exec -it "$NAME" "${COMMAND}"
-  elif [ $# -eq 3 ]; then
-    __docker run -d --network host -it --name "$NAME" --restart always "$IMAGE" &&
-      __docker container exec -it "$NAME" "${COMMAND}"
-  else
-    printf_red "Usage: $APPNAME [containerID,containerName] [commands] [image]"
-    printf_exit "$NAME either doesn't exist or is not running"
-  fi
-  return $?
+__create_volume() {
+  local mounts=()
+  for volume in "$DOCKER_RUN_MOUNTS"; do
+    if echo "$volume" | grep -q ':'; then
+      host="$(echo "$volume" | awk -F ':' '{print $1}' | sed 's|^/||g')"
+      container="$(echo "$volume" | awk -F ':' '{print $2}' | sed 's|^/||g')"
+    else
+      host="$DOCKERRUN_TEMP_DIR/$NAME/$(echo "$volume" | sed 's|^/||g')"
+      container="$(echo "$volume" | sed 's|^/||g')"
+    fi
+    mounts+=("--volume $host:/$container")
+  done
+  DOCKER_RUN_MOUNTS="${mounts[*]}"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # User defined variables/import external variables
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Default exit code
+DOCKERRUN_EXIT_STATUS=0
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Application Folders
-DOCKERRUN_CONFIG_FILE="${DOCKERRUN_CONFIG_FILE:-settings.conf}"
 DOCKERRUN_CONFIG_DIR="${DOCKERRUN_CONFIG_DIR:-$HOME/.config/myscripts/dockerrun}"
 DOCKERRUN_CONFIG_BACKUP_DIR="${DOCKERRUN_CONFIG_BACKUP_DIR:-$HOME/.local/share/myscripts/dockerrun/backups}"
 DOCKERRUN_LOG_DIR="${DOCKERRUN_LOG_DIR:-$HOME/.local/log/dockerrun}"
+DOCKERRUN_RUN_DIR="${DOCKERRUN_RUN_DIR:-$HOME/.local/run/system_scripts/$DOCKERRUN_SCRIPTS_PREFIX}"
 DOCKERRUN_TEMP_DIR="${DOCKERRUN_TEMP_DIR:-$HOME/.local/tmp/system_scripts/dockerrun}"
 DOCKERRUN_CACHE_DIR="${DOCKERRUN_CACHE_DIR:-$HOME/.cache/dockerrun}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# File settings
+DOCKERRUN_CONFIG_FILE="${DOCKERRUN_CONFIG_FILE:-settings.conf}"
+DOCKERRUN_LOG_ERROR_FILE="${DOCKERRUN_LOG_ERROR_FILE:-$DOCKERRUN_LOG_DIR/error.log}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Color Settings
 DOCKERRUN_OUTPUT_COLOR_1="${DOCKERRUN_OUTPUT_COLOR_1:-33}"
@@ -304,7 +309,9 @@ DOCKERRUN_NOTIFY_CLIENT_ICON="${DOCKERRUN_NOTIFY_CLIENT_ICON:-notification-new}"
 DOCKERRUN_NOTIFY_CLIENT_URGENCY="${DOCKERRUN_NOTIFY_CLIENT_URGENCY:-normal}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Additional Variables
-DOCKERRUN_DOCKER_BIN="${DOCKERRUN_DOCKER_BIN:-sudo docker}"
+DOCKER_RUN_DOCKER_BIN="${DOCKER_RUN_DOCKER_BIN:-docker}"
+DOCKER_RUN_DEFAULT_IMAGE="${DOCKER_RUN_DEFAULT_IMAGE:-casjaysdev/alpine}"
+DOCKER_RUN_DEFAULT_MOUNTS="app data config "
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Generate config files
 [ -f "$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE" ] || [ "$*" = "--config" ] || INIT_CONFIG="${INIT_CONFIG:-TRUE}" __gen_config ${SETARGS:-$@}
@@ -313,6 +320,7 @@ DOCKERRUN_DOCKER_BIN="${DOCKERRUN_DOCKER_BIN:-sudo docker}"
 [ -f "$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE" ] && . "$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Ensure Directories exist
+[ -d "$DOCKERRUN_RUN_DIR" ] || mkdir -p "$DOCKERRUN_RUN_DIR" |& __devnull
 [ -d "$DOCKERRUN_LOG_DIR" ] || mkdir -p "$DOCKERRUN_LOG_DIR" |& __devnull
 [ -d "$DOCKERRUN_TEMP_DIR" ] || mkdir -p "$DOCKERRUN_TEMP_DIR" |& __devnull
 [ -d "$DOCKERRUN_CACHE_DIR" ] || mkdir -p "$DOCKERRUN_CACHE_DIR" |& __devnull
@@ -350,8 +358,8 @@ SETARGS=("$@")
 SHORTOPTS=""
 SHORTOPTS+=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-LONGOPTS="completions:,config,debug,help,options,raw,version,silent,"
-LONGOPTS+=""
+LONGOPTS="completions:,config,debug,dir:,help,options,raw,version,silent,force"
+LONGOPTS+=",network:,mount:,docker:,publish:"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ARRAY=""
 ARRAY+=""
@@ -421,6 +429,28 @@ while :; do
     shift 1
     DOCKERRUN_SILENT="true"
     ;;
+  --dir)
+    CWD_IS_SET="TRUE"
+    DOCKERRUN_CWD="$2"
+    [ -d "$DOCKERRUN_CWD" ] || mkdir -p "$DOCKERRUN_CWD" |& __devnull
+    shift 2
+    ;;
+  --network)
+    DOCKER_RUN_SET_NETWORK="$2"
+    shift 2
+    ;;
+  --docker)
+    DOCKER_RUN_SET_OPTS+=("$2")
+    shift 2
+    ;;
+  --mount)
+    DOCKER_RUN_SET_MOUNTS+=("$2")
+    shift 2
+    ;;
+  --publish)
+    DOCKER_RUN_SET_PORTS+=("--publish $2")
+    shift 2
+    ;;
   --)
     shift 1
     break
@@ -454,28 +484,60 @@ DOCKERRUN_CWD="$(realpath "${DOCKERRUN_CWD:-$PWD}" 2>/dev/null)"
 export DOCKERRUN_CWD
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set actions based on variables
-
+[ -n "$1" ] || printf_exit "Please provide the container name or ID"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Check for required applications/Network check
 #requiresudo "$0" "$@" || exit 2     # exit 2 if errors
-#cmd_exists --error --ask bash || exit 3 # exit 3 if not found
+cmd_exists --error --ask bash || exit 3 # exit 3 if not found
 #am_i_online --error || exit 4           # exit 4 if no internet
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # APP Variables overrides
-
+DOCKER_RUN_NAME="$1"
+DOCKER_RUN_EXEC="${2:-/usr/bin/env sh}"
+DOCKER_RUN_PORTS="${DOCKER_RUN_SET_PORTS[*]:--P}"
+DOCKER_RUN_NETWORK="${DOCKER_RUN_SET_NETWORK:-bridge}"
+DOCKER_RUN_OPTS="${DOCKER_RUN_SET_OPTS[*]} --privileged"
+DOCKER_RUN_MOUNTS="${DOCKER_RUN_DEFAULT_MOUNTS[*]} ${DOCKER_RUN_SET_MOUNTS[*]}"
+if [ $# -eq 1 ]; then
+  DOCKER_RUN_IMAGE="$DOCKER_RUN_DEFAULT_IMAGE"
+elif [ $# -eq 2 ]; then
+  DOCKER_RUN_IMAGE="$2" DOCKER_RUN_EXEC="$3"
+elif [ $# -eq 3 ]; then
+  DOCKER_RUN_IMAGE="$2"
+else
+  printf_red "Usage: $APPNAME [containerID,containerName] [commands] [image]"
+  printf_exit "$DOCKER_RUN_NAME either doesn't exist or is not running"
+fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Actions based on env
-__cmd_exists docker || printf_exit "docker is not installed: run dockermgr init"
+DOCKER_RUN_NAME="$(echo "$DOCKER_RUN_NAME" | sed 's/[!@#\$%^&*():]//g')"
+DOCKER_RUN_CONTAINER_EXISTS="$($DOCKER_RUN_DOCKER_BIN ps -a 2>&1 | grep "$DOCKER_RUN_NAME" || echo '')"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Export variables
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # begin main app
-__execute_dockerrun "$@"
+if [ -n "$($DOCKER_RUN_DOCKER_BIN ps -q -f status=running -f name=^/${DOCKER_RUN_NAME}$)" ]; then
+  __docker_exec
+elif [ -n "$DOCKER_RUN_CONTAINER_EXISTS" ]; then
+  printf_exit "The container exists, however, it does not seem to be running"
+else
+  printf_cyan "Creating and starting $DOCKER_RUN_NAME"
+  __create_volume
+  if __docker_run; then
+    printf_blue "Your container has been created"
+  else
+    printf_return "Failed to created the container: $(tail -n1 "$DOCKERRUN_TEMP_FILE" | sed 's|docker: Error.*daemon: ||g;s|\. .*||g;s|: .*||g')"
+  fi
+fi
+DOCKERRUN_EXIT_STATUS=$?
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set exit code
-exitCode="${exitCode:-0}"
+DOCKERRUN_EXIT_STATUS="${DOCKERRUN_EXIT_STATUS:-0}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # lets exit with code
-exit ${exitCode:-0}
+exit ${DOCKERRUN_EXIT_STATUS:-0}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # ex: ts=2 sw=2 et filetype=sh
