🐛 FIXED: bin/dockerrun 🐛

diff --git a/bin/dockerrun b/bin/dockerrun
--- a/bin/dockerrun
+++ b/bin/dockerrun
@@ -1,20 +1,23 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 APPNAME="$(basename "$0")"
+VERSION="202108190117-git"
+RUN_USER="${SUDO_USER:-${USER}}"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-#set opts
+# Set bash options
+trap 'exitCode=${exitCode:-$?};[ -f "$DOCKERRUN_TEMP_FILE" ] && rm -Rf "$DOCKERRUN_TEMP_FILE" &>/dev/null' EXIT
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 202103200646-git
+##@Version       : 202108190117-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
 # @License       : WTFPL
 # @ReadME        : dockerrun --help
-# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Saturday, Mar 20, 2021 06:46 EDT
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, Casjays Developments
+# @Created       : Thursday, Aug 19, 2021 01:17 EDT
 # @File          : dockerrun
 # @Description   : run docker image
 # @TODO          :
@@ -37,27 +40,157 @@ else
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # user system devenv dfmgr dockermgr fontmgr iconmgr pkmgr systemmgr thememgr wallpapermgr
-dockermgr_install
+user_install
 __options "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__requires docker
-__requiresudo true
+# Set functions
+__list_options() { printf_custom "$1" "$2: $(echo ${3:-$ARRAY} | __sed 's|:||g;s|'$4'| '$5'|g')" 2>/dev/null; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# check for needed applications
-if cmd_exists docker || am_i_online --error; then
-  bash -c "$(__curl https://get.docker.com)" || printf_exit "Installation has failed"
-fi
+__gen_config() {
+  printf_green "Generating the config file in"
+  printf_green "$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE"
+  [ -d "$DOCKERRUN_CONFIG_DIR" ] || mkdir -p "$DOCKERRUN_CONFIG_DIR"
+  [ -d "$DOCKERRUN_CONFIG_BACKUP_DIR" ] || mkdir -p "$DOCKERRUN_CONFIG_BACKUP_DIR"
+  [ -f "$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE" ] &&
+    cp -Rf "$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE" "$DOCKERRUN_CONFIG_BACKUP_DIR/$DOCKERRUN_CONFIG_FILE.$$"
+  cat <<EOF >"$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE"
+# Settings for dockerrun
+DOCKERRUN_DOCKER_BIN="${DOCKERRUN_DOCKER_BIN:-docker}"
+
+# Notification settings
+DOCKERRUN_GOOD_MESSAGE="${DOCKERRUN_GOOD_MESSAGE:-Everything Went OK}"
+DOCKERRUN_ERROR_MESSAGE="${DOCKERRUN_ERROR_MESSAGE:-Well that didn\'t work}"
+DOCKERRUN_NOTIFY_ENABLED="${DOCKERRUN_NOTIFY_ENABLED:-yes}"
+DOCKERRUN_NOTIFY_CLIENT_NAME="${NOTIFY_CLIENT_NAME:-$APPNAME}"
+DOCKERRUN_NOTIFY_CLIENT_ICON="${NOTIFY_CLIENT_ICON:-$DOCKERRUN_NOTIFY_CLIENT_ICON}"
+
+# Colorization settings
+DOCKERRUN_OUTPUT_COLOR="${DOCKERRUN_OUTPUT_COLOR:-5}"
+DOCKERRUN_OUTPUT_COLOR_GOOD="${DOCKERRUN_OUTPUT_COLOR_GOOD:-2}"
+DOCKERRUN_OUTPUT_COLOR_ERROR="${DOCKERRUN_OUTPUT_COLOR_ERROR:-1}"
+
+EOF
+  if [ -f "$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE" ]; then
+    printf_green "Your config file for dockerrun has been created"
+    true
+  else
+    printf_red "Failed to create the config file"
+    false
+  fi
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Main application
-NAME="$(echo $1 | sed 's/[!@#\$%^&*():]//g')"
+# Additional functions
+__docker() { eval $DOCKERRUN_DOCKER_BIN "$*"; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [ "$(sudo docker ps -q -f status=running -f name=^/${NAME}$)" ]; then
-  sudo docker container exec -it "$NAME" /bin/bash -l
+# Default variables
+exitCode="0"
+DOCKERRUN_CACHE_DIR="${DOCKERRUN_CACHE_DIR:-$HOME/.cache/dockerrun}"
+DOCKERRUN_CONFIG_DIR="${DOCKERRUN_CONFIG_DIR:-$HOME/.config/myscripts/dockerrun}"
+DOCKERRUN_OPTIONS_DIR="${DOCKERRUN_OPTIONS_DIR:-$HOME/.local/share/myscripts/dockerrun/options}"
+DOCKERRUN_CONFIG_BACKUP_DIR="${DOCKERRUN_CONFIG_BACKUP_DIR:-$HOME/.local/share/myscripts/dockerrun/backups}"
+DOCKERRUN_TEMP_DIR="${DOCKERRUN_TEMP_DIR:-$HOME/.local/tmp/system_scripts/dockerrun}"
+DOCKERRUN_TEMP_FILE="${DOCKERRUN_TEMP_FILE:-$(mktemp $DOCKERRUN_TEMP_DIR/XXXXXX 2>/dev/null)}"
+DOCKERRUN_CONFIG_FILE="${DOCKERRUN_CONFIG_FILE:-settings.conf}"
+DOCKERRUN_GOOD_MESSAGE="${DOCKERRUN_GOOD_MESSAGE:-Everything Went OK}"
+DOCKERRUN_ERROR_MESSAGE="${DOCKERRUN_ERROR_MESSAGE:-Well that didn\'t work}"
+DOCKERRUN_NOTIFY_ENABLED="${DOCKERRUN_NOTIFY_ENABLED:-yes}"
+DOCKERRUN_NOTIFY_CLIENT_NAME="${NOTIFY_CLIENT_NAME:-$APPNAME}"
+DOCKERRUN_NOTIFY_CLIENT_ICON="${NOTIFY_CLIENT_ICON:-$DOCKERRUN_NOTIFY_CLIENT_ICON}"
+DOCKERRUN_OUTPUT_COLOR="${DOCKERRUN_OUTPUT_COLOR:-5}"
+DOCKERRUN_OUTPUT_COLOR_GOOD="${DOCKERRUN_OUTPUT_COLOR_GOOD:-2}"
+DOCKERRUN_OUTPUT_COLOR_ERROR="${DOCKERRUN_OUTPUT_COLOR_ERROR:-1}"
+DOCKERRUN_DOCKER_BIN="${DOCKERRUN_DOCKER_BIN:-sudo docker}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Ensure Directories exist
+[ -d "$DOCKERRUN_TEMP_DIR" ] || mkdir -p "$DOCKERRUN_TEMP_DIR" &>/dev/null
+[ -d "$DOCKERRUN_CACHE_DIR" ] || mkdir -p "$DOCKERRUN_CACHE_DIR" &>/dev/null
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Generate config files
+[ -f "$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE" ] ||
+  __gen_config &>/dev/null
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Import config
+[ -f "$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE" ] &&
+  . "$DOCKERRUN_CONFIG_DIR/$DOCKERRUN_CONFIG_FILE"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Show warn message if variables are missing
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set additional variables/Argument/Option settings
+SETARGS="$*"
+SHORTOPTS="z:"
+LONGOPTS="options,config,version,help,dir:"
+ARRAY=""
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -a -n "$PROG" -- "$@" 2>/dev/null)
+eval set -- "${setopts[@]}" 2>/dev/null
+while :; do
+  case $1 in
+  --options)
+    shift 1
+    [ -n "$1" ] || printf_blue "Current options for ${PROG:-$APPNAME}"
+    [ -z "$SHORTOPTS" ] || __list_options "5" "Short Options" "-$SHORTOPTS" ',' '-'
+    [ -z "$LONGOPTS" ] || __list_options "5" "Long Options" "--$LONGOPTS" ',' '--'
+    [ -z "$ARRAY" ] || __list_options "5" "Base Options" "$ARRAY" ',' ''
+    exit $?
+    ;;
+  --version)
+    shift 1
+    __version
+    exit $?
+    ;;
+  --help)
+    shift 1
+    __help
+    exit $?
+    ;;
+  --config)
+    shift 1
+    __gen_config
+    exit $?
+    ;;
+  -z | --dir)
+    DOCKERRUN_CWD="$2"
+    shift 2
+    ;;
+  --)
+    shift 1
+    break
+    ;;
+  esac
+done
+#set -- "$SETARGS"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Actions based on env
+if [ "$DOCKERRUN_NOTIFY_ENABLED" = "yes" ]; then
+  __notifications() {
+    export NOTIFY_GOOD_MESSAGE="${DOCKERRUN_GOOD_MESSAGE}"
+    export NOTIFY_ERROR_MESSAGE="${DOCKERRUN_ERROR_MESSAGE}"
+    export NOTIFY_CLIENT_NAME="${DOCKERRUN_NOTIFY_CLIENT_NAME}"
+    export NOTIFY_CLIENT_ICON="${DOCKERRUN_NOTIFY_CLIENT_ICON}"
+    notifications "$*" || return 1
+  }
 else
-  sudo docker run -d --network host -it --name "$NAME" --restart always "$1" /sbin/init &&
-    sudo docker container exec -it "$NAME" /bin/bash -l
+  __notifications() { false; }
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
+# Check for required applications/Network check
+cmd_exists --error --ask bash || exit 1 # exit 1 if not found
+#am_i_online --error || exit 1     # exit 1 if no internet
+{ cmd_exists docker || am_i_online --error; } || bash -c "$(__curl https://get.docker.com)" || printf_exit "Installation has failed"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# end
+# APP Variables overrides
+NAME="$(echo "$1" | sed 's/[!@#\$%^&*():]//g')"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# begin main app
+if [ "$(__docker ps -q -f status=running -f name=^/${NAME}$)" ]; then
+  __docker container exec -it "$NAME" /bin/bash -l
+else
+  __docker run -d --network host -it --name "$NAME" --restart always "$1" /sbin/init &&
+    __docker container exec -it "$NAME" /bin/bash -l
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# End application
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# lets exit with code
+exit ${exitCode:-$?}
