🗃 Modified: bin/emojify completions/_emojify_completions  🗃

diff --git a/bin/emojify b/bin/emojify
--- a/bin/emojify
+++ b/bin/emojify
@@ -4,14 +4,14 @@
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
 # @License       : WTFPL
-# @ReadME        : emojify --help
+# @ReadME        : emojify --
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
 # @Created       : Saturday, Mar 20, 2021 06:53 EDT
 # @File          : emojify
 # @Description   : Substitutes emoji aliases (like :sparkling_heart:) to emoji raw characters
 # @TODO          :
 # @Other         :
-# @Resource      :
+# @Resource      : https://github.com/mrowa44/emojify
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 APPNAME="$(basename "$0" 2>/dev/null)"
 USER="${SUDO_USER:-${USER}}"
@@ -44,7 +44,19 @@ user_install
 # To have an alias that does that for you, add something like: log = ! git log --oneline --color | emojify | less
 # Or, you could do something silly like: emojify "Hey, I just :raising_hand: you, and this is :scream: , but here's my :calling: , so :telephone_receiver: me, maybe?"
 emojify_version=2.1.0
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+version_error_message="Oh my! That’s a very old version of bash you’re using, we don’t support that anymore :(
+Consider upgrading it or, if you must use bash ${BASH_VERSION}, download an old version of
+emojify from here: https://github.com/mrowa44/emojify/blob/old_bash_support/emojify"
+# Checks the installed bash version to see if it's compatible with emojify
+if ((${BASH_VERSION%%.*} < 4)); then
+  echo -e "$version_error_message"
+  exit 1
+fi
+
+# List generated by
+# https://gist.github.com/GrenderG/fd4eb4c73eadad219b0ecb5f9345070a#file-emoji_scrap-py
+# and emoji_scrap_github.py
 declare -A emojis=(
   [":100:"]="\U1f4af"
   [":1234:"]="\U1f522"
@@ -856,7 +868,7 @@ declare -A emojis=(
   [":flag_au:"]="\U1f1e6\U1f1fa"
   [":flag_aw:"]="\U1f1e6\U1f1fc"
   [":flag_ax:"]="\U1f1e6\U1f1fd"
-  [":flag_a"]="\U1f1e6\U1f1ff"
+  [":flag_az:"]="\U1f1e6\U1f1ff"
   [":flag_ba:"]="\U1f1e7\U1f1e6"
   [":flag_bb:"]="\U1f1e7\U1f1e7"
   [":flag_bd:"]="\U1f1e7\U1f1e9"
@@ -878,7 +890,7 @@ declare -A emojis=(
   [":flag_bv:"]="\U1f1e7\U1f1fb"
   [":flag_bw:"]="\U1f1e7\U1f1fc"
   [":flag_by:"]="\U1f1e7\U1f1fe"
-  [":flag_b"]="\U1f1e7\U1f1ff"
+  [":flag_bz:"]="\U1f1e7\U1f1ff"
   [":flag_ca:"]="\U1f1e8\U1f1e6"
   [":flag_cc:"]="\U1f1e8\U1f1e8"
   [":flag_cd:"]="\U1f1e8\U1f1e9"
@@ -898,14 +910,14 @@ declare -A emojis=(
   [":flag_cw:"]="\U1f1e8\U1f1fc"
   [":flag_cx:"]="\U1f1e8\U1f1fd"
   [":flag_cy:"]="\U1f1e8\U1f1fe"
-  [":flag_c"]="\U1f1e8\U1f1ff"
+  [":flag_cz:"]="\U1f1e8\U1f1ff"
   [":flag_de:"]="\U1f1e9\U1f1ea"
   [":flag_dg:"]="\U1f1e9\U1f1ec"
   [":flag_dj:"]="\U1f1e9\U1f1ef"
   [":flag_dk:"]="\U1f1e9\U1f1f0"
   [":flag_dm:"]="\U1f1e9\U1f1f2"
   [":flag_do:"]="\U1f1e9\U1f1f4"
-  [":flag_d"]="\U1f1e9\U1f1ff"
+  [":flag_dz:"]="\U1f1e9\U1f1ff"
   [":flag_ea:"]="\U1f1ea\U1f1e6"
   [":flag_ec:"]="\U1f1ea\U1f1e8"
   [":flag_ee:"]="\U1f1ea\U1f1ea"
@@ -971,7 +983,7 @@ declare -A emojis=(
   [":flag_kr:"]="\U1f1f0\U1f1f7"
   [":flag_kw:"]="\U1f1f0\U1f1fc"
   [":flag_ky:"]="\U1f1f0\U1f1fe"
-  [":flag_k"]="\U1f1f0\U1f1ff"
+  [":flag_kz:"]="\U1f1f0\U1f1ff"
   [":flag_la:"]="\U1f1f1\U1f1e6"
   [":flag_lb:"]="\U1f1f1\U1f1e7"
   [":flag_lc:"]="\U1f1f1\U1f1e8"
@@ -1005,7 +1017,7 @@ declare -A emojis=(
   [":flag_mw:"]="\U1f1f2\U1f1fc"
   [":flag_mx:"]="\U1f1f2\U1f1fd"
   [":flag_my:"]="\U1f1f2\U1f1fe"
-  [":flag_m"]="\U1f1f2\U1f1ff"
+  [":flag_mz:"]="\U1f1f2\U1f1ff"
   [":flag_na:"]="\U1f1f3\U1f1e6"
   [":flag_nc:"]="\U1f1f3\U1f1e8"
   [":flag_ne:"]="\U1f1f3\U1f1ea"
@@ -1017,7 +1029,7 @@ declare -A emojis=(
   [":flag_np:"]="\U1f1f3\U1f1f5"
   [":flag_nr:"]="\U1f1f3\U1f1f7"
   [":flag_nu:"]="\U1f1f3\U1f1fa"
-  [":flag_n"]="\U1f1f3\U1f1ff"
+  [":flag_nz:"]="\U1f1f3\U1f1ff"
   [":flag_om:"]="\U1f1f4\U1f1f2"
   [":flag_pa:"]="\U1f1f5\U1f1e6"
   [":flag_pe:"]="\U1f1f5\U1f1ea"
@@ -1061,7 +1073,7 @@ declare -A emojis=(
   [":flag_sv:"]="\U1f1f8\U1f1fb"
   [":flag_sx:"]="\U1f1f8\U1f1fd"
   [":flag_sy:"]="\U1f1f8\U1f1fe"
-  [":flag_s"]="\U1f1f8\U1f1ff"
+  [":flag_sz:"]="\U1f1f8\U1f1ff"
   [":flag_ta:"]="\U1f1f9\U1f1e6"
   [":flag_tc:"]="\U1f1f9\U1f1e8"
   [":flag_td:"]="\U1f1f9\U1f1e9"
@@ -1078,13 +1090,13 @@ declare -A emojis=(
   [":flag_tt:"]="\U1f1f9\U1f1f9"
   [":flag_tv:"]="\U1f1f9\U1f1fb"
   [":flag_tw:"]="\U1f1f9\U1f1fc"
-  [":flag_t"]="\U1f1f9\U1f1ff"
+  [":flag_tz:"]="\U1f1f9\U1f1ff"
   [":flag_ua:"]="\U1f1fa\U1f1e6"
   [":flag_ug:"]="\U1f1fa\U1f1ec"
   [":flag_um:"]="\U1f1fa\U1f1f2"
   [":flag_us:"]="\U1f1fa\U1f1f8"
   [":flag_uy:"]="\U1f1fa\U1f1fe"
-  [":flag_u"]="\U1f1fa\U1f1ff"
+  [":flag_uz:"]="\U1f1fa\U1f1ff"
   [":flag_va:"]="\U1f1fb\U1f1e6"
   [":flag_vc:"]="\U1f1fb\U1f1e8"
   [":flag_ve:"]="\U1f1fb\U1f1ea"
@@ -2809,7 +2821,7 @@ declare -A emojis=(
   [":zombie_man:"]="\U1f9df\U200d\U2642\Ufe0f"
   [":zombie:"]="\U1f9df"
   [":zombie_woman:"]="\U1f9df\U200d\U2640\Ufe0f"
-  [":zz"]="\U1f4a4"
+  [":zzz:"]="\U1f4a4"
 )
 
 # Gets emoji from the associative array
@@ -2866,60 +2878,63 @@ emojify_line() {
 
 # Function to print help info.
 help() {
-  cat <<EOF
-    emojify - emoji on the command line 😱
-    USAGE: emojify [-h|--help] [-l|--list] TEXT
-EOF
-  if [[ 'list' == "$1" ]]; then
-    echo 'Supported emojis:'
+  if [[ "$1" == 'list' ]]; then
+    printf_cyan "All supported emojis"
     for key in "${!emojis[@]}"; do
-      echo -e "$key ${emojis[$key]}"
+      echo -e "$key ${emojis[$key]}" | sed 's/^:..*: //g' | tr '\n' ' '
     done
-  fi
-  exit 0
-}
-
-# Checks the installed bash version to see if it's compatible with emojify
-check_version() {
-  if ((${BASH_VERSION%%.*} >= 4)); then
-    return
+  elif [[ "$1" == '--raw' ]] || [[ "$1" == 'raw' ]]; then
+    for key in "${!emojis[@]}"; do
+      echo -e "$key ${emojis[$key]}" | awk '{print $1}' | sed 's|^ ||g' | sed -e 's|[,\[,\],",]||g'
+    done
   else
-    echo -e "Oh my! That’s a very old version of bash you’re using, we don’t support that anymore :(\n" \
-      "\nConsider upgrading it or, if you must use bash ${BASH_VERSION} download an old version of" \
-      "emojify from here: https://github.com/mrowa44/emojify/blob/old_bash_support/emojify"
-    exit 0
+    cat <<EOF | printf_readline
+emoji on the command line 😱
+emojify [-h|--help] [-l|--list]
+USAGE: emojify ":clap: you figured it out :smile:"
+USAGE: echo ":clap: you figured it out :smile:" | emojify
+EOF
   fi
+  printf '\n\n'
+  exit 0
 }
 
 # If arguments are provided on the command line then check for supported help
 # options or process the arguments as emoji names.
-if [[ -n $1 ]]; then
+if [[ -n "$1" ]]; then
   case $1 in
   '-h' | '--help')
+    shift 1
     help
     ;;
 
   '-l' | '--list')
-    for key in "${!emojis[@]}"; do
-      echo -e "$key ${emojis[$key]}"
-    done
+    shift 1
+    help "${1:-list}"
     ;;
 
   '-v' | '--version')
+    shift 1
     echo $emojify_version
     ;;
 
   *)
-    check_version
-    emojify_line "$*"
+    printf_blue "Emoji for $*"
+    emojify_line "$*" | printf_readline
+    emojify_line "$line" | clipboard
     ;;
   esac
+elif [[ ${#} -eq 0 ]]; then
+  if [ -p "/dev/stdin" ]; then
+    while
+      IFS=''
+      read -r line || [ -n "$line" ]
+    do
+      emojify_line "$line" | printf_readline
+      emojify_line "$line" | clipboard
+    done
+  fi
 else
-  check_version
-  while
-    IFS=''
-    read -r line || [ -n "$line" ]
-  do
-    emojify_line "$line"
-  done
+  emojify_line "$line" | printf_readline
+  emojify_line "$line" | clipboard
 fi
