🗃 Modified: bin/explainshell bin/spellcheck  🗃

diff --git a/bin/explainshell b/bin/explainshell
--- a/bin/explainshell
+++ b/bin/explainshell
@@ -1,20 +1,22 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 APPNAME="$(basename "$0")"
+VERSION="202107292206-git"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #set opts
+trap 'exitCode=${exitCode:-$?};[ -f "$EXPLAINSHELL_TEMP_FILE" ] && rm -Rf "$EXPLAINSHELL_TEMP_FILE" &>/dev/null' EXIT
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 202103200708-git
-# @Author        : Jason Hempstead
-# @Contact       : jason@casjaysdev.com
+##@Version       : 202107292206-git
+# @Author        : casjay
+# @Contact       : casjay
 # @License       : WTFPL
 # @ReadME        : explainshell --help
-# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Saturday, Mar 20, 2021 07:08 EDT
+# @Copyright     : Copyright: (c) 2021 casjay, casjay
+# @Created       : Thursday, Jul 29, 2021 22:06 EDT
 # @File          : explainshell
 # @Description   : search explainshell.com for commands
 # @TODO          :
@@ -35,38 +37,148 @@ else
   echo "Can not load the functions file: $SCRIPTSFUNCTDIR/$SCRIPTSFUNCTFILE" 1>&2
   exit 1
 fi
-__explain() {
-  curl -LSs "$URL" |
-    sed -n '/<pre/,/<\/pre>/p' |
-    sed -n '/<pre/,/<\/pre>/p' |
-    sed -s 's/<[^>]*>//g' |
-    sed -e 's/^ *//g;s/ *$//g' |
-    grep '.'
-}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # user system devenv dfmgr dockermgr fontmgr iconmgr pkmgr systemmgr thememgr wallpapermgr
 user_install
 __options "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-cmd_exists curl || exit 1
-__am_i_online_err || exit 1
+__gen_config() {
+  printf_green "Generating the config file in"
+  printf_green "$EXPLAINSHELL_CONFIG_DIR/$EXPLAINSHELL_CONFIG_FILE"
+  [ -d "$EXPLAINSHELL_CONFIG_DIR" ] || mkdir -p "$EXPLAINSHELL_CONFIG_DIR"
+  [ -d "$EXPLAINSHELL_CONFIG_BACKUP_DIR" ] || mkdir -p "$EXPLAINSHELL_CONFIG_BACKUP_DIR"
+  [ -f "$EXPLAINSHELL_CONFIG_DIR/$EXPLAINSHELL_CONFIG_FILE" ] &&
+    cp -Rf "$EXPLAINSHELL_CONFIG_DIR/$EXPLAINSHELL_CONFIG_FILE" "$EXPLAINSHELL_CONFIG_BACKUP_DIR/$EXPLAINSHELL_CONFIG_FILE.$$"
+  cat <<EOF >"$EXPLAINSHELL_CONFIG_DIR/$EXPLAINSHELL_CONFIG_FILE"
+# Settings for explainshell
+EXPLAINSHELL_API="https://explainshell.com/explain"
+EXPLAINSHELL_TEMP_FILE="${TMPDIR:-/tmp}/explainshell"
+EXPLAINSHELL_NOTIFY_ENABLED="yes"
+EXPLAINSHELL_NOTIFY_CLIENT_NAME="\${NOTIFY_CLIENT_NAME:-\$APPNAME}"
+EXPLAINSHELL_NOTIFY_CLIENT_ICON="\${NOTIFY_CLIENT_ICON:-\$EXPLAINSHELL_NOTIFY_CLIENT_ICON}"
+
+EOF
+  if [ -f "$EXPLAINSHELL_CONFIG_DIR/$EXPLAINSHELL_CONFIG_FILE" ]; then
+    printf_green "Your config file for explainshell has been created"
+    true
+  else
+    printf_red "Failed to create the config file"
+    false
+  fi
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [ -z "$1" ] || [ -z "$2" ]; then __help; fi
+__explain() {
+  local HEAD="$(curl -q -ILSsi "$URL" | grep '200 OK' | grep '^.' || false)"
+  if [ -z "$HEAD" ]; then
+    printf "Received an invalid response"
+    return 1
+  else
+    curl -q -LSs "$URL" |
+      sed -e '/<script/,/<\/script>/d' |
+      sed -e '/(function/,/});/d' |
+      sed -n '/<pre/,/<\/pre>/p' |
+      sed -s 's/<[^>]*>//g' |
+      sed -e 's/^ *//g;s/ *$//g' |
+      grep '.'
+  fi
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-CMD="$1" && shift 1
-ARGS=${*} && shift $#
-URL=$(echo "http://explainshell.com/explain/$CMD?args=$ARGS" | sed -e 's/ /+/g')
+# Defaults
+exitCode=""
+EXPLAINSHELL_CONFIG_FILE="settings.conf"
+EXPLAINSHELL_CONFIG_DIR="$HOME/.config/myscripts/explainshell"
+EXPLAINSHELL_CONFIG_BACKUP_DIR="$HOME/.local/share/myscripts/explainshell/backups"
+EXPLAINSHELL_OPTIONS_DIR="$HOME/.local/share/myscripts/explainshell/options"
+EXPLAINSHELL_TEMP_FILE="${TMPDIR:-/tmp}/explainshell"
+EXPLAINSHELL_NOTIFY_ENABLED="yes"
+EXPLAINSHELL_NOTIFY_CLIENT_NAME="${NOTIFY_CLIENT_NAME:-$APPNAME}"
+EXPLAINSHELL_NOTIFY_CLIENT_ICON="${NOTIFY_CLIENT_ICON:-$EXPLAINSHELL_NOTIFY_CLIENT_ICON}"
+EXPLAINSHELL_API="https://explainshell.com/explain"
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-RESPONSE="$(__explain)"
+# Set additional variables/Argument/Option settings
+SETARGS="$*"
+SHORTOPTS="c,v,h"
+LONGOPTS="options,config,version,help"
+ARRAY="show-commands"
+OPTS=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if echo "$RESPONSE" | grep -q "GoogleAnalyticsObject"; then
-  printf_return "Recieved an invalid response"
-else
-  printf_newline
-  printf_blue "$RESPONSE" | printf_readline
-  printf_newline
+# Generate Files
+[ -f "$EXPLAINSHELL_CONFIG_DIR/$EXPLAINSHELL_CONFIG_FILE" ] || __gen_config &>/dev/null
+[ -f "$EXPLAINSHELL_OPTIONS_DIR/options" ] || __list_options "$EXPLAINSHELL_OPTIONS_DIR" &>/dev/null
+[ -f "$EXPLAINSHELL_OPTIONS_DIR/array" ] || __list_array "$EXPLAINSHELL_OPTIONS_DIR" "$ARRAY" &>/dev/null
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Import config
+if [ -f "$EXPLAINSHELL_CONFIG_DIR/$EXPLAINSHELL_CONFIG_FILE" ]; then
+  . "$EXPLAINSHELL_CONFIG_DIR/$EXPLAINSHELL_CONFIG_FILE"
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
+# options
+for opts in $SETARGS; do
+  echo "$opts" | grep -q '\-' && OPTS+="${opts} "
+done
+
+setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -a -n "$APPNAME" -- "$@" 2>/dev/null)
+eval set -- "${setopts[@]}" 2>/dev/null
+while :; do
+  case $1 in
+  --options)
+    shift 1
+    __list_array "$EXPLAINSHELL_OPTIONS_DIR" "$ARRAY"
+    __list_options "$EXPLAINSHELL_OPTIONS_DIR"
+    exit $?
+    ;;
+  -v | --version)
+    shift 1
+    __version
+    exit $?
+    ;;
+  -h | --help)
+    shift 1
+    __help
+    exit $?
+    ;;
+  -c | --config)
+    shift 1
+    __gen_config
+    exit $?
+    ;;
+  --)
+    shift 1
+    break
+    ;;
+  esac
+done
+#set -- "$SETARGS"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# end
+# Actions based on env
+export NOTIFY_CLIENT_NAME="${EXPLAINSHELL_NOTIFY_CLIENT_NAME}"
+export NOTIFY_CLIENT_ICON="${EXPLAINSHELL_NOTIFY_CLIENT_ICON}"
+if [ "$EXPLAINSHELL_NOTIFY_ENABLED" = "yes" ]; then
+  __notifications() {
+    notifications "$*" || return 1
+  }
+else
+  __notifications() { false; }
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Check for required applications/Network check
+cmd_exists --error bash curl || exit 1
+am_i_online --error || exit 1
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# APP Variables
+CMD="$1" && shift 1
+ARGS="${OPTS:---help}" && shift $#
+URL=$(echo "$EXPLAINSHELL_API/$CMD?args=$ARGS" | sed -e 's/ /+/g')
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# begin main app
+printf_newline
+__explain | printf_readline
+printf_newline
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# End application
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# lets exit with code
+exit ${exitCode:-$?}
