🗃️ Committing everything that changed 🗃️
bin/buildx
bin/gen-dockerfile
templates/dockerfiles/almalinux.template
templates/dockerfiles/alpinelinux.template
templates/dockerfiles/archlinux.template
templates/dockerfiles/debian.template
templates/dockerfiles/template_options.source
templates/dockerfiles/ubuntu.template
templates/dockerfiles/web.template
templates/dockerfiles/xorg.template

diff --git a/bin/gen-dockerfile b/bin/gen-dockerfile
--- a/bin/gen-dockerfile
+++ b/bin/gen-dockerfile
@@ -155,6 +155,7 @@ __gen_config() {
     cp -Rf "$GEN_DOCKERFILE_CONFIG_DIR/$GEN_DOCKERFILE_CONFIG_FILE" "$GEN_DOCKERFILE_CONFIG_BACKUP_DIR/$GEN_DOCKERFILE_CONFIG_FILE.$$"
   cat <<EOF >"$GEN_DOCKERFILE_CONFIG_DIR/$GEN_DOCKERFILE_CONFIG_FILE"
 # Settings for gen-dockerfile
+GEN_DOCKERFILE_BACKUP_EXT="${GEN_DOCKERFILE_BACKUP_EXT:-}"
 GEN_DOCKER_GIT_ORG="${GEN_DOCKER_GIT_ORG:-}"
 GEN_DOCKER_REGISTRY_ORG="${GEN_DOCKER_REGISTRY_ORG:-}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -504,7 +505,7 @@ $(. "$GEN_DOCKERFILE_TEMPLATE_DIR/dotenv.template")
 EOF
   [ "$GEN_DOCKER_INIT" != "true" ] || [ ! -f "$rootfs_dir/usr/local/bin/entrypoint.sh" ] || return
   . $dotenv_file && __set_variables && repo="${GEN_DOCKERFILE_GIT_BASE:-$repo}"
-  if [ -f "$rootfs_dir/usr/local/bin/entrypoint.sh" ] && [ -f "$file.$bak_ext" ]; then
+  if [ -f "$rootfs_dir/usr/local/bin/entrypoint.sh" ] && [ -f "$file.$GEN_DOCKERFILE_BACKUP_EXT" ]; then
     printf_cyan "Generating your Dockerfile using template: $GEN_DOCKERFILE_TEMPLATE"
     if __make_file "$GEN_DOCKERFILE_TEMPLATE" "$file"; then
       printf_green "Your Dockerfile for $name has been created in: $(readlink -f "$GEN_DOCKERFILE_CWD")"
@@ -557,7 +558,7 @@ EOF
         printf_blue "Creating $rootfs_dir/usr/local/bin/entrypoint.sh"
         if [ -f "$rootfs_dir/usr/local/bin/entrypoint.sh" ]; then
           printf_yellow "Found existing entrypoint... ${GREEN}Backing up${NC}"
-          mv -f "$rootfs_dir/usr/local/bin/entrypoint.sh" "$rootfs_dir/usr/local/bin/entrypoint.sh.$bak_ext"
+          mv -f "$rootfs_dir/usr/local/bin/entrypoint.sh" "$rootfs_dir/usr/local/bin/entrypoint.sh.$GEN_DOCKERFILE_BACKUP_EXT"
         fi
         if GEN_SCRIPT_EDITFILE="N" gen-script other docker-entrypoint --name "$name" --dir "$rootfs_dir/usr/local/bin" "entrypoint.sh" &>/dev/null; then
           printf_green "Created the entrypoint script"
@@ -566,7 +567,8 @@ EOF
         fi
         # create init files
         [ -d "$rootfs_dir/root/docker/setup" ] || mkdir -p "$rootfs_dir/root/docker/setup"
-        for custom_init in init custom; do
+        for custom_init in custom files init packages post system users; do
+          printf_purple "Creating setup script: $rootfs_dir/root/docker/setup/$custom_init"
           if [ ! -f "$rootfs_dir/root/docker/setup/$custom_init" ]; then
             cat <<EOF >"$rootfs_dir/root/docker/setup/$custom_init"
 #!/usr/bin/env sh
@@ -594,14 +596,19 @@ EOF
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set env variables
 exitCode=0
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main script
 
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set the exit code
+exitCode=$?
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 exit \$exitCode
 
 EOF
           fi
+          chmod -Rf 755 "$rootfs_dir/root/docker/setup/$custom_init"
         done
         # create env files
         mkdir -p "$shared_dir/template-files/config/env/examples"
@@ -853,15 +860,15 @@ __configure_dockerfile() {
   name="${1:-$GEN_DOCKERFILE_TEMPLATE}"
   printf_yellow "Initializing $name in: ${GEN_DOCKERFILE_CWD//$PWD\//}"
   printf_blue "Setting the tag[s] to: $tag_name"
-  if [ -f "$file" ] && [ -f "$file.$bak_ext" ]; then
+  if [ -f "$file" ] && [ -f "$file.$GEN_DOCKERFILE_BACKUP_EXT" ]; then
     printf_yellow "Found an existing Dockerfile at: $file"
-    printf_cyan "Backing up to: $file.$date.$bak_ext"
-    mv -f "$file.bak" "$file.$date.$bak_ext"
-    mv -f "$file" "$file.$bak_ext"
+    printf_cyan "Backing up to: $file.$date.$GEN_DOCKERFILE_BACKUP_EXT"
+    mv -f "$file.bak" "$file.$date.$GEN_DOCKERFILE_BACKUP_EXT"
+    mv -f "$file" "$file.$GEN_DOCKERFILE_BACKUP_EXT"
   elif [ -f "$file" ]; then
     printf_yellow "Found an existing Dockerfile at: $file"
-    printf_cyan "Backing up to: $file.$bak_ext"
-    mv -f "$file" "$file.$bak_ext"
+    printf_cyan "Backing up to: $file.$GEN_DOCKERFILE_BACKUP_EXT"
+    mv -f "$file" "$file.$GEN_DOCKERFILE_BACKUP_EXT"
   fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   __set_variables
@@ -899,6 +906,7 @@ __set_variables() {
   GEN_DOCKERFILE_GIT_BASE="$(echo "${ENV_GIT_REPO_URL:-$GEN_DOCKERFILE_GIT_REPO}" | tr '[:upper:]' '[:lower:]')"
   GEN_DOCKERFILE_HUB_BASE="$(echo "${ENV_REGISTRY_URL:-$GEN_DOCKERFILE_HUB_REPO}" | tr '[:upper:]' '[:lower:]')"
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$GEN_DOCKER_REGISTRY_PUSH_ORG" = "_" ] && GEN_DOCKERFILE_PULL_URL="${GEN_DOCKERFILE_PULL_URL//*\//}"
   return
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -943,6 +951,7 @@ GEN_DOCKERFILE_OUTPUT_COLOR_GOOD="${GEN_DOCKERFILE_OUTPUT_COLOR_GOOD:-2}"
 GEN_DOCKERFILE_OUTPUT_COLOR_ERROR="${GEN_DOCKERFILE_OUTPUT_COLOR_ERROR:-1}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Notification Settings
+GEN_DOCKERFILE_BACKUP_EXT="${GEN_DOCKERFILE_BACKUP_EXT:-bak}"
 GEN_DOCKERFILE_NOTIFY_ENABLED="${GEN_DOCKERFILE_NOTIFY_ENABLED:-yes}"
 GEN_DOCKERFILE_GOOD_NAME="${GEN_DOCKERFILE_GOOD_NAME:-Great:}"
 GEN_DOCKERFILE_ERROR_NAME="${GEN_DOCKERFILE_ERROR_NAME:-Error:}"
@@ -1061,7 +1070,7 @@ SHORTOPTS+=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 LONGOPTS="completions:,config,debug,dir:,help,options,raw,version,silent"
 LONGOPTS+=",dockerfile,startup,nogit,template:,image-name:,image-version:,org:,pkmgr"
-LONGOPTS+=",registry:,git:,distro-name:,distro-version:,add-tags:,x11,init"
+LONGOPTS+=",tag:,registry:,git:,distro-name:,distro-version:,add-tags:,x11,init"
 LONGOPTS+=",apache,nginx,mysql,postgres,php,application:"
 LONGOPTS+=",alpine,almalinux,archlinux,debian,ubuntu"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -1190,11 +1199,11 @@ while :; do
     ;;
   --git)
     GEN_DOCKER_GIT_ORG="$2"
-    shift
+    shift 2
     ;;
   --registry)
-    GEN_DOCKER_REGISTRY_ORG="$2"
-    shift
+    GEN_DOCKER_REGISTRY_PUSH_ORG="$2"
+    shift 2
     ;;
   --org)
     GEN_DOCKER_GIT_ORG="$2"
@@ -1207,6 +1216,10 @@ while :; do
     shift 2
     ;;
   --image-version)
+    GEN_DOCKERFILE_DEFAULT_VERSION="$2"
+    shift 2
+    ;;
+  --tag)
     GEN_DOCKERFILE_DEFAULT_VERSION="$2"
     shift 2
     ;;
diff --git a/templates/dockerfiles/archlinux.template b/templates/dockerfiles/archlinux.template
--- a/templates/dockerfiles/archlinux.template
+++ b/templates/dockerfiles/archlinux.template
@@ -12,7 +12,7 @@ ARG DEFAULT_CONF_DIR="${DEFAULT_CONF_DIR:-/usr/local/share/template-files/config
 ARG DEFAULT_TEMPLATE_DIR="${DEFAULT_TEMPLATE_DIR:-/usr/local/share/template-files/defaults}"
 
 ARG USER="root"
-ARG SHELL_OPTS="set -ex"
+ARG SHELL_OPTS="set -e -o pipefail"
 ARG AUR_USER="aur"
 ARG AUR_HOME="/home/aur"
 
@@ -99,7 +99,7 @@ $(__setup_files)
 
 RUN \$SHELL_OPTS \\
   echo "Custom Settings"; \\
-  ${GEN_DOCKERFILE_CUSTOM_COMMANDS}echo ""ARG SHELL_OPTS="set -ex"
+  ${GEN_DOCKERFILE_CUSTOM_COMMANDS}echo ""ARG SHELL_OPTS="set -e -o pipefail"
 
 
 RUN \\
