🗃️ Committing everything that changed 🗃️
bin/gen-dockerfile

diff --git a/bin/gen-dockerfile b/bin/gen-dockerfile
--- a/bin/gen-dockerfile
+++ b/bin/gen-dockerfile
@@ -496,59 +496,59 @@ EOF
         else
           printf_red "Failed to create the entrypoint script"
         fi
-        # backup init script if exists
-        printf_blue "Creating $init_dir/zz-default.sh"
-        if [ -f "$init_dir/zz-default.sh" ]; then
-          printf_yellow "Found existing start-$name script... ${GREEN}Backing up${NC}"
-          mv -f "$init_dir/zz-default.sh" "$init_dir/zz-default.sh.$bak_ext"
-        fi
-        # create root docker init files
-        mkdir -p "$rootfs_dir/root/docker"
-        for docker_init_script in init custom files packages post; do
-          if [ ! -f "$rootfs_dir/root/docker/setup/$docker_init_script" ]; then
-            printf_yellow "Creating $docker_init_script in $rootfs_dir/root/docker/setup"
-            [ -d "$rootfs_dir/root/docker/setup" ] || mkdir -p "$rootfs_dir/root/docker/setup"
-            cat <<EEOF >"$rootfs_dir/root/docker/setup/$docker_init_script"
-#!/usr/bin/env sh
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version           :  $(date +'%Y%m%d%H%M-git')
-# @@Author           :  $GEN_DOCKERFILE_AUTHOR
-# @@Contact          :  $GEN_DOCKERFILE_MAINTAINER
-# @@License          :  MIT
-# @@ReadME           :
-# @@Copyright        :  Copyright $(date +'%Y') $GEN_DOCKERFILE_VENDOR
-# @@Created          :  $(date)
-# @@File             :  $(basename "$docker_init_script")"
-# @@Description      :  script to run $(basename "$docker_init_script")"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# shellcheck shell=sh
-# shellcheck disable=SC2016
-# shellcheck disable=SC2031
-# shellcheck disable=SC2120
-# shellcheck disable=SC2155
-# shellcheck disable=SC2199
-# shellcheck disable=SC2317
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-set -ex
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Set env variables
+        #         # backup init script if exists
+        #         printf_blue "Creating $init_dir/zz-default.sh"
+        #         if [ -f "$init_dir/zz-default.sh" ]; then
+        #           printf_yellow "Found existing start-$name script... ${GREEN}Backing up${NC}"
+        #           mv -f "$init_dir/zz-default.sh" "$init_dir/zz-default.sh.$bak_ext"
+        #         fi
+        #         # create root docker init files
+        #         mkdir -p "$rootfs_dir/root/docker"
+        #         for docker_init_script in init custom files packages post; do
+        #           if [ ! -f "$rootfs_dir/root/docker/setup/$docker_init_script" ]; then
+        #             printf_yellow "Creating $docker_init_script in $rootfs_dir/root/docker/setup"
+        #             [ -d "$rootfs_dir/root/docker/setup" ] || mkdir -p "$rootfs_dir/root/docker/setup"
+        #             cat <<EEOF >"$rootfs_dir/root/docker/setup/$docker_init_script"
+        # #!/usr/bin/env sh
+        # # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+        # ##@Version           :  $(date +'%Y%m%d%H%M-git')
+        # # @@Author           :  $GEN_DOCKERFILE_AUTHOR
+        # # @@Contact          :  $GEN_DOCKERFILE_MAINTAINER
+        # # @@License          :  MIT
+        # # @@ReadME           :
+        # # @@Copyright        :  Copyright $(date +'%Y') $GEN_DOCKERFILE_VENDOR
+        # # @@Created          :  $(date)
+        # # @@File             :  $(basename "$docker_init_script")"
+        # # @@Description      :  script to run $(basename "$docker_init_script")"
+        # # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+        # # shellcheck shell=sh
+        # # shellcheck disable=SC2016
+        # # shellcheck disable=SC2031
+        # # shellcheck disable=SC2120
+        # # shellcheck disable=SC2155
+        # # shellcheck disable=SC2199
+        # # shellcheck disable=SC2317
+        # # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+        # set -ex
+        # # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+        # # Set env variables
 
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Main script
+        # # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+        # # Main script
 
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
-EEOF
-          fi
-          chmod 755 "$rootfs_dir/root/docker/setup/$docker_init_script"
-        done
-        # Create start-service script
-        if GEN_SCRIPT_EDITFILE="N" gen-script other start-service --name "$name" --dir "$init_dir" "zz-default.sh" &>/dev/null; then
-          sed -i 's|REPLACE_SERVICE_NAME|'$name'|g' "$init_dir/zz-default.sh"
-          printf_green "Created the start script $init_dir/zz-default.sh"
-        else
-          printf_red "Failed to create the start-$name script"
-        fi
+        # # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+        # exit $?
+        # EEOF
+        #           fi
+        #           chmod 755 "$rootfs_dir/root/docker/setup/$docker_init_script"
+        #         done
+        #         # Create start-service script
+        #         if GEN_SCRIPT_EDITFILE="N" gen-script other start-service --name "$name" --dir "$init_dir" "zz-default.sh" &>/dev/null; then
+        #           sed -i 's|REPLACE_SERVICE_NAME|'$name'|g' "$init_dir/zz-default.sh"
+        #           printf_green "Created the start script $init_dir/zz-default.sh"
+        #         else
+        #           printf_red "Failed to create the start-$name script"
+        #         fi
         # create env files
         mkdir -p "$shared_dir/template-files/config/env/examples"
         __create_env "$shared_dir/template-files/config/env/default.sample"
@@ -671,7 +671,7 @@ __create_pkmgr_install_script() {
 # shellcheck disable=SC2016
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 set -e
-[ -n "\$_DEBUG" ] && set -x || { [ "\$1" = "--debug" ]&& set -x && shift 1; }
+[ -n "\$_DEBUG" ] && set -x || { [ "\$1" = "--debug" ] && set -x && shift 1; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 USER_UID="\$(id -u)"
 USER_GID="\$(id -g)"
@@ -735,8 +735,8 @@ if [ -f "/config/pkmgr/settings.conf" ]; then
 elif [ -f "/etc/pkmgr/settings.conf" ]; then
   . "/etc/pkmgr/settings.conf"
 else
-mkdir -p "/config/pkmgr"
-cat <<EEOF >"/config/pkmgr/settings.conf"
+  mkdir -p "/config/pkmgr"
+  cat <<EEOF >"/config/pkmgr/settings.conf"
 pkmgr_cmd="\$pkmgr_cmd"
 pkmgr_clean_cmd="\$pkmgr_clean_cmd"
 pkmgr_update_cmd="\$pkmgr_update_cmd"
@@ -748,13 +748,29 @@ fi
 [ -n "\$pkmgr_cmd" ] || { echo "Can not determine the package manager" && exit 1; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 case "\$1" in
+pip)
+  shift 1
+  py_version="$(\$pip_bin --version | sed 's|[pP]ython ||g' | awk -F '.' '{print \$1\$2}' | grep '[0-9]' || echo "0")"
+  [ "\$py_version" -gt "310" ] && pip_opts="--break-system-packages " || pip_opts=""
+  case "\$1" in
+  install)
+    shift 1
+    \$pip_bin -m \$pip_opts "\$@"
+    ;;
+  *)
+    \$pip_bin "\$@"
+    ;;
+  esac
+  exit \$?
+  ;;
 update | upgrade)
   shift \$#
   [ "\$USER_UID" -eq 0 ] || [ "\$USER" = "root" ] || pkmgr_update_cmd="sudo \$pkmgr_install_cmd"
   echo "Updating packages command: \$pkmgr_update_cmd"
-  \$pkmgr_mkcache_cmd;\$pkmgr_update_cmd
+  \$pkmgr_mkcache_cmd
+  \$pkmgr_update_cmd
   exit \$?
-;;
+  ;;
 clean)
   shift \$#
   [ -n "\$1" ] || exit 0
@@ -762,7 +778,7 @@ clean)
   echo "Cleaning package cache: \$pkmgr_clean_cmd"
   \$pkmgr_clean_cmd
   exit \$?
-;;
+  ;;
 install)
   shift 1
   [ -n "\$1" ] || exit 0
@@ -776,14 +792,14 @@ install)
   fi
   \$pkmgr_install_cmd \$install_list
   exit \$?
-;;
+  ;;
 *)
   [ -n "\$1" ] || exit 0
   [ "\$USER_UID" -eq 0 ] || [ "\$USER" = "root" ] || pkmgr_cmd="sudo \$pkmgr_cmd"
   echo "executing packages command: \$pkmgr_cmd \$*"
   \$pkmgr_cmd "\$@"
   exit \$?
-;;
+  ;;
 esac
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
