🗃️ Committing everything that changed 🗃️
bin/gen-dockerfile

diff --git a/bin/gen-dockerfile b/bin/gen-dockerfile
--- a/bin/gen-dockerfile
+++ b/bin/gen-dockerfile
@@ -564,6 +564,45 @@ EOF
         else
           printf_red "Failed to create the entrypoint script"
         fi
+        # create init files
+        [ -d "$rootfs_dir/root/docker/setup" ] || mkdir -p "$rootfs_dir/root/docker/setup"
+        for custom_init in init custom; do
+          if [ ! -f "$rootfs_dir/root/docker/setup/$custom_init" ]; then
+            cat <<EOF >"$rootfs_dir/root/docker/setup/$custom_init"
+#!/usr/bin/env sh
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version           :  $(date +"${VERSION_DATE_FORMAT:-%Y%m%d%H%M-git}")
+# @@Author           :  CasjaysDev
+# @@Contact          :  CasjaysDev <docker-admin@casjaysdev.pro>
+# @@License          :  MIT
+# @@ReadME           :
+# @@Copyright        :  Copyright 2023 CasjaysDev
+# @@Created          :  Mon Aug 28 06:48:42 PM EDT 2023
+# @@File             :  $custom_init
+# @@Description      :  script to run $custom_init
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# shellcheck shell=sh
+# shellcheck disable=SC2016
+# shellcheck disable=SC2031
+# shellcheck disable=SC2120
+# shellcheck disable=SC2155
+# shellcheck disable=SC2199
+# shellcheck disable=SC2317
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set bash options
+[ "\$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x\$DEBUGGER_OPTIONS || set -o pipefail
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set env variables
+exitCode=0
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main script
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit \$exitCode
+
+EOF
+          fi
+        done
         # create env files
         mkdir -p "$shared_dir/template-files/config/env/examples"
         __create_env "$shared_dir/template-files/config/env/default.sample"
