🗃️ modified: bin/gen-dockerfile 🗃️

diff --git a/bin/gen-dockerfile b/bin/gen-dockerfile
--- a/bin/gen-dockerfile
+++ b/bin/gen-dockerfile
@@ -336,9 +336,6 @@ __docker_file() {
   if [ "$GEN_DOCKER_AUTOMATED" != "true" ]; then
     [ -f "$file" ] && printf_pause "If this is what you want press enter or control-c to exit"
   fi
-  if [ ! -f "$template_dir/config" ]; then
-    __create_env "$template_dir/config/env.sample"
-  fi
   if [ -f "$file" ] && [ -f "$file.$bak_ext" ]; then
     printf_yellow "Found an existing Dockerfile at: $file"
     printf_cyan "Backing up to: $file.$date.$bak_ext"
@@ -400,6 +397,9 @@ __docker_file() {
         else
           printf_red "Failed to create the start-$name script"
         fi
+        # create env files
+        mkdir -p "$template_dir/casjaysdev/env"
+        __create_env "$template_dir/casjaysdev/env/default.sh"
         # Create .dockerignore README.md LICENSE.md and directories
         __dockerignore
         [ -f "$dir/README.md" ] || gen-readme projects docker.md "$dir/README.md"
@@ -490,6 +490,9 @@ __create_env() {
   cat <<EOF | tee "$1" &>/dev/null
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set bash options
+[ "\$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x\$DEBUGGER_OPTIONS || set -o pipefail
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # GLOBAL enviroment variables
 USER="\${USER:-root}"
 LANG="\${LANG:-C.UTF-8}"
@@ -509,8 +512,10 @@ DEFAULT_TEMPLATE_DIR="\${DEFAULT_TEMPLATE_DIR:-/usr/local/share/template-files/d
 HEALTH_ENABLED="\${HEALTH_ENABLED:-}"
 HEALTH_URL="\${HEALTH_URL:-}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# php version
+# php settings
 PHP_VERSION="\${PHP_VERSION//php/}"
+PHP_INI_DIR="\${PHP_INI_DIR:-\$(__find_php_ini)}"
+PHP_BIN_DIR="\${PHP_BIN_DIR:-\$(__find_php_bin)}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # services/ports
 ENV_PORTS="\${ENV_PORTS:-}"
@@ -549,10 +554,6 @@ ORG="\${ORG:-"Casjays Developments"}"
 DAYS_VALID="\${DAYS_VALID:-3650}"
 RSA="\${RSA:-4096}"
 CN="\${CN:-\$FULL_DOMAIN_NAME}"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# php files
-PHP_INI_DIR="\${PHP_INI_DIR:-\$(__find_php_ini)}"
-PHP_BIN_DIR="\${PHP_BIN_DIR:-\$(__find_php_bin)}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # web server configs
 HTTPD_CONFIG_FILE="\${HTTPD_CONFIG_FILE:-\$(__find_httpd_conf)}"
@@ -597,11 +598,23 @@ DATABASE_DIR_COUCHDB="\${DATABASE_DIR_COUCHDB:-\$DATABASE_BASE_DIR/couchdb}"
 DATABASE_DIR_SUPABASE="\${DATABASE_DIR_SUPABASE:-\$DATABASE_BASE_DIR/supabase}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # other
-INIT_DATE="\${INIT_DATE:-\$(date)}
-ENTRYPOINT_MESSAGE="\${ENTRYPOINT_MESSAGE:-no}"
+export INIT_DATE="\${INIT_DATE:-\$(date)}"
+export ENTRYPOINT_MESSAGE="\${ENTRYPOINT_MESSAGE:-no}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Check if this is a new container
+DATA_DIR_INITIALIZED="false" CONFIG_DIR_INITIALIZED="false" START_SERVICES="yes"
+[ -f "/config/.entrypoint.done" ] && ENTRYPOINT_FIRST_RUN="no" || ENTRYPOINT_FIRST_RUN="yes"
+[ -f "/data/.docker_has_run" ] && DATA_DIR_INITIALIZED="true" && ENTRYPOINT_MESSAGE="yes"
+[ -f "/config/.docker_has_run" ] && CONFIG_DIR_INITIALIZED="true" && ENTRYPOINT_MESSAGE="yes"
+export DATA_DIR_INITIALIZED CONFIG_DIR_INITIALIZED START_SERVICES ENTRYPOINT_FIRST_RUN
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
 EOF
+  if [ -d "$CASJAYSDEVDIR/templates/env/docker" ]; then
+    mkdir -p "/usr/local/share/template-files/config/env"
+    cp -Rf "$CASJAYSDEVDIR/templates/env/docker/." "/usr/local/share/template-files/config/env/"
+  fi
+  [ -f "$1" ] && printf_cyan "Created default env file in $1" || printf_red "failed to create $1"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __web() {
