🗃️ Committing everything that changed 🗃️

diff --git a/bin/gen-dockerfile b/bin/gen-dockerfile
--- a/bin/gen-dockerfile
+++ b/bin/gen-dockerfile
@@ -448,7 +448,7 @@ __create_start_script() {
 trap -- 'retVal=\$?; [ -f "/tmp/\$EXEC_CMD.pid" ] && rm -Rf "/tmp/\$EXEC_CMD.pid";exit \$retVal' SIGINIT SIGTERM ERR EXIT
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
-[ "\$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x\$DEBUGGER_OPTIONS || set -Eeo pipefail
+[ "\$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x\$DEBUGGER_OPTIONS || set -o pipefail
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute command options
 EXEC_CMD="$script_filename"                 # command to execute
@@ -608,8 +608,10 @@ MONGO_INITDB_ROOT_PASSWORD="\${DATABASE_PASS_ROOT:-\$MONGO_INITDB_ROOT_PASSWORD}
 COUCHDB_USER="\${DATABASE_USER_ROOT:-\$COUCHDB_USER}"
 COUCHDB_PASSWORD="\${DATABASE_PASS_ROOT:-\$COUCHDB_PASSWORD}"
 NODENAME="\${NODENAME:-}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # other
 ENTRYPOINT_MESSAGE="\${ENTRYPOINT_MESSAGE:-no}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
 EOF
 }
@@ -646,6 +648,7 @@ ARG IMAGE_VERSION="\${DISTRO_VERSION}"
 ARG BUILD_VERSION="\${DISTRO_VERSION}"
 ARG IMAGE_REPO="\${IMAGE_REPO}"
 
+FROM tianon/gosu:latest AS gosu
 FROM jlesage/baseimage-gui:debian-\${IMAGE_VERSION} AS build
 ARG USER
 ARG LANGUAGE
@@ -678,6 +681,8 @@ ENV HOSTNAME="casjaysdev-$name"
 
 USER \${USER}
 WORKDIR /root
+
+COPY --from=gosu /usr/local/bin/gosu /usr/local/bin/gosu
 COPY ./rootfs/. /
 
 RUN set -ex; \\
@@ -810,6 +815,7 @@ ARG IMAGE_VERSION="\${DISTRO_VERSION}"
 ARG BUILD_VERSION="\${DISTRO_VERSION}"
 ARG IMAGE_REPO="\${IMAGE_REPO}"
 
+FROM tianon/gosu:latest AS gosu
 FROM casjaysdevdocker/debian:\${IMAGE_VERSION} AS build
 ARG USER
 ARG LANGUAGE
@@ -843,6 +849,7 @@ ENV DEBIAN_FRONTEND="noninteractive"
 USER \${USER}
 WORKDIR /root
 
+COPY --from=gosu /usr/local/bin/gosu /usr/local/bin/gosu
 COPY ./rootfs/. /
 
 RUN set -ex; \\
@@ -980,6 +987,7 @@ ARG IMAGE_VERSION="\${DISTRO_VERSION}"
 ARG BUILD_VERSION="\${DISTRO_VERSION}"
 ARG IMAGE_REPO="\${IMAGE_REPO}"
 
+FROM tianon/gosu:latest AS gosu
 FROM casjaysdevdocker/debian:\${IMAGE_VERSION} AS build
 ARG USER
 ARG LICENSE
@@ -1013,6 +1021,7 @@ ENV DEBIAN_FRONTEND="noninteractive"
 USER \${USER}
 WORKDIR /root
 
+COPY --from=gosu /usr/local/bin/gosu /usr/local/bin/gosu
 COPY ./rootfs/. /
 
 RUN set -ex; \\
@@ -1143,6 +1152,7 @@ ARG IMAGE_VERSION="\${DISTRO_VERSION}"
 ARG BUILD_VERSION="\${DISTRO_VERSION}"
 ARG IMAGE_REPO="\${IMAGE_REPO}"
 
+FROM tianon/gosu:latest AS gosu
 FROM casjaysdevdocker/ubuntu:\${IMAGE_VERSION} AS build
 ARG USER
 ARG LICENSE
@@ -1176,6 +1186,7 @@ ENV DEBIAN_FRONTEND="noninteractive"
 USER \${USER}
 WORKDIR /root
 
+COPY --from=gosu /usr/local/bin/gosu /usr/local/bin/gosu
 COPY ./rootfs/. /
 
 RUN set -ex; \\
@@ -1306,6 +1317,7 @@ ARG IMAGE_VERSION="\${DISTRO_VERSION}"
 ARG BUILD_VERSION="\${DISTRO_VERSION}"
 ARG IMAGE_REPO="\${IMAGE_REPO}"
 
+FROM tianon/gosu:latest AS gosu
 FROM casjaysdevdocker/rockylinux:\${IMAGE_VERSION} AS build
 ARG USER
 ARG LICENSE
@@ -1337,6 +1349,8 @@ ENV HOSTNAME="casjaysdev-$name"
 
 USER \${USER}
 WORKDIR /root
+
+COPY --from=gosu /usr/local/bin/gosu /usr/local/bin/gosu
 COPY ./rootfs/. /
 
 RUN set -ex; \\
@@ -1464,6 +1478,7 @@ ARG IMAGE_VERSION="\${DISTRO_VERSION}"
 ARG BUILD_VERSION="\${DISTRO_VERSION}"
 ARG IMAGE_REPO="\${IMAGE_REPO}"
 
+FROM tianon/gosu:latest AS gosu
 FROM ${GEN_DOCKERFILE_DEFAULT_IMAGE:-casjaysdevdocker/alpine}:\${IMAGE_VERSION} AS build
 ARG USER
 ARG LICENSE
@@ -1499,6 +1514,7 @@ ENV HOSTNAME="casjaysdev-$name"
 USER \${USER}
 WORKDIR /root
 
+COPY --from=gosu /usr/local/bin/gosu /usr/local/bin/gosu
 COPY ./rootfs/. /
 
 RUN set -ex; \\
@@ -1638,6 +1654,7 @@ ARG IMAGE_VERSION="\${DISTRO_VERSION}"
 ARG BUILD_VERSION="\${DISTRO_VERSION}"
 ARG IMAGE_REPO="\${IMAGE_REPO}"
 
+FROM tianon/gosu:latest AS gosu
 FROM casjaysdevdocker/archlinux:\${IMAGE_VERSION} AS build
 ARG USER
 ARG LICENSE
@@ -1674,6 +1691,8 @@ ENV AUR_HOME="\${AUR_HOME}"
 
 USER \${USER}
 WORKDIR /root
+
+COPY --from=gosu /usr/local/bin/gosu /usr/local/bin/gosu
 COPY ./rootfs/. /
 
 RUN set -ex; \\
diff --git a/templates/scripts/functions/docker-entrypoint b/templates/scripts/functions/docker-entrypoint
--- a/templates/scripts/functions/docker-entrypoint
+++ b/templates/scripts/functions/docker-entrypoint
@@ -23,27 +23,18 @@ __random_password() { cat "/dev/urandom" | tr -dc '[0-9][a-z][A-Z]@$' | head -c$
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __replace() {
   sed -i 's|'$1'|'$2'|g' "$3" &>/dev/null
-  if grep -s -qw "$2" "$3"; then
-    printf '%s\n' "Changed $1 to $2 in $3"
-    return 0
-  else
-    printf '%s\n' "Failed to change $1 in $3"
-    return 10
-  fi
+  grep -s -q "$2" "$3" && printf '%s\n' "Changed $1 to $2 in $3" && return 0 || {
+    printf '%s\n' "Failed to change $1 in $3" && return 10
+  }
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__setup_ssl() {
-  [ "$1" = "" ] && return 0
-  [ $# -eq 2 ] || return 1
-  [ "$SSL_ENABLED" = "true" ] || return 0
-  [ -f "$1" ] && cp -Rf "$1" "$2"
-  if [ -f "$1" ] && [ -f "$1" ]; then
-    printf '%s\n' "Copied: $1 > $2"
-    return 0
-  else
+__file_copy() {
+  [ -f "$2" ] && mv -f "$2" "$2.bak"
+  [ -n "$1" ] && [ -n "$2" ] && [ $# -eq 2 ] && [ -f "$1" ] && cp -Rf "$1" "$2"
+  [ -f "$1" ] && [ -f "$2" ] && printf '%s\n' "Copied: $1 > $2" && return 0 || {
     printf '%s\n' "Copy failed: $1 < $2"
     return 1
-  fi
+  }
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __create_service_user() {
@@ -154,10 +145,10 @@ __run_backup() {
 __exec_command() {
   local exitCode=0
   local cmdExec="${*:-bash -l}"
-  local prog="$(type -P "$1" 2>/dev/null)"
+  local prog="$(type -P "${1:-bash}" 2>/dev/null)"
   if [ -f "$prog" ]; then
     echo "${exec_message:-Executing command: $cmdExec}"
-    $cmdExec || exitCode=1
+    eval $cmdExec || exitCode=1
     [ "$exitCode" = 0 ] || exitCode=10
   elif [ -f "$prog" ] && [ ! -x "$prog" ]; then
     echo "$prog is not executable"
@@ -197,76 +188,22 @@ __heath_check() {
   return $healthStatus
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Setup init scripts
+# Setup the server init scripts
 __start_init_scripts() {
+  [ "$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x$DEBUGGER_OPTIONS || set -o pipefail
+  local basename=""
   local init_pids=""
   local initStatus=0
-  if [ -d "$DEFAULT_TEMPLATE_DIR/init.d" ]; then
-    for init in "$DEFAULT_TEMPLATE_DIR/init.d"/*.sh; do
-      [ -f "$init" ] && $init &
+  if [ -d "${1:-/usr/local/etc/docker/init.d}" ]; then
+    for init in "${1:-/usr/local/etc/docker/init.d}"/*.sh; do
+      [ -f "$init" ] && eval $init 2>/dev/stderr >/dev/stdout &
       init_pids+="$! " initStatus=$(($? + initStatus))
-      sleep 1
+      sleep 2
     done
   fi
+  touch "/tmp/entrypoint.pid"
   sleep 10
   return $initStatus
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__start_all_services() {
-  local serviceStatus=0
-  local start_commands=("$@")
-  [ "$START_SERVICES" = "yes" ] || [ ! -f "/tmp/entrypoint.pid" ] || return 0
-  echo "$$" >"/tmp/entrypoint.pid"
-  __start_init_scripts
-  serviceStatus=$(($? + serviceStatus))
-  if [ -n "${start_commands[*]}" ]; then
-    for execute in "${start_commands[@]}"; do
-      __exec_command $execute &
-      serviceStatus=$(($? + serviceStatus))
-    done
-  fi
-  return $serviceStatus
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__exec_service_start() {
-  [ -n "$1" ] && EXEC_CMD="$1" && shift 1
-  [ -n "$1" ] && EXEC_CMD="$*" && shift $1
-  local EXEC_CMD="${EXEC_CMD:-$SERVICE_NAME}"            # command to execute
-  local SERVICE_ARGS="${SERVICE_ARGS:-$SERVICE_COMMAND}" # command arguments
-  local SERVICE_USER="${SERVICE_USER:-$USER}"            # execute command as another user
-  local PRE_EXEC_MESSAGE="${PRE_EXEC_MESSAGE:-}"         # Show message before execute
-  local SERVICE_EXIT_CODE=0                              # default exit code
-  echo "Determining whether we need to switch user"
-  if [ "$SERVICE_USER" = "root" ] || [ -z "$SERVICE_USER" ]; then
-    su_cmd_bin="eval"
-    su_cmd() { eval "$@" || return 1; }
-  elif [ "$(builtin type -P gosu)" ]; then
-    su_cmd_bin="gosu $SERVICE_USER"
-    su_cmd() { gosu $SERVICE_USER "$@" || return 1; }
-  elif [ "$(builtin type -P su)" ]; then
-    su_cmd_bin="su -s /bin/sh - $SERVICE_USER"
-    su_cmd() { su -s /bin/sh - $SERVICE_USER -c "$@" || return 1; }
-  elif [ "$(builtin type -P runuser)" ]; then
-    su_cmd_bin="runuser -u $SERVICE_USER"
-    su_cmd() { runuser -u $SERVICE_USER "$@" || return 1; }
-  elif [ "$(builtin type -P sudo)" ]; then
-    su_cmd_bin="sudo -u $SERVICE_USER"
-    su_cmd() { sudo -u $SERVICE_USER "$@" || return 1; }
-  else
-    echo "Can not switch to $SERVICE_USER"
-    exit 10
-  fi
-  if [ -n "$WORKDIR" ] && [ -n "$SERVICE_USER" ]; then
-    echo "Fixing file permissions"
-    su_cmd chown -Rf $SERVICE_USER $WORKDIR
-    sleep 1
-  fi
-  echo "Starting service: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
-  SERVICE_IS_RUNNING="true"
-  su_cmd "touch /tmp/$EXEC_CMD_BIN.pid"
-  su_cmd "$EXEC_CMD_BIN $EXEC_CMD_ARGS" || echo "Failed to execute: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
-  [ "$?" -ne 0 ] && SERVICE_IS_RUNNING="false" && SERVICE_EXIT_CODE=10 && rm -Rf "/tmp/$EXEC_CMD_BIN.pid"
-  return $SERVICE_EXIT_CODE
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __setup_mta() {
@@ -330,9 +267,9 @@ POSTGRES_CONFIG_FILE="${POSTGRES_CONFIG_FILE:-$(__find_pgsql_conf)}"
 export -f __cd __ps __curl __netstat __find __pcheck __pgrep __get_ip6
 export -f __get_ip4 __show_procs __listening create-ssl-cert __certbot
 export -f __create_env __run_backup __exec_command __heath_check __start_init_scripts
-export -f __start_all_services __exec_service_start __setup_mta __exec_pre_start
-export -f __create_service_user __start_message __replace __find_php_bin __find_php_ini
-export -f __find_nginx_conf __find_httpd_conf __find_lighttpd_conf __find_mysql_conf
+export -f __setup_mta __exec_pre_start __create_service_user __start_message
+export -f __replace __find_php_bin __find_php_ini __find_nginx_conf
+export -f __find_httpd_conf __find_lighttpd_conf __find_mysql_conf
 export -f __find_pgsql_conf
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # export variables
diff --git a/templates/scripts/other/start-service b/templates/scripts/other/start-service
--- a/templates/scripts/other/start-service
+++ b/templates/scripts/other/start-service
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-PATH="/usr/local/share/casjaysdev/bin:$PATH"
+export PATH="/usr/local/share/casjaysdev/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # run trap command on exit
-trap -- 'retVal=$?;[ "$SERVICE_IS_RUNNING" != "true" ] && [ -f "/tmp/$EXEC_CMD_BIN.pid" ] && rm -Rf "/tmp/$EXEC_CMD_BIN.pid";exit $retVal' SIGINT SIGTERM ERR EXIT
+trap -- 'retVal=$?;[ "$SERVICE_IS_RUNNING" != "true" ] && [ -f "/tmp/$EXEC_CMD_BIN.pid" ] && rm -Rf "/tmp/$EXEC_CMD_BIN.pid";exit $retVal' SIGINT SIGTERM EXIT
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
-[ "$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x$DEBUGGER_OPTIONS || set -Eeo pipefail
+[ "$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x$DEBUGGER_OPTIONS || set -o pipefail
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # import the functions file
 if [ -f "/usr/local/share/casjaysdev/functions/entrypoint.sh" ]; then
@@ -29,13 +29,33 @@ SERVICE_EXIT_CODE=0                       # default exit code
 # use this function to update config files - IE: change port
 __update_conf_files() {
   # __replace "FROM" "TO" "FILE"
-  # __setup_ssl "/config/apache2/httpd.ssl.conf" "/config/apache2/httpd.conf"
+  __replace "SERVER_PORT" "$SERVER_PORT" "/etc/nginx/nginx.conf"
+  __replace "SERVER_PORT" "$SERVER_PORT" "/etc/nginx/vhosts.d/nginx.conf"
+  __replace "SERVERNAME" "${SERVERNAME:-HOSTNAME}" "/etc/apache2/httpd.conf"
+  __replace "SERVER_PORT" "Listen ${SERVICE_PORT:-80}" "/etc/apache2/httpd.conf"
+  __replace "SERVERADMIN" "${HOSTADMIN:-root@$SERVERNAME}" "/etc/apache2/httpd.conf"
+  __replace "SERVER_PORT" "${SERVICE_PORT:-80}" "/etc/apache2/vhosts.d/default.conf"
   return 0
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Setup webserver ssl
+__setup_ssl() {
+  local ssl_conf=""
+  if [ "$SSL_ENABLED" = "true" ]; then
+    __file_copy "/config/nginx/nginx.ssl.conf" "/etc/nginx/nginx.ssl.conf"
+    __file_copy "/config/apache2/httpd.ssl.conf" "/etc/apache2/httpd.conf"
+    __file_copy "/config/apache2/vhosts.d/default.ssl.conf" "/etc/apache2/vhosts.d/default.ssl.conf"
+  else
+    for ssl_conf in "/etc/nginx/nginx.ssl.conf" "/config/apache2/httpd.ssl.conf" "/etc/apache2/vhosts.d/default.ssl.conf"; do
+      [ -n "$ssl_conf" ] && [ -f "$ssl_conf" ] && rm -Rf "${ssl_conf:?}"
+    done
+  fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # function to run before executing
 __pre_execute() {
   __create_service_user "$SERVICE_USER" "${SERVICE_UID:-$SERVICE_PORT}"
+
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # import variables
@@ -66,6 +86,7 @@ fi
 [ -n "$WORKDIR" ] && mkdir -p "$WORKDIR" && __cd "$WORKDIR" && echo "Changed to $PWD"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Updating config files
+__setup_ssl
 __update_conf_files
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # run the pre execute commands
@@ -80,15 +101,15 @@ if [ "$SERVICE_USER" = "root" ] || [ -z "$SERVICE_USER" ]; then
 elif [ "$(builtin type -P gosu)" ]; then
   su_cmd_bin="gosu $SERVICE_USER"
   su_cmd() { gosu $SERVICE_USER "$@" || return 1; }
-elif [ "$(builtin type -P su)" ]; then
-  su_cmd_bin="su -s /bin/sh - $SERVICE_USER"
-  su_cmd() { su -s /bin/sh - $SERVICE_USER -c "$@" || return 1; }
 elif [ "$(builtin type -P runuser)" ]; then
   su_cmd_bin="runuser -u $SERVICE_USER"
   su_cmd() { runuser -u $SERVICE_USER "$@" || return 1; }
 elif [ "$(builtin type -P sudo)" ]; then
   su_cmd_bin="sudo -u $SERVICE_USER"
   su_cmd() { sudo -u $SERVICE_USER "$@" || return 1; }
+elif [ "$(builtin type -P su)" ]; then
+  su_cmd_bin="su -s /bin/sh - $SERVICE_USER"
+  su_cmd() { su -s /bin/sh - $SERVICE_USER -c "$@" || return 1; }
 else
   echo "Can not switch to $SERVICE_USER"
   exit 10
@@ -96,10 +117,9 @@ fi
 if [ -n "$WORKDIR" ] && [ -n "$SERVICE_USER" ]; then
   echo "Fixing file permissions"
   su_cmd chown -Rf $SERVICE_USER $WORKDIR
-  sleep 1
 fi
 echo "Starting service: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
-SERVICE_IS_RUNNING="true"
+sleep 30 && SERVICE_IS_RUNNING="true"
 su_cmd "touch /tmp/$EXEC_CMD_BIN.pid"
 su_cmd "$EXEC_CMD_BIN $EXEC_CMD_ARGS" || echo "Failed to execute: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
 [ "$?" -ne 0 ] && SERVICE_IS_RUNNING="false" && SERVICE_EXIT_CODE=10 && rm -Rf "/tmp/$EXEC_CMD_BIN.pid"
