👌 IMPROVE: giadmin 👌

diff --git a/bin/gitadmin b/bin/gitadmin
--- a/bin/gitadmin
+++ b/bin/gitadmin
@@ -340,7 +340,9 @@ repos_init() {
   REPODIR="$(__basedir "${1:-$REPODIR}/.git")"
   [ -f "$VERSIONFILE" ] && date +"$VERSION_DATE_FORMAT" >"$VERSIONFILE"
   git -C "${REPODIR}" add .
-  if [ -f "${REPODIR}/gitmasterconfig" ]; then cp -Rf "${REPODIR}/gitmasterconfig" "${REPODIR}/.git/config"; fi
+  if [ -f "${REPODIR}/gitmasterconfig" ]; then
+    cp -Rf "${REPODIR}/gitmasterconfig" "${REPODIR}/.git/config"
+  fi
   __devnull2 git -C "${REPODIR}" commit -m ' 🦈🏠🐜 Initial Commit 🐜🦈🏠 '
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -358,8 +360,32 @@ git_init() {
   __git_push "$REPODIR" -u origin master
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# List gists
+ghgist_list() {
+  local USERNAME="$1"
+  local SUCCESS="Success"
+  local ERROR="Failed"
+  shift 1
+  [ -n "$USERNAME" ] || printf_exit "Please provide the an username"
+  curl -q -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" \
+    https://api.github.com/users/$USERNAME/gists && return 0 || return 1
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Delete gist
+ghgist_delete() {
+  local ID="$1"
+  local SUCCESS="Success"
+  local ERROR="Failed"
+  shift 1
+  [ -n "$ID" ] || printf_exit "Please provide the gist ID"
+  __devnull2 curl -q -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" \
+    -LSs -X DELETE https://api.github.com/gists/$ID
+  __getexitcode "$SUCCES" "$ERROR"
+  return $EXIT
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Creates a new gist
-ghgist() {
+ghgist_create() {
   [ "$1" = "--help" ] && printf_green "Usage: --gist name description text\n" && return 1
   [ "$1" = "" ] && printf_red "Usage: --gist name description text\n" && return 1
   [ "$2" = "" ] && printf_red "Usage: --gist name description text\n" && return 1
@@ -620,6 +646,29 @@ l | log)
   exit $?
   ;;
 
+gist)
+  shift 1
+  case "$1" in
+  --create)
+    shift 1
+    ghgist_create "$@"
+    exit $EXIT
+    ;;
+
+  --delete)
+    shift 1
+    ghgist_create "$@"
+    exit $EXIT
+    ;;
+
+  --list)
+    shift 1
+    ghgist_create "$@"
+    exit $EXIT
+    ;;
+  esac
+  ;;
+
 commit)
   shift 1
   gitcommit -d "$REPODIR" "$@"
@@ -811,13 +860,6 @@ clone)
   shift 1
   USERNAME="$1"
   ghdelete "$@"
-  exit $EXIT
-  ;;
-
---gist)
-  shift 1
-  USERNAME="$1"
-  ghgist "$@"
   exit $EXIT
   ;;
 
