🐛 FIXED: bin/gitadmin 🐛

diff --git a/bin/gitadmin b/bin/gitadmin
--- a/bin/gitadmin
+++ b/bin/gitadmin
@@ -111,11 +111,11 @@ __git_push() {
 __git_clone() {
   local url="$1" && shift 1
   local dir="$1" && shift 1
-  local args="$*"
+  local args="$*" && shift $#
   local regex="(https?|ftp|file|git|ssh)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]"
   if [[ "$url" =~ $regex ]]; then
     if __am_i_online; then
-      git clone "$url" "$dir" -q $args &>/dev/null && return 0 || return 1
+      git clone "$url" "$dir" -q $args &>>/dev/null && return 0 || return 1
     else
       return 1
     fi
@@ -477,33 +477,6 @@ ghsinglerepo() {
   __git_clone "https://github.com/$1/$2" "${3:-}"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# main program
-main() {
-  sleep 3
-  local USERNAME="$1"
-  local REPO_URL="$REPO_URL/$USERNAME"
-  local PROJECT_DIR="$PROJECT_DIR/github"
-  printf_yellow "ProjectDir: $PROJECT_DIR/$USERNAME"
-  for i in $(cat $TMPFILE); do
-    if [ -d "$PROJECT_DIR/$USERNAME/$i" ]; then
-      ERROR="Git pull $USERNAME/$i failed"
-      SUCCES="Git pull $USERNAME/$i completed"
-      printf_purple "Now running git pull $USERNAME/$i"
-      if [ -f "$REPODIR/gitmasterconfig" ]; then cp -Rf "$REPODIR/gitmasterconfig" "$REPODIR/.git/config"; fi
-      __git_pull "$PROJECT_DIR/$USERNAME/$i" --recurse-submodules
-      __getexitcode "$SUCCES" "$ERROR"
-    else
-      ERROR="Git clone $USERNAME/$i failed"
-      SUCCES="Git clone $USERNAME/$i completed"
-      printf_purple "Now running git clone $USERNAME/$i"
-      __git_clone "$REPO_URL/$i" "$PROJECT_DIR/$USERNAME/$i" --recurse-submodules -q
-      __getexitcode "$SUCCES" "$ERROR"
-    fi
-  done
-  rm -Rf "/tmp/github-casjaysdev-*"
-  exit "${EXIT:-$?}"
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # push local repo
 git_push_single() {
   [ "$1" = "--help" ] || [ $# -eq 0 ] && printf_help "Usage: gitadmin push MyProjectDir"
@@ -641,6 +614,34 @@ git_io() {
   else
     printf_return "Failed to create the shortened URL"
   fi
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# main cloning function
+main() {
+  sleep 3
+  local USERNAME="${1}"
+  local REPO_URL="${REPO_URL}/${USERNAME}"
+  local PROJECT_DIR="$PROJECT_DIR/github"
+  printf_yellow "ProjectDir: $PROJECT_DIR/$USERNAME"
+  printf_yellow "BaseRepo URL=$REPO_URL"
+  for i in $(cat "$TMPFILE"); do
+    if [ -d "$PROJECT_DIR/$USERNAME/$i/.git" ]; then
+      ERROR="Git pull $USERNAME/$i failed"
+      SUCCES="Git pull $USERNAME/$i completed"
+      printf_purple "Now running git pull $USERNAME/$i"
+      if [ -f "$REPODIR/gitmasterconfig" ]; then cp -Rf "$REPODIR/gitmasterconfig" "$REPODIR/.git/config"; fi
+      __git_pull "$PROJECT_DIR/$USERNAME/$i"
+      __getexitcode "$SUCCES" "$ERROR"
+    else
+      ERROR="Git clone $USERNAME/$i failed"
+      SUCCES="Git clone $USERNAME/$i completed"
+      printf_purple "Now running git clone $USERNAME/$i"
+      __git_clone "$REPO_URL/$i" "$PROJECT_DIR/$USERNAME/$i"
+      __getexitcode "$SUCCES" "$ERROR"
+    fi
+  done
+  rm -Rf "/tmp/github-casjaysdev-*"
+  exit "${EXIT:-$?}"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main application
