👌 IMPROVE: bin/gitadmin 👌
Added github pages support

diff --git a/bin/gitadmin b/bin/gitadmin
--- a/bin/gitadmin
+++ b/bin/gitadmin
@@ -1668,6 +1668,7 @@ __cd_into() {
     fi
   fi
 }
+#
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __strip_git_url() { echo "$1" | sed 's|\.git$||g' | sed -e "s/\r//g"; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -2565,6 +2566,59 @@ github) # github repo
     shift 1
     __update_repo "$@"
     exit $?
+    ;;
+
+  pages) # github pages
+    shift 1
+    case "$1" in
+    build) # force a build
+      shift 1
+      repo="${1:-}" && shift 1
+      status="$(curl -q -LSsf -X "POST" -H 'Accept: application/vnd.github+json' -H 'Authorization: token '$GITADMIN_GITHUB_AUTH_TOKEN'' -H 'X-GitHub-Api-Version: 2022-11-28' 'https://api.github.com/repos/'$repo'/pages/builds' 2>"$GITADMIN_TEMP_FILE" | jq -rc '.url')"
+      [ -n "$status" ] && printf_cyan "Build info: $status" || printf_exit 33 1 "The server returned an error: $(cat "$GITADMIN_TEMP_FILE" | grep 'error' | sed 's|.*error: ||g' | head -n1)"
+      exit $?
+      ;;
+
+    create) # create a page
+      shift 1
+      repo="${1:-}" && shift 1
+      status="$(curl -q -LSsf -X "POST" -H 'Accept: application/vnd.github+json' -H 'Authorization: token '$GITADMIN_GITHUB_AUTH_TOKEN'' -H 'X-GitHub-Api-Version: 2022-11-28' 'https://api.github.com/repos/'$repo'/pages' --data '{"cname":"'$1'","build_type":"'${3:-legacy}'","source":{"branch":"'${4:-main}'","path":"'${2:-/}'"}}' 2>"$GITADMIN_TEMP_FILE" | jq -rc '.cname')"
+      [ -n "$status" ] && printf_cyan "Created: $status" || printf_exit 33 1 "The server returned an error: $(cat "$GITADMIN_TEMP_FILE" | grep 'error' | sed 's|.*error: ||g' | head -n1)"
+      exit $?
+      ;;
+
+    update) # update a page
+      shift 1
+      repo="${1:-}" && shift 1
+      status="$(curl -q -LSsf -X "PUT" -H 'Accept: application/vnd.github+json' -H 'Authorization: token '$GITADMIN_GITHUB_AUTH_TOKEN'' -H 'X-GitHub-Api-Version: 2022-11-28' 'https://api.github.com/repos/'$repo'/pages' --data '{"cname":"'$1'","build_type":"'${3:-legacy}'","source":{"branch":"'${4:-main}'","path":"'${2:-/}'"}}' 2>"$GITADMIN_TEMP_FILE" && echo "$repo" || echo '')"
+      [ -n "$status" ] && printf_cyan "Updated: $status" || printf_exit 33 1 "The server returned an error: $(cat "$GITADMIN_TEMP_FILE" | grep 'error' | sed 's|.*error: ||g' | head -n1)"
+      exit $?
+      ;;
+
+    delete) # delete a page
+      shift 1
+      repo="${1:-}" && shift 1
+      status="$(curl -q -LSsf -X "DELETE" -H 'Accept: application/vnd.github+json' -H 'Authorization: token '$GITADMIN_GITHUB_AUTH_TOKEN'' -H 'X-GitHub-Api-Version: 2022-11-28' 'https://api.github.com/repos/'$repo'/pages' 2>"$GITADMIN_TEMP_FILE" && echo "$repo" || echo '')"
+      [ -n "$status" ] && printf_cyan "Deleted: $status" || printf_exit 33 1 "The server returned an error: $(cat "$GITADMIN_TEMP_FILE" | grep 'error' | sed 's|.*error: ||g' | head -n1)"
+      exit $?
+      ;;
+
+    health) # get dns info
+      set -x
+      shift 1
+      repo="${1:-}" && shift 1
+      status="$(curl -q -LSsf --retry-all-errors --retry 3 --retry-delay 5 -X "GET" -H 'Accept: application/vnd.github+json' -H 'Authorization: token '$GITADMIN_GITHUB_AUTH_TOKEN'' -H 'X-GitHub-Api-Version: 2022-11-28' 'https://api.github.com/repos/'$repo'/pages/health' 2>"$GITADMIN_TEMP_FILE" | jq -r '.' || echo '')"
+      [ -n "$status" ] && echo "$status" || printf_exit 33 1 "The server returned an error: $(cat "$GITADMIN_TEMP_FILE" | grep 'error' | sed 's|.*error: ||g' | head -n1)"
+      exit $?
+      ;;
+
+    *) # get info
+      repo="${1:-}" && shift 1
+      status="$(curl -q -LSsf -X "GET" -H 'Accept: application/vnd.github+json' -H 'Authorization: token '$GITADMIN_GITHUB_AUTH_TOKEN'' -H 'X-GitHub-Api-Version: 2022-11-28' 'https://api.github.com/repos/'$repo'/pages' 2>"$GITADMIN_TEMP_FILE" | jq -r '{"status":.status,"url":.cname,"url":.html_url,"build":.build_type,"https":.https_enforced,"404":.custom_404}' || echo '')"
+      [ -n "$status" ] && echo "$status" || printf_exit 33 1 "The server returned an error: $(cat "$GITADMIN_TEMP_FILE" | grep 'error' | sed 's|.*error: ||g' | head -n1)"
+      exit $?
+      ;;
+    esac
     ;;
   esac
   ;;
