🗃️ Committing everything that changed 🗃️
bin/gitcommit
.claude/settings.local.json
.gitignore

diff --git a/bin/gitcommit b/bin/gitcommit
--- a/bin/gitcommit
+++ b/bin/gitcommit
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # shellcheck shell=bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version           :  202510072157-git
+##@Version           :  202510070327-git
 # @@Author           :  Jason Hempstead
 # @@Contact          :  jason@casjaysdev.pro
 # @@License          :  WTFPL
@@ -9,8 +9,8 @@
 # @@Copyright        :  Copyright: (c) 2022 Jason Hempstead, Casjays Developments
 # @@Created          :  Monday, Aug 08, 2022 23:40 EDT
 # @@File             :  gitcommit
-# @@Description      :  Commit changes to a git repo
-# @@Changelog        :  Added .git/COMMIT_MESS file parsing support
+# @@Description      :  Commit changes to a git repo - self-contained, no external dependencies
+# @@Changelog        :  Refactored: removed external dependencies, inlined all functions, removed dead code
 # @@TODO             :  Fix/re-write variables
 # @@Other            :
 # @@Resource         :
@@ -21,7 +21,7 @@
 # shellcheck disable=SC1001,SC1003,SC2001,SC2003,SC2016,SC2031,SC2120,SC2155,SC2199,SC2317,SC2329
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 APPNAME="$(basename -- "$0" 2>/dev/null)"
-VERSION="202510072157-git"
+VERSION="202510070327-git"
 USER="${SUDO_USER:-$USER}"
 RUN_USER="${RUN_USER:-$USER}"
 USER_HOME="${USER_HOME:-$HOME}"
@@ -45,25 +45,6 @@ export CASJAYSDEV_TITLE_PREV="${CASJAYSDEV_TITLE_PREV:-${CASJAYSDEV_TITLE_SET:-$
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # pipes fail
 set -o pipefail
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Import functions
-CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
-SCRIPTSFUNCTDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}/functions"
-SCRIPTSFUNCTFILE="${SCRIPTSAPPFUNCTFILE:-testing.bash}"
-SCRIPTSFUNCTURL="${SCRIPTSAPPFUNCTURL:-https://github.com/dfmgr/installer/raw/main/functions}"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [ -f "$PWD/$SCRIPTSFUNCTFILE" ]; then
-  . "$PWD/$SCRIPTSFUNCTFILE"
-elif [ -f "$SCRIPTSFUNCTDIR/$SCRIPTSFUNCTFILE" ]; then
-  . "$SCRIPTSFUNCTDIR/$SCRIPTSFUNCTFILE"
-else
-  echo "Can not load the functions file: $SCRIPTSFUNCTDIR/$SCRIPTSFUNCTFILE" 1>&2
-  exit 1
-fi
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Options are: *_install
-# system user desktopmgr devenvmgr dfmgr dockermgr fontmgr iconmgr pkmgr systemmgr thememgr wallpapermgr
-user_install && __options "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Send all output to /dev/null
 __devnull() {
@@ -134,6 +115,169 @@ __printf_line() { printf_cyan "$1"; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # output version
 __version() { printf_cyan "$VERSION"; }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Inlined external functions - BEGIN
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Printf functions from colors.bash
+printf_newline() {
+  [[ -n "$1" ]] && printf '%b\n' "${*:-}" || printf '\n'
+}
+printf_green() {
+  printf_color "$1" 2
+  printf "\n"
+}
+printf_red() {
+  printf_color "$1" 9
+  printf "\n"
+}
+printf_purple() {
+  printf_color "$1" 5
+  printf "\n"
+}
+printf_yellow() {
+  printf_color "$1" 3
+  printf "\n"
+}
+printf_blue() {
+  printf_color "$1" 33
+  printf "\n"
+}
+printf_cyan() {
+  printf_color "$1" 6
+  printf "\n"
+}
+printf_return() {
+  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="1"
+  test -n "$1" && test -z "${1//[0-9]/}" && local exitCode="$1" && shift 1 || local exitCode="1"
+  local msg="$*"
+  [ ${#msg} = 0 ] || { printf_color "$msg" "$color" 1>&2 && printf "\n"; }
+  return ${exitCode:-2}
+}
+printf_error() {
+  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="1"
+  test -n "$1" && test -z "${1//[0-9]/}" && local exitCode="$1" && shift 1 || local exitCode="1"
+  local msg="$*"
+  printf_color "$ICON_ERROR $msg" "$color" 1>&2
+  printf "\n"
+  return $exitCode
+}
+printf_exit() {
+  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="1"
+  test -n "$1" && test -z "${1//[0-9]/}" && local exitCode="$1" && shift 1 || local exitCode="1"
+  local msg="$*"
+  shift
+  printf_color "$msg" "$color" 1>&2
+  printf "\n"
+  exit "$exitCode"
+}
+printf_read_question() {
+  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="1"
+  local msg="$1" && shift 1
+  test -n "$1" && test -z "${1//[0-9]/}" && local lines="$1" && shift 1 || local lines="120"
+  local reply="${1:-REPLY}" && shift 1
+  local readopts="${1:-}" && shift 1
+  printf_color "$msg " "${PRINTF_COLOR:-$color}"
+  read -t 30 -e -r -n $lines ${readopts:-} ${reply:-} || return 1
+  [ -z "$reply" ] && printf '\n' && return 1 || return 0
+}
+printf_answer_yes() {
+  local answerVar="${1:-$REPLY}"
+  if [[ "$answerVar" =~ ${2:-^[Yy]$} ]]; then
+    exitCode=0
+  elif [ -z "$answerVar" ] || [ "$answerVar" = "" ]; then
+    printf '\n'
+    exitCode=1
+  else
+    exitCode=1
+  fi
+  return ${exitCode:-0}
+}
+printf_custom() {
+  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="5"
+  local msg="$*"
+  shift
+  printf_color "$msg" "${PRINTF_COLOR:-$color}"
+  printf "\n"
+}
+printf_readline() {
+  set -o pipefail
+  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="6"
+  while read line; do
+    printf_color "$line" "${PRINTF_COLOR:-$color}"
+    printf "\n"
+  done
+  set +o pipefail
+}
+printf_column() {
+  local -a column=""
+  set -o pipefail
+  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="7"
+  cat - |& column | printf_readline "${color:-$COLOR}"
+  printf "\n"
+  set +o pipefail
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Exit status functions from exit_status.bash
+__setexitstatus() {
+  local EXITCODE=$?
+  test -n "$1" && test -z "${1//[0-9]/}" && local EXITCODE="$1" && shift 1
+  [ -z "$1" ] || EXIT="$1"
+  if [ "$EXITCODE" = 0 ]; then
+    NEW_BG_EXIT="${BG_GREEN}"
+  else
+    NEW_BG_EXIT="${BG_RED}"
+  fi
+  export NEW_BG_EXIT
+  return ${exitCode:-0}
+}
+__returnexitcode() {
+  local EXITCODE=$?
+  test -n "$1" && test -z "${1//[0-9]/}" && local EXITCODE="$1" && shift 1
+  if [ $EXITCODE -eq 0 ]; then
+    NEW_BG_EXIT="${BG_GREEN}"
+    NEW_PS_SYMBOL=" 😺 [ $EXITCODE] "
+    EXIT=0
+  elif [ $EXITCODE -gt 1 ]; then
+    NEW_BG_EXIT="${BG_RED}"
+    NEW_PS_SYMBOL=" ⁉️ [ $EXITCODE] "
+  else
+    NEW_BG_EXIT="${BG_RED}"
+    NEW_PS_SYMBOL=" 😟 [ $EXITCODE] "
+  fi
+  export NEW_BG_EXIT NEW_PS_SYMBOL
+  return ${exitCode:-0}
+}
+__getexitcode() {
+  local EXITCODE=$?
+  test -n "$1" && test -z "${1//[0-9]/}" && EXITCODE="$1" && shift 1 || EXITCODE="${EXITCODE:-0}"
+  if [ -n "$1" ]; then
+    local PSUCCES="$1"
+  elif [ -n "$SUCCES" ]; then
+    local PSUCCES="$SUCCES"
+  elif [ -n "$GETEXITCODE_SUCCES" ]; then
+    local PSUCCES="$GETEXITCODE_SUCCES"
+  else
+    local PSUCCES="Command successful"
+  fi
+  if [ -n "$2" ]; then
+    local PERROR="$2"
+  elif [ -n "$ERROR" ]; then
+    local PERROR="$ERROR"
+  elif [ -n "$GETEXITCODE_ERROR" ]; then
+    local PSUCCES="$GETEXITCODE_ERROR"
+  else
+    local PERROR="Last command failed to complete"
+  fi
+  if [ "$EXITCODE" = 0 ]; then
+    printf_cyan "$PSUCCES"
+  else
+    printf_error "$PERROR"
+  fi
+  __returnexitcode "$EXITCODE"
+  return "$EXITCODE"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Inlined external functions - END
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # list options
 __list_options() {
@@ -266,75 +410,6 @@ __help() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # check if arg is a builtin option
 __is_an_option() { if echo "$ARRAY" | grep -q "${1:-^}"; then return 1; else return 0; fi; }
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Is current user root
-__user_is_root() {
-  { [ $(id -u) -eq 0 ] || [ $EUID -eq 0 ] || [ "$WHOAMI" = "root" ]; } && return 0 || return 1
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Is current user not root
-__user_is_not_root() {
-  if { [ $(id -u) -eq 0 ] || [ $EUID -eq 0 ] || [ "$WHOAMI" = "root" ]; }; then return 1; else return 0; fi
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Check if user is a member of sudo
-__sudo_group() {
-  grep -sh "${1:-$USER}" "/etc/group" | grep -Eq 'wheel|adm|sudo' || return 1
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# # Get sudo password
-__sudoask() {
-  ask_for_password sudo true && return 0 || return 1
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Run sudo
-__sudorun() {
-  __sudoif && __cmd_exists sudo && sudo -HE "$@" || { __sudoif && eval "$@"; }
-  return $?
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Test if user has access to sudo
-__can_i_sudo() {
-  (sudo -vn && sudo -ln) 2>&1 | grep -vq 'may not' >/dev/null && return 0
-  __sudo_group "${1:-$USER}" || __sudoif || __sudo true &>/dev/null || return 1
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# User can run sudo
-__sudoif() {
-  __user_is_root && return 0
-  __can_i_sudo "${RUN_USER:-$USER}" && return 0
-  __user_is_not_root && __sudoask && return 0 || return 1
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Run command as root
-requiresudo() {
-  if [ "$GITCOMMIT_REQUIRE_SUDO" = "yes" ] && [ -z "$GITCOMMIT_REQUIRE_SUDO_RUN" ]; then
-    export GITCOMMIT_REQUIRE_SUDO="no"
-    export GITCOMMIT_REQUIRE_SUDO_RUN="true"
-    __sudo "$@"
-    exit $?
-  else
-    return 0
-  fi
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Execute sudo
-__sudo() {
-  CMD="${1:-echo}" && shift 1
-  CMD_ARGS="${*:--e "${RUN_USER:-$USER}"}"
-  SUDO="$(builtin command -v sudo 2>/dev/null || echo 'eval')"
-  [ "$(basename -- "$SUDO" 2>/dev/null)" = "sudo" ] && OPTS="--preserve-env=PATH -HE"
-  if __sudoif; then
-    export PATH="$PATH"
-    $SUDO ${OPTS:-} $CMD $CMD_ARGS && true || false
-    exitCode=$?
-  else
-    printf '%b\n' "This requires root to run"
-    exitCode=1
-  fi
-  return ${exitCode:-1}
-}
-# End of sudo functions
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __trap_exit() {
   exitCode=${exitCode:-0}
@@ -700,6 +775,49 @@ __git_mod() {
   unset changed_files prepend
   return ${exitCode:-0}
 }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Additional git helper functions (previously external)
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__basename() {
+  basename -- "${1:-.}" 2>/dev/null
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__git_top_dir() {
+  git -C "${1:-.}" rev-parse --show-toplevel 2>/dev/null |
+    grep -v fatal && return 0 || echo "${1:-$PWD}"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__git_remote_pull() {
+  git -C "${1:-.}" remote -v 2>/dev/null |
+    grep push | head -n 1 | awk '{print $2}' 2>/dev/null |
+    grep '^'
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__git_remote_fetch() {
+  git -C "${1:-.}" remote -v 2>/dev/null |
+    grep fetch | head -n 1 | awk '{print $2}' 2>/dev/null |
+    grep '^' && return 0 || return 1
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__git_remote_origin() {
+  __git_remote_pull "${1:-.}" &&
+    return 0 || return 1
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__git_porcelain_count() {
+  [ -d "$(__git_top_dir ${1:-.})/.git" ] &&
+    [ "$(git -C "${1:-.}" status --porcelain 2>/dev/null | wc -l 2>/dev/null)" -eq "0" ] &&
+    return 0 || return 1
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__git_porcelain() {
+  __git_porcelain_count "${1:-.}" &&
+    return 0 || return 1
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__git_repobase() { __basename "$(__git_top_dir "${1:-$PWD}")" 2>/dev/null || echo "$(__basename "$PWD")"; }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# End additional git helper functions
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __git_add() {
   local message="$*"
