🗃️ modified: bin/gitcommit 🗃️

diff --git a/bin/gitcommit b/bin/gitcommit
--- a/bin/gitcommit
+++ b/bin/gitcommit
@@ -186,8 +186,8 @@ __gitcommit_cmd() {
 __gitcommit() {
   __git_porcelain "$GITCOMMIT_CWD" &>/dev/null && return
   local mess="${commitmess:-}"
-  local succ="🔗 Successfully committed the changes to 🔗"
-  local fail=":no_entry: Failed to commit the changes to :no_entry:"
+  local succ="Successfully committed the changes to"
+  local fail="Failed to commit the changes to"
   local column_length=$(($(tput cols) - 20))
   local removemess="${commitmess:10:30}"
   [ -n "$message_set" ] || __gitmessage "$mess"
@@ -198,7 +198,7 @@ __gitcommit() {
   [ -n "$show_message" ] && printf_blue "${show_message:0:$column_length}"
   if __gitcommit_cmd; then
     if [ "$NO_MESSAGE" != "true" ]; then
-      if __getexitcode "${GITCOMMIT_EXITCODE:-$?}" "$succ $(__git_repobase "$GITCOMMIT_CWD")" "$fail $(__git_repobase "$GITCOMMIT_CWD")"; then
+      if __getexitcode "${GITCOMMIT_EXITCODE:-$?}" "🔗 $succ $(__git_repobase "$GITCOMMIT_CWD") 🔗" "🚫 $fail $(__git_repobase "$GITCOMMIT_CWD") 🚫"; then
         printf_green "🆔commit ID: $(__git_commitid "$GITCOMMIT_CWD") 🆔"
         COMMIT_ID="$(__git_commitid "$GITCOMMIT_CWD")"
       fi
@@ -452,15 +452,15 @@ __write_version() {
 __set_version() {
   if [ "$1" = "--force" ] || [ -f "$GITCOMMIT_CWD/$GITCOMMIT_VERSION_FILE" ]; then
     local git_dir="$GITCOMMIT_CWD"
-    local git_sucess="🔗 Successfully committed the new version to 🔗"
-    local git_failed=":no_entry:Failed to commit the version change in :no_entry:"
+    local git_sucess="Successfully committed the new version to"
+    local git_failed="Failed to commit the version change in"
     local GITCOMMIT_MESSAGE="🚀 Version Bump: $(cat "$GITCOMMIT_CWD/$GITCOMMIT_VERSION_FILE") 🚀 "
     local GITCOMMIT_EXITCODE=0
     __write_version "$1" || printf_exit "Version files doesn't exist"
     git -C "$GITCOMMIT_CWD" add "$GITCOMMIT_VERSION_FILE" &>/dev/null &&
       git -C "$GITCOMMIT_CWD" commit -m "$GITCOMMIT_MESSAGE" &>/dev/null &&
       GITCOMMIT_EXITCODE=0 || GITCOMMIT_EXITCODE=1
-    __getexitcode $GITCOMMIT_EXITCODE "$git_sucess $(__git_repobase "$git_dir")" "$git_failed ${git_dir//$PWD/.}"
+    __getexitcode $GITCOMMIT_EXITCODE "🔗 $git_sucess $(__git_repobase "$git_dir")🔗 " "🚫 $git_failed ${git_dir//$PWD/.} 🚫"
   fi
   export NO_MESSAGE=true PUSH_ENABLE=true
 }
