🗃️ Committing everything that changed 🗃️

diff --git a/bin/latest-releases b/bin/latest-releases
--- a/bin/latest-releases
+++ b/bin/latest-releases
@@ -85,7 +85,7 @@ __cmd_exists() {
 # Check for a valid internet connection
 __am_i_online() {
   local exitCode=0
-  curl -q -LSsfI --max-time 1 --retry 0 "${1:-http://1.1.1.1}" 2>&1 | grep -qi 'server:.*cloudflare' || exitCode=4
+  curl -q -LSsfI --max-time 1 --retry 0 "${1:-http://1.1.1.1}" 2>&1 | __grep -qi 'server:.*cloudflare' || exitCode=4
   return ${exitCode:-$?}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -147,7 +147,7 @@ LATEST_RELEASES_NOTIFY_CLIENT_ICON="${LATEST_RELEASES_NOTIFY_CLIENT_ICON:-}"
 LATEST_RELEASES_NOTIFY_CLIENT_URGENCY="${LATEST_RELEASES_NOTIFY_CLIENT_URGENCY:-}"
 
 EOF
-  if builtin type -t __gen_config_local | grep -q 'function'; then __gen_config_local; fi
+  if builtin type -t __gen_config_local | __grep -q 'function'; then __gen_config_local; fi
   if [ -f "$LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASES_CONFIG_FILE" ]; then
     [ "$INIT_CONFIG" = "TRUE" ] || printf_green "Your config file for $APPNAME has been created"
     . "$LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASES_CONFIG_FILE"
@@ -192,7 +192,7 @@ __user_is_not_root() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Check if user is a member of sudo
 __sudo_group() {
-  grep -s "${1:-$USER}" "/etc/group" | grep -Eq 'wheel|adm|sudo' || return 1
+  __grep -s "${1:-$USER}" "/etc/group" | __grep -Eq 'wheel|adm|sudo' || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # # Get sudo password
@@ -208,7 +208,7 @@ __sudorun() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Test if user has access to sudo
 __can_i_sudo() {
-  (sudo -vn && sudo -ln) 2>&1 | grep -vq 'may not' >/dev/null && return 0
+  (sudo -vn && sudo -ln) 2>&1 | __grep -vq 'may not' >/dev/null && return 0
   __sudo_group "${1:-$USER}" || __sudoif || __sudo true &>/dev/null || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -252,19 +252,23 @@ __sudo() {
 __trap_exit() {
   exitCode=${exitCode:-$?}
   [ -f "$LATEST_RELEASES_TEMP_FILE" ] && rm -Rf "$LATEST_RELEASES_TEMP_FILE" &>/dev/null
-  if builtin type -t __trap_exit_local | grep -q 'function'; then __trap_exit_local; fi
+  if builtin type -t __trap_exit_local | __grep -q 'function'; then __trap_exit_local; fi
   return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # User defined functions
+__grep() {
+  grep "$@" 2>/dev/null
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 search_gh_api() {
   local -a results=()
   local api_results=""
   api_results="$(curl -q -LSsf -H "Accept: application/vnd.github+json" "https://api.github.com/search/repositories?q=$1&sort=stars&order=desc&per_page=60" 2>/dev/null | jq '.items | .[]')"
-  results=("$(echo "${api_results}" | jq -c '[.full_name,.description]' | sed 's|\]||g;s|\[||g;s|"||g' | awk -F',' '{print $1": "$2}' | grep -iwF "$1")")
+  results=("$(echo "${api_results}" | jq -c '[.full_name,.description]' | sed 's|\]||g;s|\[||g;s|"||g' | awk -F',' '{print $1": "$2}' | __grep -iwF "$1")")
   if [ -n "${results[*]}" ]; then
     for line in "${results[@]}"; do
-      echo "$line" | cut -c 1-120 | grep -v ': null' | grep '^'
+      echo "$line" | cut -c 1-120 | __grep -v ': null' | __grep '^'
       exitCode+=$?
     done
   else
@@ -293,7 +297,7 @@ __gitea() {
     get_arch="arm64"
   fi
   arch="${LATEST_RELEASES_ARCH_TYPE:-$get_arch}"
-  url="$(curl -q -LSs -X 'GET' "$api_url" -H 'accept: application/json' 2>/dev/null | jq -rc '.[].assets | .[] | {name: .name, link: .browser_download_url}' | grep ''$arch'"' | grep -i "$(uname -s)" | jq -c | head -n1 | jq -r | grep link | awk -F '":' '{print $2}' | sed 's|"||g;s| ||g')"
+  url="$(curl -q -LSs -X 'GET' "$api_url" -H 'accept: application/json' 2>/dev/null | jq -rc '.[].assets | .[] | {name: .name, link: .browser_download_url}' | __grep ''$arch'"' | __grep -i "$(uname -s)" | jq -c | head -n1 | jq -r | __grep link | awk -F '":' '{print $2}' | sed 's|"||g;s| ||g')"
   printf_green "Attempting to download $filename from $url"
   printf_green "and save to $download_dir/$filename"
   curl -q -LSs "$url" -o "$tempfile" 2>/dev/null || printf_exit "Failed to download the file"
@@ -328,7 +332,7 @@ __gitlab() {
     get_arch="arm64"
   fi
   arch="${LATEST_RELEASES_ARCH_TYPE:-$get_arch}"
-  url="$(curl -q -LSs -X 'GET' "$api_url" -H 'accept: application/json' 2>/dev/null | jq -rc '.[].assets | .[] | {name: .name, link: .browser_download_url}' | grep ''$arch'"' | grep -i "$(uname -s)" | jq -c | head -n1 | jq -r | grep link | awk -F '":' '{print $2}' | sed 's|"||g;s| ||g')"
+  url="$(curl -q -LSs -X 'GET' "$api_url" -H 'accept: application/json' 2>/dev/null | jq -rc '.[].assets | .[] | {name: .name, link: .browser_download_url}' | __grep ''$arch'"' | __grep -i "$(uname -s)" | jq -c | head -n1 | jq -r | __grep link | awk -F '":' '{print $2}' | sed 's|"||g;s| ||g')"
   printf_green "Attempting to download $filename from $url"
   printf_green "and save to $download_dir/$filename"
   curl -q -LSs "$url" -o "$tempfile" 2>/dev/null || printf_exit "Failed to download the file"
@@ -344,15 +348,15 @@ __gitlab() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __add_to_latest() {
-  if ! grep -qs "$1" "$LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASE_REPO_LIST"; then
+  if ! __grep -qs "$1" "$LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASE_REPO_LIST"; then
     printf_purple "Added ${2:-$1} to $LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASE_REPO_LIST"
     printf '%s\n' "${2:-$1}" | tee -a "$LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASE_REPO_LIST" &>/dev/null
   fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __remove_from_latest() {
-  if grep -qs "$1" "$LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASE_REPO_LIST"; then
-    if grep -v "$1" "$LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASE_REPO_LIST" | tee "$LATEST_RELEASES_TEMP_FILE" &>/dev/null; then
+  if __grep -qs "$1" "$LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASE_REPO_LIST"; then
+    if __grep -v "$1" "$LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASE_REPO_LIST" | tee "$LATEST_RELEASES_TEMP_FILE" &>/dev/null; then
       __mv_f "$LATEST_RELEASES_TEMP_FILE" "$LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASE_REPO_LIST"
       printf_purple "Removed ${2:-$1} from $LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASE_REPO_LIST"
     fi
@@ -402,11 +406,11 @@ EOF
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __install_latest() {
-  echo "$1" | grep -qv '^#' || return
-  echo "$1" | grep -qv '^$' || [ -n "$LATEST_RELEASE_FULL_URL" ] || return
+  echo "$1" | __grep -qv '^#' || return
+  echo "$1" | __grep -qv '^$' || [ -n "$LATEST_RELEASE_FULL_URL" ] || return
   set_arch="$(uname -m)"
   [ "$1" = search ] && search="true" && shift 1
-  if echo "$1" | grep -q './.' || [ $# == 1 ]; then
+  if echo "$1" | __grep -q './.' || [ $# == 1 ]; then
     repo="$1"
     shift 1
   elif [ $# -gt 1 ]; then
@@ -437,7 +441,7 @@ __install_latest() {
     latest_download="$LATEST_RELEASE_FULL_URL"
   elif [ -n "$LATEST_RELEASES_FILENAME" ]; then
     latest_json="$(__curl_json_all "$repo")"
-    latest_download="$(echo "$latest_json" | grep -i "$LATEST_RELEASES_FILENAME" | head -n1 | grep '^')"
+    latest_download="$(echo "$latest_json" | __grep -i "$LATEST_RELEASES_FILENAME" | head -n1 | __grep '^')"
   else
     latest_json="$(__curl_json)"
     latest_download="$(__browser_download_url "$latest_json" "$arch" || return 1)"
@@ -457,7 +461,7 @@ __install_latest() {
   extract_name="$(basename "$repo")"
   extract_dir="$LATEST_RELEASE_INSTALL_DIR/$extract_name"
   if [ "$search" = "true" ]; then
-    echo "$latest_json" | grep -iE 'browser_download_url' | awk '{print $2}' | sed 's|"||g' | printf_readline '6'
+    echo "$latest_json" | __grep -iE 'browser_download_url' | awk '{print $2}' | sed 's|"||g' | printf_readline '6'
   elif [ -n "$latest_download" ]; then
     printf_green "Attempting to download $latest_download "
     if __wget_latest "$latest_download" "$tempfile"; then
@@ -512,7 +516,7 @@ __install_latest() {
       ;;
     *) ;;
     esac
-    find_file="$(find "$extract_dir" -maxdepth 3 -type f -name "$extract_name" 2>/dev/null | grep "$extract_name$" | head -n1 | grep '^')"
+    find_file="$(find "$extract_dir" -maxdepth 3 -type f -name "$extract_name" 2>/dev/null | __grep "$extract_name$" | head -n1 | __grep '^')"
     [ -z "$LATEST_RELEASES_BIN_NAME" ] || extract_name="$LATEST_RELEASES_BIN_NAME"
     if [ "$(find "$extract_dir" -maxdepth 1 2>/dev/null | wc -l)" -gt 4 ]; then
       ln -sf "$extract_dir/$extract_name" "$HOME/.local/bin/$extract_name" &&
@@ -558,12 +562,12 @@ __install_latest() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __browser_download_url() {
   echo "${1:-$latest_json}" |
-    grep -iE 'browser_download_url' |
-    grep -vE '.*.deb|.*.rpm' |
-    grep -E 'tar.*|*.bz|*.zip|.*' |
+    __grep -iE 'browser_download_url' |
+    __grep -vE '.*.deb|.*.rpm' |
+    __grep -E 'tar.*|*.bz|*.zip|.*' |
     cut -d '"' -f 4 |
-    grep -i "$(uname -s)" | grep -i "${2:-$arch}" |
-    head -n1 | grep '^' || return 1
+    __grep -i "$(uname -s)" | __grep -i "${2:-$arch}" |
+    head -n1 | __grep '^' || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __wget_latest() {
@@ -607,12 +611,12 @@ __curl_json() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __curl_json_all() {
   local results=""
-  echo "$1" | grep -qs './.' || printf_exit "Usage: $APPNAME username/reponame"
+  echo "$1" | __grep -qs './.' || printf_exit "Usage: $APPNAME username/reponame"
   results="$(__curl_json "https://api.github.com/repos/${1:-$repo}/releases" 2>/dev/null)"
   if [ -n "$results" ]; then
-    printf '%s\n' "$results" | jq -r '.[]' | jq -r '.assets | .[].browser_download_url' | sort | grep '^' ||
+    printf '%s\n' "$results" | jq -r '.[]' | jq -r '.assets | .[].browser_download_url' | sort | __grep '^' ||
       {
-        manual_dl="$(echo $results | jq -r '.[] | .html_url' | sort -n | tail -n1 | grep '^')"
+        manual_dl="$(echo $results | jq -r '.[] | .html_url' | sort -n | tail -n1 | __grep '^')"
         printf_custom $LATEST_RELEASES_OUTPUT_COLOR_ERROR "No releases found from ${1:-$repo}"
         if [ -n "$manual_dl" ]; then
           printf_purple "However I did find the following link:"
@@ -661,7 +665,7 @@ __update_install() {
       repo_list=
     done <"$LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASE_REPO_LIST"
   else
-    echo "$@" | grep -q '/' || { printf_red "You provided an invalid repo" && printf_exit "Usage: $APPNAME install user/repo"; }
+    echo "$@" | __grep -q '/' || { printf_red "You provided an invalid repo" && printf_exit "Usage: $APPNAME install user/repo"; }
     for l in "$@"; do
       __install_latest "$l"
     done
@@ -671,7 +675,7 @@ __update_install() {
 __api_repos() {
   res="$(curl -q -LSs -H "Authorization: token $LATEST_RELEASE_GITHUB_TOKEN" \
     "https://api.github.com/users/$1/repos&per_page=500&sort=updated" 2>/dev/null |
-    jq -r '.[] | .name' 2>/dev/null | grep '^' || return 1)"
+    jq -r '.[] | .name' 2>/dev/null | __grep '^' || return 1)"
   [ -n "$res" ] && printf '%s\n' "$res" | sort -n || __api_search "$1"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -789,7 +793,7 @@ while :; do
   --raw)
     shift 1
     export SHOW_RAW="true"
-    printf_column() { tee | grep '^'; }
+    printf_column() { tee | __grep '^'; }
     printf_color() { printf '%b' "$1" | tr -d '\t' | sed '/^%b$/d;s,\x1B\[ 0-9;]*[a-zA-Z],,g'; }
     ;;
   --debug)
@@ -978,19 +982,19 @@ search)
     release)
       shift 1
       [ $# = 0 ] && __search_help && exit 1 || printf_purple "Searching for $*"
-      if echo "$1" | grep -vq './.' && [ $# = 0 ]; then
+      if echo "$1" | __grep -vq './.' && [ $# = 0 ]; then
         __search_help
       elif [ $# -eq 1 ]; then
         __curl_json_all "$1" | printf_readline "$LATEST_RELEASES_OUTPUT_COLOR_1"
       elif [ $# -gt 1 ]; then
-        __curl_json_all "$1" | grep -i $3 "$2" | printf_readline "$LATEST_RELEASES_OUTPUT_COLOR_1"
+        __curl_json_all "$1" | __grep -i $3 "$2" | printf_readline "$LATEST_RELEASES_OUTPUT_COLOR_1"
       fi
       ;;
     *)
       query="$1"
       # { printf_purple "Searching github for $*" && __api_search "$@" || printf_exit "No results found for ${1:-$repo}"; }
       printf_purple "Searching github for $*"
-      results="$(search_gh_api "$query" | grep '^' || __api_search "$query")"
+      results="$(search_gh_api "$query" | __grep '^' || __api_search "$query")"
       if [ -n "$results" ]; then
         #printf_cyan "Found the following results for $query"
         printf '%s\n' "$results" | printf_readline "$LATEST_RELEASES_OUTPUT_COLOR_1"
@@ -1010,7 +1014,7 @@ search)
 *)
   if [ $# -ne 0 ]; then
     for app in "$@"; do
-      if echo "$app" | grep -q '/'; then
+      if echo "$app" | __grep -q '/'; then
         __install_latest "$app" && true || false
       else
         printf_custom "${YELLOW}$app${NC} ${RED}is an invalid repo: format is user/repo${NC}"
