🗃️ Committing everything that changed 🗃️
bin/latest-iso

diff --git a/bin/latest-iso b/bin/latest-iso
--- a/bin/latest-iso
+++ b/bin/latest-iso
@@ -542,9 +542,9 @@ __latest_iso() {
   [ -d "$download_file" ] && rm -Rf "$download_file"
   [ -d "$download_dir" ] || mkdir -p "$download_dir"
   [ -d "$LATEST_ISO_DOWNLOAD_DIR" ] || mkdir -p "$LATEST_ISO_DOWNLOAD_DIR"
-  [ -n "$latest" ] || printf_exit "No iso found on $url\n"
-  [ -d "$LATEST_ISO_DOWNLOAD_DIR" ] || printf_exit "The download file should not be a directory: $LATEST_ISO_DOWNLOAD_DIR\n"
-  echo "$latest" | grep -qE '.iso$|.gz$|.tar$' || printf_exit "$latest seems to be invalid\n"
+  [ -n "$latest" ] || { printf_red "No iso found on $url\n" && return 1; }
+  [ -d "$LATEST_ISO_DOWNLOAD_DIR" ] || { printf_red "The download file should not be a directory: $LATEST_ISO_DOWNLOAD_DIR\n" && return 1; }
+  echo "$latest" | grep -qE '.iso$|.gz$|.tar$' || { printf_red "$latest seems to be invalid\n" && return 1; }
   __grab_iso "$latest" "$download_file" "$archive_iso_name" && exitCode="0" || exitCode="1"
   if [ "$exitCode" = 0 ]; then
     return 0
@@ -704,7 +704,7 @@ __github_api() {
 __latest_list() {
   local statusCode=0
   while :; do
-    case $1 in
+    case "$@" in
     alma)
       shift 1
       LATEST_ISO_NAME="${LATEST_ISO_NAME:-minimal}"
@@ -807,6 +807,7 @@ __latest_list() {
     flatcar)
       shift 1
       __latest_iso "$LATEST_ISO_FLATCAR_URL/flatcar_production_iso_image.iso" "$LATEST_ISO_DOWNLOAD_DIR/flatcar.iso"
+      statusCode=$(($? + $statusCode))
       ;;
     freenas)
       shift 1
