🗃️  Committing everything that changed 🗃️

diff --git a/bin/latest-releases b/bin/latest-releases
--- a/bin/latest-releases
+++ b/bin/latest-releases
@@ -377,10 +377,10 @@ __gen_repolist() {
     printf_green "Creating sample repo lists"
     cat <<EOF | tee "$LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASE_REPO_LIST" &>/dev/null
 # Format user/repo symlinkName
-gokcehan/lf
-go-gitea/gitea
-codeskyblue/gohttpserver
-jesseduffield/lazydocker
+gokcehan/lf                          filemanager
+go-gitea/gitea                       git Server
+codeskyblue/gohttpserver             http server written in go
+jesseduffield/lazydocker             docker script
 koalaman/shellcheck                  shellcheck
 mvdan/sh                             shfmt
 
@@ -622,18 +622,13 @@ __curl_json_all() {
   echo "$1" | __grep -qs './.' || printf_exit "Usage: $APPNAME username/reponame"
   results="$(__curl_json "https://api.github.com/repos/${1:-$repo}/releases" 2>/dev/null)"
   if [ -n "$results" ]; then
-    printf '%s\n' "$results" | jq -r '.[]' | jq -r '.assets | .[].browser_download_url' | sort | __grep '^' ||
-      {
-        manual_dl="$(echo $results | jq -r '.[] | .html_url' | sort -n | tail -n1 | __grep '^')"
-        printf_custom $LATEST_RELEASES_OUTPUT_COLOR_ERROR "No releases found from ${1:-$repo}"
-        if [ -n "$manual_dl" ]; then
-          printf_purple "However I did find the following link:"
-          printf '%s\n' "$manual_dl" | printf_readline $LATEST_RELEASES_OUTPUT_COLOR_1
-        fi
-        exit 1
-      }
-  else
-    printf_exit "No releases found for ${1:-$repo}"
+    links="$(printf '%s\n' "$results" | jq -r '.[]' | jq -r '.assets | .[].browser_download_url' | grep -vE '.sig$|.pem$|.gpg$|.txt$|.md5$|.sha512$|sha256$' | sort -rV | __grep '^' || echo '')"
+    if [ -n "$links" ]; then
+      printf '%s\n' "$links"
+    else
+      printf '%s\n' "Error: "
+      return 1
+    fi
   fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -666,7 +661,6 @@ __show_latest() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __update_install() {
   local l="" repo_list=""
-
   if [ -f "$LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASE_REPO_LIST" ] && [ -z "$1" ]; then
     grep -sv '^#' "$LATEST_RELEASES_CONFIG_DIR/$LATEST_RELEASE_REPO_LIST" | while read -r get_repo_list; do
       if [ -n "$get_repo_list" ]; then
