🗃️ modified: bin/latest-iso 🗃️

diff --git a/bin/latest-iso b/bin/latest-iso
--- a/bin/latest-iso
+++ b/bin/latest-iso
@@ -99,15 +99,20 @@ EOF
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Additional functions
 __test_iso() {
-  local test="$(echo "$1" | grep -aE 'http|ftp' | grep -a '.iso$' | grep '^' || echo '')"
+  local test="$(echo "$1" | __grep_a -aE 'http|ftp' | __grep_a -a '.iso$' | __grep_a '^' || echo '')"
   local verify="$([[ -n "$test" ]] && __urlcheck "$test" &>/dev/null && echo 'valid' || echo 'error')"
   [[ "$verify" = "valid" ]] || test=""
   [[ -n "$test" ]] && return 0 || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__grep_a() {
+  local args="$*"
+  grep -a $args
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __sort_v() {
   __strip_tags |
-    grep '^[0-9]' |
+    __grep_a '^[0-9]' |
     sort -rV |
     head -n1 |
     sed 's|/$||g' |
@@ -115,11 +120,11 @@ __sort_v() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __strip_iso() {
-  grep -aE '[_|-|.]*.*[_|-|.]' |
-    grep -av 'torrent' |
-    grep -av 'target' |
-    grep -av 'ti-download' |
-    grep -a '.iso'
+  __grep_a -aE '[_|-|.]*.*[_|-|.]' |
+    __grep_a -av 'torrent' |
+    __grep_a -av 'target' |
+    __grep_a -av 'ti-download' |
+    __grep_a -a '.iso'
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __strip_tags() {
@@ -133,20 +138,20 @@ __strip_tags() {
     sed 's|>.*||g' |
     sed "s|$iso/download$|$iso|g" |
     sed 's|.iso.torrent|.iso|g' |
-    grep -v '^$'
+    __grep_a -v '^$'
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __verify_arch() {
   local latest="${1:-$latest}"
-  if echo "$latest" | grep -q 'x86_64'; then
+  if echo "$latest" | __grep_a -q 'x86_64'; then
     arch="x86_64"
-  elif echo "$latest" | grep -q 'amd64'; then
+  elif echo "$latest" | __grep_a -q 'amd64'; then
     arch="x86_64"
-  elif echo "$latest" | grep -qE 'i[1-9]86'; then
+  elif echo "$latest" | __grep_a -qE 'i[1-9]86'; then
     arch="i386"
-  elif echo "$latest" | grep -q 'aarch64'; then
+  elif echo "$latest" | __grep_a -q 'aarch64'; then
     arch="aarch64"
-  elif echo "$latest" | grep -q 'arm*'; then
+  elif echo "$latest" | __grep_a -q 'arm*'; then
     arch="arm"
   else
     arch="x86_64"
@@ -155,7 +160,7 @@ __verify_arch() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __get_arch() {
-  get_arch=$(uname -i | grep -v 'unknown' | grep '^' || uname -m | grep '^' || uname -p | grep '^')
+  get_arch=$(uname -i | __grep_a -v 'unknown' | __grep_a '^' || uname -m | __grep_a '^' || uname -p | __grep_a '^')
   if [[ $get_arch == x86_64* ]]; then
     echo "x86_64"
   elif [[ $get_arch == i*86 ]]; then
@@ -174,27 +179,27 @@ __find_iso() {
   if __test_iso "$url"; then
     iso_url="$url"
   else
-    iso_url="$(curl -q -LSsf "$url" 2>/dev/null | grep "$arch" | grep 'href="*.*"' | grep -E '[http,ftp]*.*\.iso' | __strip_tags | __strip_iso | head -n1 | grep '^' || echo '')"
+    iso_url="$(curl -q -LSsf "$url" 2>/dev/null | __grep_a "$arch" | __grep_a 'href="*.*"' | __grep_a -E '[http,ftp]*.*\.iso' | __strip_tags | __strip_iso | head -n1 | __grep_a '^' || echo '')"
     [ -n "$iso_url" ] && __test_iso "$iso_url" || iso_url=""
     if [ -z "$iso_url" ]; then
-      iso_url="$(curl -q -LSsf "$url" 2>/dev/null | grep 'href="*.*"' | grep -iE "$arch" | __strip_tags | __strip_iso | head -n1 | grep '^' || echo '')"
+      iso_url="$(curl -q -LSsf "$url" 2>/dev/null | __grep_a 'href="*.*"' | __grep_a -iE "$arch" | __strip_tags | __strip_iso | head -n1 | __grep_a '^' || echo '')"
       [ -n "$iso_url" ] && __test_iso "$iso_url" || iso_url=""
     fi
     if [ -z "$iso_url" ]; then
-      iso_url="$(curl -q -LSsf "$url" 2>/dev/null | grep -E 'x86_64|amd64' | __strip_tags | __strip_iso | head -n1 | grep '^' || echo '')"
+      iso_url="$(curl -q -LSsf "$url" 2>/dev/null | __grep_a -E 'x86_64|amd64' | __strip_tags | __strip_iso | head -n1 | __grep_a '^' || echo '')"
       [ -n "$iso_url" ] && __test_iso "$iso_url" || iso_url=""
     fi
     if [ -z "$iso_url" ]; then
-      iso_url="$(curl -q -LSsf "$url" 2>/dev/null | __strip_tags | __strip_iso | head -n1 | grep '^' || echo '')"
+      iso_url="$(curl -q -LSsf "$url" 2>/dev/null | __strip_tags | __strip_iso | head -n1 | __grep_a '^' || echo '')"
       [ -n "$iso_url" ] && __test_iso "$iso_url" || iso_url=""
     fi
     if [ -z "$iso_url" ]; then
-      isor="$(curl -q -LSsf "$url" 2>/dev/null | grep '\.iso' | __strip_tags | __strip_iso | head -n1 | grep '^' || echo '')"
+      isor="$(curl -q -LSsf "$url" 2>/dev/null | __grep_a '\.iso' | __strip_tags | __strip_iso | head -n1 | __grep_a '^' || echo '')"
       iso_url="$url/$isor"
       [ -n "$iso_url" ] && __test_iso "$iso_url" || iso_url=""
     fi
     if [ -z "$iso_url" ]; then
-      iso_url="$(curl -q -LSsf "$url" 2>/dev/null | __strip_tags | __strip_iso | head -n1 | grep '^' || echo '')"
+      iso_url="$(curl -q -LSsf "$url" 2>/dev/null | __strip_tags | __strip_iso | head -n1 | __grep_a '^' || echo '')"
       [ -n "$iso_url" ] && __test_iso "$iso_url" || iso_url=""
     fi
   fi
@@ -223,7 +228,7 @@ __latest_iso() {
   [ -d "$download_dir" ] || mkdir -p "$download_dir"
   [ -z "$latest" ] && printf_exit "No iso found on $url"
   [ -d "$download_file" ] && printf_exit "The download file should not be a directory: $download_file"
-  echo "$latest" | grep -q '.iso$' || printf_exit "$latest seems to be invalid"
+  echo "$latest" | __grep_a -q '.iso$' || printf_exit "$latest seems to be invalid"
   if [ -e "$download_file" ] && [ "$LATEST_ISO_OVERWRITE" != "yes" ]; then
     printf_exit "File already exists: $download_file"
   fi
@@ -267,11 +272,11 @@ __grab_iso() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __filesize() {
   local head="$(curl -q -sfSLI "$1" 2>/dev/null)"
-  local content_length_count="$(echo "$head" | grep -ic 'content-length' || echo 1)"
+  local content_length_count="$(echo "$head" | __grep_a -ic 'content-length' || echo 1)"
   if [[ $content_length_count = 1 ]]; then
-    content_length="$(echo "$head" | grep -ai 'content-length' | head -n1 | awk -v IGNORECASE=1 'BEGIN{RS="\r\n"} /^content-length/ { print $2 }')"
+    content_length="$(echo "$head" | __grep_a -ai 'content-length' | head -n1 | awk -v IGNORECASE=1 'BEGIN{RS="\r\n"} /^content-length/ { print $2 }')"
   elif [[ "$content_length_count" != 1 ]]; then
-    content_length="$(echo "$head" | grep -ai 'content-length' | tail -n1 | awk -v IGNORECASE=1 'BEGIN{RS="\r\n"} /^content-length/ { print $2 }')"
+    content_length="$(echo "$head" | __grep_a -ai 'content-length' | tail -n1 | awk -v IGNORECASE=1 'BEGIN{RS="\r\n"} /^content-length/ { print $2 }')"
   fi
   if [[ "$content_length" = 0B ]]; then
     content_length=0
@@ -287,7 +292,7 @@ __filesize() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __get_iso() {
-  curl -q -LSsf "$1" 2>/dev/null | grep -a "$2" | __strip_tags | __strip_iso | head -n1 || return
+  curl -q -LSsf "$1" 2>/dev/null | __grep_a -a "$2" | __strip_tags | __strip_iso | head -n1 || return
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Default variables
@@ -408,7 +413,7 @@ while :; do
   --all)
     shift 1
     export PATH="/home/jason/Projects/github/casjay-dotfiles/scripts/bin:$PATH"
-    isos="$(echo "$ARRAY" | tr ' ' '\n' | sort | grep -Ev 'iso')"
+    isos="$(echo "$ARRAY" | tr ' ' '\n' | sort | __grep_a -Ev 'iso')"
     for d in $isos; do eval $APPNAME $d; done
     exit $?
     ;;
@@ -449,7 +454,7 @@ iso)
 alma)
   shift 1
   isourl="$(curl -q -LSsf "$LATEST_ISO_ALMA_URL" 2>/dev/null | __sort_v)/isos/x86_64"
-  isoname="$LATEST_ISO_ALMA_URL/$isourl/$(curl -q -LSsf "$LATEST_ISO_ALMA_URL/$isourl" 2>/dev/null | __strip_tags | grep 'minimal.iso$' | head -n1)"
+  isoname="$LATEST_ISO_ALMA_URL/$isourl/$(curl -q -LSsf "$LATEST_ISO_ALMA_URL/$isourl" 2>/dev/null | __strip_tags | __grep_a 'minimal.iso$' | head -n1)"
   __latest_iso "$isoname" "$LATEST_ISO_DOWNLOAD_DIR/alma.iso"
   ;;
 alpine)
@@ -491,13 +496,13 @@ photon)
   ;;
 proxmox)
   shift 1
-  isourl="$(curl -q -LSsf "$LATEST_ISO_PROXMOX_URL" 2>/dev/null | grep 'proxmox-ve_' | __sort_v)"
+  isourl="$(curl -q -LSsf "$LATEST_ISO_PROXMOX_URL" 2>/dev/null | __grep_a 'proxmox-ve_' | __sort_v)"
   __latest_iso "$LATEST_ISO_PROXMOX_URL/$isourl" "$LATEST_ISO_DOWNLOAD_DIR/proxmox.iso"
   ;;
 rocky)
   shift 1
   isourl="$(curl -q -LSsf "$LATEST_ISO_ROCKY_URL" 2>/dev/null | __sort_v)/isos/x86_64"
-  isoname="$LATEST_ISO_ROCKY_URL/$isourl/$(curl -q -LSsf "$LATEST_ISO_ROCKY_URL/$isourl" 2>/dev/null | __strip_tags | grep 'minimal.iso$')"
+  isoname="$LATEST_ISO_ROCKY_URL/$isourl/$(curl -q -LSsf "$LATEST_ISO_ROCKY_URL/$isourl" 2>/dev/null | __strip_tags | __grep_a 'minimal.iso$')"
   __latest_iso "$isoname" "$LATEST_ISO_DOWNLOAD_DIR/rocky.iso"
   ;;
 ubuntu)
