🐛 FIXED: bin/logout-menu 🐛

diff --git a/bin/logout-menu b/bin/logout-menu
--- a/bin/logout-menu
+++ b/bin/logout-menu
@@ -1,22 +1,23 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 APPNAME="$(basename "$0")"
-VERSION="202104130302-git"
+VERSION="202108190117-git"
+RUN_USER="${SUDO_USER:-${USER}}"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-#set opts
+# Set bash options
 trap 'exitCode=${exitCode:-$?};[ -f "$LOGOUT_MENU_TEMP_FILE" ] && rm -Rf "$LOGOUT_MENU_TEMP_FILE" &>/dev/null' EXIT
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 202104130302-git
+##@Version       : 202108190117-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
-# @License       : LICENSE.md
+# @License       : WTFPL
 # @ReadME        : logout-menu --help
-# @Copyright     : Copyright: (c) 2021 Jason, CasjaysDev
-# @Created       : Tuesday, Apr 13, 2021 03:05 EDT
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, Casjays Developments
+# @Created       : Thursday, Aug 19, 2021 01:17 EDT
 # @File          : logout-menu
 # @Description   : Logout, shutdown, reboot or lock screen
 # @TODO          :
@@ -42,6 +43,9 @@ fi
 user_install
 __options "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set functions
+__list_options() { printf_custom "$1" "$2: $(echo ${3:-$ARRAY} | __sed 's|:||g;s|'$4'| '$5'|g')" 2>/dev/null; }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __gen_config() {
   printf_green "Generating the config file in"
   printf_green "$LOGOUT_MENU_CONFIG_DIR/$LOGOUT_MENU_CONFIG_FILE"
@@ -51,11 +55,19 @@ __gen_config() {
     cp -Rf "$LOGOUT_MENU_CONFIG_DIR/$LOGOUT_MENU_CONFIG_FILE" "$LOGOUT_MENU_CONFIG_BACKUP_DIR/$LOGOUT_MENU_CONFIG_FILE.$$"
   cat <<EOF >"$LOGOUT_MENU_CONFIG_DIR/$LOGOUT_MENU_CONFIG_FILE"
 # Settings for logout-menu
-LOGOUT_MENU_LOCKER_APP="${LOCKER:=slock}"
-LOGOUT_MENU_TEMP_FILE="${TMPDIR:-/tmp}/logout-menu"
-LOGOUT_MENU_NOTIFY_ENABLED="yes"
-LOGOUT_MENU_NOTIFY_CLIENT_NAME="\${NOTIFY_CLIENT_NAME:-\$APPNAME}"
-LOGOUT_MENU_NOTIFY_CLIENT_ICON="\${NOTIFY_CLIENT_ICON:-\$LOGOUT_MENU_NOTIFY_CLIENT_ICON}"
+LOGOUT_MENU_LOCKER_APP="${LOGOUT_MENU_LOCKER_APP:=slock}"
+
+# Notification settings
+LOGOUT_MENU_GOOD_MESSAGE="${LOGOUT_MENU_GOOD_MESSAGE:-Everything Went OK}"
+LOGOUT_MENU_ERROR_MESSAGE="${LOGOUT_MENU_ERROR_MESSAGE:-Well that didn\'t work}"
+LOGOUT_MENU_NOTIFY_ENABLED="${LOGOUT_MENU_NOTIFY_ENABLED:-yes}"
+LOGOUT_MENU_NOTIFY_CLIENT_NAME="${NOTIFY_CLIENT_NAME:-$APPNAME}"
+LOGOUT_MENU_NOTIFY_CLIENT_ICON="${NOTIFY_CLIENT_ICON:-$LOGOUT_MENU_NOTIFY_CLIENT_ICON}"
+
+# Colorization settings
+LOGOUT_MENU_OUTPUT_COLOR="${LOGOUT_MENU_OUTPUT_COLOR:-5}"
+LOGOUT_MENU_OUTPUT_COLOR_GOOD="${LOGOUT_MENU_OUTPUT_COLOR_GOOD:-2}"
+LOGOUT_MENU_OUTPUT_COLOR_ERROR="${LOGOUT_MENU_OUTPUT_COLOR_ERROR:-1}"
 
 EOF
   if [ -f "$LOGOUT_MENU_CONFIG_DIR/$LOGOUT_MENU_CONFIG_FILE" ]; then
@@ -67,47 +79,60 @@ EOF
   fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-output() {
-  ${OUTPUT} "dmlogout" "$@"
-}
+# Additional functions
+output() { ${OUTPUT} "dmlogout" "$@"; }
+cmd_exists rofi && __dmenu() { rofi -dmenu -i -p "${choice}?" "${@}" || return 1; }
+cmd_exist dmenu && __dmenu() { dmenu -i -p "${choice}?" "${@}" || return 1; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Defaults
-exitCode=""
-LOGOUT_MENU_CONFIG_FILE="settings.conf"
-LOGOUT_MENU_CONFIG_DIR="$HOME/.config/myscripts/logout-menu"
-LOGOUT_MENU_CONFIG_BACKUP_DIR="$HOME/.local/share/myscripts/logout-menu/backups"
-LOGOUT_MENU_OPTIONS_DIR="$HOME/.local/share/myscripts/logout-menu/options"
-LOGOUT_MENU_TEMP_FILE="${TMPDIR:-/tmp}/logout-menu"
-LOGOUT_MENU_NOTIFY_ENABLED="yes"
+# Default variables
+exitCode="0"
+LOGOUT_MENU_CACHE_DIR="${LOGOUT_MENU_CACHE_DIR:-$HOME/.cache/logout-menu}"
+LOGOUT_MENU_CONFIG_DIR="${LOGOUT_MENU_CONFIG_DIR:-$HOME/.config/myscripts/logout-menu}"
+LOGOUT_MENU_OPTIONS_DIR="${LOGOUT_MENU_OPTIONS_DIR:-$HOME/.local/share/myscripts/logout-menu/options}"
+LOGOUT_MENU_CONFIG_BACKUP_DIR="${LOGOUT_MENU_CONFIG_BACKUP_DIR:-$HOME/.local/share/myscripts/logout-menu/backups}"
+LOGOUT_MENU_TEMP_DIR="${LOGOUT_MENU_TEMP_DIR:-$HOME/.local/tmp/system_scripts/logout-menu}"
+LOGOUT_MENU_TEMP_FILE="${LOGOUT_MENU_TEMP_FILE:-$(mktemp $LOGOUT_MENU_TEMP_DIR/XXXXXX 2>/dev/null)}"
+LOGOUT_MENU_CONFIG_FILE="${LOGOUT_MENU_CONFIG_FILE:-settings.conf}"
+LOGOUT_MENU_GOOD_MESSAGE="${LOGOUT_MENU_GOOD_MESSAGE:-Everything Went OK}"
+LOGOUT_MENU_ERROR_MESSAGE="${LOGOUT_MENU_ERROR_MESSAGE:-Well that didn\'t work}"
+LOGOUT_MENU_NOTIFY_ENABLED="${LOGOUT_MENU_NOTIFY_ENABLED:-yes}"
 LOGOUT_MENU_NOTIFY_CLIENT_NAME="${NOTIFY_CLIENT_NAME:-$APPNAME}"
 LOGOUT_MENU_NOTIFY_CLIENT_ICON="${NOTIFY_CLIENT_ICON:-$LOGOUT_MENU_NOTIFY_CLIENT_ICON}"
+LOGOUT_MENU_OUTPUT_COLOR="${LOGOUT_MENU_OUTPUT_COLOR:-5}"
+LOGOUT_MENU_OUTPUT_COLOR_GOOD="${LOGOUT_MENU_OUTPUT_COLOR_GOOD:-2}"
+LOGOUT_MENU_OUTPUT_COLOR_ERROR="${LOGOUT_MENU_OUTPUT_COLOR_ERROR:-1}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Ensure Directories exist
+[ -d "$LOGOUT_MENU_TEMP_DIR" ] || mkdir -p "$LOGOUT_MENU_TEMP_DIR" &>/dev/null
+[ -d "$LOGOUT_MENU_CACHE_DIR" ] || mkdir -p "$LOGOUT_MENU_CACHE_DIR" &>/dev/null
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Generate config files
+[ -f "$LOGOUT_MENU_CONFIG_DIR/$LOGOUT_MENU_CONFIG_FILE" ] ||
+  __gen_config &>/dev/null
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Import config
+[ -f "$LOGOUT_MENU_CONFIG_DIR/$LOGOUT_MENU_CONFIG_FILE" ] &&
+  . "$LOGOUT_MENU_CONFIG_DIR/$LOGOUT_MENU_CONFIG_FILE"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Show warn message if variables are missing
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set additional variables/Argument/Option settings
 SETARGS="$*"
-SHORTOPTS="v,h"
-LONGOPTS="options,config,version,help"
+SHORTOPTS="z:"
+LONGOPTS="options,config,version,help,dir:"
 ARRAY=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Generate Files
-[ -f "$LOGOUT_MENU_CONFIG_DIR/$LOGOUT_MENU_CONFIG_FILE" ] || __gen_config &>/dev/null
-[ -f "$LOGOUT_MENU_OPTIONS_DIR/options" ] || __list_options "$LOGOUT_MENU_OPTIONS_DIR" &>/dev/null
-[ -f "$LOGOUT_MENU_OPTIONS_DIR/array" ] || __list_array "$LOGOUT_MENU_OPTIONS_DIR" "$ARRAY" &>/dev/null
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Import config
-if [ -f "$LOGOUT_MENU_CONFIG_DIR/$LOGOUT_MENU_CONFIG_FILE" ]; then
-  . "$LOGOUT_MENU_CONFIG_DIR/$LOGOUT_MENU_CONFIG_FILE"
-fi
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# options
-setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -a -n "$APPNAME" -- "$@" 2>/dev/null)
+setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -a -n "$PROG" -- "$@" 2>/dev/null)
 eval set -- "${setopts[@]}" 2>/dev/null
 while :; do
   case $1 in
   --options)
     shift 1
-    __list_array "$LOGOUT_MENU_OPTIONS_DIR" "$ARRAY"
-    __list_options "$LOGOUT_MENU_OPTIONS_DIR"
+    [ -n "$1" ] || printf_blue "Current options for ${PROG:-$APPNAME}"
+    [ -z "$SHORTOPTS" ] || __list_options "5" "Short Options" "-$SHORTOPTS" ',' '-'
+    [ -z "$LONGOPTS" ] || __list_options "5" "Long Options" "--$LONGOPTS" ',' '--'
+    [ -z "$ARRAY" ] || __list_options "5" "Base Options" "$ARRAY" ',' ''
     exit $?
     ;;
   --version)
@@ -125,6 +150,10 @@ while :; do
     __gen_config
     exit $?
     ;;
+  -z | --dir)
+    LOGOUT_MENU_CWD="$2"
+    shift 2
+    ;;
   --)
     shift 1
     break
@@ -134,10 +163,12 @@ done
 #set -- "$SETARGS"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Actions based on env
-export NOTIFY_CLIENT_NAME="${LOGOUT_MENU_NOTIFY_CLIENT_NAME}"
-export NOTIFY_CLIENT_ICON="${LOGOUT_MENU_NOTIFY_CLIENT_ICON}"
 if [ "$LOGOUT_MENU_NOTIFY_ENABLED" = "yes" ]; then
   __notifications() {
+    export NOTIFY_GOOD_MESSAGE="${LOGOUT_MENU_GOOD_MESSAGE}"
+    export NOTIFY_ERROR_MESSAGE="${LOGOUT_MENU_ERROR_MESSAGE}"
+    export NOTIFY_CLIENT_NAME="${LOGOUT_MENU_NOTIFY_CLIENT_NAME}"
+    export NOTIFY_CLIENT_ICON="${LOGOUT_MENU_NOTIFY_CLIENT_ICON}"
     notifications "$*" || return 1
   }
 else
@@ -145,9 +176,11 @@ else
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Check for required applications/Network check
-cmd_exists --error --ask bash dmenu systemd slock notify-send || exit 1
+cmd_exists --error --ask bash systemd slock || exit 1 # exit 1 if not found
+#am_i_online --error || exit 1     # exit 1 if no internet
+type -p __dmenu &>/dev/null || printf_exit "This requires either rofi or dmenu to be installed"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# APP Variables
+# APP Variables overrides
 declare -a MANAGERS
 while IFS= read -r manager; do
   MANAGERS+=("${manager,,}")
@@ -158,13 +191,11 @@ declare -a options=(
   "Logout"
   "Reboot"
   "Shutdown"
-  "Suspend"
   "Quit"
 )
-
 OUTPUT="echo"
 if [[ ${TERM} == 'dumb' ]]; then
-  OUTPUT="notify-send"
+  OUTPUT="__notifications"
 fi
 export OUTPUT
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -172,7 +203,7 @@ export OUTPUT
 choice=$(printf '%s\n' "${options[@]}" | dmenu -i -p 'Shutdown menu:' "${@}")
 case $choice in
 'Logout')
-  if [[ "$(echo -e "No\nYes" | dmenu -i -p "${choice}?" "${@}")" == "Yes" ]]; then
+  if [[ "$(echo -e "No\nYes" | __dmenu "${@}")" == "Yes" ]]; then
     for manager in "${MANAGERS[@]}"; do
       killall "${manager}" || output "Process ${manager} was not running."
     done
@@ -181,24 +212,24 @@ case $choice in
   fi
   ;;
 'Lock screen')
-  ${LOCKER}
+  ${LOGOUT_MENU_LOCKER_APP}
   ;;
 'Reboot')
-  if [[ "$(echo -e "No\nYes" | dmenu -i -p "${choice}?" "${@}")" == "Yes" ]]; then
+  if [[ "$(echo -e "No\nYes" | __dmenu "${@}")" == "Yes" ]]; then
     systemctl reboot
   else
     output "User chose not to reboot." && exit 0
   fi
   ;;
 'Shutdown')
-  if [[ "$(echo -e "No\nYes" | dmenu -i -p "${choice}?" "${@}")" == "Yes" ]]; then
+  if [[ "$(echo -e "No\nYes" | __dmenu "${@}")" == "Yes" ]]; then
     systemctl poweroff
   else
     output "User chose not to shutdown." && exit 0
   fi
   ;;
 'Suspend')
-  if [[ "$(echo -e "No\nYes" | dmenu -i -p "${choice}?" "${@}")" == "Yes" ]]; then
+  if [[ "$(echo -e "No\nYes" | __dmenu "${@}")" == "Yes" ]]; then
     systemctl suspend
   else
     output "User chose not to suspend." && exit 0
