🐛 FIXED: bin/notes 🐛

diff --git a/bin/notes b/bin/notes
--- a/bin/notes
+++ b/bin/notes
@@ -372,13 +372,24 @@ __client() {
   local _SERVER="${NOTES_SERVER_NAME}"
   local _PORT=${NOTES_SERVER_PORT}
   local _PATH="$NOTES_TEMP_FILE"
+  local _WRITE_MESSAGE="$(printf "%s\n" "$*" >"$_PATH" 2>>$NOTES_TMPDIR/notes_client && echo success || echo failed)"
+  local _POSTMESSAGE="$(cat "$_PATH" 2>>$NOTES_TMPDIR/notes_client | __nc_send "$_SERVER" "$_PORT" 2>>$NOTES_TMPDIR/notes_client && echo success || echo failed)"
   __netcat_test
   printf_green "Attempting to send message to $_SERVER on $_PORT"
-  if printf "%s\n" "$*" >"$_PATH" 2>>$NOTES_TMPDIR/notes_client &&
-    cat "$_PATH" 2>>$NOTES_TMPDIR/notes_client | __nc_send "$_SERVER" "$_PORT" 2>>$NOTES_TMPDIR/notes_client; then
+  if [[ "$_WRITE_MESSAGE" == "success" ]] && [[ "$_POSTMESSAGE" == "success" ]]; then
     __dedup "$MESSAGE" "$NOTES_PATH"
     __success "NotesCLI"
     exitCode=0
+  elif [[ "$_WRITE_MESSAGE" == "success" ]] || [[ "$_POSTMESSAGE" == "success" ]]; then
+    $_POSTMESSAGE
+    if [[ "$_POSTMESSAGE" == "true" ]]; then
+      __dedup "$MESSAGE" "$NOTES_PATH"
+      __success "NotesCLI"
+      exitCode=0
+    else
+      __failed "NotesCLI"
+      exitCode=1
+    fi
   else
     __failed "NotesCLI"
     exitCode=1
