🐛 FIXED: bin/pastebin 🐛

diff --git a/bin/pastebin b/bin/pastebin
--- a/bin/pastebin
+++ b/bin/pastebin
@@ -55,26 +55,13 @@ __gen_config() {
     cp -Rf "$PASTEBIN_CONFIG_DIR/$PASTEBIN_CONFIG_FILE" "$PASTEBIN_CONFIG_BACKUP_DIR/$PASTEBIN_CONFIG_FILE.$$"
   cat <<EOF >"$PASTEBIN_CONFIG_DIR/$PASTEBIN_CONFIG_FILE"
 # Settings for pastebin
-PASTEBIN_API_URL="${PASTEBIN_API_URL:-http://pastebin.com/api/api_post.php}"
-# Change to your API Developer Key
-#PASTEBIN_API_KEY="97d4dbcc849cf72fe005154e40904f71"
-# Change to your pastebin.com username, if you want to log into your account
-#PASTEBIN_USER_NAME=""
-# Change to your pastebin.com password
-#PASTEBIN_PASSWORD=""
-# Set to 1 if you want to log into your account automatically
-# (you may login with -l, -u, -p arguments also)
-#PASTEBIN_LOGIN="0"
-# Default paste title, if -n argument is not defined
-#PASTEBIN_PASTE_NAME=""
-# Default paste highlighting, if -f argument is not defined
-# (see http://pastebin.com/api#5 for more)
-#PASTEBIN_PASTE_FORMAT="text"
-# Default private settings, if -p argument is not defined
-# (0=public, 1=unlisted, 2=private)
-#PASTEBIN_PASTE_PRIVATE="0"
-# Default expire date, if -e argument is not defined
-#PASTEBIN_PASTE_EXPIRES="N"
+api_dev_key="${PASTEBIN_API_KEY:-97d4dbcc849cf72fe005154e40904f71}"
+logintopastebin="0"
+api_paste_name=""
+api_paste_format="text"
+api_paste_private="0"
+api_paste_expire_date="N"
+api_url="https://pastebin.com/api"
 
 # Notification settings
 PASTEBIN_GOOD_MESSAGE="${PASTEBIN_GOOD_MESSAGE:-Everything Went OK}"
@@ -99,15 +86,99 @@ EOF
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Additional functions
+__set_pastebin_opts() {
+  while getopts "hu:p:ln:f:c:e:r:o" OPTION; do
+    case $OPTION in
+    o)
+      sample_config
+      exit
+      ;;
+    u)
+      api_user_name="$OPTARG"
+      logintopastebin=1
+      ;;
+    p) api_user_password="$OPTARG" ;;
+    l) logintopastebin=1 ;;
+    n) api_paste_name="$OPTARG" ;;
+    f) api_paste_format="$OPTARG" ;;
+    e) case $OPTARG in
+      n | never) api_paste_expire_date=N ;;
+      10M) api_paste_expire_date=10M ;;
+      1H) api_paste_expire_date=1H ;;
+      1D) api_paste_expire_date=1D ;;
+      1M) api_paste_expire_date=1M ;;
+      1W) api_paste_expire_date=1W ;;
+      2W) api_paste_expire_date=2W ;;
+      *)
+        echo "Invalid expire date"
+        exit 1
+        ;;
+      esac ;;
+    r)
+      case $OPTARG in
+      public | 0) api_paste_private=0 ;;
+      unlisted | 1) api_paste_private=1 ;;
+      private | 2)
+        if [ $logintopastebin -ne 1 ]; then
+          echo "You need to log in (option -l or -u) if you want to post private pastes."
+          exit 1
+        else
+          api_paste_private=2
+        fi
+        ;;
+      *)
+        echo "Invalid private value"
+        exit 1
+        ;;
+      esac
+      ;;
+    c)
+      if [ -f "$OPTARG" ]; then
+        # shellcheck source=/dev/null
+        source "$OPTARG"
+      else
+        echo "$OPTARG is not exists"
+        exit 1
+      fi
+      ;;
+    *) shift ;;
+    esac
+  done
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+sample_config() {
+  cat <<EOF
+# Change to your API Developer Key
+#api_dev_key=""
+# Change to your pastebin.com username, if you want to log into your account
+#api_user_name=""
+# Change to your pastebin.com password
+#api_user_password=""
+# Set to 1 if you want to log into your account automatically
+# (you may login with -l, -u, -p arguments also)
+#logintopastebin="0"
+# Default paste title, if -n argument is not defined
+#api_paste_name=""
+# Default paste highlighting, if -f argument is not defined
+# (see http://pastebin.com/api#5 for more)
+#api_paste_format="text"
+# Default private settings, if -p argument is not defined
+# (0=public, 1=unlisted, 2=private)
+#api_paste_private="0"
+# Default expire date, if -e argument is not defined
+#api_paste_expire_date="N"
+EOF
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 auth_user() {
-  if [ -z "$PASTEBIN_USER_NAME" ] || [ -z "$PASTEBIN_PASSWORD" ]; then
+  if [ -z "$api_user_name" ] || [ -z "$api_user_password" ]; then
     echo "Username and/or password is undefined."
-    echo "Please adjust 'PASTEBIN_USER_NAME' and 'PASTEBIN_PASSWORD' in the configuration file '$config_file'"
+    echo "Please adjust 'api_user_name' and 'api_user_password' in the configuration file '$config_file'"
     exit 1
   fi
-  server_reply="$(curl --silent --data "PASTEBIN_API_KEY=$PASTEBIN_API_KEY" --data-urlencode "PASTEBIN_USER_NAME=$PASTEBIN_USER_NAME" --data-urlencode "PASTEBIN_PASSWORD=$PASTEBIN_PASSWORD" "$api_url/api_login.php")"
+  server_reply="$(curl --silent --data "api_dev_key=$api_dev_key" --data-urlencode "api_user_name=$api_user_name" --data-urlencode "api_user_password=$api_user_password" "$api_url/api_login.php")"
   if [[ $server_reply == Bad* ]]; then
-    echo "Username: $PASTEBIN_USER_NAME"
+    echo "Username: $api_user_name"
     echo "$server_reply"
     exit 1
   else
@@ -120,6 +191,21 @@ _cat() {
   while IFS= read -r line; do
     printf '%s\n' "$line" # Or: env POSIXLY_CORRECT=1 echo "$line"
   done < <(cat -- "$file")
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__pasteit() {
+  curl -q -LSs -X POST -0 --show-error \
+    --data "api_dev_key=$api_dev_key" \
+    --data "api_option=paste" \
+    --data "api_paste_code=$api_paste_code" \
+    --data "api_paste_format=$api_paste_format" \
+    --data "api_paste_private=$api_paste_private" \
+    --data "api_paste_expire_date=$api_paste_expire_date" \
+    --data "api_user_key=$api_user_key" \
+    --data-urlencode "api_paste_name=$api_paste_name" \
+    --data-urlencode "api_paste_code=$api_paste_code" \
+    "$api_url/api_post.php"
+  echo
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Default variables
@@ -139,15 +225,6 @@ PASTEBIN_NOTIFY_CLIENT_ICON="${NOTIFY_CLIENT_ICON:-$PASTEBIN_NOTIFY_CLIENT_ICON}
 PASTEBIN_OUTPUT_COLOR="${PASTEBIN_OUTPUT_COLOR:-5}"
 PASTEBIN_OUTPUT_COLOR_GOOD="${PASTEBIN_OUTPUT_COLOR_GOOD:-2}"
 PASTEBIN_OUTPUT_COLOR_ERROR="${PASTEBIN_OUTPUT_COLOR_ERROR:-1}"
-PASTEBIN_API_KEY="${PASTEBIN_API_KEY:-97d4dbcc849cf72fe005154e40904f71}"
-PASTEBIN_USER_NAME="${PASTEBIN_USER_NAME:-}"
-PASTEBIN_PASSWORD="${PASTEBIN_PASSWORD:-}"
-PASTEBIN_LOGIN="${PASTEBIN_LOGIN:-0}"
-PASTEBIN_PASTE_NAME="${PASTEBIN_PASTE_NAME:-}"
-PASTEBIN_PASTE_FORMAT="${PASTEBIN_PASTE_FORMAT:-text}"
-PASTEBIN_PASTE_PRIVATE="${PASTEBIN_PASTE_PRIVATE:-0}"
-PASTEBIN_PASTE_EXPIRES="${PASTEBIN_PASTE_EXPIRES:-N}"
-PASTEBIN_API_URL="${PASTEBIN_API_URL:-http://pastebin.com/api/api_post.php}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Ensure Directories exist
 [ -d "$PASTEBIN_TEMP_DIR" ] || mkdir -p "$PASTEBIN_TEMP_DIR" &>/dev/null
@@ -166,7 +243,7 @@ PASTEBIN_API_URL="${PASTEBIN_API_URL:-http://pastebin.com/api/api_post.php}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set additional variables/Argument/Option settings
 SETARGS="$*"
-SHORTOPTS="z:,h,u:,p:,l,n:,f:,e:,r:"
+SHORTOPTS="z:"
 LONGOPTS="options,config,version,help,dir:"
 ARRAY=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -201,85 +278,6 @@ while :; do
     PASTEBIN_CWD="$2"
     shift 2
     ;;
-  l)
-    PASTEBIN_LOGIN=1
-    shift 1
-    ;;
-  u)
-    PASTEBIN_USER_NAME="$OPTARG"
-    PASTEBIN_LOGIN=1
-    shift 2
-    ;;
-  p)
-    PASTEBIN_PASSWORD="$OPTARG"
-    shift 2
-    ;;
-  n)
-    PASTEBIN_PASTE_NAME="$OPTARG"
-    shift 2
-    ;;
-  f)
-    PASTEBIN_PASTE_FORMAT="$OPTARG"
-    shift 2
-    ;;
-  e)
-    case $OPTARG in
-    n | never)
-      PASTEBIN_PASTE_EXPIRES=N
-      shift 1
-      ;;
-    10M)
-      PASTEBIN_PASTE_EXPIRES=10M
-      shift 1
-      ;;
-    1H)
-      PASTEBIN_PASTE_EXPIRES=1H
-      shift 1
-      ;;
-    1D)
-      PASTEBIN_PASTE_EXPIRES=1D
-      shift 1
-      ;;
-    1M)
-      PASTEBIN_PASTE_EXPIRES=1M
-      shift 1
-      ;;
-    1W)
-      PASTEBIN_PASTE_EXPIRES=1W
-      shift 1
-      ;;
-    2W)
-      PASTEBIN_PASTE_EXPIRES=2W
-      shift 1
-      ;;
-    *)
-      PASTEBIN_PASTE_EXPIRES=N
-      ;;
-    esac
-    shift 1
-    ;;
-  r)
-    case $OPTARG in
-    public | 0)
-      PASTEBIN_PASTE_PRIVATE=0
-      shift 1
-      ;;
-    unlisted | 1)
-      PASTEBIN_PASTE_PRIVATE=1
-      shift 1
-      ;;
-    private | 2)
-      if [ $PASTEBIN_LOGIN -ne 1 ]; then
-        echo "You need to log in (option -l or -u) if you want to post private pastes."
-        exit 1
-      else
-        PASTEBIN_PASTE_PRIVATE=2
-      fi
-      shift 1
-      ;;
-    esac
-    shift 1
-    ;;
   --)
     shift 1
     break
@@ -302,27 +300,24 @@ else
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Check for required applications/Network check
-cmd_exists --error --ask bash curl || exit 1 # exit 1 if not found
-am_i_online --error || exit 1                # exit 1 if no internet
+cmd_exists --error --ask bash || exit 1 # exit 1 if not found
+am_i_online --error || exit 1           # exit 1 if no internet
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # APP Variables overrides
-
+api_dev_key="${PASTEBIN_API_KEY:-$api_dev_key}"
+logintopastebin="${logintopastebin:-0}"
+api_paste_name="${api_paste_name:-}"
+api_paste_format="${api_paste_format:-text}"
+api_paste_private="${api_paste_private:-0}"
+api_paste_expire_date="${api_paste_expire_date:-N}"
+api_url="${api_url:-https://pastebin.com/api}"
+__set_pastebin_opts "${SETARGS}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # begin main app
-[ $PASTEBIN_LOGIN -ne 0 ] && auth_user
+[ $logintopastebin -ne 0 ] && auth_user
 api_paste_code=$(_cat "$@")
-curl -X POST -0 --show-error \
-  --data "api_dev_key=$PASTEBIN_API_KEY" \
-  --data "api_option=paste" \
-  --data "api_paste_code=$api_paste_code" \
-  --data "api_paste_format=$PASTEBIN_PASTE_FORMAT" \
-  --data "api_paste_private=$PASTEBIN_PASTE_PRIVATE" \
-  --data "api_paste_expire_date=$PASTEBIN_PASTE_EXPIRES" \
-  --data "api_user_key=$api_user_key" \
-  --data-urlencode "api_paste_name=$PASTEBIN_PASTE_NAME" \
-  --data-urlencode "api_paste_code=$api_paste_code" \
-  "$PASTEBIN_API_URL"
-printf_newline
+paste="$(__pasteit)"
+echo $paste | printf_readline $PASTEBIN_OUTPUT_COLOR
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
