🗃️ Committing everything that changed 🗃️
bin/detectostype
bin/gen-caddy
bin/pkmgr

diff --git a/bin/pkmgr b/bin/pkmgr
--- a/bin/pkmgr
+++ b/bin/pkmgr
@@ -52,6 +52,7 @@ else
   echo "Can not load the functions file: $SCRIPTSFUNCTDIR/$SCRIPTSFUNCTFILE" 1>&2
   exit 1
 fi
+[ -f "$SCRIPT_SRC_DIR/detectostype" ] && . "$SCRIPT_SRC_DIR/detectostype"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Options are: *_install
 # desktopmgr devenvmgr dfmgr dockermgr fontmgr iconmgr
@@ -257,21 +258,22 @@ __trap_exit() {
 # User defined functions
 __log_info() {
   tee -a "$PKMGR_LOG_INFO"
-} 
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __log_error() {
   tee -a "$PKMGR_LOG_ERROR"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-run_updatecheck() { 
-  __am_i_online && pkmgrcheckupdates || echo 0; }
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__rm_rf() { 
-  sudo rm -Rf "$@" 
+run_updatecheck() {
+  __am_i_online && pkmgrcheckupdates || echo 0
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__cp_rf() { 
-  sudo cp -Rf "$@" 
+__rm_rf() {
+  sudo rm -Rf "$@"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__cp_rf() {
+  sudo cp -Rf "$@"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __curl() {
@@ -380,7 +382,7 @@ npm_run() {
   NODE_PATH="$(echo "$PATH" | tr ':' '\n' | grep node || return)"
   PATH="$NODE_PATH:$PATH"
   if __cmd_exists fnm; then
-  eval $(fnm env)
+    eval $(fnm env)
     fnm use 18 &>/dev/null
     npm i -g "$*" 2>/dev/null | grep -v '^$' || return 1
   elif __cmd_exists npm; then
@@ -395,7 +397,7 @@ npm_remove() {
   local NODE_PATH="" PATH="${PATH}"
   NODE_PATH="$(echo $PATH | tr ':' '\n' | grep node || return)"
   PATH="$NODE_PATH:$PATH"
-  if __cmd_exists fnm; then                       
+  if __cmd_exists fnm; then
     eval $(fnm env)
     fnm use 18 &>/dev/null
     npm remove -g "$*" 2>/dev/null | grep -v '^$' || return 1
@@ -569,22 +571,13 @@ EOF
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 show_info() {
   local col="" truncate=""
-  col=""
-  truncate=""
-  [[ -n "$COLUMNS" ]] && col="$(($COLUMNS - 50))" || col=90
+  [ -n "$COLUMNS" ] && col="$(($COLUMNS - 50))" || col=90
   printf_red "System info for $(hostname -f)         "
-  if [ -n "$DISTRO" ]; then
-    printf_blue "Distribution:               $DISTRO"
-    printf_blue "Distro Version:             $DISTRO_VERSION"
-    [ -z "$CODENAME" ] ||
-      printf_yellow "Release version:            $CODENAME"
-  elif cmd_exists lsb_release; then
-    printf_yellow "Distribution:               $(lsb_release -a 2>dev/null | grep -i Distributor | awk '{print $3}')"
-    printf_yellow "Codename:                   $(lsb_release -a 2>dev/null | grep -i Codename | awk '{print $2}')"
-    printf_yellow "Release version:            $(lsb_release -a 2>dev/null | grep -i Release | awk '{print $2}')"
-  fi
-  printf_yellow "Kernel version              $(uname -r)"
-  if [[ "$1" = "truncate" ]]; then
+  printf_blue "Distribution:               $DISTRO_NAME"
+  printf_blue "Distro Version:             $DISTRO_VERSION"
+  printf_yellow "Codename:                   $CODE_NAME"
+  printf_yellow "Kernel version              $KERNEL_VERSION"
+  if [ "$1" = "truncate" ]; then
     truncate="true"
     printf_cyan "Repo:                       ${dotfilesrepo:0:$col}"
     printf_cyan "system package manager:     ${pkgmgrbin:0:$col}"
@@ -621,7 +614,7 @@ show_info() {
   printf_purple "Gem:                        $(builtin type -P gem || __not_installed)"
   printf_blue "Lua                         $(builtin type -P lua || __not_installed)"
   printf_blue "Luarocks                    $(builtin type -P luarocks || __not_installed)"
-  if [[ "$truncate" = "true" ]]; then
+  if [ "$truncate" = "true" ]; then
     printf_red "Results may have been truncated to $col"
     printf_red "add notruncate for no truncation"
   fi
@@ -990,7 +983,7 @@ __execute_pkmgr() {
     am_i_online --error || exit 1
     declare -a LISTARRAY=("$@")
     #for pkg in "${LISTARRAY[@]}"; do
-    eval "$pkgmgrbinins" "$@"  && exitCode+=0 || exitCode+=1
+    eval "$pkgmgrbinins" "$@" && exitCode+=0 || exitCode+=1
     #done
     exit ${exitCode:-$?}
     ;;
@@ -1108,7 +1101,7 @@ __execute_pkmgr() {
       searchcmd "${LISTARRAY[*]}"
     else
       declare -a LISTARRAY=("$@")
-      searchcmd "${LISTARRAY[*]}" 
+      searchcmd "${LISTARRAY[*]}"
     fi
     exit $?
     ;;
@@ -1121,38 +1114,6 @@ __execute_pkmgr() {
     for pkg in "${LISTARRAY[@]}"; do
       __execute "$pkgmgrbininssil $pkg" "Installing $pkg" exitCode+=0 || exitCode+=1
     done
-    exit ${exitCode:-$?}
-    ;;
-
-  silent-install) # Silently install packages
-    shift 1
-    [ "$1" = "help" ] && printf_help "Silently install packages"
-    am_i_online --error || exit 1
-    declare -a LISTARRAY=("$@")
-    for pkg in "${LISTARRAY[@]}"; do
-      $pkgmgrbininssil "$pkg" |& __devnull && exitCode+=0 || exitCode+=1
-    done
-    exit ${exitCode:-$?}
-    ;;
-
-  silent-remove) # Silently remove packages
-    shift 1
-    [ "$1" = "help" ] && printf_help "Silently remove packages"
-    declare -a LISTARRAY=("$@")
-    for pkg in "${LISTARRAY[@]}"; do
-      $pkgmgrbinremsil "*$pkg*" |& __devnull && exitCode+=0 || exitCode+=1
-    done
-    exit ${exitCode:-$?}
-    ;;
-
-  silent-upgrade | silent-update) # Silently update packages
-    shift 1
-    [ "$1" = "help" ] && printf_help "Silently upgrade your system"
-    am_i_online --error || exit 1
-    if [ -f "$(builtin type -P systemmgr)" ]; then
-      sudo systemmgr install scripts |& __devnull && exitCode+=0 || exitCode+=1
-    fi
-    $pkgmgrbinupdsil |& __devnull && exitCode+=0 || exitCode+=1
     exit ${exitCode:-$?}
     ;;
 
@@ -1409,7 +1370,39 @@ __execute_pkmgr() {
       ;;
     esac
     ;;
+    # TODO: Remove this legacy code
+  silent-install) # Silently install packages
+    shift 1
+    [ "$1" = "help" ] && printf_help "Silently install packages"
+    am_i_online --error || exit 1
+    declare -a LISTARRAY=("$@")
+    for pkg in "${LISTARRAY[@]}"; do
+      eval "$pkgmgrbininssil" "$pkg" |& __devnull && exitCode+=0 || exitCode+=1
+    done
+    exit ${exitCode:-$?}
+    ;;
 
+  silent-remove) # Silently remove packages
+    shift 1
+    [ "$1" = "help" ] && printf_help "Silently remove packages"
+    declare -a LISTARRAY=("$@")
+    for pkg in "${LISTARRAY[@]}"; do
+      $pkgmgrbinremsil "*$pkg*" |& __devnull && exitCode+=0 || exitCode+=1
+    done
+    exit ${exitCode:-$?}
+    ;;
+
+  silent-upgrade | silent-update) # Silently update packages
+    shift 1
+    [ "$1" = "help" ] && printf_help "Silently upgrade your system"
+    am_i_online --error || exit 1
+    if [ -f "$(builtin type -P systemmgr)" ]; then
+      sudo systemmgr install scripts |& __devnull && exitCode+=0 || exitCode+=1
+    fi
+    $pkgmgrbinupdsil |& __devnull && exitCode+=0 || exitCode+=1
+    exit ${exitCode:-$?}
+    ;;
+    # TODO: END
   silent) # Silent
     case "$2" in
     install) # Silently install packages
@@ -1428,7 +1421,7 @@ __execute_pkmgr() {
       [ "$1" = "help" ] && printf_help "Silently remove packages"
       declare -a LISTARRAY=("$@")
       for pkg in "${LISTARRAY[@]}"; do
-        $pkgmgrbinremsil "*$pkg*" |& __devnull && exitCode+=0 || exitCode+=1
+        eval "$pkgmgrbinremsil" "*$pkg*" |& __devnull && exitCode+=0 || exitCode+=1
       done
       exit ${exitCode:-$?}
       ;;
