🗃️ Committing everything that changed 🗃️

diff --git a/bin/pkmgr b/bin/pkmgr
--- a/bin/pkmgr
+++ b/bin/pkmgr
@@ -259,6 +259,12 @@ __trap_exit() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # User defined functions
+__write_log_status() {
+  printf '### $(date)\n' | tee -a "${2:-/var/log/pkmgr.log}" &>/dev/null
+  printf '%s\n' "$1" | tee -a "${2:-/var/log/pkmgr.log}" &>/dev/null
+  printf '## Completed\n\n' | tee -a "${2:-/var/log/pkmgr.log}" &>/dev/null
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __logging() {
   eval "$*"
 }
@@ -950,6 +956,23 @@ __execute_pkmgr() {
     exit ${exitCode:-$?}
     ;;
 
+  init) # Update package manager and upgrade system
+    shift 1
+    [ "$1" = "help" ] && printf_help "Initialize the system by making the cache and updating"
+    am_i_online --error || exit 1
+    __execute "$pkginit" "Initializing System" && exitCode+=0 || exitCode+=1
+    exit ${exitCode:-$?}
+    ;;
+
+  makecache) # Create the package manage cache file
+    shift 1
+    [ "$1" = "help" ] && printf_help "Create the cache for the package manager"
+    printf_blue "Updating the package manager cache files - May take a while"
+    update_mirrors
+    eval "$pkgmgrbincac" |& __devnull && exitCode+=0 || exitCode+=1
+    exit ${exitCode:-$?}
+    ;;
+
   aliases) # Generate aliases
     shift 1
     if [ -d "$HOME/.config/bash/local" ] && grep -q userbashprofilelocal "$HOME/.bashrc" &>/dev/null; then
@@ -989,6 +1012,35 @@ __execute_pkmgr() {
     echo
     ;;
 
+  export) # Export installed packages
+    shift 1
+    [ "$1" = "help" ] && printf_help "Export installed packages to a list"
+    exportpkg
+    ;;
+
+  clean) # Clean package manager files
+    shift 1
+    [ "$1" = "help" ] && printf_help "Clean up package manager files"
+    eval "$pkgmgrbincle"
+    ;;
+
+  search) # Search for packages
+    shift 1
+    [ $# = 0 ] && printf_help "Search for a package"
+    [ "$1" = "help" ] && printf_help "Search for a package"
+    if [ "$1" == "show-raw" ] || [ "$1" == "raw" ] || [ "$SHOW_RAW" = "true" ]; then
+      [ "$SHOW_RAW" != "true" ] && shift 1
+      printf_readline() { tee; }
+      printf_red() { echo "$*"; }
+      declare -a LISTARRAY=("$@")
+      searchcmd "${LISTARRAY[*]}"
+    else
+      declare -a LISTARRAY=("$@")
+      searchcmd "${LISTARRAY[*]}"
+    fi
+    exit $?
+    ;;
+
   keys | -k)
     shift 1
     if cmd_exists pacman-key; then
@@ -1001,27 +1053,6 @@ __execute_pkmgr() {
     else
       printf_error "This is only supported on Arch based distros"
     fi
-    ;;
-
-  install | -i) # Install packages
-    shift 1
-    [ "$1" = "help" ] && printf_help "Install a package"
-    am_i_online --error || exit 1
-    declare -a LISTARRAY=("$@")
-    #for pkg in "${LISTARRAY[@]}"; do
-    eval "$pkgmgrbinins" "$@" && exitCode+=0 || exitCode+=1
-    #done
-    exit ${exitCode:-$?}
-    ;;
-
-  remove | -r) # Remove packages
-    shift 1
-    [ "$1" = "help" ] && printf_help "Remove a package"
-    declare -a LISTARRAY=("$@")
-    #for pkg in "${LISTARRAY[@]}"; do
-    eval "$pkgmgrbindel" "$@" && exitCode+=0 || exitCode+=1
-    #done
-    exit ${exitCode:-$?}
     ;;
 
   list) # Install package in a list file
@@ -1084,64 +1115,6 @@ __execute_pkmgr() {
     exit ${exitCode:-$?}
     ;;
 
-  upgrade | update) # Update packages
-    shift 1
-    [ "$1" = "help" ] && printf_help "Update your system"
-    am_i_online --error || exit 1
-    if __cmd_exists systemmgr; then
-      systemmgr update installer && exitCode+=0 || exitCode+=1
-    fi
-    printf_cyan "Updating system packages"
-    eval "$pkgmgrbinupd" "$@" && exitCode+=0 || exitCode+=1
-    exit ${exitCode:-$?}
-    ;;
-
-  export) # Export installed packages
-    shift 1
-    [ "$1" = "help" ] && printf_help "Export installed packages to a list"
-    exportpkg
-    ;;
-
-  clean) # Clean package manager files
-    shift 1
-    [ "$1" = "help" ] && printf_help "Clean up package manager files"
-    eval "$pkgmgrbincle"
-    ;;
-
-  init) # Update package manager and upgrade system
-    shift 1
-    [ "$1" = "help" ] && printf_help "Initialize the system by making the cache and updating"
-    am_i_online --error || exit 1
-    __execute "$pkginit" "Initializing System" && exitCode+=0 || exitCode+=1
-    exit ${exitCode:-$?}
-    ;;
-
-  makecache) # Create the package manage cache file
-    shift 1
-    [ "$1" = "help" ] && printf_help "Create the cache for the package manager"
-    printf_blue "Updating the package manager cache files - May take a while"
-    update_mirrors
-    eval "$pkgmgrbincac" |& __devnull && exitCode+=0 || exitCode+=1
-    exit ${exitCode:-$?}
-    ;;
-
-  search) # Search for packages
-    shift 1
-    [ $# = 0 ] && printf_help "Search for a package"
-    [ "$1" = "help" ] && printf_help "Search for a package"
-    if [ "$1" == "show-raw" ] || [ "$1" == "raw" ] || [ "$SHOW_RAW" = "true" ]; then
-      [ "$SHOW_RAW" != "true" ] && shift 1
-      printf_readline() { tee; }
-      printf_red() { echo "$*"; }
-      declare -a LISTARRAY=("$@")
-      searchcmd "${LISTARRAY[*]}"
-    else
-      declare -a LISTARRAY=("$@")
-      searchcmd "${LISTARRAY[*]}"
-    fi
-    exit $?
-    ;;
-
   required) # Install required files
     shift 1
     [ "$1" = "help" ] && printf_help "Install required packages"
@@ -1151,6 +1124,132 @@ __execute_pkmgr() {
       __execute "$pkgmgrbininssil $pkg" "Installing $pkg" exitCode+=0 || exitCode+=1
     done
     exit ${exitCode:-$?}
+    ;;
+
+  install | -i) # Install packages
+    shift 1
+    [ "$1" = "help" ] && printf_help "Install a package"
+    am_i_online --error || exit 1
+    declare -a LISTARRAY=("$@")
+    #for pkg in "${LISTARRAY[@]}"; do
+    eval "$pkgmgrbinins" "$@" && exitCode+=0 || exitCode+=1
+    [ "$exitCode" = "0" ] && __write_log_status "Success" || __write_log_status "Failed with status: $exitCode"
+    exit ${exitCode:-$?}
+    ;;
+
+  upgrade | update) # Update packages
+    shift 1
+    [ "$1" = "help" ] && printf_help "Update your system"
+    am_i_online --error || exit 1
+    if __cmd_exists systemmgr; then
+      systemmgr update installer && exitCode+=0 || exitCode+=1
+    fi
+    printf_cyan "Updating system packages"
+    eval "$pkgmgrbinupd" "$@" && exitCode+=0 || exitCode+=1
+    [ "$exitCode" = "0" ] && __write_log_status "Success" || __write_log_status "Failed with status: $exitCode"
+    exit ${exitCode:-$?}
+    ;;
+
+  remove | -r) # Remove packages
+    shift 1
+    [ "$1" = "help" ] && printf_help "Remove a package"
+    declare -a LISTARRAY=("$@")
+    #for pkg in "${LISTARRAY[@]}"; do
+    eval "$pkgmgrbindel" "$@" && exitCode+=0 || exitCode+=1
+    [ "$exitCode" = "0" ] && __write_log_status "Success" || __write_log_status "Failed with status: $exitCode"
+    exit ${exitCode:-$?}
+    ;;
+
+    # TODO: Remove this legacy code
+  silent-install) # Silently install packages
+    shift 1
+    [ "$1" = "help" ] && printf_help "Silently install packages"
+    am_i_online --error || exit 1
+    declare -a LISTARRAY=("$@")
+    for pkg in "${LISTARRAY[@]}"; do
+      eval "$pkgmgrbininssil" "$pkg" |& __devnull && exitCode+=0 || exitCode+=1
+    done
+    [ "$exitCode" = "0" ] && __write_log_status "Success" || __write_log_status "Failed with status: $exitCode"
+    exit ${exitCode:-$?}
+    ;;
+
+  silent-remove) # Silently remove packages
+    shift 1
+    [ "$1" = "help" ] && printf_help "Silently remove packages"
+    declare -a LISTARRAY=("$@")
+    for pkg in "${LISTARRAY[@]}"; do
+      $pkgmgrbinremsil "*$pkg*" |& __devnull && exitCode+=0 || exitCode+=1
+    done
+    [ "$exitCode" = "0" ] && __write_log_status "Success" || __write_log_status "Failed with status: $exitCode"
+    exit ${exitCode:-$?}
+    ;;
+
+  silent-upgrade | silent-update) # Silently update packages
+    shift 1
+    [ "$1" = "help" ] && printf_help "Silently upgrade your system"
+    am_i_online --error || exit 1
+    if __cmd_exists systemmgr; then
+      systemmgr update scripts |& __devnull && exitCode+=0 || exitCode+=1
+    fi
+    $pkgmgrbinupdsil |& __devnull && exitCode+=0 || exitCode+=1
+    [ "$exitCode" = "0" ] && __write_log_status "Success" || __write_log_status "Failed with status: $exitCode"
+    exit ${exitCode:-$?}
+    ;;
+    # TODO: END
+
+  silent) # Silent
+    case "$2" in
+    install) # Silently install packages
+      shift 2
+      [ "$1" = "help" ] && printf_help "Silently install packages"
+      am_i_online --error || exit 1
+      declare -a LISTARRAY=("$@")
+      for pkg in "${LISTARRAY[@]}"; do
+        eval "$pkgmgrbininssil" "$pkg" |& __devnull && exitCode+=0 || exitCode+=1
+      done
+      [ "$exitCode" = "0" ] && __write_log_status "Success" || __write_log_status "Failed with status: $exitCode"
+      exit ${exitCode:-$?}
+      ;;
+
+    remove) # Silently remove packages
+      shift 2
+      [ "$1" = "help" ] && printf_help "Silently remove packages"
+      declare -a LISTARRAY=("$@")
+      for pkg in "${LISTARRAY[@]}"; do
+        eval "$pkgmgrbinremsil" "*$pkg*" |& __devnull && exitCode+=0 || exitCode+=1
+      done
+      [ "$exitCode" = "0" ] && __write_log_status "Success" || __write_log_status "Failed with status: $exitCode"
+      exit ${exitCode:-$?}
+      ;;
+
+    upgrade) # Silently update packages
+      shift 2
+      [ "$1" = "help" ] && printf_help "Silently upgrade your system"
+      am_i_online --error || exit 1
+      if __cmd_exists systemmgr; then
+        systemmgr update installer |& __devnull
+      fi
+      eval "$pkgmgrbinupdsil" |& __devnull && exitCode+=0 || exitCode+=1
+      [ "$exitCode" = "0" ] && __write_log_status "Success" || __write_log_status "Failed with status: $exitCode"
+      exit ${exitCode:-$?}
+      ;;
+
+    *) # Silently update packages
+      shift 1
+      [ "$1" = "help" ] && printf_help "Silently install packages | defaults to a silent update"
+      am_i_online --error || exit 1
+      if [ -z "$1" ]; then
+        eval "$pkgmgrbinupdsil" |& __devnull && exitCode+=0 || exitCode+=1
+      else
+        declare -a LISTARRAY=("$@")
+        for pkg in "${LISTARRAY[@]}"; do
+          eval "$pkgmgrbininssil" "$pkg" |& __devnull && exitCode+=0 || exitCode+=1
+        done
+      fi
+      [ "$exitCode" = "0" ] && __write_log_status "Success" || __write_log_status "Failed with status: $exitCode"
+      exit ${exitCode:-$?}
+      ;;
+    esac
     ;;
 
   cpan | perl) # perl CPAN modules
@@ -1402,89 +1501,6 @@ __execute_pkmgr() {
       for pkg in "${LISTARRAY[@]}"; do
         lua_run "$pkg" && exitCode+=0 || exitCode+=1
       done
-      exit ${exitCode:-$?}
-      ;;
-    esac
-    ;;
-    # TODO: Remove this legacy code
-  silent-install) # Silently install packages
-    shift 1
-    [ "$1" = "help" ] && printf_help "Silently install packages"
-    am_i_online --error || exit 1
-    declare -a LISTARRAY=("$@")
-    for pkg in "${LISTARRAY[@]}"; do
-      eval "$pkgmgrbininssil" "$pkg" |& __devnull && exitCode+=0 || exitCode+=1
-    done
-    exit ${exitCode:-$?}
-    ;;
-
-  silent-remove) # Silently remove packages
-    shift 1
-    [ "$1" = "help" ] && printf_help "Silently remove packages"
-    declare -a LISTARRAY=("$@")
-    for pkg in "${LISTARRAY[@]}"; do
-      $pkgmgrbinremsil "*$pkg*" |& __devnull && exitCode+=0 || exitCode+=1
-    done
-    exit ${exitCode:-$?}
-    ;;
-
-  silent-upgrade | silent-update) # Silently update packages
-    shift 1
-    [ "$1" = "help" ] && printf_help "Silently upgrade your system"
-    am_i_online --error || exit 1
-    if __cmd_exists systemmgr; then
-      systemmgr update scripts |& __devnull && exitCode+=0 || exitCode+=1
-    fi
-    $pkgmgrbinupdsil |& __devnull && exitCode+=0 || exitCode+=1
-    exit ${exitCode:-$?}
-    ;;
-    # TODO: END
-  silent) # Silent
-    case "$2" in
-    install) # Silently install packages
-      shift 2
-      [ "$1" = "help" ] && printf_help "Silently install packages"
-      am_i_online --error || exit 1
-      declare -a LISTARRAY=("$@")
-      for pkg in "${LISTARRAY[@]}"; do
-        eval "$pkgmgrbininssil" "$pkg" |& __devnull && exitCode+=0 || exitCode+=1
-      done
-      exit ${exitCode:-$?}
-      ;;
-
-    remove) # Silently remove packages
-      shift 2
-      [ "$1" = "help" ] && printf_help "Silently remove packages"
-      declare -a LISTARRAY=("$@")
-      for pkg in "${LISTARRAY[@]}"; do
-        eval "$pkgmgrbinremsil" "*$pkg*" |& __devnull && exitCode+=0 || exitCode+=1
-      done
-      exit ${exitCode:-$?}
-      ;;
-
-    upgrade) # Silently update packages
-      shift 2
-      [ "$1" = "help" ] && printf_help "Silently upgrade your system"
-      am_i_online --error || exit 1
-      if __cmd_exists systemmgr; then
-        systemmgr update installer |& __devnull
-      fi
-      eval "$pkgmgrbinupdsil" |& __devnull && exitCode+=0 || exitCode+=1
-      exit ${exitCode:-$?}
-      ;;
-
-    *) # Silently update packages
-      shift 1
-      [ "$1" = "help" ] && printf_help "Silently install packages | defaults to a silent update"
-      am_i_online --error || exit 1
-      if [ -z "$1" ]; then
-        eval "$pkgmgrbinupdsil" |& __devnull && exitCode+=0 || exitCode+=1
-      else
-        declare -a LISTARRAY=("$@")
-        for pkg in "${LISTARRAY[@]}"; do
-          eval "$pkgmgrbininssil" "$pkg" |& __devnull && exitCode+=0 || exitCode+=1
-        done
-      fi
       exit ${exitCode:-$?}
       ;;
     esac
