🗃 Modified: bin/pkmgr functions/testing.bash  🗃

diff --git a/bin/pkmgr b/bin/pkmgr
--- a/bin/pkmgr
+++ b/bin/pkmgr
@@ -592,7 +592,7 @@ pkginit="$pkgmgrbincle ; $pkgmgrbincac ; $pkgmgrbinupdsil"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # begin main app
 case "$1" in
-check)
+check) # Check for updates
   UPDATECHECKFILE="${CACHE_DIR:-$HOME/.cache}/updatechecheck"
   if [ "$1" = "force" ] || [ "$FORCE" = "yes" ]; then
     __rm_rf "$UPDATECHECKFILE" && run_updatechecheck
@@ -604,12 +604,12 @@ check)
   exit
   ;;
 
-available)
+available) # List
   shift 1
   run_install_available "$APPNAME"
   ;;
 
-aliases)
+aliases) # Generate aliases
   shift 1
   if [ -d "$HOME/.config/bash/local" ] && __devnull grep userbashprofilelocal "$HOME/.bashrc"; then
     ALIASFILE="$HOME/.config/bash/local/pkmgr.bash"
@@ -631,13 +631,13 @@ aliases)
   fi
   ;;
 
-cron)
+cron) # run via cron
   shift 1
   [ "$1" = "help" ] && printf_help "Options are add, remove, or run"
   __schedule "$@"
   ;;
 
-ask)
+ask) # Ask user to install missing
   shift 1
   if [ -n "$DISPLAY" ]; then
     __attemp_install_menus "$@"
@@ -647,7 +647,7 @@ ask)
   echo
   ;;
 
-install | -i)
+install | -i) # Install packages
   shift 1
   [ "$1" = "help" ] && printf_help "Install a package"
   am_i_online --error || exit 1
@@ -655,14 +655,14 @@ install | -i)
   set --
   ;;
 
-remove | -r)
+remove | -r) # Remove packages
   shift 1
   [ "$1" = "help" ] && printf_help "Remove a package"
   $pkgmgrbindel "${@}" && exit 0 || exit 1
   set --
   ;;
 
-list)
+list) # Install package in a list file
   shift 1
   [ "$1" = "help" ] && printf_help "Install package via a list: pkmgr list ./listToInstall"
   am_i_online --error || exit 1
@@ -673,7 +673,7 @@ list)
   done
   ;;
 
-curl)
+curl) # Download a list file and install
   shift 1
   [ "$1" = "help" ] && printf_help "pkmgr curl arch min or pkmgr curl fullURLtoList"
   am_i_online --error || exit 1
@@ -687,7 +687,7 @@ curl)
   [ -n "$VDEBUG" ] || __rm_rf "$PKMGR_TEMP_FILE"
   ;;
 
-dotfiles)
+dotfiles) # Install dfmgr packages
   shift 1
   [ "$1" = "help" ] && printf_help "pkmgr dotfiles git"
   am_i_online --error || exit 1
@@ -700,7 +700,7 @@ dotfiles)
   [ -n "$VDEBUG" ] || __rm_rf "$PKMGR_TEMP_FILE"
   ;;
 
-script)
+script) # Execute a script
   shift 1
   [ "$1" = "help" ] && printf_help "pkmgr script ./myScript or fullURLtoScript"
   am_i_online --error || exit 1
@@ -708,7 +708,7 @@ script)
   set --
   ;;
 
-upgrade | update | -u)
+upgrade | update | -u) # Update packages
   shift 1
   [ "$1" = "help" ] && printf_help "Update your system"
   am_i_online --error || exit 1
@@ -718,32 +718,32 @@ upgrade | update | -u)
   $pkgmgrbinupd
   ;;
 
-export | -x)
+export | -x) # Export installed packages
   shift 1
   [ "$1" = "help" ] && printf_help "Export installed packages to a list"
   exportpkg
   ;;
 
-clean | -c)
+clean | -c) # Clean package manager files
   shift 1
   [ "$1" = "help" ] && printf_help "Clean up package manager files"
   $pkgmgrbincle
   ;;
 
-init | -in)
+init | -in) # Update package manager and upgrade system
   shift 1
   [ "$1" = "help" ] && printf_help "Initialize the system by making the cache and updating"
   am_i_online --error || exit 1
   __execute "$pkginit" "Initializing System"
   ;;
 
-makecache | -ca)
+makecache | -ca) # Create the package manage cache file
   shift 1
   [ "$1" = "help" ] && printf_help "Create the cache for the package manager"
   __devnull $pkgmgrbincac || exit 1
   ;;
 
-search | -s)
+search | -s) # Search for packages
   shift 1
   [ "$1" = "help" ] && printf_help "Search for a package"
   declare -a LISTARRAY="$*"
@@ -752,7 +752,7 @@ search | -s)
   done
   ;;
 
-required)
+required) # Install required files
   shift 1
   [ "$1" = "help" ] && printf_help "Install required packages"
   am_i_online --error || exit 1
@@ -762,7 +762,7 @@ required)
   done
   ;;
 
-silent-install)
+silent-install) # Silently install packages
   shift 1
   [ "$1" = "help" ] && printf_help "Silently install packages"
   am_i_online --error || exit 1
@@ -772,7 +772,7 @@ silent-install)
   done
   ;;
 
-silent-remove)
+silent-remove) # Silently remove packages
   shift 1
   [ "$1" = "help" ] && printf_help "Silently remove packages"
   declare -a LISTARRAY="$*"
@@ -781,7 +781,7 @@ silent-remove)
   done
   ;;
 
-silent-upgrade | silent-update)
+silent-upgrade | silent-update) # Silently update packages
   shift 1
   [ "$1" = "help" ] && printf_help "Silently upgrade your system"
   am_i_online --error || exit 1
@@ -791,10 +791,10 @@ silent-upgrade | silent-update)
   __devnull $pkgmgrbinupdsil && exit 0 || exit 1
   ;;
 
-cpan | perl)
+cpan | perl) # perl CPAN modules
   shift 1
   case $1 in
-  install)
+  install) # Install perl modules
     shift 1
     [ "$1" = "help" ] && printf_help "install perl modules via cpan"
     am_i_online --error || exit 1
@@ -804,7 +804,7 @@ cpan | perl)
     done
     ;;
 
-  remove)
+  remove) # Remove perl modules
     shift 1
     [ "$1" = "help" ] && printf_help "Remove perl modules via cpan"
     declare -a LISTARRAY="$*"
@@ -813,7 +813,7 @@ cpan | perl)
     done
     ;;
 
-  check)
+  check) # Check to see if perl modules are installed
     shift 1
     [ "$1" = "help" ] && printf_help "Check for cpan module"
     declare -a LISTARRAY="$*"
@@ -822,7 +822,7 @@ cpan | perl)
     done
     ;;
 
-  *)
+  *) # Install perl modules
     [ "$1" = "help" ] && printf_help "install perl modules via cpan"
     am_i_online --error || exit 1
     declare -a LISTARRAY="$*"
@@ -833,10 +833,10 @@ cpan | perl)
   esac
   ;;
 
-pip | python)
+pip | python) # Python modules
   shift 1
   case $1 in
-  install)
+  install) # Install python modules
     shift 1
     [ "$1" = "help" ] && printf_help "Install python modules via pip"
     am_i_online --error || exit 1
@@ -846,7 +846,7 @@ pip | python)
     done
     ;;
 
-  remove)
+  remove) # Remove python modules
     shift 1
     [ "$1" = "help" ] && printf_help "Remove python modules via pip"
     declare -a LISTARRAY="$*"
@@ -855,7 +855,7 @@ pip | python)
     done
     ;;
 
-  check)
+  check) # Check to see if python module is installed
     shift 1
     [ "$1" = "help" ] && printf_help "Check for pip module"
     declare -a LISTARRAY="$*"
@@ -863,9 +863,41 @@ pip | python)
       __python_exists --sudo "$pkg" || printf_red "PIP module $pkg is missing"
     done
     ;;
+  esac
+  ;;
 
-  *)
+lua) # LUA modules
+  shift 1
+  case $1 in
+  install) # Install lua modules
+    shift 1
     [ "$1" = "help" ] && printf_help "Install python modules via pip"
+    am_i_online --error || exit 1
+    declare -a LISTARRAY="$*"
+    for pkg in ${LISTARRAY[*]}; do
+      lua_run "$pkg"
+    done
+    ;;
+
+  remove) # Remove lua modules
+    shift 1
+    [ "$1" = "help" ] && printf_help "Remove python modules via pip"
+    declare -a LISTARRAY="$*"
+    for pkg in ${LISTARRAY[*]}; do
+      lua_remove "$pkg"
+    done
+    ;;
+
+  check) # Check to see if lua module is installed
+    shift 1
+    [ "$1" = "help" ] && printf_help "Check for lua module"
+    declare -a LISTARRAY="$*"
+    for pkg in ${LISTARRAY[*]}; do
+      __lua_exists --sudo "$pkg" || printf_red "lua module $pkg is missing"
+    done
+    ;;
+  *) # Install lua modules
+    [ "$1" = "help" ] && printf_help "Install lua modules via luarocks"
     am_i_online --error || exit 1
     declare -a LISTARRAY="$*"
     for pkg in ${LISTARRAY[*]}; do
@@ -875,10 +907,10 @@ pip | python)
   esac
   ;;
 
-gem | ruby)
+gem | ruby) # ruby modules
   shift 1
   case $1 in
-  install)
+  install) # Install ruby modules
     shift 1
     [ "$1" = "help" ] && printf_help "Install ruby modules via rubygems"
     am_i_online --error || exit 1
@@ -888,7 +920,7 @@ gem | ruby)
     done
     ;;
 
-  remove)
+  remove) # remove ruby modules
     shift 1
     [ "$1" = "help" ] && printf_help "Remove ruby modules via rubygems"
     declare -a LISTARRAY="$*"
@@ -897,7 +929,7 @@ gem | ruby)
     done
     ;;
 
-  check)
+  check) # Check to see if ruby module is installed
     shift 1
     [ "$1" = "help" ] && printf_help "Remove ruby modules via rubygems"
     declare -a LISTARRAY="$*"
@@ -906,7 +938,7 @@ gem | ruby)
     done
     ;;
 
-  *)
+  *) # Install ruby modules
     [ "$1" = "help" ] && printf_help "Install ruby modules via rubygems"
     am_i_online --error || exit 1
     declare -a LISTARRAY="$*"
@@ -917,10 +949,10 @@ gem | ruby)
   esac
   ;;
 
-npm | node)
+npm | node) # node modules
   shift 1
   case $1 in
-  install)
+  install) # Install node modules
     shift 1
     [ "$1" = "help" ] && printf_help "Install node package via npm"
     am_i_online --error || exit 1
@@ -930,7 +962,7 @@ npm | node)
     done
     ;;
 
-  remove)
+  remove) # Remove node modules
     shift 1
     [ "$1" = "help" ] && printf_help "Remove node package via npm"
     declare -a LISTARRAY="$*"
@@ -939,7 +971,7 @@ npm | node)
     done
     ;;
 
-  check)
+  check) # Check to see if node module is installed
     shift 1
     [ "$1" = "help" ] && printf_help "Check npm module"
     declare -a LISTARRAY="$*"
@@ -948,7 +980,7 @@ npm | node)
     done
     ;;
 
-  *)
+  *) # Install node modules
     [ "$1" = "help" ] && printf_help "Install node package via npm"
     am_i_online --error || exit 1
     declare -a LISTARRAY="$*"
@@ -959,10 +991,10 @@ npm | node)
   esac
   ;;
 
-silent)
+silent) # Silent
   shift 1
   case $1 in
-  install)
+  install) # Silently install packages
     shift 1
     [ "$1" = "help" ] && printf_help "Silently install packages"
     am_i_online --error || exit 1
@@ -972,7 +1004,7 @@ silent)
     done
     ;;
 
-  remove)
+  remove) # Silently remove packages
     shift 1
     [ "$1" = "help" ] && printf_help "Silently remove packages"
     declare -a LISTARRAY="$*"
@@ -981,7 +1013,7 @@ silent)
     done
     ;;
 
-  upgrade | update)
+  upgrade | update) # Silently update packages
     shift 1
     [ "$1" = "help" ] && printf_help "Silently upgrade your system"
     am_i_online --error || exit 1
@@ -991,7 +1023,7 @@ silent)
     __devnull $pkgmgrbinupdsil && exit 0 || exit 1
     ;;
 
-  *)
+  *) # Silently update packages
     [ "$1" = "help" ] && printf_help "Silently install packages | defaults to a silent update"
     am_i_online --error || exit 1
     if [ -z "$1" ]; then
@@ -1006,19 +1038,19 @@ silent)
   esac
   ;;
 
-info)
+info) # Show system info
   shift 1
   [ "$1" = "help" ] && printf_help "Show info about your system"
   show_info
   ;;
 
-version)
+version) # Show version
   shift 1
   run_install_version "$@"
   exit
   ;;
 
-*)
+*) # Help
   __help
   ;;
 esac
