🐛 FIXED: bin/pkmgr 🐛

diff --git a/bin/pkmgr b/bin/pkmgr
--- a/bin/pkmgr
+++ b/bin/pkmgr
@@ -72,20 +72,20 @@ __list_available() { echo -e '' | tr ' ' '\n'; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 run_updatecheck() { am_i_online --error && pkmgrcheckupdates; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__install_packages() {
-  local pack=""
-  local newpackage=""
-  declare -a LISTARRAY="$*"
-  for pack in "${LISTARRAY[@]}"; do
-    [[ $pack == php* ]] && pack="$(echo "$pack" | sed 's/^php[0-9].[0-9]/'php$PHPVER'/')"
-    [[ $pack == python* ]] && pack="$(echo "$pack" | sed 's/^python[0-9]*/'$PYTHONVER'/')"
-    [[ $DISTRO == Debian || $DISTRO == Ubuntu ]] && [[ $pack == httpd* ]] && pack="$(echo "$pack" | sed 's/^httpd*/apache2/')"
-    [[ $DISTRO == Arch ]] && [[ $pack == httpd* ]] && pack="$(echo "$pack" | sed 's/^httpd*/apache/')"
-    [[ $DISTRO == Arch ]] && [[ $pack == apache* ]] && pack="$(echo "$pack" | sed 's/^apache2/apache/')"
-    newpackage+="$pack"
-  done
-  $run_command "$newpackage" && return 0 || return 1
-}
+#run_command() {
+#  local pack=""
+#  local newpackage=""
+#  declare -a LISTARRAY="$*"
+#  for pack in "${LISTARRAY[@]}"; do
+#    [[ $pack == php* ]] && pack="$(echo "$pack" | sed 's/^php[0-9].[0-9]/'php$PHPVER'/')"
+#    [[ $pack == python* ]] && pack="$(echo "$pack" | sed 's/^python[0-9]*/'$PYTHONVER'/')"
+#    [[ $DISTRO == Debian || $DISTRO == Ubuntu ]] && [[ $pack == httpd* ]] && pack="$(echo "$pack" | sed 's/^httpd*/apache2/')"
+#    [[ $DISTRO == Arch ]] && [[ $pack == httpd* ]] && pack="$(echo "$pack" | sed 's/^httpd*/apache/')"
+#    [[ $DISTRO == Arch ]] && [[ $pack == apache* ]] && pack="$(echo "$pack" | sed 's/^apache2/apache/')"
+#    newpackage+="$pack"
+#  done
+#  $run_command "$newpackage" && return 0 || return 1
+#}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __rm_rf() { sudo rm -Rf "$@"; }
 __cp_rf() { sudo cp -Rf "$@"; }
@@ -673,7 +673,7 @@ available) # List
 aliases) # Generate aliases
   shift 1
   if [ -d "$HOME/.config/bash/local" ] && __devnull grep userbashprofilelocal "$HOME/.bashrc"; then
-    ALIASFILE="$HOME/.config/bash/local/pkmgr.bash"
+    [ -f "$HOME/.config/bash/local/pkmgr.bash" ] || ALIASFILE="$HOME/.config/bash/local/pkmgr.bash"
   else
     ALIASFILE="$HOME/.bash_profile"
   fi
@@ -708,125 +708,42 @@ ask) # Ask user to install missing
   echo
   ;;
 
-keys | -k)
+keys) # Arch linux keys
   shift 1
   if cmd_exists pacman-key; then
     [ "$1" = "help" ] && printf_help "Usage: $APPNAME keys [arch,manjaro,arcolinux] - Manage arch keys"
     sudo rm -R /etc/pacman.d/gnupg/
     sudo rm -R /root/.gnupg/
     sudo gpg --refresh-keys
-    sudo pacman-key --init && sudo pacman-key --populate "${1:-archlinux}"
+    sudo pacman-key --init && sudo pacman-key --populate ${1:-archlinux} ${2:-}
     sudo pacman-key --refresh-keys
   else
     printf_error "This is only supported on Arch based distros"
   fi
   ;;
 
-install | -i) # Install packages
-  shift 1
-  [ "$1" = "help" ] && printf_help "Install a package"
-  am_i_online --error || exit 1
-  export run_command="$pkgmgrbinins"
-  declare -a LISTARRAY="$*"
-  __install_packages "${LISTARRAY[*]}" && exit 0 || exit 1
-  set --
-  ;;
-
-remove | -r) # Remove packages
-  shift 1
-  [ "$1" = "help" ] && printf_help "Remove a package"
-  export run_command="$pkgmgrbinins"
-  declare -a LISTARRAY="$*"
-  __install_packages "${LISTARRAY[*]}" && exit 0 || exit 1
-  set --
-  ;;
-
-list) # Install package in a list file
-  shift 1
-  [ "$1" = "help" ] && printf_help "Install package via a list: pkmgr list ./listToInstall"
-  am_i_online --error || exit 1
-  PCKLIST="$(grep -Ev '^$|^#' "$1" | sort -u | tr '\n' ' ' && echo)"
-  declare -a LISTARRAY=$PCKLIST
-  export run_command="$pkgmgrbinins"
-  for pkg in ${LISTARRAY[*]}; do
-    __execute "__install_packages $pkg" "Installing $pkg"
-  done
-  ;;
-
-curl) # Download a list file and install
-  shift 1
-  [ "$1" = "help" ] && printf_help "pkmgr curl arch min or pkmgr curl fullURLtoList"
-  am_i_online --error || exit 1
-  curl_run "$@"
-  set --
-  PCKLIST="$(grep -Ev '^$|^#' "$PKMGR_TEMP_FILE" | sort -u | tr '\n' ' ' && echo)"
-  declare -a LISTARRAY=$PCKLIST
-  export run_command="$pkgmgrbinins"
-  for pkg in ${LISTARRAY[*]}; do
-    __execute "__install_packages $pkg" "Installing $pkg"
-  done
-  [ -n "$VDEBUG" ] || __rm_rf "$PKMGR_TEMP_FILE"
-  ;;
-
-dotfiles) # Install dfmgr packages
-  shift 1
-  [ "$1" = "help" ] && printf_help "pkmgr dotfiles git"
-  am_i_online --error || exit 1
-  dotfiles_run "$@"
-  PCKLIST="$(grep -Ev '^$|^#' "$PKMGR_TEMP_FILE" | sort -u | tr '\n' ' ' && echo)"
-  declare -a LISTARRAY=$PCKLIST
-  export run_command="$pkgmgrbinins"
-  for pkg in ${LISTARRAY[*]}; do
-    __execute "__install_packages $pkg" "Installing $pkg"
-  done
-  [ -n "$VDEBUG" ] || __rm_rf "$PKMGR_TEMP_FILE"
-  ;;
-
-script) # Execute a script
-  shift 1
-  [ "$1" = "help" ] && printf_help "pkmgr script ./myScript or fullURLtoScript"
-  am_i_online --error || exit 1
-  script_run "$@"
-  set --
-  ;;
-
-upgrade | update | -u) # Update packages
-  shift 1
-  [ "$1" = "help" ] && printf_help "Update your system"
-  am_i_online --error || exit 1
-  if [ -f "$(builtin type -P systemmgr)" ]; then
-    sudo systemmgr install installer
-  fi
-  $pkgmgrbinupd
-  ;;
-
-export | -x) # Export installed packages
-  shift 1
-  [ "$1" = "help" ] && printf_help "Export installed packages to a list"
-  exportpkg
-  ;;
-
-clean | -c) # Clean package manager files
+clean) # Clean package manager files
   shift 1
   [ "$1" = "help" ] && printf_help "Clean up package manager files"
   $pkgmgrbincle
   ;;
 
-init | -in) # Update package manager and upgrade system
-  shift 1
-  [ "$1" = "help" ] && printf_help "Initialize the system by making the cache and updating"
-  am_i_online --error || exit 1
-  export run_command="$pkginit"
-  __execute "__install_packages" "Initializing System"
-  ;;
-
-makecache | -ca) # Create the package manage cache file
+makecache) # Create the package manage cache file
   shift 1
   [ "$1" = "help" ] && printf_help "Create the cache for the package manager"
   __devnull $pkgmgrbincac || exit 1
   ;;
 
-search | -s) # Search for packages
+init) # Update package manager and upgrade system
+  shift 1
+  [ "$1" = "help" ] && printf_help "Initialize the system by making the cache and updating"
+  am_i_online --error || exit 1
+  export run_command="$pkginit"
+  __execute "$run_command" "Initializing System"
+  ;;
+
+
+search) # Search for packages
   shift 1
   [ "$1" = "help" ] && printf_help "Search for a package"
   declare -a LISTARRAY="$*"
@@ -842,6 +759,61 @@ search | -s) # Search for packages
   fi
   ;;
 
+export) # Export installed packages
+  shift 1
+  [ "$1" = "help" ] && printf_help "Export installed packages to a list"
+  exportpkg
+  ;;
+
+dotfiles) # Install pkmgr/dfmgr packages
+  shift 1
+  [ "$1" = "help" ] && printf_help "pkmgr dotfiles git"
+  am_i_online --error || exit 1
+  dotfiles_run "$@"
+  PCKLIST="$(grep -Ev '^$|^#' "$PKMGR_TEMP_FILE" | sort -u | tr '\n' ' ' && echo)"
+  declare -a LISTARRAY=$PCKLIST
+  export run_command="$pkgmgrbininssil"
+  for pkg in ${LISTARRAY[*]}; do
+    __execute "$run_command $pkg" "Installing $pkg"
+  done
+  [ -n "$VDEBUG" ] || __rm_rf "$PKMGR_TEMP_FILE"
+  ;;
+
+list) # Install package in a list file
+  shift 1
+  [ "$1" = "help" ] && printf_help "Install package via a list: pkmgr list ./listToInstall"
+  am_i_online --error || exit 1
+  PCKLIST="$(grep -Ev '^$|^#' "$1" | sort -u | tr '\n' ' ' && echo)"
+  declare -a LISTARRAY=$PCKLIST
+  export run_command="$pkgmgrbininssil"
+  for pkg in ${LISTARRAY[*]}; do
+    __execute "$run_command $pkg" "Installing $pkg"
+  done
+  ;;
+
+curl) # Download a list file and install
+  shift 1
+  [ "$1" = "help" ] && printf_help "pkmgr curl arch min or pkmgr curl fullURLtoList"
+  am_i_online --error || exit 1
+  curl_run "$@"
+  set --
+  PCKLIST="$(grep -Ev '^$|^#' "$PKMGR_TEMP_FILE" | sort -u | tr '\n' ' ' && echo)"
+  declare -a LISTARRAY=$PCKLIST
+  export run_command="$pkgmgrbininssil"
+  for pkg in ${LISTARRAY[*]}; do
+    __execute "$run_command $pkg" "Installing $pkg"
+  done
+  [ -n "$VDEBUG" ] || __rm_rf "$PKMGR_TEMP_FILE"
+  ;;
+
+script) # Execute a script
+  shift 1
+  [ "$1" = "help" ] && printf_help "pkmgr script ./myScript or fullURLtoScript"
+  am_i_online --error || exit 1
+  script_run "$@"
+  set --
+  ;;
+
 required) # Install required files
   shift 1
   [ "$1" = "help" ] && printf_help "Install required packages"
@@ -849,8 +821,37 @@ required) # Install required files
   declare -a LISTARRAY="$*"
   export run_command="$pkgmgrbininssil"
   for pkg in ${LISTARRAY[*]}; do
-    __execute "__install_packages $pkg" "Installing $pkg" || exit 1
+    __execute "$run_command $pkg" "Installing $pkg" || exit 1
   done
+  ;;
+
+install) # Install packages
+  shift 1
+  [ "$1" = "help" ] && printf_help "Install a package"
+  am_i_online --error || exit 1
+  declare -a LISTARRAY="$*"
+  export run_command="$pkgmgrbinins"
+  $run_command "${LISTARRAY[*]}" && exit 0 || exit 1
+  set --
+  ;;
+
+remove) # Remove packages
+  shift 1
+  [ "$1" = "help" ] && printf_help "Remove a package"
+  declare -a LISTARRAY="$*"
+  export run_command="$pkgmgrbindel"
+  $run_command "${LISTARRAY[*]}" && exit 0 || exit 1
+  set --
+  ;;
+
+upgrade) # Update packages
+  shift 1
+  [ "$1" = "help" ] && printf_help "Update your system"
+  am_i_online --error || exit 1
+  if [ -f "$(builtin type -P systemmgr)" ]; then
+    sudo systemmgr install scripts
+  fi
+  $pkgmgrbinupd
   ;;
 
 silent-install) # Silently install packages
@@ -860,7 +861,7 @@ silent-install) # Silently install packages
   declare -a LISTARRAY="$*"
   export run_command="$pkgmgrbininssil"
   for pkg in ${LISTARRAY[*]}; do
-    __devnull __install_packages "$pkg" && exit 0 || exit 1
+    __devnull $run_command "$pkg" && exit 0 || exit 1
   done
   ;;
 
@@ -881,6 +882,53 @@ silent-upgrade | silent-update) # Silently update packages
     __devnull sudo systemmgr install installer
   fi
   __devnull $pkgmgrbinupdsil && exit 0 || exit 1
+  ;;
+
+silent) # Silent
+  shift 1
+  case $1 in
+  install) # Silently install packages
+    shift 1
+    [ "$1" = "help" ] && printf_help "Silently install packages"
+    am_i_online --error || exit 1
+    declare -a LISTARRAY="$*"
+    for pkg in ${LISTARRAY[*]}; do
+      __devnull $pkgmgrbininssil "$pkg" && exit 0 || exit 1
+    done
+    ;;
+
+  remove) # Silently remove packages
+    shift 1
+    [ "$1" = "help" ] && printf_help "Silently remove packages"
+    declare -a LISTARRAY="$*"
+    for pkg in ${LISTARRAY[*]}; do
+      __devnull $pkgmgrbinremsil "*$pkg*" && exit 0 || exit 1
+    done
+    ;;
+
+  upgrade | update) # Silently update packages
+    shift 1
+    [ "$1" = "help" ] && printf_help "Silently upgrade your system"
+    am_i_online --error || exit 1
+    if [ -f "$(builtin type -P systemmgr)" ]; then
+      __devnull sudo systemmgr install installer
+    fi
+    __devnull $pkgmgrbinupdsil && exit 0 || exit 1
+    ;;
+
+  *) # Silently update packages
+    [ "$1" = "help" ] && printf_help "Silently install packages | defaults to a silent update"
+    am_i_online --error || exit 1
+    if [ -z "$1" ]; then
+      __devnull $pkgmgrbinupdsil && exit 0 || exit 1
+    else
+      declare -a LISTARRAY="$*"
+      for pkg in ${LISTARRAY[*]}; do
+        __devnull $pkgmgrbininssil "$pkg" && exit 0 || exit 1
+      done
+    fi
+    ;;
+  esac
   ;;
 
 cpan | perl) # perl CPAN modules
@@ -1120,53 +1168,6 @@ lua) # LUA modules
     for pkg in ${LISTARRAY[*]}; do
       lua_run "$pkg"
     done
-    ;;
-  esac
-  ;;
-
-silent) # Silent
-  shift 1
-  case $1 in
-  install) # Silently install packages
-    shift 1
-    [ "$1" = "help" ] && printf_help "Silently install packages"
-    am_i_online --error || exit 1
-    declare -a LISTARRAY="$*"
-    for pkg in ${LISTARRAY[*]}; do
-      __devnull $pkgmgrbininssil "$pkg" && exit 0 || exit 1
-    done
-    ;;
-
-  remove) # Silently remove packages
-    shift 1
-    [ "$1" = "help" ] && printf_help "Silently remove packages"
-    declare -a LISTARRAY="$*"
-    for pkg in ${LISTARRAY[*]}; do
-      __devnull $pkgmgrbinremsil "*$pkg*" && exit 0 || exit 1
-    done
-    ;;
-
-  upgrade | update) # Silently update packages
-    shift 1
-    [ "$1" = "help" ] && printf_help "Silently upgrade your system"
-    am_i_online --error || exit 1
-    if [ -f "$(builtin type -P systemmgr)" ]; then
-      __devnull sudo systemmgr install installer
-    fi
-    __devnull $pkgmgrbinupdsil && exit 0 || exit 1
-    ;;
-
-  *) # Silently update packages
-    [ "$1" = "help" ] && printf_help "Silently install packages | defaults to a silent update"
-    am_i_online --error || exit 1
-    if [ -z "$1" ]; then
-      __devnull $pkgmgrbinupdsil && exit 0 || exit 1
-    else
-      declare -a LISTARRAY="$*"
-      for pkg in ${LISTARRAY[*]}; do
-        __devnull $pkgmgrbininssil "$pkg" && exit 0 || exit 1
-      done
-    fi
     ;;
   esac
   ;;
