🗃️ Committing everything that changed 🗃️

diff --git a/bin/reqpkgs b/bin/reqpkgs
--- a/bin/reqpkgs
+++ b/bin/reqpkgs
@@ -292,6 +292,12 @@ YUM_PACKAGE_NAMES+=""
 PAC_PACKAGE_NAMES="python3 python-pip net-tools vim "
 PAC_PACKAGE_NAMES+=""
 
+# Alpinelinux
+APK_PACKAGE_NAMES="iproute2,ssmtp,openssl,jq,ca-certificates,tzdata,mailcap,ncurses,util-linux,"
+APK_PACKAGE_NAMES+="pciutils,usbutils,coreutils,binutils,findutils,grep,rsync,zip,certbot,tini,"
+APK_PACKAGE_NAMES+="certbot,py3-pip,procps,net-tools,coreutils,sed,gawk,grep,attr,findutils,readline,"
+APK_PACKAGE_NAMES+="lsof,less,curl"
+
 # NPM Packages
 REQ_NPM_PACKAGE_NAMES="heroku vercel "
 REQ_PIP_PACKAGE_NAMES+=""
@@ -337,8 +343,8 @@ __initialize_reqpkgs() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __pip_bin() {
-  phpbin="$(builtin type -P python3 2>/dev/null || builtin type -P python2 2>/dev/null || builtin type -P python 2>/dev/null || builtin type -P pip 2>/dev/null || false)"
-  eval $phpbin -m pip install --user "$@" 2>>"$REQPKGS_LOG_FILE_ERR" >>"$REQPKGS_LOG_FILE_INFO" || return 1
+  pipbin="$(builtin type -P python3 2>/dev/null || builtin type -P python2 2>/dev/null || builtin type -P python 2>/dev/null || false)"
+  eval $pipbin -m pip install --user "$@" 2>>"$REQPKGS_LOG_FILE_ERR" >>"$REQPKGS_LOG_FILE_INFO" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __npm_bin() {
@@ -354,7 +360,9 @@ __lua_bin() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __go_bin() {
-  eval GO111MODULE=off GOBIN="$HOME/.local/bin/" go get "$@" 2>>"$REQPKGS_LOG_FILE_ERR" >>"$REQPKGS_LOG_FILE_INFO" || return 1
+  export GO111MODULE="${GO111MODULE:-off}"
+  export GOBIN="$HOME/.local/bin/"
+  eval go get "$@" 2>>"$REQPKGS_LOG_FILE_ERR" >>"$REQPKGS_LOG_FILE_INFO" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __sys_bin() {
@@ -593,13 +601,27 @@ __system_pkg_mgr() {
   local SET_YUM_PACKAGE_NAMES="${SYS_PACKAGE_NAMES:-$YUM_PACKAGE_NAMES}"
   local SET_DEB_PACKAGE_NAMES="${SYS_PACKAGE_NAMES:-$DEB_PACKAGE_NAMES}"
   local SET_PAC_PACKAGE_NAMES="${SYS_PACKAGE_NAMES:-$PAC_PACKAGE_NAMES}"
+  local SET_APK_PACKAGE_NAMES="${SYS_PACKAGE_NAMES:-$APK_PACKAGE_NAMES}"
   # format package list
   YUM_PACKAGE_NAMES="${SET_YUM_PACKAGE_NAMES//,/ }"
   DEB_PACKAGE_NAMES="${SET_DEB_PACKAGE_NAMES//,/ }"
   PAC_PACKAGE_NAMES="${SET_PAC_PACKAGE_NAMES//,/ }"
+  APK_PACKAGE_NAMES="${SET_APK_PACKAGE_NAMES//,/ }"
   # Execute
-  if [ -n "$YUM_PACKAGE_NAMES" ] || [ -n "$DEB_PACKAGE_NAMES" ] || [ -n "$PAC_PACKAGE_NAMES" ]; then
-    if cat /etc/*release | grep -E '^NAME=|^ID=|^ID_LIKE=' | grep -qi CentOS; then
+  if [ -n "$YUM_PACKAGE_NAMES" ] || [ -n "$DEB_PACKAGE_NAMES" ] || [ -n "$PAC_PACKAGE_NAMES" ] || [ -n "$APK_PACKAGE_NAMES" ]; then
+    if cat /etc/*release | grep -E '^NAME=|^ID=|^ID_LIKE=' | grep -qiE 'Alpine'; then
+      printf_green "============================================="
+      printf_green "Installing packages for AlpineLinux          "
+      printf_green "============================================="
+      pkg=""
+      for pkg in ${APK_PACKAGE_NAMES} ${GLOBAL_PACKAGES}; do
+        printf '\r%b' "${PURPLE}installing ${pkg}${NC} "
+        sudo pacman -Syyu --noconfirm --needed $pkg | __sys_bin && exitCode=$(($exitCode + 0)) || { exitCode=$(($exitCode + 1)) && errorpkgs=("${errorpkgs[@]}" "$pkg") && false; }
+        [ $? -eq 0 ] &&
+          printf '\r%b                                                     %b \n' "${CYAN}Installed ${pkg}" "${NC}" ||
+          printf '\r%b                                                     %b \n' "${YELLOW}Failed to install: ${pkg}" "${NC}"
+      done
+    elif cat /etc/*release | grep -E '^NAME=|^ID=|^ID_LIKE=' | grep -qi CentOS; then
       printf_green "============================================="
       printf_green "Installing packages for CentOS               "
       printf_green "============================================="
@@ -716,7 +738,7 @@ __system_pkg_mgr() {
           printf '\r%b                                                     %b \n' "${CYAN}Installed ${pkg}" "${NC}" ||
           printf '\r%b                                                     %b \n' "${YELLOW}Failed to install: ${pkg}" "${NC}"
       done
-    elif cat /etc/*release | grep -E '^NAME=|^ID=|^ID_LIKE=' | grep -qE 'Arch|Arco|Manjaro'; then
+    elif cat /etc/*release | grep -E '^NAME=|^ID=|^ID_LIKE=' | grep -qiE 'Arch|Arco|Manjaro'; then
       printf_green "============================================="
       printf_green "Installing packages for Arch                 "
       printf_green "============================================="
