🗃  Modified: bin/run_server 🗃

diff --git a/bin/run_server b/bin/run_server
--- a/bin/run_server
+++ b/bin/run_server
@@ -101,8 +101,6 @@ __get_port() {
   local ORIG_PORT="$RUN_SERVER_PORT"
   local i=0
   if __port_used $port; then
-    printf_red "Something appears to be running on port $RUN_SERVER_PORT}"
-    printf_yellow "Attempting the next port: $((port + 1))"
     while :; do
       __port_free $port && break || set_port="$((port + 1)) "
       sleep .5
@@ -117,23 +115,18 @@ __get_port() {
 __main__() {
   mainPid="$$"
   trap '__exit $mainPid' INT
-  prog=""
   SERVER_PORT="${1:-$RUN_SERVER_DEFAULT_PORT}"
   MAX_NUMBER_OF_TRIES=${MAX_NUMBER_OF_TRIES:-20}
   RUN_SERVER_TEMP_DIR="${RUN_SERVER_TEMP_DIR:-/tmp}"
-  SERVER_DIR=""
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   i=0
   echo "$RUN_SERVER_PORT" >"$RUN_SERVER_LOG_DIR/$mainPid"
-  SERVER_LOG="${SERVER_LOG:-$RUN_SERVER_TEMP_DIR/run_server_$RUN_SERVER_PORT.log}"
-  printf '%s\n' "Starting the server on port $RUN_SERVER_PORT" &>"$SERVER_LOG"
-  SERVER_URL="http://$RUN_SERVER_ADDR:$RUN_SERVER_PORT"
-  SERVER_PORT="${SERVER_PORT:-$RUN_SERVER_PORT}"
-  export SERVER_DIR SERVER_URL SERVER_PORT
+  printf '%s\n' "Starting the server on port $RUN_SERVER_PORT" &>"$RUN_SERVER_LOG"
+  export RUN_SERVER_DIR RUN_SERVER_URL RUN_SERVER_PORT
   while [ $i -lt $MAX_NUMBER_OF_TRIES ]; do
-    if __port_used "$SERVER_PORT" || __lsof; then
+    if __port_used "$RUN_SERVER_PORT" || __lsof; then
       sleep 1
-      open_url "http://$RUN_SERVER_ADDR:$RUN_SERVER_PORT"
+      open_url "$RUN_SERVER_URL"
       BROWSER_PID="$!"
       trap 'kill -9 $BROWSER_PID &>/dev/null || exit 0' EXIT
       i=$MAX_NUMBER_OF_TRIES
@@ -142,92 +135,92 @@ __main__() {
     i=$((i + 1))
     sleep 5
   done &
-  printf_purple "serving files from $SERVER_DIR with pid: $$"
-  printf_blue "Log file: $SERVER_LOG"
+  printf_purple "serving files from $RUN_SERVER_CWD with pid: $$"
+  printf_blue "Log file: $RUN_SERVER_LOG"
   printf_yellow "Access from the network: http://$RUN_SERVER_ADDR:$RUN_SERVER_PORT"
-  open_filemanager "$SERVER_DIR"
+  open_filemanager "$RUN_SERVER_CWD"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__return_error() { printf '%s\n' "Failed to start server" &>>"$SERVER_LOG" && printf_exit 1 1 "Failed to start the server"; }
+__return_error() { printf '%s\n' "Failed to start server" &>>"$RUN_SERVER_LOG" && printf_exit 1 1 "Failed to start the server"; }
 __lsof() { lsof -i -nP | grep "${1:-$RUN_SERVER_PORT}" | grep -v 'grep' | grep -i "${prog:-python2}" | grep -q '^' && return 0 || return 1; }
-__netcat_serv() { while true; do nc -l "$RUN_SERVER_PORT" <.; done &>>"$SERVER_LOG" && echo netcat started &>>"$SERVER_LOG" || return 1; }
+__netcat_serv() { while true; do nc -l "$RUN_SERVER_PORT" <.; done &>>"$RUN_SERVER_LOG" && echo netcat started &>>"$RUN_SERVER_LOG" || return 1; }
 __port_used() { sleep 5 && sudo netstat -tauln 2>/dev/null | grep 'LISTEN' | grep ":${1:-$RUN_SERVER_PORT}" | grep -q '^' && return 0 || return 1; }
 __port_free() { sleep 5 && sudo netstat -tauln 2>/dev/null | grep 'LISTEN' | grep ":${1:-$RUN_SERVER_PORT}" | grep -q '^' && return 1 || return 0; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __go() {
   cmd_exists gohttpserver && cd "$RUN_SERVER_CWD" &&
-    gohttpserver --theme dark --port $RUN_SERVER_PORT --title="Dev Server" -r "." --xheaders --cors &>>"$SERVER_LOG" &&
-    echo gohttpserver started &>>"$SERVER_LOG" || return 1
+    gohttpserver --theme dark --port $RUN_SERVER_PORT --title="Dev Server" -r "." --xheaders --cors &>>"$RUN_SERVER_LOG" &&
+    echo gohttpserver started &>>"$RUN_SERVER_LOG" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __caddy() {
   cmd_exists caddy && cd "$RUN_SERVER_CWD" &&
-    caddy file-server -browse -listen :$RUN_SERVER_PORT -root "." -templates &>>"$SERVER_LOG" &&
-    echo caddy started &>>"$SERVER_LOG" || return 1
+    caddy file-server -browse -listen :$RUN_SERVER_PORT -root "." -templates &>>"$RUN_SERVER_LOG" &&
+    echo caddy started &>>"$RUN_SERVER_LOG" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __proxy() {
   cmd_exists caddy && cd "$RUN_SERVER_CWD" &&
-    caddy reverse-proxy -to 127.0.0.1:${port:-3000} -from :${other_port:-20000} &>>"$SERVER_LOG" &&
-    echo caddy started &>>"$SERVER_LOG" && other_port="${other_port:-20000}" || return 1
+    caddy reverse-proxy -to 127.0.0.1:${port:-3000} -from :${other_port:-20000} &>>"$RUN_SERVER_LOG" &&
+    echo caddy started &>>"$RUN_SERVER_LOG" && other_port="${other_port:-20000}" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __jekyll() {
   cmd_exists jekyll && cd "$RUN_SERVER_CWD" &&
-    jekyll serve -P $RUN_SERVER_PORT -l -H 0.0.0.0 &>>"$SERVER_LOG" &&
-    echo jekyll started &>>"$SERVER_LOG" || return 1
+    jekyll serve -P $RUN_SERVER_PORT -l -H 0.0.0.0 &>>"$RUN_SERVER_LOG" &&
+    echo jekyll started &>>"$RUN_SERVER_LOG" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __js_serv() {
   cmd_exists http-server && cd "$RUN_SERVER_CWD" &&
-    http-server -a 0.0.0.0 -p $RUN_SERVER_PORT &>>"$SERVER_LOG" &&
-    echo http-server started &>>"$SERVER_LOG" || return 1
+    http-server -a 0.0.0.0 -p $RUN_SERVER_PORT &>>"$RUN_SERVER_LOG" &&
+    echo http-server started &>>"$RUN_SERVER_LOG" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __php_serv() {
   cmd_exists php && cd "$RUN_SERVER_CWD" &&
-    php -S 0.0.0.0:$RUN_SERVER_PORT &>>"$SERVER_LOG" &&
-    echo php started &>>"$SERVER_LOG" || return 1
+    php -S 0.0.0.0:$RUN_SERVER_PORT &>>"$RUN_SERVER_LOG" &&
+    echo php started &>>"$RUN_SERVER_LOG" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __ruby_serv() {
   cmd_exists ruby && cd "$RUN_SERVER_CWD" &&
-    ruby -run -ehttpd -p $RUN_SERVER_PORT &>>"$SERVER_LOG" &&
-    echo ruby started &>>"$SERVER_LOG" || return 1
+    ruby -run -ehttpd -p $RUN_SERVER_PORT &>>"$RUN_SERVER_LOG" &&
+    echo ruby started &>>"$RUN_SERVER_LOG" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __rails_serv() {
   cmd_exists rails && cd "$RUN_SERVER_CWD" &&
-    server -p "$RUN_SERVER_PORT" &>>"$SERVER_LOG" &&
-    echo ruby started &>>"$SERVER_LOG" || return 1
+    server -p "$RUN_SERVER_PORT" &>>"$RUN_SERVER_LOG" &&
+    echo ruby started &>>"$RUN_SERVER_LOG" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __python3_serv() {
   cmd_exists python3 && cd "$RUN_SERVER_CWD" &&
-    python3 -m http.server --cgi --bind "$RUN_SERVER_ADDR" "$RUN_SERVER_PORT" &>>"$SERVER_LOG" &&
-    echo Py3 started &>>"$SERVER_LOG" || return 1
+    python3 -m http.server --cgi --bind "$RUN_SERVER_ADDR" "$RUN_SERVER_PORT" &>>"$RUN_SERVER_LOG" &&
+    echo Py3 started &>>"$RUN_SERVER_LOG" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __python2_serv() {
   cmd_exists python2 && cd "$RUN_SERVER_CWD" &&
-    python2 -m http.server --cgi --bind "$RUN_SERVER_ADDR" "$RUN_SERVER_PORT" &>>"$SERVER_LOG" &&
-    echo Py2 started &>>"$SERVER_LOG" || return 1
+    python2 -m http.server --cgi --bind "$RUN_SERVER_ADDR" "$RUN_SERVER_PORT" &>>"$RUN_SERVER_LOG" &&
+    echo Py2 started &>>"$RUN_SERVER_LOG" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __py_simple() {
   cmd_exists python && cd "$RUN_SERVER_CWD" &&
-    python -m SimpleHTTPServer "$RUN_SERVER_PORT" &>>"$SERVER_LOG" &&
-    echo "Py simple start" &>>"$SERVER_LOG" || return 1
+    python -m SimpleHTTPServer "$RUN_SERVER_PORT" &>>"$RUN_SERVER_LOG" &&
+    echo "Py simple start" &>>"$RUN_SERVER_LOG" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __default_srv() {
   cmd_exists python2 && cd "$RUN_SERVER_CWD" &&
-    python2 -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$RUN_SERVER_PORT" &>>"$SERVER_LOG" &&
+    python2 -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$RUN_SERVER_PORT" &>>"$RUN_SERVER_LOG" &&
     echo "Default has started" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __netcat_serv() {
-  cd "$RUN_SERVER_CWD" && while true; do nc -l "$RUN_SERVER_PORT" <.; done &>>"$SERVER_LOG" && echo netcat started &>>"$SERVER_LOG" || return 1
+  cd "$RUN_SERVER_CWD" && while true; do nc -l "$RUN_SERVER_PORT" <.; done &>>"$RUN_SERVER_LOG" && echo netcat started &>>"$RUN_SERVER_LOG" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __static() { __go || __caddy || __php_serv || __default_srv || return 1; }
@@ -279,8 +272,10 @@ __set_vars() {
   RUN_SERVER_HOST="$(__gethostname)"
   RUN_SERVER_PORT="$(__get_port "${1:-$RUN_SERVER_DEFAULT_PORT}")"
   RUN_SERVER_ADDR="$(__getlipaddr && echo "$CURRIP4" || echo '127.0.0.1')"
-  RUN_SERVER_CWD="$(realpath "${RUN_SERVER_CWD:-$PWD}" || echo "${RUN_SERVER_CWD:-$PWD}")"
-  export RUN_SERVER_HOST RUN_SERVER_PORT RUN_SERVER_ADDR RUN_SERVER_CWD
+  RUN_SERVER_CWD="$(realpath "${RUN_SERVER_CWD:-$PWD}" || dirname "${RUN_SERVER_CWD:-$PWD}/.")"
+  RUN_SERVER_LOG="${RUN_SERVER_LOG:-$RUN_SERVER_TEMP_DIR/run_server_$RUN_SERVER_PORT.log}"
+  RUN_SERVER_URL="${RUN_SERVER_URL:-http://$RUN_SERVER_ADDR:$RUN_SERVER_PORT}"
+  export RUN_SERVER_HOST RUN_SERVER_PORT RUN_SERVER_ADDR RUN_SERVER_CWD RUN_SERVER_URL
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 screen_config() {
@@ -472,8 +467,8 @@ while :; do
   --bg)
     shift 1
     echo "launching background process"
-    export SERVER_LOG="${RUN_SERVER_TEMP_DIR:-/tmp}/run_server_bg.log"
-    $APPNAME "$*" &>"$SERVER_LOG" &
+    export RUN_SERVER_LOG="${RUN_SERVER_TEMP_DIR:-/tmp}/run_server_bg.log"
+    $APPNAME "$*" &>"$RUN_SERVER_LOG" &
     exit $?
     ;;
   --filemanager)
@@ -483,7 +478,7 @@ while :; do
     ;;
   --browser)
     shift 1
-    open_url "${SERVER_URL:-http://localhost:${SERVER_PORT:-$RUN_SERVER_DEFAULT_PORT}}"
+    open_url "${RUN_SERVER_URL:-http://localhost:${SERVER_PORT:-$RUN_SERVER_DEFAULT_PORT}}"
     exit
     ;;
   --screen)
