🐛 FIXED: bin/run_server 🐛✔️

diff --git a/bin/run_server b/bin/run_server
--- a/bin/run_server
+++ b/bin/run_server
@@ -246,6 +246,7 @@ start_run_server() {
 __main__() {
   mainPid="$$"
   trap '__exit $mainPid' INT
+  RUN_SERVER_CONSOLE_CMD="start_run_server $1"
   RUN_SERVER_PORT="${RUN_SERVER_PORT:-$RUN_SERVER_DEFAULT_PORT}"
   MAX_NUMBER_OF_TRIES=${MAX_NUMBER_OF_TRIES:-20}
   RUN_SERVER_TEMP_DIR="${RUN_SERVER_TEMP_DIR:-/tmp}"
@@ -259,7 +260,7 @@ __main__() {
   export RUN_SERVER_OPEN_FM RUN_SERVER_OPEN_WEB RUN_SERVER_OPEN_EDITOR
   export RUN_SERVER_SCREEN_OPEN_WEB RUN_SERVER_SCREEN_OPEN_CMD RUN_SERVER_SCREEN_OPEN_FM RUN_SERVER_SCREEN_OPEN_EDITOR
   export RUN_SERVER_DIR RUN_SERVER_URL RUN_SERVER_PORT
-  exec_screen
+  [ -n "$SCREEN_SESSION" ] && exec_screen
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   $RUN_SERVER_CONSOLE_CMD
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -298,7 +299,15 @@ run_web_browser() {
   [[ -n "$SCREEN_SHELL" ]] && trap 'kill -9 $BROWSER_PID &>/dev/null || exit 0' INT
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__return_error() { printf '%s\n' "Failed to start server" &>>"$RUN_SERVER_LOG" && printf_exit 1 1 "Failed to start the server"; }
+__return_error() {
+  printf_newline '\n\n'
+  [ -n "$ERROR_MESSAGE" ] && printf_red "$ERROR_MESSAGE"
+  printf '%s\n' "Failed to start server" &>>"$RUN_SERVER_LOG"
+  printf_red "Failed to start the server"
+  printf_pause "$APPNAME will now be killed"
+  kill -9 "$MAIN_PID" &>/dev/null
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __lsof() { lsof -i -nP | grep "${1:-$RUN_SERVER_PORT}" | grep -v 'grep' | grep -i "${prog:-python2}" | grep -q '^' && return 0 || return 1; }
 __netcat_serv() { while true; do nc -l "$RUN_SERVER_PORT" <.; done &>>"$RUN_SERVER_LOG" && echo netcat started &>>"$RUN_SERVER_LOG" || return 1; }
 __port_used() { sleep .1 && sudo netstat -tauln 2>/dev/null | grep 'LISTEN' | grep ":${1:-$RUN_SERVER_PORT}" | grep -q '^' && return 0 || return 1; }
@@ -378,7 +387,13 @@ __default_srv() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __netcat_serv() {
-  cd "$RUN_SERVER_CWD" && while true; do nc -l "$RUN_SERVER_PORT" <.; done &>>"$RUN_SERVER_LOG" && echo netcat started &>>"$RUN_SERVER_LOG" || return 1
+  local file
+  cd "$RUN_SERVER_CWD" || return 1
+  while :; do
+    file="$([ -f "index.html" ] && echo index.html || find "." -mindepth 1 -printf '%P\n' 2>/dev/null | head -n1 || echo 'Running')"
+    cat "$file" | nc -l -p "$RUN_SERVER_PORT" &>>"$RUN_SERVER_LOG"
+  done &>>"$RUN_SERVER_LOG" &&
+    echo netcat started &>>"$RUN_SERVER_LOG" || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __static() { __go || __caddy || __php_serv || __default_srv || return 1; }
@@ -412,10 +427,9 @@ open_editor() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __prog_check() {
-  cmd_exists --error "${1:-$prog}" || {
+  cmd_exists "${1:-$prog}" || {
     clear
-    printf_newline '\n\n\n'
-    printf_red "Error: ${1:-$prog} is not installed\n"
+    export ERROR_MESSAGE="Error: ${1:-$prog} is not installed"
     return 1
   }
 }
@@ -512,7 +526,7 @@ else
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Show warn message if variables are missing
-
+MAIN_PID="$$"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set additional variables/Argument/Option settings
 SETARGS="$*"
