🗃️ Committing everything that changed 🗃️
bin/setupmgr

diff --git a/bin/setupmgr b/bin/setupmgr
--- a/bin/setupmgr
+++ b/bin/setupmgr
@@ -496,6 +496,8 @@ __download_extract() { __curl "$1" -o "$SETUPMGR_TEMP_DIR/$(basename -- "$1")" &
 # url tmpFile tmpFile moveTo
 __download_and_move() { __curl "$1" -o "$SETUPMGR_TEMP_DIR/$(basename -- "$2")" && mv -f "$SETUPMGR_TEMP_DIR/$(basename -- "$2")" "$3" && chmod +x "$3" && rm -Rf "$2" || return 1; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__check_for_vulkan_support() { __cmd_exists vulkaninfo && { vulkaninfo 2>&1 | grep '^ERROR ' | grep -v 'ERROR_INCOMPATIBLE_DRIVER' | head -n1 | grep '^' || return 2; } || return 1; }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # User defined functions
 _tar_extract() {
   local file="$1"
@@ -547,6 +549,7 @@ __extract() {
   fi
   [ -n "$tmp_bin_file" ] && tmp_bin_file="$tmpDir/$tmp_bin_file" || tmp_bin_file="$(ls "$tmpDir" | grep "$binFile$" || find "$tmpDir" -type f -iname "$binFile" 2>/dev/null)"
   if [ -n "$installDir" ]; then
+    tmp_bin_file="${tmp_bin_file//$tmpDir\//}"
     mkdir -p "$installDir"
     rsync -avhP "$tmpDir"/* "$installDir/" --delete >/dev/null 2>&1
     if [ -n "$tmp_bin_file" ]; then
@@ -1516,6 +1519,11 @@ __setup_zed() {
   local installDir="$ZED_INSTALL_DIR"
   local release_url="https://zed.dev/api/releases/stable/latest"
   tmp_bin_file="bin/zed"
+  __check_for_vulkan_support
+  if [ $? -eq 2 ]; then
+    printf_red "This system doesn't seem to have vulkan support"
+    return 1
+  fi
   case $arch in
   x86_64) download_url="$release_url/zed-linux-x86_64.tar.gz" ;;
   aarch64 | arm64) download_url="$release_url/zed-linux-aarch64.tar.gz" ;;
