🗃️ Committing everything that changed 🗃️
bin/setupmgr

diff --git a/bin/setupmgr b/bin/setupmgr
--- a/bin/setupmgr
+++ b/bin/setupmgr
@@ -786,21 +786,21 @@ __setup_lua() {
   fi
   if type luaver &>/dev/null; then
     printf_green "Installing lua version: $version"
-    # luaver -f install "$version" >>"$logFile" 2>>"$logFile.err" &&
-    # luaver set-default "$version" >>"$logFile" 2>>"$logFile.err" &&
-    # luaver -f install-luarocks "$rversion" >>"$logFile" 2>>"$logFile.err" &&
-    # luaver install-luajit "$jversion" >>"$logFile" 2>>"$logFile.err" &&
-    # luaver set-default "$version" >>"$logFile" 2>>"$logFile.err" || error="true"
-    # get_ver="$(luaver current | grep 'lua' | grep '^')"
-    # get_rver="$(luaver set-default-luarocks 3.8.0 2>&1 | tr ' ' '\n' | grep '[0-9].[0-9]' | grep '^')"
-    # if [ -n "$get_ver" ] && [ -n "$get_rver" ] && [ -z "$error" ]; then
-    # printf_green "Finished installing lua! $get_ver"
-    # [ -f "$logFile" ] && rm -Rf "$logFile"
-    # [ -f "$logFile.err" ] && rm -Rf "$logFile.err"
-    # else
-    # printf_exit "Installation of lua has failed: log saved to $logFile.err" >&2
-    # exitCode=1
-    # fi
+    yes | luaver install "$version" >>"$logFile" 2>>"$logFile.err" &&
+      luaver set-default "$version" >>"$logFile" 2>>"$logFile.err" &&
+      yes | luaver install-luarocks "$rversion" >>"$logFile" 2>>"$logFile.err" &&
+      luaver install-luajit "$jversion" >>"$logFile" 2>>"$logFile.err" &&
+      luaver set-default "$version" >>"$logFile" 2>>"$logFile.err" || error="true"
+    get_ver="$(luaver current | grep 'lua' | grep '^')"
+    get_rver="$(luaver set-default-luarocks 3.8.0 2>&1 | tr ' ' '\n' | grep '[0-9].[0-9]' | grep '^')"
+    if [ -n "$get_ver" ] && [ -n "$get_rver" ] && [ -z "$error" ]; then
+      printf_green "Finished installing lua! $get_ver"
+      [ -f "$logFile" ] && rm -Rf "$logFile"
+      [ -f "$logFile.err" ] && rm -Rf "$logFile.err"
+    else
+      printf_exit "Installation of lua has failed: log saved to $logFile.err" >&2
+      exitCode=1
+    fi
   else
     printf_red "Failed to setup luaver"
   fi
