🗃 Modified: bin/shortenurl  🗃

diff --git a/bin/shortenurl b/bin/shortenurl
--- a/bin/shortenurl
+++ b/bin/shortenurl
@@ -57,11 +57,29 @@ __gen_config() {
     cp -Rf "$SHORTENURL_CONFIG_DIR/$SHORTENURL_CONFIG_FILE" "$SHORTENURL_CONFIG_BACKUP_DIR/$SHORTENURL_CONFIG_FILE.$$"
   cat <<EOF >"$SHORTENURL_CONFIG_DIR/$SHORTENURL_CONFIG_FILE"
 # Settings for shortenurl
-SHORTENURL_URL="${SHORTENURL_URL:-https://is.gd/create.php?logstats=1&format=simple&url=}"
+# private, gd_is, tny_im, yourls, github - defaults to yourls
+SHORTENURL_DEFAULT="${SHORTENURL_DEFAULT:-yourls}"
 
-# See https://github.com/casjay-coffee/casjay.link
-SHORTENURL_URL_CUSTOM="${SHORTENURL_URL_CUSTOM:-https://casjay.link}"
-SHORTENURL_URL_CUSTOM_API="${SHORTENURL_URL_CUSTOM_API:-https://casjay.link/url}"
+# private: See https://github.com/casjay-coffee/casjay.link for self hosted option
+SHORTENURL_URL_PRIVATE="${SHORTENURL_URL_PRIVATE:-https://casjay.link}"
+SHORTENURL_URL_PRIVATE_API="${SHORTENURL_URL_PRIVATE_API:-$SHORTENURL_URL_PRIVATE/url}"
+
+# yourls: See http://yourls.org for self hosted option
+SHORTENURL_URL_YOURLS="${SHORTENURL_URL_YOURLS:-https://t25b.xyz}"
+SHORTENURL_URL_YOURLS_API="${SHORTENURL_URL_YOURLS_API:-$SHORTENURL_URL_YOURLS/yourls-api.php}"
+SHORTENURL_URL_YOURLS_API_KEY="${SHORTENURL_URL_YOURLS_API_KEY}"
+
+# gd_is: See https://is.gd
+SHORTENURL_URL_IS="${SHORTENURL_URL_IS:-https://is.gd}"
+SHORTENURL_URL_IS_API="${SHORTENURL_URL_IS_API:-$SHORTENURL_URL_IS/create.php?logstats=1&format=simple&url=}"
+
+# yourls: See http://tny.im
+SHORTENURL_URL_TNY="${SHORTENURL_URL_YOURLS:-https://t25b.xyz}"
+SHORTENURL_URL_TNY_API="${SHORTENURL_URL_YOURLS_API:-$SHORTENURL_URL_YOURLS/yourls-api.php}"
+SHORTENURL_URL_TNY_API_KEY="${SHORTENURL_URL_YOURLS_API_KEY}"
+
+# github: See https://git.io
+SHORTENURL_URL_GITHUB="${SHORTENURL_URL_GITHUB:-https://git.io}"
 
 # Notification settings
 SHORTENURL_GOOD_MESSAGE="${SHORTENURL_GOOD_MESSAGE:-Everything Went OK}"
@@ -94,35 +112,88 @@ EOF
 __curl() { curl -q --connect-timeout 3 --retry 0 --fail "$*" 2>/dev/null || return 1; }
 __urlencode() { perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "${1:-$URL}"; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__default_url() {
-  local host="$1"
-  local encoded="$(__urlencode "$1" | sed 's| ||g')"
-  local results="$(__curl "$SHORTENURL_URL$encoded" | grep '^')"
-  [[ -n "$result" ]] && echo "$results" && exitCode=0 ||
-    { echo "Something seems to have gone creating the shortened url" && echo "$SHORTENURL_URL$encoded" && exitCode=1; }
-  return ${exitCode:-$?}
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__custom_url() {
+__private_url() {
   local host="$1"
   local slug="${2:-$(tr -dc 'a-zA-Z' </dev/urandom | head -c 6)}"
   echo "$host" | grep -Eq 'http|https' || { echo "Please enter a valid URL" && return 1; }
-  results="$(curl -q -LSs --header "Content-Type: application/json" --request POST --data '{"url":"'$host'","slug":"'$slug'"}' "$SHORTENURL_URL_CUSTOM_API")"
-  { echo echo "$results" | grep -q 'Too many requests' && echo "You have been rate limited. Please try again later. 🍔" && exitCode=1; }
-  { echo "$results" | grep -q 'Slug in use.' && echo "The slug $2 is in use. 🍔" && exitCode=1; } ||
-    { echo "$results" | grep -q 'Error:' && echo "An error has occured. 🍔" && exitCode=1; } ||
-    { echo "$results" | jq -r '.url' | sed 's|"||g' | grep -q '^' && echo "$SHORTENURL_URL_CUSTOM/$slug points to $host" && exitCode=0; } ||
-    exitCode=1
+  results="$(curl -q -LSs --header "Content-Type: application/json" --request POST --data '{"url":"'$host'","slug":"'$slug'"}' "$SHORTENURL_URL_PRIVATE_API")"
+  if echo "$results" | grep -q 'Too many requests'; then
+    result="$(echo "You have been rate limited. Please try again later. 🍔")"
+    exitCodeTmp=1
+  elif echo "$results" | grep -q 'Slug in use.'; then
+    result="$(echo "The slug $2 is in use. 🍔")"
+    exitCodeTmp=1
+  elif echo "$results" | grep -q 'Error:'; then
+    result="$(echo "An error has occured. 🍔")"
+    exitCodeTmp=1
+  elif echo "$results" | jq -r '.url' | sed 's|"||g' | grep -q '^'; then
+    result="$(echo "$SHORTENURL_URL_PRIVATE/$slug points to $host" && exitCodeTmp=0)"
+  else
+    result="$(echo An error has occurred)"
+    exitCodeTmp=1
+  fi
+  exitCode=${exitCodeTmp:-$?}
   return ${exitCode:-$?}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__guthub_url() {
+__gd_is_url() {
+  local host="$1"
+  local encoded="$(__urlencode "$1" | sed 's| ||g')"
+  local results="$(__curl "$SHORTENURL_URL_IS_API$encoded" | grep '^')"
+  if [[ -n "$results" ]]; then
+    result="$(echo "$results")"
+    exitCode=0
+  else
+    result="$(echo "Something seems to have gone creating the shortened url" && echo "$SHORTENURL_URL_IS_API$encoded")"
+    exitCodeTmp=1
+  fi
+  exitCode=${exitCodeTmp:-$?}
+  return ${exitCode:-$?}
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__yourls_url() {
+  local host="$1"
+  local slug="${2:-$(tr -dc 'a-zA-Z' </dev/urandom | head -c 6)}"
+  results="$(wget -q -O - "$SHORTENURL_URL_YOURLS_API?action=shorturl\&format=simple\&url=$host\&keyword=$slug")"
+  if [[ -n "$result" ]]; then
+    result="$(echo "$results")"
+    exitCodeTmp=0
+  else
+    result="$(echo "Something seems to have gone")"
+    exitCodeTmp=1
+  fi
+  exitCode=${exitCodeTmp:-$?}
+  return ${exitCode:-$?}
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__tny_url() {
+  local host="$1"
+  local slug="${2:-$(tr -dc 'a-zA-Z' </dev/urandom | head -c 6)}"
+  results="$(wget -q -O - "$SHORTENURL_URL_TNY_API?action=shorturl\&format=simple\&url=$host\&keyword=$slug")"
+  if [[ -n "$result" ]]; then
+    result="$(echo "$results")"
+    exitCodeTmp=0
+  else
+    result="$(echo "Something seems to have gone")"
+    exitCodeTmp=1
+  fi
+  exitCode=${exitCodeTmp:-$?}
+  return ${exitCode:-$?}
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__github_url() {
   local host="$1"
   local slug="${2:-$(tr -dc 'a-zA-Z' </dev/urandom | head -c 6)}"
   echo "$host" | grep -Eq 'github' || { echo "Please enter a valid github URL" && return 1; }
-  results="$(curl -q -LSsi https://git.io -F "url=$host" 2>/dev/null | grep 'Location: ')"
-  [[ -n "$result" ]] && echo "$results" && exitCode=0 ||
-    { echo "Something seems to have gone creating the github url" && exitCode=1; }
+  results="$(curl -q -LSsi "$SHORTENURL_URL_GITHUB" -F "url=$short_url" -F "code=$slug" 2>/dev/null | grep 'Location: ')"
+  if [[ -n "$result" ]]; then
+    result="$(echo "$results")"
+    exitCodeTmp=0
+  else
+    result="$(echo "Something seems to have gone creating the github url")"
+    exitCodeTmp=1
+  fi
+  exitCode=${exitCodeTmp:-$?}
   return ${exitCode:-$?}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -153,9 +224,18 @@ SHORTENURL_NOTIFY_CLIENT_NAME="${NOTIFY_CLIENT_NAME:-$APPNAME}"
 SHORTENURL_NOTIFY_CLIENT_ICON="${NOTIFY_CLIENT_ICON:-$SHORTENURL_NOTIFY_CLIENT_ICON}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Application overrides
-SHORTENURL_URL="${SHORTENURL_URL:-https://is.gd/create.php?logstats=1&format=simple&url=}"
-SHORTENURL_URL_CUSTOM="${SHORTENURL_URL_CUSTOM:-https://casjay.link}"
-SHORTENURL_URL_CUSTOM_API="${SHORTENURL_URL_CUSTOM_API:-https://casjay.link/url}"
+SHORTENURL_DEFAULT="${SHORTENURL_DEFAULT:-yourls}"
+SHORTENURL_URL_PRIVATE="${SHORTENURL_URL_PRIVATE:-https://casjay.link}"
+SHORTENURL_URL_PRIVATE_API="${SHORTENURL_URL_PRIVATE_API:-$SHORTENURL_URL_PRIVATE/url}"
+SHORTENURL_URL_YOURLS="${SHORTENURL_URL_YOURLS:-https://t25b.xyz}"
+SHORTENURL_URL_YOURLS_API="${SHORTENURL_URL_YOURLS_API:-$SHORTENURL_URL_YOURLS/yourls-api.php}"
+SHORTENURL_URL_YOURLS_API_KEY="${SHORTENURL_URL_YOURLS_API_KEY:-}"
+SHORTENURL_URL_IS="${SHORTENURL_URL_IS:-https://is.gd}"
+SHORTENURL_URL_IS_API="${SHORTENURL_URL_IS_API:-$SHORTENURL_URL_IS/create.php?logstats=1&format=simple&url=}"
+SHORTENURL_URL_TNY="${SHORTENURL_URL_YOURLS:-https://t25b.xyz}"
+SHORTENURL_URL_TNY_API="${SHORTENURL_URL_YOURLS_API:-$SHORTENURL_URL_YOURLS/yourls-api.php}"
+SHORTENURL_URL_TNY_API_KEY="${SHORTENURL_URL_YOURLS_API_KEY}"
+SHORTENURL_URL_GITHUB="${SHORTENURL_URL_GITHUB:-https://git.io}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Import config
 [ -f "$SHORTENURL_CONFIG_DIR/$SHORTENURL_CONFIG_FILE" ] && . "$SHORTENURL_CONFIG_DIR/$SHORTENURL_CONFIG_FILE"
@@ -238,29 +318,63 @@ cmd_exists --error --ask bash || exit 1 # exit 1 if not found
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # begin main app
 case "$1" in
-github)
-  shift 1
-  [ -z "$1" ] && seturl=$(printclip) || seturl="$1"
-  result="$(__github_url $seturl $2)"
-  echo "$result" | printf_readline $SHORTENURL_OUTPUT_COLOR
-  echo "$result" | putclip
-  exit $?
-  ;;
-
 private)
   shift 1
-  [ -z "$1" ] && seturl=$(printclip) || seturl="$1"
-  result="$(__custom_url $seturl $2)"
+  [ -p /dev/stdin ] && host="$(</dev/stdin)"
+  [ -z "$host" ] && seturl=$(printclip) || seturl="${host:-$1}"
+  __private_url $seturl $2
   echo "$result" | printf_readline $SHORTENURL_OUTPUT_COLOR
   echo "$result" | putclip
-  exit $?
+  exit ${exitCode:-$?}
+  ;;
+
+github)
+  shift 1
+  [ -p /dev/stdin ] && host="$(</dev/stdin)"
+  [ -z "$host" ] && seturl=$(printclip) || seturl="${host:-$1}"
+  __github_url $seturl $2
+  echo "$result" | printf_readline $SHORTENURL_OUTPUT_COLOR
+  echo "$result" | putclip
+  exit ${exitCode:-$?}
+  ;;
+
+gd_is)
+  shift 1
+  [ -p /dev/stdin ] && host="$(</dev/stdin)"
+  [ -z "$host" ] && seturl=$(printclip) || seturl="${host:-$1}"
+  __gd_is_url $seturl $2
+  echo "$result" | printf_readline $SHORTENURL_OUTPUT_COLOR
+  echo "$result" | putclip
+  exit ${exitCode:-$?}
+  ;;
+
+tny_im)
+  shift 1
+  [ -p /dev/stdin ] && host="$(</dev/stdin)"
+  [ -z "$host" ] && seturl=$(printclip) || seturl="${host:-$1}"
+  __tny_url $seturl $2
+  echo "$result" | printf_readline $SHORTENURL_OUTPUT_COLOR
+  echo "$result" | putclip
+  exit ${exitCode:-$?}
+  ;;
+
+yourls)
+  shift 1
+  [ -p /dev/stdin ] && host="$(</dev/stdin)"
+  [ -z "$host" ] && seturl=$(printclip) || seturl="${host:-$1}"
+  __yourls_url $seturl $2
+  echo "$result" | printf_readline $SHORTENURL_OUTPUT_COLOR
+  echo "$result" | putclip
+  exit ${exitCode:-$?}
   ;;
 
 *)
-  [ -z "$1" ] && seturl=$(printclip) || seturl="$1"
-  result="$(__default_url $seturl)"
+  [ -p /dev/stdin ] && host="$(</dev/stdin)"
+  [ -z "$host" ] && seturl=$(printclip) || seturl="${host:-$1}"
+  __yourls_url $seturl $2
   echo "$result" | printf_readline $SHORTENURL_OUTPUT_COLOR
   echo "$result" | putclip
+  exit ${exitCode:-$?}
   ;;
 esac
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
