🐛 FIXED: bin/tor-site 🐛

diff --git a/bin/tor-site b/bin/tor-site
--- a/bin/tor-site
+++ b/bin/tor-site
@@ -103,10 +103,10 @@ __server_status() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __run_server() {
+  __cd "$TOR_SITE_CWD"
   { python3 -m http.server --cgi --bind 127.0.0.1 "$TOR_SITE_PORT" &>/dev/null ||
     python2 -m http.server --cgi --bind 127.0.0.1 "$TOR_SITE_PORT" &>/dev/null ||
     python -m SimpleHTTPServer "$TOR_SITE_PORT" &>/dev/null || return 1; } &
-  disown
   sleep 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -132,8 +132,6 @@ __start_py_server() {
 __systemd() {
   mkdir -p "$HOME/Public/tor/$TOR_SITE_PORT" &>/dev/null
   cat <<EOF
-# tor hidden site
-
 [Unit]
 Description=Tor Hidden Site localhost:$TOR_SITE_PORT
 Before=tor.service
@@ -145,10 +143,10 @@ User=$USER
 Environment=TOR_SITE_PORT="$TOR_SITE_PORT"
 Environment=TOR_SITE_CWD="$HOME/Public/tor/$TOR_SITE_PORT"
 WorkingDirectory=$HOME/Public/tor/$TOR_SITE_PORT
-ExecStart=$SRC_DIR/$APPNAME run $TOR_SITE_PORT $HOME/Public/tor/$TOR_SITE_PORT
-ExecStop=$SRC_DIR/$APPNAME stop $TOR_SITE_PORT
+ExecStart=/bin/bash -c "$SRC_DIR/$APPNAME systemd run $TOR_SITE_PORT $HOME/Public/tor/$TOR_SITE_PORT"
+ExecStop=/bin/bash -c "$SRC_DIR/$APPNAME stop $TOR_SITE_PORT"
 Restart=always
-RestartSec=10
+#RestartSec=5
 #StartLimitBurst=10
 #StartLimitInterval=60s
 
@@ -308,6 +306,21 @@ systemd)
     fi
     exit $?
     ;;
+
+  run)
+    shift 1
+    TOR_SITE_PORT="${1:-$TOR_SITE_PORT}"
+    TOR_SITE_CWD="${2:-$TOR_SITE_CWD}"
+    if __run_server "$TOR_SITE_CWD" "$TOR_SITE_PORT"; then
+      echo "Tor Server is running"
+      exitCode=0
+    else
+      echo "Tor Server failed to start"
+      exitCode=1
+    fi
+    exit ${exitCode:-$?}
+    ;;
+
   *)
     if sudo -n true &>/dev/null; then
       printf_green "Creating systemd service"
@@ -324,22 +337,6 @@ systemd)
     fi
     ;;
   esac
-  ;;
-
-run)
-  shift 1
-  TOR_SITE_PORT="${1:-$TOR_SITE_PORT}"
-  TOR_SITE_CWD="${2:-$TOR_SITE_CWD}"
-  [ -d "$TOR_SITE_CWD" ] && __cd "$TOR_SITE_CWD" || exit 1
-  if __run_server "$TOR_SITE_CWD" "$TOR_SITE_PORT"; then
-    systemd-notify READY=1
-    echo "Tor Server is running"
-    exitCode=0
-  else
-    echo "Tor Server failed to start"
-    exitCode=1
-  fi
-  exit ${exitCode:-$?}
   ;;
 
 *)
