🗃 Modified: bin/virt-display  🗃

diff --git a/bin/virt-display b/bin/virt-display
--- a/bin/virt-display
+++ b/bin/virt-display
@@ -81,8 +81,9 @@ EOF
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Additional functions
 __virsh() { sudo virsh "$@" || return 1; }
-__list_running() { sudo virsh list --all | grep -E 'running|shut off' | grep '^' || return 1; }
 __list_ips() { __virsh net-dhcp-leases default || return 1; }
+__list_running() { sudo virsh list --all | grep -E 'running|shut off' | grep '^' || return 1; }
+__list_vms() { __virsh list --all | grep -Ev 'Id.*.Name.*.State|----|^$' | awk '{print $2}' | grep '^' || return 1; }
 __get_pid() { sudo ps aux 2>/dev/null | grep "qemu" | grep "$1" | grep -v 'grep' | awk '{print $2}' | grep '^' || return 1; }
 __get_port() { sudo netstat -apn 2>/dev/null | grep "$(__get_pid "$1")" | grep 'tcp' | awk '{print $4}' | grep '^' || return 1; }
 __viewer() { __local_viewer "$1" || __remote_viewer "$1" || return 1; }
@@ -163,14 +164,15 @@ __restore() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __start() {
   domain="$1"
-  start="$(__virsh start --domain $domain 2>&1 | grep -qi ' started' || echo 'Failed')"
+  start="$(__virsh start --domain $domain 2>&1 | grep -qiE 'error:|failed:' && echo 'Failed')"
   [[ -z "$start" ]] && printf_green "$domain has been started" || printf_return "Failed to start $domain"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__no_args() {
+__check_vm_args() {
   if [[ $# -eq 0 ]]; then
     printf_exit "Please provide the vm name"
   else
+    __list_vms | grep -q "$1" || printf_exit "Can not find the vm named $1"
     return 0
   fi
 }
@@ -308,30 +310,30 @@ list)
 
 start)
   shift 1
-  __no_args $1
+  __check_vm_args $1
   __start "$@"
   ;;
 
 ssh)
   shift 1
-  __no_args $1
+  __check_vm_args $1
   __ssh_viewer "$1" "$2" "$3"
   ;;
 
 restore)
   shift 1
-  __no_args $1
+  __check_vm_args $1
   __restore "$@"
   ;;
 
 create)
   shift 1
-  __no_args "$1"
+  __check_vm_args "$1"
   __snapshot "$@"
   ;;
 
 *)
-  __no_args $1
+  __check_vm_args $1
   __list_running | grep -q "$1" && __viewer "$1"
   ;;
 esac
