🗃 Modified: bin/virt-display completions/_virt-display_completions  🗃

diff --git a/bin/virt-display b/bin/virt-display
--- a/bin/virt-display
+++ b/bin/virt-display
@@ -141,7 +141,7 @@ __remote_viewer() {
 __snapshot() {
   domain="$1"
   snapshot="${2:-Default}"
-  destroy="$(__virsh destroy --domain "$domain" &>/dev/null &>/dev/null)"
+  destroy="$(__virsh destroy --domain "$domain" &>/dev/null)"
   snapshot="$(__virsh snapshot-create-as "${snapshot:-Default}" --domain "$domain" &>/dev/null)"
   created="$(snapshot-list --domain $domain 2>&1 | grep -q "$snapshot" || echo 'Failed')"
   [[ -z "$created" ]] || printf_return "Failed to create snapshot $snapshot"
@@ -159,6 +159,16 @@ __restore() {
   start="$(__virsh start --domain $domain 2>&1 | grep -qi ' started' || echo 'Failed')"
   [[ -z "$start" ]] && printf_green "Started $domain" || printf_return "Failed to start $domain"
   return $?
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__start() {
+  domain="$1"
+  start="$(__virsh start --domain $domain 2>&1 | grep -qi ' started' || echo 'Failed')"
+  [[ -z "$start" ]] && printf_green "$domain has been started" || printf_return "Failed to start $domain"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__no_args() {
+  [[ $# = 0 ]] && printf_exit "Please provide the vm name"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Default variables
@@ -291,22 +301,32 @@ list)
   fi
   ;;
 
+start)
+  shift 1
+  __no_args "$1"
+  __start "$@"
+  ;;
+
 ssh)
   shift 1
+  __no_args "$1"
   __ssh_viewer "$1" "$2" "$3"
   ;;
 
 restore)
   shift 1
+  __no_args "$1"
   __restore "$@"
   ;;
 
 create)
   shift 1
+  __no_args "$1"
   __snapshot "$@"
   ;;
 
 *)
+  __no_args "$1"
   __list_running | grep -q "$1" && __viewer "$1"
   ;;
 esac
