🗃️ Committing everything that changed 🗃️

diff --git a/bin/weather b/bin/weather
--- a/bin/weather
+++ b/bin/weather
@@ -373,6 +373,24 @@ __wttrimage() {
   fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__scripts() {
+  local mtime="120"
+  local cache_file="$WEATHER_CACHE_DIR/weather.txt"
+  [ -s "$cache_file" ] || rm -Rf "$cache_file"
+  [ -f "$cache_file" ] && find "$cache_file" -maxdepth 1 -daystart -maxdepth 1 -mmin +${mtime} -type f -name -exec rm -f {} \; 2>/dev/null && exitCode=1 || exitCode=0
+  if [ "$exitCode" -ne 0 ] || [ ! -s "$cache_file" ]; then
+    curl -q -LSsf -m 1 "https://wttr.in/?format=3" 2>/dev/null | grep -viE ^'Unknown location;' | awk '{print $1,$(NF-1),$NF}' | sed 's|, |: |g' | grep '^' >"$cache_file" || rm -Rf "$cache_file"
+  fi
+  if [ -f "$cache_file" ]; then
+    grep -s '^' "$cache_file"
+    exitCode="$?"
+  else
+    echo "Error"
+    exitCode=${exitCode:-1}
+  fi
+  return ${exitCode:-$?}
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # User defined variables/import external variables
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -631,6 +649,11 @@ simple)
   else
     __wttrsimple "$@"
   fi
+  ;;
+script)
+  shift 1
+  __scripts
+  exit $?
   ;;
 :help | help)
   shift 1
