🗃️ Committing everything that changed 🗃️
bin/web-notify

diff --git a/bin/web-notify b/bin/web-notify
--- a/bin/web-notify
+++ b/bin/web-notify
@@ -323,6 +323,12 @@ format_file_as_JSON_string() {
     tr -d "\n"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__mailx() {
+  title="Notification from $HOSTNAME"
+  echo "$1" | mailx -s "$title" -r "$APPNAME <no-reply@$HOSTNAME>" root@$HOSTNAME >>"$WEB_NOTIFY_LOG_ERROR_FILE" 2>&1 || exitCode=1
+  [ "$exitCode" = 0 ] && __append_log "Message was sent via email" || __append_log "Failed to send message via email"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __pushbullet() {
   local message="$*"
   local exitCode=0
@@ -500,7 +506,7 @@ SHORTOPTS+=""
 LONGOPTS="completions:,config,debug,dir:,help,options,raw,version,silent,force,no-*,"
 LONGOPTS+="discord-token:,slack-token:,telegram-token:,telegram-channel:,pushover-token:,pushbullet-token:"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-ARRAY="discord slack telegram pushover pushbullet"
+ARRAY="email discord slack telegram pushover pushbullet"
 ARRAY+=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 LIST=""
@@ -691,6 +697,18 @@ printf '%s\n' "# Start Log $(date)" >>"$WEB_NOTIFY_LOG_ERROR_FILE"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # begin main app
 case "$1" in
+email)
+  if [ -p "/dev/stdin" ]; then
+    SEND="$(<"/dev/stdin")"
+  elif [ -f "$1" ]; then
+    SEND="$(<"$1")"
+  else
+    SEND="$*"
+  fi
+  __mailx "$SEND"
+  __end_log $?
+  exit
+  ;;
 discord)
   shift 1
   if [ -p "/dev/stdin" ]; then
