🗃️ Committing everything that changed 🗃️
bin/web-notify

diff --git a/bin/web-notify b/bin/web-notify
--- a/bin/web-notify
+++ b/bin/web-notify
@@ -303,53 +303,61 @@ format_file_as_JSON_string() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __pushbullet() {
   local message="$*"
+  local exitCode=0
   local msg_content="$message"
-  local key="${WEB_NOTIFY_PUSHOVER_API_ID:-}"
-  local token="${PUSHBULLET_ACCESS_TOKEN:-}"
-  local api_url="$PUSHBULLET_API_HOST"
+  local token="${WEB_NOTIFY_PUSHBULLET_ACCESS_TOKEN:-}"
+  local api_url="$WEB_NOTIFY_PUSHBULLET_API_HOST"
   [ "$1" = "help" ] && printf_help "Usage: $APPNAME pushbullet [file/text]"
-  [ -n "$token" ] || { printf_red "token is not set PUSHBULLET_ACCESS_TOKEN" && return 0; }
+  [ -n "$token" ] || { printf_red "token is not set PUSHBULLET_ACCESS_TOKEN" && return 1; }
   title="notify"
   body="$(echo "$message" | __format_file_as_JSON_string)"
   printf_cyan "Attempting to send to pushbullet"
-  curl -q -LSsf -u ${token}: --header 'Content-Type: application/json' -X POST "$api_url" -d "{\"type\": \"note\", \"title\": \"$title\", \"body\": \"$body\"}" 2>/dev/null | grep -q active
-  return $?
+  curl -q -LSsf -u ${token}: --header 'Content-Type: application/json' -X POST "$api_url" -d "{\"type\": \"note\", \"title\": \"$title\", \"body\": \"$body\"}" >>"$WEB_NOTIFY_LOG_ERROR_FILE" 2>&1 || exitCode=1
+  [ "$exitCode" = 0 ] && __append_log "Message was sent to pushbullet" || __append_log "Failed to send message to pushbullet"
+  return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __pushover() {
   local message="$*"
+  local exitCode=0
   local msg_content=\"$message\"
-  local key="${WEB_NOTIFY_PUSHOVER_API_ID:-}"
-  local token="${WEB_NOTIFY_PUSHOVER_API_KEY:-}"
+  local token="${WEB_NOTIFY_PUSHOVER_API_ID:-}"
+  local key="${WEB_NOTIFY_PUSHOVER_API_KEY:-}"
   [ "$1" = "help" ] && printf_help "Usage: $APPNAME pushover [file/text]"
-  [ -n "$token" ] || { printf_red "token is not set WEB_NOTIFY_PUSHOVER_API_ID" && return 0; }
+  [ -n "$key" ] || { printf_red "token is not set WEB_NOTIFY_PUSHOVER_API_ID" && return 1; }
+  [ -n "$token" ] || { printf_red "token is not set WEB_NOTIFY_PUSHOVER_API_KEY" && return 1; }
   printf_cyan "Attempting to send to pushover"
-  printf '%b\n' "$msg_content" | curl -q -LSsf -s -X POST --form-string "token=$token" --form-string "user=$key" --data-urlencode message@- https://api.pushover.net/1/messages.json
-  return $?
+  printf '%b\n' "$msg_content" | curl -q -LSsf -s -X POST -d "token=$token" -d "user=$key" --data-urlencode message@- https://api.pushover.net/1/messages.json >>"$WEB_NOTIFY_LOG_ERROR_FILE" 2>&1 || exitCode=1
+  [ "$exitCode" = 0 ] && __append_log "Message was sent to pushover" || __append_log "Failed to send message to pushover"
+  return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __telegram() {
   local message="$*"
+  local exitCode=0
   local msg_content="$message"
   local token="${WEB_NOTIFY_TELEGRAM_API:-}"
   local channel="-${WEB_NOTIFY_TELEGRAM_CHANNEL:-}"
   [ "$1" = "help" ] && printf_help "Usage: $APPNAME telegram [file/text]"
-  [ -n "$token" ] || { printf_red "token is not set WEB_NOTIFY_TELEGRAM_API" && return 0; }
-  [ -n "$channel" ] || { printf_red "channel is not set WEB_NOTIFY_TELEGRAM_CHANNEL: see https://api.telegram.org/bot${token}/getUpdates" && return 0; }
+  [ -n "$token" ] || { printf_red "token is not set WEB_NOTIFY_TELEGRAM_API" && return 1; }
+  [ -n "$channel" ] || { printf_red "channel is not set WEB_NOTIFY_TELEGRAM_CHANNEL: see https://api.telegram.org/bot${token}/getUpdates" && return 1; }
   printf_cyan "Attempting to send to telegram"
-  printf '%b\n' "$msg_content" | curl -q -LSsf -s -X POST "https://api.telegram.org/bot${token}/sendMessage" -d chat_id="$channel" --data-urlencode text@- 2>>"$WEB_NOTIFY_LOG_ERROR_FILE" | jq -rc '.ok' 2>/dev/null | grep -q 'true' || exitCode=1
-  return $?
+  printf '%b\n' "$msg_content" | curl -q -LSsf -s -X POST "https://api.telegram.org/bot${token}/sendMessage" -d chat_id="$channel" --data-urlencode text@- >>"$WEB_NOTIFY_LOG_ERROR_FILE" 2>&1 | jq -rc '.ok' 2>/dev/null | grep -q 'true' || exitCode=1
+  [ "$exitCode" = 0 ] && __append_log "Message was sent to telegram" || __append_log "Failed to send message to telegram"
+  return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __discord() {
   local message="$*"
+  local exitCode=0
   local msg_content="$(printf '%b\n' "$message" | format_file_as_JSON_string)"
   local url="https://discord.com/api/webhooks/$WEB_NOTIFY_DISCORD_WEBHOOK"
   [ "$1" = "help" ] && printf_help "Usage: $APPNAME discord [file/text]"
-  [ -n "$url" ] || { printf_red "url is not set WEB_NOTIFY_DISCORD_WEBHOOK: see https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks" && return 0; }
+  [ -n "$url" ] || { printf_red "url is not set WEB_NOTIFY_DISCORD_WEBHOOK: see https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks" && return 1; }
   printf_cyan "Attempting to send to discord"
-  curl -q -LSsf -X POST -H "Content-Type: application/json" -d "{\"content\": \"$msg_content\"}" $url 2>>"$WEB_NOTIFY_LOG_ERROR_FILE" >/dev/null || exitCode=1
-  return $?
+  curl -q -LSsf -X POST -H "Content-Type: application/json" -d "{\"content\": \"$msg_content\"}" $url >>"$WEB_NOTIFY_LOG_ERROR_FILE" 2>&1 || exitCode=1
+  [ "$exitCode" = 0 ] && __append_log "Message was sent to discord" || __append_log "Failed to send message to discord"
+  return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __slack() {
@@ -358,15 +366,18 @@ __slack() {
   local msg_content="$(printf '%b\n' "$message" | format_file_as_JSON_string)"
   local url="$WEB_NOTIFY_SLACK_WEBHOOK"
   [ "$1" = "help" ] && printf_help "Usage: $APPNAME slack [file/text]"
-  [ -n "$url" ] || { printf_red "channel is not set WEB_NOTIFY_SLACK_WEBHOOK" && return 0; }
+  [ -n "$url" ] || { printf_red "channel is not set WEB_NOTIFY_SLACK_WEBHOOK" && return 1; }
   printf_cyan "Attempting to send to slack"
-  curl -q -LSsf -X POST -H 'Content-type: application/json' --data '{"text":'"$msg_content"'}' "$url" 2>>"$WEB_NOTIFY_LOG_ERROR_FILE" >/dev/null || exitCode=1
+  curl -q -LSsf -X POST -H 'Content-type: application/json' --data '{"text":'"$msg_content"'}' "$url" >>"$WEB_NOTIFY_LOG_ERROR_FILE" 2>&1 || exitCode=1
+  [ "$exitCode" = 0 ] && __append_log "Message was sent to slack" || __append_log "Failed to send message to slack"
   return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__append_log() { printf '%s\n' "$*" >>"$WEB_NOTIFY_LOG_ERROR_FILE"; }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __end_log() {
   WEB_NOTIFY_EXIT_STATUS=${1:-$?}
-  printf '%s\n\n' " # End Log $(date) #" >>"$WEB_NOTIFY_LOG_ERROR_FILE"
+  __append_log "# End Log $(date) #" >>"$WEB_NOTIFY_LOG_ERROR_FILE"
   [ "$WEB_NOTIFY_EXIT_STATUS" -eq 0 ] && printf_blue "Your message/file has been sent" || printf_yellow "Errors logged to: $WEB_NOTIFY_LOG_ERROR_FILE"
   return $WEB_NOTIFY_EXIT_STATUS
 }
@@ -551,7 +562,7 @@ while :; do
     __no_options_function "$@"
     ;;
   --pushbullet-token)
-    WEB_NOTIFY_PUSHOVER_API_KEY="$2"
+    WEB_NOTIFY_PUSHBULLET_ACCESS_TOKEN="$2"
     shift 2
     ;;
   --pushover-token)
