🗃️ Committing everything that changed 🗃️
bin/web-notify

diff --git a/bin/web-notify b/bin/web-notify
--- a/bin/web-notify
+++ b/bin/web-notify
@@ -142,6 +142,10 @@ WEB_NOTIFY_SLACK_WEBHOOK="${WEB_NOTIFY_SLACK_WEBHOOK:-}"
 # discord
 WEB_NOTIFY_DISCORD_WEBHOOK="${WEB_NOTIFY_DISCORD_WEBHOOK:-}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# pushover
+WEB_NOTIFY_PUSHOVER_API_KEY="${WEB_NOTIFY_PUSHOVER_API_KEY:-$PUSHOVER_API_KEY}"
+WEB_NOTIFY_PUSHOVER_API_ID="${WEB_NOTIFY_PUSHOVER_API_ID:-a8xbbw7e7jrnqpg7ngdrtwd6vxfyv5}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Color Settings
 WEB_NOTIFY_OUTPUT_COLOR_1="${WEB_NOTIFY_OUTPUT_COLOR_1:-}"
 WEB_NOTIFY_OUTPUT_COLOR_2="${WEB_NOTIFY_OUTPUT_COLOR_2:-}"
@@ -288,37 +292,37 @@ __pushover() {
   local token="${WEB_NOTIFY_PUSHOVER_API_KEY:-}"
   [ "$1" = "help" ] && printf_help "Usage: $APPNAME telegram [file/text]"
   [ -n "$token" ] || { printf_red "token is not set WEB_NOTIFY_TELEGRAM_API" && return 0; }
-  curl -q -LSsf -s -X POST --form-string "token=$token" --form-string "user=$key" --form-string "message=\"$message\"" https://api.pushover.net/1/messages.json
+  printf '%b\n' "$message" | curl -q -LSsf -s -X POST --form-string "token=$token" --form-string "user=$key" --data-urlencode message@- https://api.pushover.net/1/messages.json
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __telegram() {
   local message="$*"
-  local msg_content=\"$message\"
+  local msg_content="$message"
   local token="${WEB_NOTIFY_TELEGRAM_API:-}"
   local channel="-${WEB_NOTIFY_TELEGRAM_CHANNEL:-}"
   [ "$1" = "help" ] && printf_help "Usage: $APPNAME telegram [file/text]"
   [ -n "$token" ] || { printf_red "token is not set WEB_NOTIFY_TELEGRAM_API" && return 0; }
   [ -n "$channel" ] || { printf_red "channel is not set WEB_NOTIFY_TELEGRAM_CHANNEL: see https://api.telegram.org/bot${token}/getUpdates" && return 0; }
   printf_cyan "Attempting to send to telegram"
-  curl -q -LSsf -s -X POST "https://api.telegram.org/bot${token}/sendMessage" -d chat_id="$channel" -d text="$msg_content" 2>>"$WEB_NOTIFY_LOG_ERROR_FILE" | jq -rc '.ok' 2>/dev/null | grep -q 'true' || exitCode=1
+  printf '%b\n' "$msg_content" | curl -q -LSsf -s -X POST "https://api.telegram.org/bot${token}/sendMessage" -d chat_id="$channel" --data-urlencode text@- 2>>"$WEB_NOTIFY_LOG_ERROR_FILE" | jq -rc '.ok' 2>/dev/null | grep -q 'true' || exitCode=1
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __discord() {
   local message="$*"
-  local msg_content=\"$message\"
+  local msg_content="$(printf '%b\n' "$message" | tr '\n' '\\' | sed 's|[\\]|\\r|g')"
   local url="https://discord.com/api/webhooks/$WEB_NOTIFY_DISCORD_WEBHOOK"
   [ "$1" = "help" ] && printf_help "Usage: $APPNAME discord [file/text]"
   [ -n "$url" ] || { printf_red "url is not set WEB_NOTIFY_DISCORD_WEBHOOK: see https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks" && return 0; }
   printf_cyan "Attempting to send to discord"
-  curl -q -LSsf -X POST -H "Content-Type: application/json" -d "{\"content\": $msg_content}" $url 2>>"$WEB_NOTIFY_LOG_ERROR_FILE" >/dev/null || exitCode=1
+  curl -q -LSsf -X POST -H "Content-Type: application/json" -d "{\"content\": \"$msg_content\"}" $url 2>>"$WEB_NOTIFY_LOG_ERROR_FILE" >/dev/null || exitCode=1
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __slack() {
   local message="$*"
   local exitCode=0
-  local msg_content=\"$message\"
+  local msg_content="$(printf '%b\n' "$message" | tr '\n' '\\' | sed 's|[\\]|\\r|g')"
   local url="$WEB_NOTIFY_SLACK_WEBHOOK"
   [ "$1" = "help" ] && printf_help "Usage: $APPNAME slack [file/text]"
   [ -n "$url" ] || { printf_red "channel is not set WEB_NOTIFY_SLACK_WEBHOOK" && return 0; }
@@ -329,7 +333,7 @@ __slack() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __end_log() {
   WEB_NOTIFY_EXIT_STATUS=${1:-$?}
-  printf '%s\n\n' "# End Log $(date) #" >>"$WEB_NOTIFY_LOG_ERROR_FILE"
+  printf '%s\n\n' " # End Log $(date) #" >>"$WEB_NOTIFY_LOG_ERROR_FILE"
   [ "$WEB_NOTIFY_EXIT_STATUS" -eq 0 ] && printf_blue "Your message/file has been sent" || printf_yellow "Errors logged to: $WEB_NOTIFY_LOG_ERROR_FILE"
   return $WEB_NOTIFY_EXIT_STATUS
 }
@@ -375,8 +379,8 @@ WEB_NOTIFY_GOTIFY_HOST="${WEB_NOTIFY_GOTIFY_HOST:-}"
 WEB_NOTIFY_GOTIFY_API_KEY="${WEB_NOTIFY_GOTIFY_API_KEY:-}"
 WEB_NOTIFY_TELEGRAM_API="${WEB_NOTIFY_TELEGRAM_API:-$TELEGRAM_API_TOKEN}"
 WEB_NOTIFY_TELEGRAM_CHANNEL="${WEB_NOTIFY_TELEGRAM_CHANNEL:-$TELEGRAM_API_CHANNEL}"
-WEB_NOTIFY_SLACK_WEBHOOK="${WEB_NOTIFY_SLACK_WEBHOOK:-SLACK_WEBHOOK_URL}"
-WEB_NOTIFY_DISCORD_WEBHOOK="${WEB_NOTIFY_DISCORD_WEBHOOK:-DISCORD_WEBHOOK_URL}"
+WEB_NOTIFY_SLACK_WEBHOOK="${WEB_NOTIFY_SLACK_WEBHOOK:-$SLACK_WEBHOOK_URL}"
+WEB_NOTIFY_DISCORD_WEBHOOK="${WEB_NOTIFY_DISCORD_WEBHOOK:-$DISCORD_WEBHOOK_URL}"
 WEB_NOTIFY_PUSHOVER_API_KEY="${WEB_NOTIFY_PUSHOVER_API_KEY:-$PUSHOVER_API_KEY}"
 WEB_NOTIFY_PUSHOVER_API_ID="${WEB_NOTIFY_PUSHOVER_API_ID:-a8xbbw7e7jrnqpg7ngdrtwd6vxfyv5}"
 WEB_NOTIFY_PUSHBULLET_ACCESS_TOKEN="${WEB_NOTIFY_PUSHBULLET_ACCESS_TOKEN:-$PUSHBULLET_ACCESS_TOKEN}"
