🗃️  Committing everything that changed 🗃️

diff --git a/bin/ytda b/bin/ytda
--- a/bin/ytda
+++ b/bin/ytda
@@ -444,15 +444,12 @@ __download() {
 __show_error_log() {
   local error=""
   local url="$1"
-  error="$(grep --no-filename -B5 '^ERROR: ' "$YTDA_YOUTUBE_DL_LOG_FILE" || echo '')"
   if [ -f "$YTDA_YOUTUBE_DL_LOG_FILE" ]; then
-    if [ -n "$error" ]; then
-      title="$(echo "$error" | sed 's/[^ ]* //;s|:||g;s|-||g' | tail -n1)"
-      printf_red "😿 Failed to download files from $url 😿 "
-      printf_red "💔 The error is : $title 💔 "
-    else
-      printf_red "😿 Failed to download files from $url 😿 "
-    fi
+    error="$(grep --no-filename -B5 '^ERROR: ' "$YTDA_YOUTUBE_DL_LOG_FILE" | sed 's/[^ ]* //;s|:||g;s|-||g' | tail -n1 | grep '^' || echo '')"
+    printf_red "😿 Failed to download files from $url 😿 "
+    [ -z "$error" ] || printf_red "💔 The error is : $error 💔 "
+  else
+    printf_red "😿 Failed to download files from $url 😿 "
   fi
   return 1
 }
