🗃️  Committing everything that changed 🗃️

diff --git a/bin/ytda b/bin/ytda
--- a/bin/ytda
+++ b/bin/ytda
@@ -160,24 +160,13 @@ EOF
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Help function - Align to 50
-__help() { # wav vorbis opus mp3 m4a flac aac nightcorea nightcorev video ytda yta ytv *
+__help() { # ytv yta nightcorev nightcorea aac flac m4a mp3 opus vorbis wav ytda ytdv *
   __printf_head "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
   __printf_opts "ytda: Video downloader and mp3 converter - $VERSION"
   __printf_head "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
   __printf_line "Usage: ytda [options] [commands]"
-  __printf_line "ytv                             - "
-  __printf_line "yta                             - "
-  __printf_line "ytda                            - "
-  __printf_line "video                           - "
-  __printf_line "nightcorev                      - "
-  __printf_line "nightcorea                      - "
-  __printf_line "aac                             - "
-  __printf_line "flac                            - "
-  __printf_line "m4a                             - "
-  __printf_line "mp3                             - "
-  __printf_line "opus                            - "
-  __printf_line "vorbis                          - "
-  __printf_line "wav                             - "
+  __printf_line " - "
+  __printf_line " - "
   __printf_line "--dir                           - Sets the working directory"
   __printf_head "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
   __printf_opts "Other Options"
@@ -281,9 +270,7 @@ __check_yt_conf() {
   if [ -f "$1" ]; then
     return 0
   else
-    printf_yellow "Can not find the config file: $1"
-    printf_yellow "Please install my youtube-dl config files - dfmgr install youtube-dl"
-    exit 1
+    return 1
   fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -292,97 +279,123 @@ __youtube_dl() {
   local retries="${YTDA_RETRY_LIMIT:-15}"
   local sleep="${YTDA_SLEEP_INTERVAL:-5}"
   local ytbdl_bin="$(builtin type -P youtube-dl || false)"
-  $ytbdl_bin --mark-watched --retries $retries --no-progress --sleep-interval $sleep $opts "$@"
+  $ytbdl_bin --restrict-filenames --retries $retries --no-progress --sleep-interval $sleep $opts --no-warnings --mark-watched --ignore-errors --continue "$@"
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 nightcorea() {
-  __check_yt_conf "$YTDA_YOUTUBE_DL_CONF_DIR/nightcorea"
-  __youtube_dl --extract-audio --audio-format mp3 --embed-thumbnail \
-    --add-metadata --audio-quality 320k --config-location "$YTDA_YOUTUBE_DL_CONF_DIR/nightcorea" "$@"
+  local config="$YTDA_YOUTUBE_DL_CONF_DIR/nightcorea"
+  local dir="$HOME/Music/Nightcore/%(title)s.%(ext)s"
+  __check_yt_conf "$config" && opts="--config-location $config" || opts="--ignore-config"
+  __youtube_dl --audio-format mp3 -o $dir --metadata-from-title "「Nightcore」→ (?P<title>.+)" \
+    --add-metadata --embed-thumbnail --extract-audio --audio-quality 320k $opts "$@"
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 nightcorev() {
-  __check_yt_conf "$YTDA_YOUTUBE_DL_CONF_DIR/music"
-  __youtube_dl -f bestvideo+bestaudio \
-    --config-location "$YTDA_YOUTUBE_DL_CONF_DIR/nightcorev" "$@"
-  return $?
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-ytv-best() {
-  __check_yt_conf "$YTDA_YOUTUBE_DL_CONF_DIR/music"
-  __youtube_dl -f bestvideo+bestaudio \
-    --config-location "$YTDA_YOUTUBE_DL_CONF_DIR/music" "$@"
+  local config="$YTDA_YOUTUBE_DL_CONF_DIR/nightcorev"
+  local dir="$HOME/Videos/Music/Nightcore/%(title)s.%(ext)s"
+  __check_yt_conf "$config" && opts="--config-location $config" || opts="--ignore-config"
+  __youtube_dl -f bestvideo+bestaudio -o $dir --metadata-from-title '(?P<artist>.+?) - (?P<title>.+)' --add-metadata $opts "$@"
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 yta-aac() {
-  __check_yt_conf "$YTDA_YOUTUBE_DL_CONF_DIR/music"
-  __youtube_dl --extract-audio --audio-format aac \
-    --config-location "$YTDA_YOUTUBE_DL_CONF_DIR/music" "$@"
+  local config="$YTDA_YOUTUBE_DL_CONF_DIR/music"
+  local dir="$HOME/Music/ytdl/%(channel)s/%(title)s.%(ext)s"
+  __check_yt_conf "$config" && opts="--config-location $config" || opts="--ignore-config"
+  __youtube_dl --audio-format aac -f bestaudio -o $dir --metadata-from-title '(?P<artist>.+?) - (?P<title>.+)' \
+    --add-metadata --embed-thumbnail --extract-audio --audio-quality 320k $opts "$@"
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 yta-best() {
-  __check_yt_conf "$YTDA_YOUTUBE_DL_CONF_DIR/music"
-  __youtube_dl --extract-audio --audio-format best \
-    --config-location "$YTDA_YOUTUBE_DL_CONF_DIR/music" "$@"
+  local config="$YTDA_YOUTUBE_DL_CONF_DIR/music"
+  local dir="$HOME/Music/ytdl/%(channel)s/%(title)s.%(ext)s"
+  __check_yt_conf "$config" && opts="--config-location $config" || opts="--ignore-config"
+  __youtube_dl --audio-format mp3 -f bestaudio -o $dir --metadata-from-title '(?P<artist>.+?) - (?P<title>.+)' \
+    --add-metadata --embed-thumbnail --extract-audio --audio-quality 320k $opts "$@"
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 yta-flac() {
-  __check_yt_conf "$YTDA_YOUTUBE_DL_CONF_DIR/music"
-  __youtube_dl --extract-audio --audio-format flac \
-    --config-location "$YTDA_YOUTUBE_DL_CONF_DIR/music" "$@"
+  local config="$YTDA_YOUTUBE_DL_CONF_DIR/music"
+  local dir="$HOME/Music/ytdl/%(channel)s/%(title)s.%(ext)s"
+  __check_yt_conf "$config" && opts="--config-location $config" || opts="--ignore-config"
+  __youtube_dl --audio-format flac -f bestaudio -o $dir --metadata-from-title '(?P<artist>.+?) - (?P<title>.+)' \
+    --add-metadata --embed-thumbnail --extract-audio --audio-quality 320k $opts "$@"
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 yta-m4a() {
-  __check_yt_conf "$YTDA_YOUTUBE_DL_CONF_DIR/music"
-  __youtube_dl --extract-audio --audio-format m4a \
-    --config-location "$YTDA_YOUTUBE_DL_CONF_DIR/music" "$@"
+  local config="$YTDA_YOUTUBE_DL_CONF_DIR/music"
+  local dir="$HOME/Music/ytdl/%(channel)s/%(title)s.%(ext)s"
+  __check_yt_conf "$config" && opts="--config-location $config" || opts="--ignore-config"
+  __youtube_dl --audio-format m4a -f bestaudio -o $dir --metadata-from-title '(?P<artist>.+?) - (?P<title>.+)' \
+    --add-metadata --embed-thumbnail --extract-audio --audio-quality 320k $opts "$@"
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 yta-mp3() {
-  __check_yt_conf "$YTDA_YOUTUBE_DL_CONF_DIR/music"
-  __youtube_dl --audio-quality 320k --extract-audio \
-    --audio-format mp3 --config-location "$YTDA_YOUTUBE_DL_CONF_DIR/music" "$@"
+  local config="$YTDA_YOUTUBE_DL_CONF_DIR/music"
+  local dir="$HOME/Music/ytdl/%(channel)s/%(title)s.%(ext)s"
+  __check_yt_conf "$config" && opts="--config-location $config" || opts="--ignore-config"
+  __youtube_dl --audio-format mp3 -f bestaudio -o $dir --metadata-from-title '(?P<artist>.+?) - (?P<title>.+)' \
+    --add-metadata --embed-thumbnail --extract-audio --audio-quality 320k $opts "$@"
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 yta-opus() {
-  __check_yt_conf "$YTDA_YOUTUBE_DL_CONF_DIR/music"
-  __youtube_dl --extract-audio --audio-format opus \
-    --config-location "$YTDA_YOUTUBE_DL_CONF_DIR/music" "$@"
+  local config="$YTDA_YOUTUBE_DL_CONF_DIR/music"
+  local dir="$HOME/Music/ytdl/%(channel)s/%(title)s.%(ext)s"
+  __check_yt_conf "$config" && opts="--config-location $config" || opts="--ignore-config"
+  __youtube_dl --audio-format opus -f bestaudio -o $dir --metadata-from-title '(?P<artist>.+?) - (?P<title>.+)' \
+    --add-metadata --embed-thumbnail --extract-audio --audio-quality 320k $opts "$@"
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 yta-vorbis() {
-  __check_yt_conf "$YTDA_YOUTUBE_DL_CONF_DIR/music"
-  __youtube_dl --extract-audio --audio-format vorbis \
-    --config-location "$YTDA_YOUTUBE_DL_CONF_DIR/music" "$@"
+  local config="$YTDA_YOUTUBE_DL_CONF_DIR/music"
+  local dir="$HOME/Music/ytdl/%(channel)s/%(title)s.%(ext)s"
+  __check_yt_conf "$config" && opts="--config-location $config" || opts="--ignore-config"
+  __youtube_dl --audio-format vorbis -f bestaudio -o $dir --metadata-from-title '(?P<artist>.+?) - (?P<title>.+)' \
+    --add-metadata --embed-thumbnail --extract-audio --audio-quality 320k $opts "$@"
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 yta-wav() {
-  __check_yt_conf "$YTDA_YOUTUBE_DL_CONF_DIR/music"
-  __youtube_dl --extract-audio --audio-format wav \
-    --config-location "$YTDA_YOUTUBE_DL_CONF_DIR/music" "$@"
+  local config="$YTDA_YOUTUBE_DL_CONF_DIR/music"
+  local dir="$HOME/Music/ytdl/%(channel)s/%(title)s.%(ext)s"
+  __check_yt_conf "$config" && opts="--config-location $config" || opts="--ignore-config"
+  __youtube_dl --audio-format wav -f bestaudio -o $dir --metadata-from-title '(?P<artist>.+?) - (?P<title>.+)' \
+    --add-metadata --embed-thumbnail --extract-audio --audio-quality 320k $opts "$@"
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ytda() {
-  __check_yt_conf "$YTDA_YOUTUBE_DL_CONF_DIR/music"
-  __youtube_dl -f bestaudio --extract-audio --audio-format mp3 \
-    $YTDA_AUDIO_CONF -o "$HOME/Music/ytdl/%(playlist_title)s/%(title)s.%(ext)s" "$@"
+  local config="$YTDA_YOUTUBE_DL_CONF_DIR/music"
+  local dir="$HOME/Music/ytdl/%(channel)s/%(title)s.%(ext)s"
+  __check_yt_conf "$config" && opts="--config-location $config" || opts="--ignore-config"
+  __youtube_dl --audio-format mp3 -f bestaudio -o $dir --metadata-from-title '(?P<artist>.+?) - (?P<title>.+)' \
+    --add-metadata --embed-thumbnail --extract-audio --audio-quality 320k $YTDA_AUDIO_CONF $opts "$@"
+  return $?
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+ytv-best() {
+  local config="$YTDA_YOUTUBE_DL_CONF_DIR/videos"
+  local dir="$HOME/Videos/ytdl/%(channel)s/%(title)s.%(ext)s"
+  __check_yt_conf "$config" && opts="--config-location $config" || opts="--ignore-config"
+  __youtube_dl -f bestvideo+bestaudio -o $dir --metadata-from-title '(?P<artist>.+?) - (?P<title>.+)' \
+    --add-metadata --embed-thumbnail $opts "$@"
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 video() {
-  __check_yt_conf "$YTDA_YOUTUBE_DL_CONF_DIR/videos"
-  __youtube_dl -f bestvideo+bestaudio --config-location "$YTDA_YOUTUBE_DL_CONF_DIR/videos" "$@"
+  local config="$YTDA_YOUTUBE_DL_CONF_DIR/videos"
+  local dir="$HOME/Videos/ytdl/%(channel)s/%(title)s.%(ext)s"
+  __check_yt_conf "$config" && opts="--config-location $config" || opts="--ignore-config"
+  __youtube_dl -f bestvideo+bestaudio -o $dir --metadata-from-title '(?P<artist>.+?) - (?P<title>.+)' \
+    --add-metadata --embed-thumbnail $opts "$@"
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -402,23 +415,25 @@ __download() {
   local action="$1" && shift 1
   urls=$(echo "$@" | tr ',' '\n' | tr ' ' '\n' | sed "s|[']||g")
   for url in $urls; do
+    pretty="${url//*:\/\//}"
     if echo "$url" | grep -q 'list='; then
       printf '%b ' "🔻 ${YELLOW}Downloading videos from playlist${NC} 🔻 "
     else
-      printf '%b ' "🔻 ${YELLOW}Downloading video from $url${NC} 🔻 "
+      printf '%b ' "🔻 ${YELLOW}Downloading video from $pretty${NC} 🔻 "
     fi
     if __is_url "$url"; then
       file_url="$url"
     else
       file_url="${YTDA_DEFAULT_URL}$url"
     fi
+    pretty="${file_url//*:\/\//}"
     __grab_file "$action" "$file_url" "$message"
     if [ $? -eq 0 ]; then
       rm -Rf "$YTDA_YOUTUBE_DL_LOG_FILE"
-      printf_green "😀 Successfully downloaded $file_url 😀 "
+      printf_green "😀 Successfully downloaded $pretty 😀 "
       exitCode=$(($exitCode + 0))
     else
-      printf_red "😿 Failed to download files from $file_url 😿 "
+      printf_red "😿 Failed to download files from $pretty 😿 "
       __show_error_log | printf_readline $YTDA_OUTPUT_COLOR_2
       exitCode=$(($exitCode + 1))
     fi
@@ -432,7 +447,7 @@ __show_error_log() {
   error="$(grep --no-filename -B5 '^ERROR: ' "$YTDA_YOUTUBE_DL_LOG_FILE" || echo '')"
   if [ -f "$YTDA_YOUTUBE_DL_LOG_FILE" ]; then
     if [ -n "$error" ]; then
-      title="$(echo "$error" | awk -F ':' '{print $1}' | sed 's/[^ ]* //;s|:||g;s|-||g' | head -n1)"
+      title="$(echo "$error" | sed 's|http*://||g' | sed 's/[^ ]* //;s|:||g;s|-||g' | head -n1)"
       echo "Failed to download $title"
       return 1
     else
@@ -473,8 +488,8 @@ YTDA_RETRY_LIMIT="${YTDA_RETRY_LIMIT:-15}"
 YTDA_SLEEP_INTERVAL="${YTDA_SLEEP_INTERVAL:-5}"
 YTDA_COOKIE_FILE="${YTDA_COOKIE_FILE:-$YTDA_CONFIG_DIR/cookies.txt}"
 YTDA_DEFAULT_URL="${YTDA_DEFAULT_URL:-https://youtube.com/watch?v=}"
-YTDA_YOUTUBE_DL_CONF_DIR="${YTDA_YOUTUBE_DL_CONF_DIR:-$HOME/.config/youtube-dl}"
-YTDA_AUDIO_CONF="--metadata-from-title '(?P<artist>.+?) - (?P<title>.+)' --add-metadata --embed-thumbnail --no-warnings --ignore-errors"
+YTDA_YOUTUBE_DL_CONF_DIR="${YTDA_YOUTUBE_DL_CONF_DIR:-$HOME/.config/ytda/inc}"
+YTDA_AUDIO_CONF="${YTDA_AUDIO_CONF:---metadata-from-title '(?P<artist>.+?) - (?P<title>.+)' --add-metadata --embed-thumbnail}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Generate config files
 [ -f "$YTDA_CONFIG_DIR/$YTDA_CONFIG_FILE" ] ||
@@ -647,18 +662,22 @@ YTDA_CWD="$(realpath "${YTDA_CWD:-$PWD}" 2>/dev/null)"
 export YTDA_CWD
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set actions based on variables
-[ -d "$YTDA_YOUTUBE_DL_CONF_DIR" ] || printf_exit "Please install youtube-dl configs - dfmgr install youtube-dl"
+[ -d "$YTDA_YOUTUBE_DL_CONF_DIR" ] || mkdir -p "$YTDA_YOUTUBE_DL_CONF_DIR"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Check for required applications/Network check
 #requiresudo "$0" "$@" || exit 2     # exit 2 if errors
 cmd_exists --error --ask bash || exit 3 # exit 3 if not found
-__cmd_exists youtube-dl || printf_exit "youtube-dl is not installed"
 #am_i_online --error || exit 4           # exit 4 if no internet
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # APP Variables overrides
 YTDA_YOUTUBE_DL_LOG_FILE="$YTDA_LOG_DIR/ytda.$$.log"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Actions based on env
+if ! __cmd_exists youtube-dl; then
+  curl -L https://yt-dl.org/downloads/latest/youtube-dl -o "$HOME/.local/bin/youtube-dl"
+  chmod a+rx "$HOME/.local/bin/youtube-dl"
+  [ -x "$HOME/.local/bin/youtube-dl" ] || printf_exit "Failed to install youtube-dl"
+fi
 [ -n "$OPTS" ] && YTDL_OPTS="$YTDL_OPTS $OPTS"
 [ -f "$YTDA_COOKIE_FILE" ] && YTDL_OPTS="$YTDL_OPTS --cookies $YTDA_COOKIE_FILE"
 if [ -p "/dev/stdin" ]; then
