🗃️  Committing everything that changed 🗃️

diff --git a/bin/ytda b/bin/ytda
--- a/bin/ytda
+++ b/bin/ytda
@@ -445,12 +445,16 @@ __show_error_log() {
   local error=""
   local url="$1"
   if [ -f "$YTDA_YOUTUBE_DL_LOG_FILE" ]; then
-    error="$(grep --no-filename -B5 '^ERROR: ' "$YTDA_YOUTUBE_DL_LOG_FILE" | sed 's/[^ ]* //;s|:||g;s|-||g' | tail -n2 | tr '\n' ' ' | grep '^' || echo '')"
+    error="$(grep --no-filename -B5 '^ERROR: ' "$YTDA_YOUTUBE_DL_LOG_FILE" | __gen_error_message || echo '')"
     [ -z "$error" ] || printf_red "💔 I'm sorry but an error has occured : $error 💔 "
   else
     printf_red "😿 Failed to download files from $url 😿 "
   fi
   return 1
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__gen_error_message() {
+  sed 's/[^ ]* //;s|:||g;s|-||g' | tail -n2 | tr '\n' '|' | sed 's|Downloading webpage ||g' | awk -F '|' '{print $2" "$1}' | grep '^' || return 1
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # User defined variables/import external variables
