🗃️ Committing everything that changed 🗃️

diff --git a/bin/ytda b/bin/ytda
--- a/bin/ytda
+++ b/bin/ytda
@@ -407,7 +407,7 @@ __download() {
       printf_green "😀 Successfully downloaded $file_url 😀 "
       exitCode=$(($exitCode + 0))
     else
-      printf_red "😿 Failed to download $file_url 😿 "
+      printf_red "😿 Failed to download files from $file_url 😿 "
       __show_error_log | printf_readline $YTDA_OUTPUT_COLOR_2
       exitCode=$(($exitCode + 1))
     fi
@@ -417,8 +417,15 @@ __download() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __show_error_log() {
+  local error=""
+  error="$(grep --no-filename -B5 '^ERROR: ' "$YTDA_YOUTUBE_DL_LOG_FILE" || echo '')"
   if [ -f "$YTDA_YOUTUBE_DL_LOG_FILE" ]; then
-    grep --no-filename -B5 '^ERROR: ' "$YTDA_YOUTUBE_DL_LOG_FILE" && return 1 || return 0
+    if [ -n "$error" ]; then
+      echo "$error"
+      return 1
+    else
+      return 0
+    fi
   fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
