🗃️  Committing everything that changed 🗃️

diff --git a/bin/ytda b/bin/ytda
--- a/bin/ytda
+++ b/bin/ytda
@@ -445,7 +445,7 @@ __show_error_log() {
   local error=""
   local url="$1"
   if [ -f "$YTDA_YOUTUBE_DL_LOG_FILE" ]; then
-    error="$(grep --no-filename -B5 '^ERROR: ' "$YTDA_YOUTUBE_DL_LOG_FILE" | sed 's/[^ ]* //;s|:||g;s|-||g' | tail -n1 | grep '^' || echo '')"
+    error="$(grep --no-filename -B5 '^ERROR: ' "$YTDA_YOUTUBE_DL_LOG_FILE" | sed 's/[^ ]* //;s|:||g;s|-||g' | tail -n2 | grep '^' || echo '')"
     [ -z "$error" ] || printf_red "💔 I'm sorry but an error has occured : $error 💔 "
   else
     printf_red "😿 Failed to download files from $url 😿 "
