🗃️ Committing everything that changed 🗃️

diff --git a/bin/ytda b/bin/ytda
--- a/bin/ytda
+++ b/bin/ytda
@@ -377,10 +377,12 @@ video() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __grab_file() {
-  printf '%s\n' "#### Downloading from $2" >>"$YTDA_YOUTUBE_DL_LOG_FILE"
-  $1 "$2" &>>"$YTDA_YOUTUBE_DL_LOG_FILE"
-  exitStatus=$?
-  printf '\n%s\n\n' "#### Downloading finished with exit code: $exitStatus" >>"$YTDA_YOUTUBE_DL_LOG_FILE"
+  {
+    printf '%s\n' "#### Downloading from $2"
+    $1 "$2"
+    exitStatus=$?
+    printf '\n%s\n\n' "#### Downloading finished with exit code: $exitStatus"
+  } >>"$YTDA_YOUTUBE_DL_LOG_FILE"
   printf '\n'
   return $exitStatus
 }
@@ -415,7 +417,11 @@ __download() {
   return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__show_error_log() { grep --no-filename -B5 '^ERROR: ' "$YTDA_YOUTUBE_DL_LOG_FILE" && return 1 || return 0; }
+__show_error_log() {
+  if [ -f "$YTDA_YOUTUBE_DL_LOG_FILE" ]; then
+    grep --no-filename -B5 '^ERROR: ' "$YTDA_YOUTUBE_DL_LOG_FILE" && return 1 || return 0
+  fi
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # User defined variables/import external variables
 
