🐛 FIXED: bin/ytstream 🐛

diff --git a/bin/ytstream b/bin/ytstream
--- a/bin/ytstream
+++ b/bin/ytstream
@@ -141,8 +141,27 @@ __console_app() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __play_vid() {
-  [[ -n "$1" ]] && local url="$1" || return 1
-  $YTSTREAM_DEFAULT_PLAYER "$url" || printf_exit "Failed to play video from $set_video_url"
+  local exitCode=0
+  for url in "$@"; do
+    check_uri "$url" && set_video_url="$url" || set_video_url="https://youtube.com/watch?v=$url"
+    play_url="$(youtube-dl --quiet --no-warnings --get-url --format best "$set_video_url" 2>/dev/null || echo "")"
+    if [[ -n "$play_url" ]]; then
+      echo "Playing $url" >>"$YTSTREAM_LOG_DIR"
+      date +'%m-%d-Y at %H:%M' >>"$YTSTREAM_LOG_DIR/play.log"
+      if $YTSTREAM_DEFAULT_PLAYER "$play_url" 2>>"$YTSTREAM_LOG_DIR/play.log"; then
+        exitCode+=0
+      else
+        echo "Failed to play video from $url" >>"$YTSTREAM_LOG_DIR/play.log"
+        exitCode+=1
+      fi
+    else
+      echo "An error has occured: $url" >>"$YTSTREAM_LOG_DIR/play.log"
+      exitCode=5
+    fi
+    date +'%m-%d-Y at %H:%M' >>"$YTSTREAM_LOG_DIR/play.log"
+    printf '\n\n' >>"$YTSTREAM_LOG_DIR/play.log"
+  done
+  return ${exitCode:-$?}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __get_youtubeDL() {
@@ -261,7 +280,7 @@ done
 #set -- "$SETARGS"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Actions based on env
-url="${shortcode:-$1}"
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Check for required applications/Network check
 am_i_online --error || exit 1                      # exit 1 if no internet
@@ -270,18 +289,17 @@ cmd_exists youtube-dl || __get_youtubeDL || exit 1 # exit 1 if no youtube-dl
 __get_player
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # APP Variables overrides
-check_uri "$url" && set_video_url="$url" || set_video_url="https://youtube.com/watch?v=$url"
-play_url="$(youtube-dl --quiet --no-warnings --get-url --format best "$set_video_url" 2>/dev/null || echo "")"
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # begin main app
-if [[ -n "$play_url" ]]; then
-  if __console_app; then
-    __play_vid "$play_url" 2>/dev/null
-  else
-    __play_vid "$play_url" &>/dev/null &
-  fi
+if __console_app; then
+  __play_vid "${shortcode:-$@}" 2>/dev/null
 else
-  printf_exit "Failed to get video from $set_video_url"
+  __play_vid "${shortcode:-$@}" &>/dev/null &
+fi
+if [[ $exitCode -ne 0 ]]; then
+  printf_red "Please look in $YTSTREAM_LOG_DIR/play.log"
+  exitCode=1
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # End application
