🗃️ Committing everything that changed 🗃️
templates/scripts/shell/sh

diff --git a/templates/scripts/shell/sh b/templates/scripts/shell/sh
--- a/templates/scripts/shell/sh
+++ b/templates/scripts/shell/sh
@@ -39,25 +39,26 @@ fi
 cmd_exists() {
   local exitCode=0
   for cmd in "$@"; do
-    command -v "$cmd" &>/dev/null && true || exitCode+=1
+    command -v "$cmd" 1>/dev/null 2>/dev/null && true || exitCode+=1
   done
   return ${exitCode:-$?}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # output version
-__version() { echo -e ${GREEN:-}"$VERSION"${NC:-}; }
+version() { echo -e ${GREEN:-}"$VERSION"${NC:-}; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Check for needed applications
 cmd_exists bash || exit 3 # exit 3 if not found
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set variables
-exitCode="0"
 GEN_SCRIPT_REPLACE_ENV_CONFIG_FILE="settings.conf"
 GEN_SCRIPT_REPLACE_ENV_CONFIG_DIR="$HOME/.config/GEN_SCRIPT_REPLACE_FILENAME"
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set additional variables
 
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Create directories
+[ -d "$GEN_SCRIPT_REPLACE_ENV_CONFIG_DIR" ] || mkdir -p "$GEN_SCRIPT_REPLACE_ENV_CONFIG_DIR"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # bring in user config
 [ -f "$GEN_SCRIPT_REPLACE_ENV_CONFIG_DIR/$GEN_SCRIPT_REPLACE_ENV_CONFIG_FILE" ] &&
@@ -66,7 +67,9 @@ GEN_SCRIPT_REPLACE_ENV_CONFIG_DIR="$HOME/.config/GEN_SCRIPT_REPLACE_FILENAME"
 # Main application
 printf_color "Name: $APPNAME $ARGS"
 printf_color "Version: $VERSION"
-
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set exit code
+exitCode="${exitCode:-$?}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
