🗃️  Committing everything that changed 🗃️

diff --git a/templates/scripts/functions/docker-entrypoint b/templates/scripts/functions/docker-entrypoint
--- a/templates/scripts/functions/docker-entrypoint
+++ b/templates/scripts/functions/docker-entrypoint
@@ -259,9 +259,12 @@ EOF
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __exec_command() {
-  local exitCode=0 prog=""
-  local cmdExec="${*:-bash -l}"
-  prog="$(type -P "${1:-bash}" 2>/dev/null)"
+  local arg=("$@")
+  local prog_bin=""
+  local exitCode="0"
+  local cmdExec="${arg:-}"
+  prog_bin="$(echo "${arg[@]}" | tr ' ' '\n' | grep -v '^$' | head -n1 || echo '')"
+  [ -n "$prog_bin" ] && prog="$(type -P "${prog_bin}" 2>/dev/null || echo ':ERROR:')" || prog="bash"
   if [ -f "$prog" ]; then
     echo "${exec_message:-Executing command: $cmdExec}"
     eval $cmdExec || exitCode=1
