🗃️ Committing everything that changed 🗃️

diff --git a/templates/scripts/functions/docker-entrypoint b/templates/scripts/functions/docker-entrypoint
--- a/templates/scripts/functions/docker-entrypoint
+++ b/templates/scripts/functions/docker-entrypoint
@@ -48,15 +48,15 @@ __setup_ssl() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __create_service_user() {
   local create_user="$1" create_gid="$1"
-  local home_dir="/opt/$create_user" set_home_dir=""
+  local create_home_dir="/opt/$create_user" set_home_dir=""
   [ -n "$SERVICE_USER" ] || return 0
   if ! grep -q "$create_user" "/etc/passwd"; then
     echo "creating system user $create_user"
     addgroup -g ${create_gid} -S $create_user &>/dev/null
-    adduser -u ${create_gid} -D -h "$home_dir" -g $create_user $create_user &>/dev/null
+    adduser -u ${create_gid} -D -h "$create_home_dir" -g $create_user $create_user &>/dev/null
     grep -q "$create_user" "/etc/passwd" "/etc/groups" && set_home_dir="$home_dir" && exitStatus=0 || exitStatus=0
   fi
-  export HOMEDIR="${set_home_dir:-$HOME}"
+  WORKDIR="${set_home_dir:-}"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __show_procs() {
@@ -229,33 +229,44 @@ __start_all_services() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __exec_service_start() {
-  local EXEC_CMD="${EXEC_CMD:-${SERVICE_NAME:-$1}}"                          # command to execute
-  local SERVICE_ARGS="${SERVICE_ARGS:-${SERVICE_COMMAND:-${@//$EXEC_CMD/}}}" # command arguments
-  local SERVICE_USER="${SERVICE_USER:-$USER}"                                # execute command as another user
-  local PRE_EXEC_MESSAGE="${PRE_EXEC_MESSAGE:-}"                             # Show message before execute
-  local SERVICE_EXIT_CODE=0                                                  # default exit code
-  echo "Setting up service to run as $SERVICE_USER"
+  [ -n "$1" ] && EXEC_CMD="$1" && shift 1
+  [ -n "$1" ] && EXEC_CMD="$*" && shift $1
+  local EXEC_CMD="${EXEC_CMD:-$SERVICE_NAME}"            # command to execute
+  local SERVICE_ARGS="${SERVICE_ARGS:-$SERVICE_COMMAND}" # command arguments
+  local SERVICE_USER="${SERVICE_USER:-$USER}"            # execute command as another user
+  local PRE_EXEC_MESSAGE="${PRE_EXEC_MESSAGE:-}"         # Show message before execute
+  local SERVICE_EXIT_CODE=0                              # default exit code
+  echo "Determining whether we need to switch user"
   if [ "$SERVICE_USER" = "root" ] || [ -z "$SERVICE_USER" ]; then
+    su_cmd_bin="eval"
     su_cmd() { eval "$@" || return 1; }
   elif [ "$(builtin type -P gosu)" ]; then
+    su_cmd_bin="gosu $SERVICE_USER"
     su_cmd() { gosu $SERVICE_USER "$@" || return 1; }
   elif [ "$(builtin type -P su)" ]; then
+    su_cmd_bin="su -s /bin/sh - $SERVICE_USER"
     su_cmd() { su -s /bin/sh - $SERVICE_USER -c "$@" || return 1; }
   elif [ "$(builtin type -P runuser)" ]; then
+    su_cmd_bin="runuser -u $SERVICE_USER"
     su_cmd() { runuser -u $SERVICE_USER "$@" || return 1; }
   elif [ "$(builtin type -P sudo)" ]; then
+    su_cmd_bin="sudo -u $SERVICE_USER"
     su_cmd() { sudo -u $SERVICE_USER "$@" || return 1; }
   else
     echo "Can not switch to $SERVICE_USER"
     exit 10
   fi
-  sleep 30
-  [ -n "$PRE_EXEC_MESSAGE" ] && echo "$PRE_EXEC_MESSAGE"
-  echo "Starting service: $EXEC_CMD $CMD_ARGS"
-  su_cmd "touch /tmp/$EXEC_CMD.pid"
-  su_cmd "$EXEC_CMD $CMD_ARGS" || echo "Failed to execute: $EXEC_CMD $CMD_ARGS"
-  [ "$?" -ne 0 ] && SERVICE_EXIT_CODE=10 && rm -Rf "/tmp/$EXEC_CMD.pid"
-  return $exitCode
+  if [ -n "$WORKDIR" ] && [ -n "$SERVICE_USER" ]; then
+    echo "Fixing file permissions"
+    su_cmd chown -Rf $SERVICE_USER $WORKDIR
+    sleep 1
+  fi
+  echo "Starting service: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
+  SERVICE_IS_RUNNING="true"
+  su_cmd "touch /tmp/$EXEC_CMD_BIN.pid"
+  su_cmd "$EXEC_CMD_BIN $EXEC_CMD_ARGS" || echo "Failed to execute: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
+  [ "$?" -ne 0 ] && SERVICE_IS_RUNNING="false" && SERVICE_EXIT_CODE=10 && rm -Rf "/tmp/$EXEC_CMD_BIN.pid"
+  return $SERVICE_EXIT_CODE
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __setup_mta() {
