🗃️ Committing everything that changed 🗃️
templates/scripts/functions/docker-entrypoint

diff --git a/templates/scripts/functions/docker-entrypoint b/templates/scripts/functions/docker-entrypoint
--- a/templates/scripts/functions/docker-entrypoint
+++ b/templates/scripts/functions/docker-entrypoint
@@ -278,8 +278,8 @@ __cron() {
   trap '[ -f "/run/cron/$cmd" ] && rm -Rf "/run/cron/$cmd";exit 0' SIGINT ERR EXIT
   test -n "$1" && test -z "${1//[0-9]/}" && interval=$(($1 * 60)) && shift 1 || interval="5"
   [ $# -eq 0 ] && echo "Usage: cron [interval] [command]" && exit 1
-  command="$*"
-  cmd="${CRON_NAME:-$(echo "$command" | awk -F' ' '{print $1}')}"
+  local command="$*"
+  local cmd="${CRON_NAME:-$(echo "$command" | awk -F' ' '{print $1}')}"
   [ -d "/run/cron" ] || mkdir -p "/run/cron"
   echo "$command" >"/run/cron/$cmd"
   while :; do
@@ -319,22 +319,23 @@ __symlink() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __file_copy() {
-  local from="$1" to="$2"
-  if [ -n "$from" ] && [ -e "$from" ] && [ -n "$to" ]; then
+  local from="$1"
+  local dest="$2"
+  if [ -n "$from" ] && [ -e "$from" ] && [ -n "$dest" ]; then
     if [ -d "$from" ]; then
-      if cp -Rf "$from/." "$to/" &>/dev/null; then
-        printf '%s\n' "Copied: $from > $to"
+      if cp -Rf "$from/." "$dest/" &>/dev/null; then
+        printf '%s\n' "Copied: $from > $dest"
         return 0
       else
-        printf '%s\n' "Copy failed: $from < $to" >&2
+        printf '%s\n' "Copy failed: $from < $dest" >&2
         return 1
       fi
     else
-      if cp -Rf "$from" "$to" &>/dev/null; then
-        printf '%s\n' "Copied: $from > $to"
+      if cp -Rf "$from" "$dest" &>/dev/null; then
+        printf '%s\n' "Copied: $from > $dest"
         return 0
       else
-        printf '%s\n' "Copy failed: $from < $to" >&2
+        printf '%s\n' "Copy failed: $from < $dest" >&2
         return 1
       fi
     fi
@@ -752,18 +753,21 @@ __initialize_db_users() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __initialize_system_etc() {
   local conf_dir="$1"
-  local file="" directories=""
+  local dir=""
+  local file=()
+  local directories=()
   if [ -n "$conf_dir" ] && [ -e "$conf_dir" ]; then
-    files="$(find "$conf_dir"/* -not -path '*/env/*' -type f 2>/dev/null | sed 's|'/config/'||g' | sort -u | grep -v '^$' | grep '^' || false)"
-    directories="$(find "$conf_dir"/* -not -path '*/env/*' -type d 2>/dev/null | sed 's|'/config/'||g' | sort -u | grep -v '^$' | grep '^' || false)"
+    files=("$(find "$conf_dir"/* -not -path '*/env/*' -type f 2>/dev/null | sed 's|'/config/'||g' | sort -u | grep -v '^$' | grep '^' || false)")
+    directories=("$(find "$conf_dir"/* -not -path '*/env/*' -type d 2>/dev/null | sed 's|'/config/'||g' | sort -u | grep -v '^$' | grep '^' || false)")
     echo "Copying config files to system: $conf_dir > /etc/${conf_dir//\/config\//}"
-    if [ -n "$directories" ]; then
-      for d in $directories; do
-        echo "Creating directory: /etc/$d"
-        mkdir -p "/etc/$directories"
+    if [ -n "${directories[*]}" ]; then
+      for d in "${directories[@]}"; do
+        dir="/etc/$d"
+        echo "Creating directory: $dir"
+        mkdir -p "$dir"
       done
     fi
-    for f in $files; do
+    for f in "${files[@]}"; do
       etc_file="/etc/$f"
       conf_file="/config/$f"
       [ -f "$etc_file" ] && rm -Rf "$etc_file"
@@ -774,7 +778,7 @@ __initialize_system_etc() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __initialize_custom_bin_dir() {
-  SET_USR_BIN=""
+  local SET_USR_BIN=""
   [ -d "/data/bin" ] && SET_USR_BIN+="$(__find /data/bin f) "
   [ -d "/config/bin" ] && SET_USR_BIN+="$(__find /config/bin f) "
   if [ -n "$SET_USR_BIN" ]; then
