🗃️ Added set -e and ERR trap to kill 1 on error 🗃️
templates/scripts/functions/docker-entrypoint
templates/scripts/other/docker-entrypoint
templates/scripts/other/start-service

diff --git a/templates/scripts/functions/docker-entrypoint b/templates/scripts/functions/docker-entrypoint
--- a/templates/scripts/functions/docker-entrypoint
+++ b/templates/scripts/functions/docker-entrypoint
@@ -642,6 +642,8 @@ __exec_command() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Setup the server init scripts
 __start_init_scripts() {
+  set -e
+  trap 'echo "❌ Fatal error, killing container"; kill -TERM 1' ERR
   [ "$1" = " " ] && shift 1
   [ "$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x$DEBUGGER_OPTIONS || set -o pipefail
   local retPID=""
@@ -678,7 +680,7 @@ __start_init_scripts() {
             printf '# - - - %s has been started - pid: %s\n' "$service" "${retPID:-error}"
           else
             initStatus="1"
-            printf '# - - - %s has falied to start - check log %s\n' "$service" "docker log $CONTAINER_NAME"
+            printf '# - - - %s has failed to start - check log %s\n' "$service" "docker log $CONTAINER_NAME"
           fi
           echo ""
         fi
