🗃️  Committing everything that changed 🗃️

diff --git a/templates/scripts/functions/docker-entrypoint b/templates/scripts/functions/docker-entrypoint
--- a/templates/scripts/functions/docker-entrypoint
+++ b/templates/scripts/functions/docker-entrypoint
@@ -4,6 +4,7 @@
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __rm() { [ -f "$1" ] && rm -Rf "${1:?}"; }
 __cd() { [ -d "$1" ] && builtin cd "$1" || return 1; }
+__grep_test() { grep -s "$1" "$2" | grep -qwF "${3:-$1}" || return 1; }
 __netstat() { [ -f "$(type -P netstat)" ] && netstat "$@" || return 10; }
 __is_dir_empty() { [ "$(ls -A "$1" 2>/dev/null | wc -l)" -ne 0 ] || return 1; }
 __curl() { curl -q -sfI --max-time 3 -k -o /dev/null "$@" &>/dev/null || return 10; }
@@ -209,9 +210,9 @@ __cron() {
 __replace() {
   [ -f "$3" ] || return
   grep -s -q "$1" "$3" &>/dev/null || return
-  sed -i 's|'$1'|'$2'|g' "$3" &>/dev/null
+  sed -i 's|'$1'|'$2'|g' "$3" &>/dev/null || sed -i "s|$1|$2|g" "$3" &>/dev/null
   grep -s -q "$2" "$3" && printf '%s\n' "Changed $1 to $2 in $3" && return 0 || {
-    printf '%s\n' "Failed to change $1 in $3" && return 10
+    printf '%s\n' "Failed to change $1 in $3" >&2 && return 2
   }
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -219,23 +220,23 @@ __file_copy() {
   [ -e "$1" ] || return
   [ -n "$1" ] && [ -n "$2" ] && [ -e "$1" ] && cp -Rf "$1" "$2" &>/dev/null
   [ -e "$1" ] && [ -e "$2" ] && printf '%s\n' "Copied: $1 > $2" && return 0 || {
-    printf '%s\n' "Copy failed: $1 < $2"
-    return 1
+    printf '%s\n' "Copy failed: $1 < $2" >&2 && return 2
   }
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __create_service_user() {
-  local create_user="$1" create_gid="$1"
-  local create_home_dir="/opt/$create_user" set_home_dir=""
+  local create_user="$1" create_home_dir="$2" create_gid="${USER_GID:-${USER_UID:-$3}}"
+  local create_home_dir="${create_home_dir:-/home/$create_user}" set_home_dir=""
   [ "$ENTRYPOINT_FIRST_RUN" = "no" ] || return 0
   [ -n "$SERVICE_USER" ] || [ "$SERVICE_USER" != "root" ] || return 0
   if ! grep -q "$create_user" "/etc/passwd"; then
     echo "creating system user $create_user"
     addgroup -g ${create_gid} -S $create_user &>/dev/null
     adduser -u ${create_gid} -D -h "$create_home_dir" -g $create_user $create_user &>/dev/null
-    grep -q "$create_user" "/etc/passwd" "/etc/groups" && set_home_dir="$home_dir" && exitStatus=0 || exitStatus=0
+    grep -q "$create_user" "/etc/passwd" "/etc/groups" && set_home_dir="$home_dir" && exitStatus=0 || exitStatus=1
   fi
-  WORKDIR="${set_home_dir:-}"
+  [ $exitStatus -eq 0 ] && export WORKDIR="${set_home_dir:-}"
+  return $exitStatus
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __create_env() {
@@ -403,6 +404,6 @@ POSTGRES_CONFIG_FILE="${POSTGRES_CONFIG_FILE:-$(__find_pgsql_conf)}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # export the functions
-
+export -f __start_init_scripts
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end of functions
