🗃️  Committing everything that changed 🗃️

diff --git a/templates/scripts/functions/docker-entrypoint b/templates/scripts/functions/docker-entrypoint
--- a/templates/scripts/functions/docker-entrypoint
+++ b/templates/scripts/functions/docker-entrypoint
@@ -11,6 +11,7 @@ __is_dir_empty() { [ "$(ls -A "$1" 2>/dev/null | wc -l)" -eq 0 ] || return 1; }
 __curl() { curl -q -sfI --max-time 3 -k -o /dev/null "$@" &>/dev/null || return 10; }
 __find() { find "$1" -mindepth 1 -type ${2:-f,d} 2>/dev/null | grep '^' || return 10; }
 __pcheck() { [ -n "$(which pgrep 2>/dev/null)" ] && pgrep -o "$1" &>/dev/null || return 10; }
+__sed() { sed -i 's|'$1'|'$2'|g' "$3" &>/dev/null || sed -i "s|$1|$2|g" "$3" &>/dev/null || return 1; }
 __ps() { [ -f "$(type -P ps)" ] && ps "$@" 2>/dev/null | grep -Fw " ${1:-$GEN_SCRIPT_REPLACE_APPNAME}" || return 10; }
 __pgrep() { __pcheck "${1:-GEN_SCRIPT_REPLACE_APPNAME}" || __ps "${1:-$GEN_SCRIPT_REPLACE_APPNAME}" | grep -qv ' grep' || return 10; }
 __get_ip6() { ip a 2>/dev/null | grep -w 'inet6' | awk '{print $2}' | grep -vE '^::1|^fe' | sed 's|/.*||g' | head -n1 | grep '^' || echo ''; }
@@ -209,16 +210,24 @@ __cron() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __replace() {
-  [ -f "$3" ] || return
-  grep -s -q "$1" "$3" &>/dev/null || return
-  sed -i 's|'$1'|'$2'|g' "$3" &>/dev/null || sed -i "s|$1|$2|g" "$3" &>/dev/null
-  grep -s -q "$2" "$3" && printf '%s\n' "Changed $1 to $2 in $3" && return 0 || {
+  [ -f "$3" ] || return 1
+  grep -s -qR "$1" "$3" &>/dev/null && __sed "$1" "$2" "$3" || return 0
+  grep -s -qR "$2" "$3" && printf '%s\n' "Changed $1 to $2 in $3" && return 0 || {
+    printf '%s\n' "Failed to change $1 in $3" >&2 && return 2
+  }
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__find_replace() {
+  [ -e "$3" ] || return 1
+  grep -s -qR "$1" "$3" &>/dev/null || return 0
+  find "$3" -type f -exec sed -i "|$1|$2|g" {} \;
+  grep -s -qR "$2" "$3" && printf '%s\n' "Changed $1 to $2 in $3" && return 0 || {
     printf '%s\n' "Failed to change $1 in $3" >&2 && return 2
   }
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __file_copy() {
-  [ -e "$1" ] || return
+  [ -e "$1" ] || return 1
   [ -n "$1" ] && [ -n "$2" ] && [ -e "$1" ] && cp -Rf "$1" "$2" &>/dev/null
   [ -e "$1" ] && [ -e "$2" ] && printf '%s\n' "Copied: $1 > $2" && return 0 || {
     printf '%s\n' "Copy failed: $1 < $2" >&2 && return 2
@@ -226,14 +235,19 @@ __file_copy() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __create_service_user() {
-  local create_user="$1" create_home_dir="$2" create_gid="${USER_GID:-${USER_UID:-$3}}"
+  local create_user="$1"
+  local create_home_dir="$2"
+  local create_gid="${USER_GID:-${USER_UID:-${3:-10000}}}"
   local create_home_dir="${create_home_dir:-/home/$create_user}" set_home_dir=""
   [ "$ENTRYPOINT_FIRST_RUN" = "no" ] || return 0
   [ -n "$SERVICE_USER" ] || [ "$SERVICE_USER" != "root" ] || return 0
-  if ! grep -q "$create_user" "/etc/passwd"; then
+  if ! grep -s -q "$create_user" "/etc/groups"; then
+    echo "creating system group $create_user"
+    addgroup -g $create_gid -S $create_user &>/dev/null
+  fi
+  if ! grep -s -q "$create_user" "/etc/passwd"; then
     echo "creating system user $create_user"
-    addgroup -g ${create_gid} -S $create_user &>/dev/null
-    adduser -u ${create_gid} -D -h "$create_home_dir" -g $create_user $create_user &>/dev/null
+    adduser -u $create_gid -D -h "$create_home_dir" -g $create_user $create_user &>/dev/null
     grep -q "$create_user" "/etc/passwd" "/etc/groups" && set_home_dir="$home_dir" && exitStatus=0 || exitStatus=1
   fi
   [ $exitStatus -eq 0 ] && export WORKDIR="${set_home_dir:-}"
diff --git a/templates/scripts/other/start-service b/templates/scripts/other/start-service
--- a/templates/scripts/other/start-service
+++ b/templates/scripts/other/start-service
@@ -27,16 +27,16 @@ done
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Default predefined variables
-WORKDIR=""                                                        # set working directory
-DATA_DIR="/data"                                                  # set data directory
-RUN_DIR="/run/init.d"                                             # set scripts pid dir
-ETC_DIR="/etc/GEN_SCRIPT_REPLACE_APPNAME"                         # set etc directory
-CONF_DIR="/config/GEN_SCRIPT_REPLACE_APPNAME"                     # set data directory
-LOG_DIR="/data/logs/GEN_SCRIPT_REPLACE_APPNAME"                   # set log directory
-WWW_DIR="/data/www/htdocs"                                        # set the web root
-DATABASE_DIR="/data/db/GEN_SCRIPT_REPLACE_APPNAME"                # set the database directory
-ROOT_FILE_PREFIX="/config/secure/GEN_SCRIPT_REPLACE_APPNAME_root" # where to save password for root user
-USER_FILE_PREFIX="/config/secure/GEN_SCRIPT_REPLACE_APPNAME_user" # where to save password for normal user
+WORKDIR=""                                         # set working directory
+DATA_DIR="/data"                                   # set data directory
+ETC_DIR="/etc/GEN_SCRIPT_REPLACE_APPNAME"          # set etc directory
+CONF_DIR="/config/GEN_SCRIPT_REPLACE_APPNAME"      # set data directory
+LOG_DIR="/data/logs/GEN_SCRIPT_REPLACE_APPNAME"    # set log directory
+WWW_DIR="/data/www/htdocs"                         # set the web root
+RUN_DIR="/run/init.d"                              # set scripts pid dir
+DATABASE_DIR="/data/db/GEN_SCRIPT_REPLACE_APPNAME" # set the database directory
+ROOT_FILE_PREFIX="$CONF_DIR/auth/root"             # directory to save password for root user
+USER_FILE_PREFIX="$CONF_DIR/auth/user"             # directory to save password for normal user
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Is this service a database server
 IS_WEB_SERVER="no"
@@ -63,94 +63,113 @@ EXEC_CMD_ARGS=""                          # command arguments
 # Additional variables
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# usernames and passwords
+# usernames
 user_name=""
-user_pass=""
 root_user_name=""
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# passwords [password/random]
+user_pass=""
 root_user_pass=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Overwrite variables from files
-[ -f "${USER_FILE_PREFIX}_name" ] && user_name="$(<"${USER_FILE_PREFIX}_name")"
-[ -f "${USER_FILE_PREFIX}_pass" ] && user_pass="$(<"${USER_FILE_PREFIX}_pass")"
-[ -f "${ROOT_FILE_PREFIX}_name" ] && root_user_name="$(<"${ROOT_FILE_PREFIX}_name")"
-[ -f "${ROOT_FILE_PREFIX}_pass" ] && root_user_pass="$(<"${ROOT_FILE_PREFIX}_pass")"
+[ -f "${USER_FILE_PREFIX}/name" ] && user_name="$(<"${USER_FILE_PREFIX}/name")"
+[ -f "${USER_FILE_PREFIX}/pass" ] && user_pass="$(<"${USER_FILE_PREFIX}/pass")"
+[ -f "${ROOT_FILE_PREFIX}/name" ] && root_user_name="$(<"${ROOT_FILE_PREFIX}/name")"
+[ -f "${ROOT_FILE_PREFIX}/pass" ] && root_user_pass="$(<"${ROOT_FILE_PREFIX}/pass")"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Specifiy custom directories to be created
 ADD_APPLICATION_FILES=""
 ADD_APPLICATION_DIRS=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-APPLICATION_FILES="$LOG_DIR/GEN_SCRIPT_REPLACE_APPNAME"
+APPLICATION_FILES="$LOG_DIR/*"
 APPLICATION_DIRS="$RUN_DIR $ETC_DIR $CONF_DIR $LOG_DIR"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # use this function to update config files - IE: change port
 __update_conf_files() {
-  local exitCode=0 filedirs="" application_files=""
+  local exitCode=0                   # default exit code
+  local user="${SERVICE_USER:-root}" # specifiy different user
 
   # define actions
 
   # create default directories
   for filedirs in $ADD_APPLICATION_DIRS $APPLICATION_DIRS; do
     if [ -n "$filedirs" ] && [ ! -d "$filedirs" ]; then
-      echo "Creating directory $filedirs with permissions 777" | tee -a /data/logs/entrypoint.log &>/dev/null
-      mkdir -p "$filedirs" && chmod -Rf 777 "$filedirs"
+      (
+        echo "Creating directory $filedirs with permissions 777"
+        mkdir -p "$filedirs" && chmod -Rf 777 "$filedirs"
+      ) |& tee -a "/data/logs/init.d/${SERVICE_NAME}.txt" &>/dev/null
     fi
   done
   # create default files
   for application_files in $ADD_APPLICATION_FILES $APPLICATION_FILES; do
     if [ -n "$application_files" ] && [ ! -e "$application_files" ]; then
-      echo "Creating file $application_files with permissions 777" | tee -a /data/logs/entrypoint.log &>/dev/null
-      touch "$application_files" && chmod -Rf 777 "$application_files"
+      (
+        echo "Creating file $application_files with permissions 777"
+        touch "$application_files" && chmod -Rf 777 "$application_files"
+      ) |& tee -a "/data/logs/init.d/${SERVICE_NAME}.txt" &>/dev/null
     fi
   done
   # create directories if variable is yes"
-  [ "$IS_WEB_SERVER" = "yes" ] && { [ -d "$WWW_DIR" ] || { echo "Creating directory $WWW_DIR with permissions 777" && mkdir -p "$WWW_DIR" && chmod -f 777 "$WWW_DIR"; }; }
-  [ "$IS_DATABASE_SERVICE" = "yes" ] && { [ -d "$DATABASE_DIR" ] || { echo "Creating directory $DATABASE_DIR with permissions 777" && mkdir -p "$DATABASE_DIR" && chmod -f 777 "$DATABASE_DIR"; }; }
-  # copy config files
-  __file_copy "$CONF_DIR/." "$ETC_DIR/"
-  # replace variables
+  [ "$IS_WEB_SERVER" = "yes" ] && { [ -d "$WWW_DIR" ] || { (echo "Creating directory $WWW_DIR with permissions 777" && mkdir -p "$WWW_DIR" && chmod -f 777 "$WWW_DIR") |& tee -a "/data/logs/init.d/${SERVICE_NAME}.txt" &>/dev/null; }; }
+  [ "$IS_DATABASE_SERVICE" = "yes" ] && { [ -d "$DATABASE_DIR" ] || { (echo "Creating directory $DATABASE_DIR with permissions 777" && mkdir -p "$DATABASE_DIR" && chmod -f 777 "$DATABASE_DIR") |& tee -a "/data/logs/init.d/${SERVICE_NAME}.txt" &>/dev/null; }; }
+  # copy config files to system
+  __file_copy "$CONF_DIR/." "$ETC_DIR/" |& tee -a "/data/logs/init.d/${SERVICE_NAME}.txt" &>/dev/null
+  # replace variables variables
+  # sed -i "" "" "$CONF_DIR/"
   # __replace "" "" "$CONF_DIR/"
   # custom commands
 
   # other
+
+  # unset unneeded variables
+  unset application_files filedirs
 
   return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # function to run before executing
 __pre_execute() {
-  local exitCode=0 permissions=""
-
+  local exitCode=0                   # default exit code
+  local user="${SERVICE_USER:-root}" # specifiy different user
   # define commands
 
-  # make sure password files are owned by root
-  chmod -Rf 600 "${ROOT_FILE_PREFIX}"_* "${USER_FILE_PREFIX}"_*
-  chown -Rf root:root "${ROOT_FILE_PREFIX}"_* "${USER_FILE_PREFIX}"_*
-  # set permissions to read only user on password files
-  for filesperms in "${ROOT_FILE_PREFIX}"_* "${USER_FILE_PREFIX}"_*; do
+  # create the directories if needed
+  [ -d "$USER_FILE_PREFIX" ] || mkdir -p "$USER_FILE_PREFIX"
+  [ -d "$ROOT_FILE_PREFIX" ] || mkdir -p "$ROOT_FILE_PREFIX"
+  # set permissions to root read only on password files
+  for filesperms in "${ROOT_FILE_PREFIX}"/* "${USER_FILE_PREFIX}"/*; do
     if [ -e "$filesperms" ]; then
-      mkdir -p "$ETC_DIR/auth"
-      filename="$(basename "$filesperms")"
-      cp -Rf "$filesperms" "$ETC_DIR/auth/$filename" && chmod 600 -Rf "$ETC_DIR/auth/$filename"
+      (
+        chmod -Rf 600 "${ROOT_FILE_PREFIX}"/* "${USER_FILE_PREFIX}"/*
+        chown -Rf root:root "${ROOT_FILE_PREFIX}"/* "${USER_FILE_PREFIX}"/*
+      ) |& tee -a "/data/logs/init.d/${SERVICE_NAME}.txt" &>/dev/null
     fi
   done
+  # create user if needed
+  # __create_service_user "$user" "/home/$user" "${USER_GID:-${USER_UID:-1000}"
   # set user on files/folders
-  if [ -n "$SERVICE_USER" ] && [ "$SERVICE_USER" != "root" ]; then
-    if grep -s -q "$SERVICE_USER:" "/etc/passwd"; then
+  if [ -n "$user" ] && [ "$user" != "root" ]; then
+    if grep -s -q "$user:" "/etc/passwd"; then
       for permissions in $WWW_DIR $DATABASE_DIR $ADD_APPLICATION_FILES $APPLICATION_FILES $APPLICATION_FILES $APPLICATION_DIRS; do
         if [ -n "$permissions" ] && [ -e "$permissions" ]; then
-          chown -Rf $SERVICE_USER:$SERVICE_USER "$permissions" && echo "changed ownership on $permissions to $SERVICE_USER"
+          (chown -Rf $user:$user "$permissions" && echo "changed ownership on $permissions to $user") |& tee -a /data/logs/init.log &>/dev/null
         fi
       done
     fi
   fi
 
+  # unset unneeded variables
+  unset filesperms filename
   return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # function to run after executing
 __post_execute() {
-  local exitCode=0
-  sleep 60
+  local exitCode=0                   # default exit code
+  local user="${SERVICE_USER:-root}" # specifiy different user
+  sleep 60                           # how long to wait before executing
+  echo "Running post commands"       # message
+  # execute commands
 
   return $exitCode
 }
@@ -158,10 +177,10 @@ __post_execute() {
 # use this function to update config files - IE: change port
 __pre_message() {
   local exitCode=0
-  [ -n "$user_name" ] && echo "username:               $username" && echo "$user_name" >"${USER_FILE_PREFIX}_name"
-  [ -n "$user_pass" ] && echo "password:               saved to ${USER_FILE_PREFIX}_pass" && echo "$user_pass" >"${USER_FILE_PREFIX}_pass"
-  [ -n "$root_user_name" ] && echo "root username:     $root_user_name" && echo "$root_user_name" >"${ROOT_FILE_PREFIX}_name"
-  [ -n "$root_user_pass" ] && echo "root password:     saved to ${ROOT_FILE_PREFIX}_pass" && echo "$root_user_pass" >"${ROOT_FILE_PREFIX}_pass"
+  [ -n "$user_name" ] && echo "username:               $username" && echo "$user_name" >"${USER_FILE_PREFIX}/name"
+  [ -n "$user_pass" ] && echo "password:               saved to ${USER_FILE_PREFIX}/pass" && echo "$user_pass" >"${USER_FILE_PREFIX}/pass"
+  [ -n "$root_user_name" ] && echo "root username:     $root_user_name" && echo "$root_user_name" >"${ROOT_FILE_PREFIX}/name"
+  [ -n "$root_user_pass" ] && echo "root password:     saved to ${ROOT_FILE_PREFIX}/pass" && echo "$root_user_pass" >"${ROOT_FILE_PREFIX}/pass"
 
   return $exitCode
 }
@@ -187,6 +206,10 @@ __create_env() {
 # EXEC_CMD_BIN="${ENV_EXEC_CMD_BIN:-$EXEC_CMD_BIN}"                 # command to execute
 # EXEC_CMD_ARGS="${ENV_EXEC_CMD_ARGS:-$EXEC_CMD_ARGS}"              # command arguments
 # EXEC_CMD_NAME="$(basename "$EXEC_CMD_BIN")"                       # set the binary name
+# ENV_USER_NAME="${user_name:-$ENV_USER_NAME}"                      #
+# ENV_USER_PASS="${user_pass:-$ENV_USER_PASS}"                      #
+# ENV_ROOT_USER_NAME="${root_user_name:-$ENV_ROOT_USER_NAME}"       #
+# ENV_ROOT_USER_PASS="${root_user_pass:-$ENV_ROOT_USER_PASS}"       #
 
 EOF
   [ -f "/config/env/${SERVICE_NAME:-$SCRIPT_NAME}.sh" ] || return 1
@@ -209,9 +232,9 @@ __run_start_script() {
   [ -n "$workdir" ] && __cd "$workdir" || { [ -n "$home" ] && __cd "$home"; } || __cd "/tmp"
   [ "$user" != "root " ] && [ -d "$home" ] && chmod -f 777 "$home"
   [ "$user" != "root " ] && [ -d "$workdir" ] && chmod -f 777 "$workdir"
-  echo "Starting service: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
+  echo "Starting service: $EXEC_CMD_NAME $EXEC_CMD_ARGS"
   su_cmd touch "$SERVICE_PID_FILE"
-  __post_execute 2>/dev/stderr | tee -a "/data/logs/entrypoint.log" &>/dev/null &
+  __post_execute 2>/dev/stderr | tee -a "/data/logs/init.d/${SERVICE_NAME}.txt" &
   su_cmd env -i HOME="$home" LC_CTYPE="$lc_type" PATH="$path" USER="$user" sh -c "$cmd" || return 10
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -260,10 +283,25 @@ EXEC_CMD_ARGS="${ENV_EXEC_CMD_ARGS:-$EXEC_CMD_ARGS}"              # command argu
 SERVICE_PID_NUMBER="$(__pgrep)"                                   # check if running
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Allow per init script usernames and passwords
-[ -f "$ETC_DIR/auth/GEN_SCRIPT_REPLACE_APPNAME_user_name" ] && user_name="$(<"$ETC_DIR/auth/GEN_SCRIPT_REPLACE_APPNAME_user_name")"
-[ -f "$ETC_DIR/auth/GEN_SCRIPT_REPLACE_APPNAME_user_pass" ] && user_pass="$(<"$ETC_DIR/auth/GEN_SCRIPT_REPLACE_APPNAME_user_pass")"
-[ -f "$ETC_DIR/auth/GEN_SCRIPT_REPLACE_APPNAME_root_name" ] && root_user_name="$(<"$ETC_DIR/auth/GEN_SCRIPT_REPLACE_APPNAME_root_name")"
-[ -f "$ETC_DIR/auth/GEN_SCRIPT_REPLACE_APPNAME_root_pass" ] && root_user_pass="$(<"$ETC_DIR/auth/GEN_SCRIPT_REPLACE_APPNAME_root_pass")"
+[ -f "$ETC_DIR/auth/user/name" ] && user_name="$(<"$ETC_DIR/auth/user/name")"
+[ -f "$ETC_DIR/auth/user/pass" ] && user_pass="$(<"$ETC_DIR/auth/user/pass")"
+[ -f "$ETC_DIR/auth/root/name" ] && root_user_name="$(<"$ETC_DIR/auth/root/name")"
+[ -f "$ETC_DIR/auth/root/pass" ] && root_user_pass="$(<"$ETC_DIR/auth/root/pass")"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Allow setting initial users and passwords via environment
+user_name="${user_name:-$ENV_USER_NAME}"
+user_pass="${user_pass:-$ENV_USER_PASS}"
+root_user_name="${root_user_name:-$ENV_ROOT_USER_NAME}"
+root_user_pass="${root_user_pass:-$ENV_ROOT_USER_PASS}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+if [ -z "$user_pass" ] && [ "$user_pass" = "random" ]; then
+  user_pass="$(__random_password)"
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+if [ -z "$root_user_pass" ] && [ "$root_user_pass" = "random" ]; then
+  root_user_pass="$(__random_password)"
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Allow variables via imports - Overwrite existing
 [ -f "/config/env/${SERVICE_NAME:-$SCRIPT_NAME}.sh" ] && . "/config/env/${SERVICE_NAME:-$SCRIPT_NAME}.sh"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
