🗃️ Committing everything that changed 🗃️
bin/gen-dockerfile
templates/env/docker/00-directory.sh
templates/env/docker/certbot.sh
templates/env/docker/couchdb.sh
templates/scripts/functions/docker-entrypoint
templates/scripts/other/docker-entrypoint
templates/scripts/other/start-service

diff --git a/templates/scripts/functions/docker-entrypoint b/templates/scripts/functions/docker-entrypoint
--- a/templates/scripts/functions/docker-entrypoint
+++ b/templates/scripts/functions/docker-entrypoint
@@ -48,7 +48,7 @@ __get_ip4() { ip a 2>/dev/null | grep -w 'inet' | awk '{print $2}' | grep -vE '^
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __no_exit() {
   [ -f "/run/no_exit.pid" ] && return
-  exec /bin/sh -c "trap 'sleep 1; rm -Rf /run/no_exit.pid;exit 0' TERM INT; (while true; do echo $!>/run/no_exit.pid;tail -qf /data/logs/entrypoint.log /data/logs/*/*log 2>/dev/null||sleep 20; done) & wait"
+  exec /bin/sh -c "trap 'sleep 1;rm -Rf /run/no_exit.pid;exit 0' TERM INT;(while true; do echo $!>/run/no_exit.pid;tail -qf /data/logs/entrypoint.log /data/logs/*/*log 2>/dev/null||sleep 20; done) & wait"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __find_php_bin() { find -L '/usr'/*bin -maxdepth 4 -name 'php-fpm*' 2>/dev/null | head -n1 | grep '^' || echo ''; }
@@ -275,7 +275,7 @@ __cron() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __replace() {
-  [ -n "$3" ] && [ -f "$3" ] || return 1
+  [ $# -eq 3 ] && [ -e "$3" ] || return 1
   grep -s -qR "$1" "$3" &>/dev/null && __sed "$1" "$2" "$3" || return 0
   grep -s -qR "$2" "$3" && printf '%s\n' "Changed $1 to $2 in $3" && return 0 || {
     printf '%s\n' "Failed to change $1 in $3" >&2 && return 2
@@ -283,7 +283,7 @@ __replace() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __find_replace() {
-  [ -n "$3" ] && [ -e "$3" ] || return 1
+  [ $# -eq 3 ] && [ -e "$3" ] || return 1
   grep -s -qR "$1" "$3" &>/dev/null || return 0
   find "$3" -type f -not -path '.git*' -exec sed -i "s|$1|$2|g" {} \;
   grep -s -qR "$2" "$3" && printf '%s\n' "Changed $1 to $2 in $3" && return 0 || {
@@ -291,12 +291,36 @@ __find_replace() {
   }
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__symlink() {
+  if [ -e "$1" ]; then
+    [ -e "$2" ] && rm -Rf "$2"
+    ln -sf "$1" "$2" && echo "Created symlink to $1 > $2"
+  fi
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __file_copy() {
-  [ -n "$1" ] && [ -e "$1" ] || return 1
-  [ -n "$1" ] && [ -n "$2" ] && [ -e "$1" ] && cp -Rf "$1" "$2" &>/dev/null
-  [ -e "$1" ] && [ -e "$2" ] && printf '%s\n' "Copied: $1 > $2" && return 0 || {
-    printf '%s\n' "Copy failed: $1 < $2" >&2 && return 2
-  }
+  if [ -n "$1" ] && [ -e "$1" ] && [ -n "$2" ]; then
+    if [ -d "$1" ]; then
+      if cp -Rf "$1/." "$2/" &>/dev/null; then
+        printf '%s\n' "Copied: $1 > $2"
+        return 0
+      else
+        printf '%s\n' "Copy failed: $1 < $2" >&2
+        return 1
+      fi
+    else
+      if cp -Rf "$1" "$2" &>/dev/null; then
+        printf '%s\n' "Copied: $1 > $2"
+        return 0
+      else
+        printf '%s\n' "Copy failed: $1 < $2" >&2
+        return 1
+      fi
+    fi
+  else
+    printf '%s\n' "$1 does not exist"
+    return 2
+  fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __generate_random_uids() {
