🗃️ Committing everything that changed 🗃️

diff --git a/templates/scripts/functions/docker-entrypoint b/templates/scripts/functions/docker-entrypoint
--- a/templates/scripts/functions/docker-entrypoint
+++ b/templates/scripts/functions/docker-entrypoint
@@ -32,6 +32,20 @@ __replace() {
   fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__setup_ssl() {
+  [ "$1" = "" ] && return 0
+  [ $# -eq 2 ] || return 1
+  [ "$SSL_ENABLED" = "true" ] || return 0
+  [ -f "$1" ] && cp -Rf "$1" "$2"
+  if [ -f "$1" ] && [ -f "$1" ]; then
+    printf '%s\n' "Copied: $1 > $2"
+    return 0
+  else
+    printf '%s\n' "Copy failed: $1 < $2"
+    return 1
+  fi
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __create_service_user() {
   local create_user="$1" create_gid="$1"
   local home_dir="/opt/$create_user" set_home_dir=""
diff --git a/templates/scripts/other/start-service b/templates/scripts/other/start-service
--- a/templates/scripts/other/start-service
+++ b/templates/scripts/other/start-service
@@ -4,7 +4,12 @@
 trap -- 'retVal=$?;[ "$SERVICE_IS_RUNNING" != "true" ] && [ -f "/tmp/$EXEC_CMD_BIN.pid" ] && rm -Rf "/tmp/$EXEC_CMD_BIN.pid";exit $retVal' SIGINT SIGTERM ERR EXIT
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
-[ "$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x$DEBUGGER_OPTIONS || set -Eeuo pipefail
+[ "$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x$DEBUGGER_OPTIONS || set -Eeo pipefail
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# import the functions file
+if [ -f "/usr/local/share/casjaysdev/functions/entrypoint.sh" ]; then
+  . "/usr/local/share/casjaysdev/functions/entrypoint.sh"
+fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute command options
 WORKDIR=""                                # change to directory
@@ -22,19 +27,14 @@ SERVICE_EXIT_CODE=0                       # default exit code
 # use this function to update config files - IE: change port
 __update_conf_files() {
   # __replace "FROM" "TO" "FILE"
-
-  return $?
+  # __setup_ssl "/config/apache2/httpd.ssl.conf" "/config/apache2/httpd.conf"
+  return 0
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # function to run before executing
 __pre_execute() {
   __create_service_user "$SERVICE_USER" "${SERVICE_UID:-$SERVICE_PORT}"
 }
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# import the functions file
-if [ -f "/usr/local/share/casjaysdev/functions/entrypoint.sh" ]; then
-  . "/usr/local/share/casjaysdev/functions/entrypoint.sh"
-fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # import variables
 [ -f "/root/env.sh" ] && . "/root/env.sh"
