🗃️ Committing everything that changed 🗃️
templates/scripts/bash/simple
templates/scripts/bash/system
templates/scripts/bash/terminal
templates/scripts/bash/user
templates/scripts/completions/system.bash
templates/scripts/completions/user.bash
templates/scripts/installers/mgr-script.system.sh
templates/scripts/installers/mgr-script.user.sh
templates/scripts/os/arch.sh
templates/scripts/os/centos.sh
templates/scripts/os/debian.sh
templates/scripts/os/fedora.sh
templates/scripts/os/macos.sh
templates/scripts/os/void.sh
templates/scripts/other/build

diff --git a/templates/scripts/other/build b/templates/scripts/other/build
--- a/templates/scripts/other/build
+++ b/templates/scripts/other/build
@@ -181,21 +181,21 @@ __packages() {
   #   if cmd_exists pkmgr; then
   #     for pkg in LIST; do
   #        pkmgr silent install "$pkg" |&__devnull
-  #        [  $? = 0  ] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
+  #        [ $? = 0 ] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
   #     done
   #   fi
   # elif cmd_exists dnf; then
   #   if cmd_exists pkmgr; then
   #     for pkg in LIST; do
   #        pkmgr silent install "$pkg" |&__devnull
-  #        [  $? = 0  ] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
+  #        [ $? = 0 ] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
   #     done
   #   fi
   # elif cmd_exists yum; then
   #   if cmd_exists pkmgr; then
   #     for pkg in LIST; do
   #        pkmgr silent install "$pkg" |&__devnull
-  #        [  $? = 0  ] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
+  #        [ $? = 0 ] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
   #     done
   #   fi
   # fi
