🗃️ Committing everything that changed 🗃️
.shellcheckrc
templates/scripts/bash/simple
templates/scripts/bash/system
templates/scripts/bash/terminal
templates/scripts/bash/user
templates/scripts/completions/simple.bash
templates/scripts/completions/system.bash
templates/scripts/completions/user.bash
templates/scripts/installers/desktopmgr.sh
templates/scripts/installers/devenvmgr.sh
templates/scripts/installers/dfmgr.sh
templates/scripts/installers/dockermgr.sh
templates/scripts/installers/fontmgr.sh
templates/scripts/installers/iconmgr.sh
templates/scripts/installers/mgr-script.system.sh
templates/scripts/installers/mgr-script.user.sh
templates/scripts/installers/personal.sh
templates/scripts/installers/systemmgr.sh
templates/scripts/installers/thememgr.sh
templates/scripts/installers/wallpapermgr.sh
templates/scripts/os/arch.sh
templates/scripts/os/centos.sh
templates/scripts/os/debian.sh
templates/scripts/os/fedora.sh
templates/scripts/os/macos.sh
templates/scripts/os/void.sh
templates/scripts/other/autostart
templates/scripts/other/build
templates/scripts/other/docker-entrypoint
templates/scripts/shell/bash
templates/scripts/shell/sh
templates/shellcheckrc

diff --git a/templates/scripts/other/build b/templates/scripts/other/build
--- a/templates/scripts/other/build
+++ b/templates/scripts/other/build
@@ -25,9 +25,9 @@ SRC_DIR="${BASH_SOURCE%/*}"            # Set the dir to script
 PATH="${PATH//:./}"                    # Remove . from path
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set bash options
-[[ "$1" == "--debug" ]] && set -xo pipefail && export SCRIPT_OPTS="--debug" && export _DEBUG="on"
+[ "$1" == "--debug" ] && set -xo pipefail && export SCRIPT_OPTS="--debug" && export _DEBUG="on"
 trap 'exitCode=${exitCode:-$?};[ -n "$GEN_SCRIPT_REPLACE_ENV_TEMP_FILE" ] && [ -f "$GEN_SCRIPT_REPLACE_ENV_TEMP_FILE" ] && rm -Rf "$GEN_SCRIPT_REPLACE_ENV_TEMP_FILE" |&__devnull;exit ${exitCode:-$?}' EXIT
-[[ "$1" == "--raw" ]] && export SHOW_RAW="true"
+[ "$1" == "--raw" ] && export SHOW_RAW="true"
 set -Eo pipefail
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set functions
@@ -48,8 +48,8 @@ __cmd_exists() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # colorization
-if [[ "$SHOW_RAW" = "true" ]]; then
-  printf_color() { printf '%b' "$1\n" | tr -d '\t' | sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'; }
+if [ "$SHOW_RAW" = "true" ]; then
+  printf_color() { printf '%b' "$1\n" | tr -d '\t' | sed '/^%b$/d;s,\x1B\[ 0-9;]*[a-zA-Z],,g'; }
 else
   printf_color() { printf "%b" "$(tput setaf "${2:-7}" 2>/dev/null)" "\t\t$1\n" "$(tput sgr0 2>/dev/null)"; }
 fi
@@ -59,7 +59,7 @@ __version() { echo -e '\t\t'${GREEN:-}"$VERSION"${NC:-}; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # send notifications
 __notifications() {
-  [[ -n "$DISPLAY" ]] && [[ -z "$SSH_CONNECTION" ]] &&
+  [ -n "$DISPLAY" ] && [ -z "$SSH_CONNECTION" ] &&
     __cmd_exists notifications &>/dev/null && notifications "$@" || echo "$*"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -73,8 +73,8 @@ printf_readline() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __help() {
-  [[ -z "$ARRAY" ]] || local array="[${ARRAY//,/ }]"
-  [[ -z "$LONGOPTS" ]] || local opts="[--${LONGOPTS//,/ --}]"
+  [ -z "$ARRAY" ] || local array="[${ARRAY//,/ }]"
+  [ -z "$LONGOPTS" ] || local opts="[--${LONGOPTS//,/ --}]"
   printf_color "Usage: $APPNAME $opts $array" "$BLUE"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -84,13 +84,13 @@ __make_build() {
   local exitCode_make="0"
   local exitCode_cmake="0"
   local exitCode_configure="0"
-  if [[ -f "$BUILD_SRC_DIR/CMakeLists.txt" ]]; then
+  if [ -f "$BUILD_SRC_DIR/CMakeLists.txt" ]; then
     mkdir -p "$BUILD_SRC_DIR/build" && cd "$BUILD_SRC_DIR/build" || exit 10
     cmake .. 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull || exitCode+=1
     make -j$(nproc) 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull || exitCode+=1
     sudo make install DESTDIR="$BUILD_DESTDIR" 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull || exitCode+=1
     exitCode_cmake="$?"
-  elif [[ -f "$BUILD_SRC_DIR/configure" ]]; then
+  elif [ -f "$BUILD_SRC_DIR/configure" ]; then
     printf_color "Running configure" "$GREEN"
     make clean 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull
     ./configure \
@@ -99,21 +99,21 @@ __make_build() {
       --with-pmenu 2>&1 |
       tee -a "$BUILD_LOG_FILE" |& __devnull
     exitCode_configure="$?"
-    if [[ -f "$BUILD_SRC_DIR/Makefile" ]]; then
+    if [ -f "$BUILD_SRC_DIR/Makefile" ]; then
       printf_color "Running make" "$GREEN"
       make -j$(nproc) 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull || exitCode+=1
       sudo make 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull &&
         sudo make install
       exitCode_make="$?"
     fi
-  elif [[ -f "$BUILD_SRC_DIR/Makefile" ]]; then
+  elif [ -f "$BUILD_SRC_DIR/Makefile" ]; then
     printf_color "Running make" "$GREEN"
     make clean 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull
     make -j$(nproc) 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull || exitCode+=1
     sudo make install DESTDIR="$BUILD_DESTDIR" 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull
     exitCode_make="$?"
   fi
-  if [[ "$exitCode_configure" = 0 ]] && [[ "$exitCode_make" = 0 ]] && [[ "$exitCode_cmake" = 0 ]]; then
+  if [ "$exitCode_configure" = 0 ] && [ "$exitCode_make" = 0 ] && [ "$exitCode_cmake" = 0 ]; then
     exitCode=0
   else
     printf_color "Building $BUILD_NAME has failed" "$RED"
@@ -124,20 +124,20 @@ __make_build() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
 # Set main functions
 __run_git() {
-  if [[ -d ".git" ]]; then
+  if [ -d ".git" ]; then
     printf_color "Updating the git repo" "$CYAN"
     git reset --hard 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull &&
       git pull 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull
-    if [[ $? = 0 ]]; then
+    if [ $? = 0 ]; then
       return 0
     else
       printf_color "Failed to update: $BUILD_SRC_DIR" "$RED"
       exit 1
     fi
-  elif [[ -n "$BUILD_SRC_URL" ]]; then
+  elif [ -n "$BUILD_SRC_URL" ]; then
     printf_color "Cloning the git repo to: $BUILD_SRC_DIR" "$CYAN"
     git clone "$BUILD_SRC_URL" "$BUILD_SRC_DIR" 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull
-    if [[ $? = 0 ]]; then
+    if [ $? = 0 ]; then
       return 0
     else
       printf_color "Failed to clone: $BUILD_SRC_URL" "$RED"
@@ -148,16 +148,16 @@ __run_git() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __check_log() {
   local exitCode="$?"
-  if [[ -f "$BUILD_LOG_FILE" ]]; then
+  if [ -f "$BUILD_LOG_FILE" ]; then
     errors="$(grep -i 'fatal error' "$BUILD_LOG_FILE" || echo '')"
     warnings="$(grep -i 'warning: ' "$BUILD_LOG_FILE" || echo '')"
-    if [[ -n "$warnings" ]]; then
+    if [ -n "$warnings" ]; then
       printf_color "The following warnings have occurred:" "$RED"
       echo -e "$warnings" |& printf_readline
       printf_color "Log file saved to $BUILD_LOG_FILE" "$YELLOW"
       exitCode=0
     fi
-    if [[ -n "$errors" ]] || [[ "$exitCode" -ne 0 ]]; then
+    if [ -n "$errors" ] || [ "$exitCode" -ne 0 ]; then
       printf_color "The following errors have occurred:" "$RED"
       echo -e "$errors" |& printf_readline
       printf_color "Log file saved to $BUILD_LOG_FILE" "$YELLOW"
@@ -178,21 +178,21 @@ __packages() {
   #   if cmd_exists pkmgr; then
   #     for pkg in LIST; do
   #        pkmgr silent install "$pkg" |&__devnull
-  #        [[ $? = 0 ]] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
+  #        [  $? = 0  ] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
   #     done
   #   fi
   # elif cmd_exists dnf; then
   #   if cmd_exists pkmgr; then
   #     for pkg in LIST; do
   #        pkmgr silent install "$pkg" |&__devnull
-  #        [[ $? = 0 ]] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
+  #        [  $? = 0  ] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
   #     done
   #   fi
   # elif cmd_exists yum; then
   #   if cmd_exists pkmgr; then
   #     for pkg in LIST; do
   #        pkmgr silent install "$pkg" |&__devnull
-  #        [[ $? = 0 ]] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
+  #        [  $? = 0  ] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
   #     done
   #   fi
   # fi
@@ -201,7 +201,7 @@ __packages() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __init() {
-  if [[ -z "$BUILD_FORCE" ]] && [[ -f "$(builtin type -P "$BUILD_NAME" 2>/dev/null)" ]]; then
+  if [ -z "$BUILD_FORCE" ] && [ -f "$(builtin type -P "$BUILD_NAME" 2>/dev/null)" ]; then
     printf_color "$BUILD_NAME is already installed at:" "$RED" 1>&2
     printf_color "$(builtin type -P "$BUILD_NAME" "$GREEN" 2>/dev/null)"
     printf_color "run with --force to rebuild" "$YELLOW" 1>&2
@@ -302,7 +302,7 @@ else
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main application
-if [[ -d "$BUILD_SRC_DIR" ]]; then
+if [ -d "$BUILD_SRC_DIR" ]; then
   if ! builtin cd "$BUILD_SRC_DIR"; then
     printf_color "Failed to cd into $BUILD_SRC_DIR" "$RED"
     exit 1
@@ -316,7 +316,7 @@ if [[ -d "$BUILD_SRC_DIR" ]]; then
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # check
-if [[ "$exitCode" -eq 10 || "$exitCode" -eq 0 ]] && [[ -n "$(builtin type -P "$BUILD_NAME")" ]]; then
+if { [ "$exitCode" -eq 10 ] || [ "$exitCode" -eq 0 ]; } && [ -n "$(builtin type -P "$BUILD_NAME")" ]; then
   printf_color "Successfully installed $BUILD_NAME" "$GREEN"
   exitCode=0
 else
