🗃️ Committing everything that changed 🗃️

diff --git a/templates/scripts/other/docker-entrypoint b/templates/scripts/other/docker-entrypoint
--- a/templates/scripts/other/docker-entrypoint
+++ b/templates/scripts/other/docker-entrypoint
@@ -19,8 +19,7 @@
 # @@Template         :  other/docker-entrypoint
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set bash options
-set -o pipefail
-[ "$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -x$DEBUGGER_OPTIONS
+[ "$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x$DEBUGGER_OPTIONS || set -o pipefail
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set functions
 __exec_command() {
@@ -330,8 +329,8 @@ case "$1" in
   ;;
 
 healthcheck) # Docker healthcheck
-  __heath_check || exitCode=10
-  exit ${exitCode:-$?}
+  __heath_check
+  exit $?
   ;;
 
 ports)
@@ -349,7 +348,7 @@ procs)
 */bin/sh | */bin/bash | bash | shell | sh) # Launch shell
   shift 1
   __exec_command "${@:-/bin/bash}"
-  exit ${exitCode:-$?}
+  exit $?
   ;;
 
 certbot)
@@ -364,21 +363,27 @@ certbot)
   else
     __exec_command "certbot" "$@"
   fi
+  exit $?
+  ;;
+
+exec)
+  shift 1
+  __exec_command "${@:-bash}"
+  exit $?
   ;;
 
 *) # Execute primary command
   if [ $# -eq 0 ]; then
-    exec "$0"
+    __start_all_services
     exit $?
   else
     __exec_command "$@"
-    exitCode=$?
+    exit $?
   fi
   ;;
 esac
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end of entrypoint
-exit ${exitCode:-$?}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
 # ex: ts=2 sw=2 et filetype=sh
diff --git a/templates/scripts/other/start-service b/templates/scripts/other/start-service
--- a/templates/scripts/other/start-service
+++ b/templates/scripts/other/start-service
@@ -18,12 +18,8 @@
 # @@sudo/root        :  GEN_SCRIPT_REPLACE_SUDO
 # @@Template         :  other/start-service
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Set trap
-trap -- 'retVal=$?;kill -9 $$;exit $retVal' SIGINT
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set bash options
-set -o pipefail
-[ "$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -x$DEBUGGER_OPTIONS
+[ "$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x$DEBUGGER_OPTIONS || set -o pipefail
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set functions
 __cd() { [ -d "$1" ] && builtin cd "$1" || return 1; }
@@ -51,7 +47,6 @@ __exec_command() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __exec_service_start() {
-  [ -n "$DEBUG" ] && set -x
   local exitCode=0 cmd="${SERVICE_COMMAND:-false}"
   sleep 30
   echo "Setting up service to run as $SERVICE_USER"
@@ -191,6 +186,7 @@ case "$1" in
 backup)
   shift 1
   __run_backup "${1:-$BACKUP_DIR}"
+  exit $?
   ;;
 
 certbot)
@@ -199,26 +195,24 @@ certbot)
   if [ "$1" = "create" ]; then
     shift 1
     __certbot
+    exit $?
   elif [ "$1" = "renew" ]; then
     shift 1
     __certbot "renew certonly --force-renew"
+    exit $?
   else
     __exec_command "certbot" "$@"
+    exit $?
   fi
   ;;
 
 *)
   __exec_pre_start && __exec_service_start
+  exit $?
   ;;
 esac
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Set exit code
-exitCode="${exitCode:-$?}"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# lets exit with code
-exit ${exitCode:-$?}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# end
+
 # ex: ts=2 sw=2 et filetype=sh
