🗃️ Committing everything that changed 🗃️
templates/scripts/other/start-service

diff --git a/templates/scripts/other/start-service b/templates/scripts/other/start-service
--- a/templates/scripts/other/start-service
+++ b/templates/scripts/other/start-service
@@ -260,7 +260,7 @@ __pre_execute() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # function to run after executing
 __post_execute() {
-  local message="Running post commands"                          # message to show
+  local postMessage="Running post commands"                      # message to show
   local waitTime=60                                              # how long to wait before executing
   local exitCode=0                                               # default exit code
   local sysname="${SERVER_NAME:-${FULL_DOMAIN_NAME:-$HOSTNAME}}" # set hostname
@@ -268,13 +268,12 @@ __post_execute() {
   # execute commands
   (
     sleep 60
-    echo "$message"
+    echo "$postMessage"
     # commands to execute
     true
     # code to return
     return ${retVal:-0}
   ) 2>"/dev/stderr" | tee -p -a "$LOG_DIR/init.txt" >/dev/null
-  exitCode="$?"
   return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -361,8 +360,8 @@ __run_start_script() {
       echo "$name is already running" >&2
       return 0
     else
-      # cd to dir
       # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+      # cd to dir
       __cd "${workdir:-$home}"
       # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       # show message if env exists
@@ -411,7 +410,7 @@ echo $! >"$SERVICE_PID_FILE"
 EOF
         fi
         [ -x "$START_SCRIPT" ] || chmod 755 -Rf "$START_SCRIPT"
-        eval $su_exec sh -c "$START_SCRIPT"
+        eval $su_exec "$START_SCRIPT"
         runExitCode=$?
       fi
       return $runExitCode
@@ -567,12 +566,14 @@ __run_secure_function
 # run the pre execute commands
 __pre_execute
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__run_start_script |& tee -p -a "/data/logs/entrypoint.log" "$LOG_DIR/init.txt" &>/dev/null && errorCode=0 || errorCode=10
+__run_start_script 2>>/dev/stderr | tee -p -a "/data/logs/entrypoint.log" "$LOG_DIR/init.txt" >/dev/null && errorCode=0 || errorCode=10
 if [ "$errorCode" -ne 0 ] && [ -n "$EXEC_CMD_BIN" ]; then
-  eval echo "Failed to execute: ${cmd_exec:-$EXEC_CMD_BIN $EXEC_CMD_ARGS}" |& tee -p -a "/data/logs/entrypoint.log" "$LOG_DIR/init.txt"
+  echo "Failed to execute: ${cmd_exec:-$EXEC_CMD_BIN $EXEC_CMD_ARGS}" | tee -p -a "$LOG_DIR/init.txt"
   rm -Rf "$SERVICE_PID_FILE"
   SERVICE_EXIT_CODE=10
   SERVICE_IS_RUNNING="false"
 fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+printf '%s\n' "# - - - Initializing of GEN_SCRIPT_REPLACE_APPNAME has completed with statusCode: $SERVICE_EXIT_CODE - - - #" | tee -p -a "/data/logs/entrypoint.log" "$LOG_DIR/init.txt"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 exit $SERVICE_EXIT_CODE
