🗃️ Committing everything that changed 🗃️

diff --git a/templates/scripts/other/start-service b/templates/scripts/other/start-service
--- a/templates/scripts/other/start-service
+++ b/templates/scripts/other/start-service
@@ -20,6 +20,7 @@ done
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute command variables
 WORKDIR=""                                # change to directory
+ALT_SCRIPT="no"                           # Set to yes to run the __alt_execute_script
 SERVICE_USER="root"                       # execute command as another user
 SERVICE_UID=""                            # set the user id
 SERVICE_PORT=""                           # port which service is listening on
@@ -49,19 +50,24 @@ __pre_execute() {
   return 0
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# alternate script to start server
+__alt_execute_script() { true; }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # process check functions
 __pcheck() { [ -n "$(type -P pgrep 2>/dev/null)" ] && pgrep -x "$1" &>/dev/null && return 0 || return 10; }
 __pgrep() { __pcheck "${1:-EXEC_CMD_BIN}" || __ps aux 2>/dev/null | grep -Fw " ${1:-$EXEC_CMD_BIN}" | grep -qv ' grep' | grep '^' && return 0 || return 10; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Allow ENV_ variable
 [ -f "/config/env/$EXEC_CMD_BIN.sh" ] && "/config/env/$EXEC_CMD_BIN.sh" # Import env file
-WORKDIR="${ENV_WORKDIR:-$WORKDIR}"                                      # change to directory
-SERVICE_USER="${ENV_SERVICE_USER:-$SERVICE_USER}"                       # execute command as another user
-SERVICE_UID="${ENV_SERVICE_UID:-$SERVICE_UID}"                          # set the user id
-SERVICE_PORT="${ENV_SERVICE_PORT:-$SERVICE_PORT}"                       # port which service is listening on
-EXEC_CMD_BIN="${ENV_EXEC_CMD_BIN:-$EXEC_CMD_BIN}"                       # command to execute
-EXEC_CMD_ARGS="${ENV_EXEC_CMD_ARGS:-$EXEC_CMD_ARGS}"                    # command arguments
-PRE_EXEC_MESSAGE="${ENV_PRE_EXEC_MESSAGE:-$PRE_EXEC_MESSAGE}"           # Show message before execute
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+WORKDIR="${ENV_WORKDIR:-$WORKDIR}"                            # change to directory
+ALT_SCRIPT="${ENV_ALT_SCRIPT:-$ALT_SCRIPT}"                   # Set to yes to run the __alt_execute_script
+SERVICE_USER="${ENV_SERVICE_USER:-$SERVICE_USER}"             # execute command as another user
+SERVICE_UID="${ENV_SERVICE_UID:-$SERVICE_UID}"                # set the user id
+SERVICE_PORT="${ENV_SERVICE_PORT:-$SERVICE_PORT}"             # port which service is listening on
+EXEC_CMD_BIN="${ENV_EXEC_CMD_BIN:-$EXEC_CMD_BIN}"             # command to execute
+EXEC_CMD_ARGS="${ENV_EXEC_CMD_ARGS:-$EXEC_CMD_ARGS}"          # command arguments
+PRE_EXEC_MESSAGE="${ENV_PRE_EXEC_MESSAGE:-$PRE_EXEC_MESSAGE}" # Show message before execute
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 printf '%s\n' "# - - - Attempting to start $EXEC_CMD_BIN - - - #"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -129,7 +135,11 @@ else
 fi
 export SERVICE_IS_RUNNING="true"
 su_cmd "touch /run/$EXEC_CMD_BIN.init.pid"
-su_cmd "$EXEC_CMD_BIN $EXEC_CMD_ARGS" || echo "Failed to execute: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
+if [ "$ALT_SCRIPT" = "yes" ]; then
+  __alt_execute_script "$@"
+else
+  su_cmd "$EXEC_CMD_BIN $EXEC_CMD_ARGS" || echo "Failed to execute: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
+fi
 [ "$?" -ne 0 ] && SERVICE_IS_RUNNING="false" && SERVICE_EXIT_CODE=10 && rm -Rf "/run/$EXEC_CMD_BIN.init.pid"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 exit $SERVICE_EXIT_CODE
