🗃️  Committing everything that changed 🗃️

diff --git a/templates/scripts/other/start-service b/templates/scripts/other/start-service
--- a/templates/scripts/other/start-service
+++ b/templates/scripts/other/start-service
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+printf '%s\n' "# - - - Initializing GEN_SCRIPT_REPLACE_APPNAME - - - #"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
 SCRIPT_NAME="$(basename "$0" 2>/dev/null)"
 [ "$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x$DEBUGGER_OPTIONS || set -o pipefail
@@ -7,7 +9,7 @@ SCRIPT_NAME="$(basename "$0" 2>/dev/null)"
 export PATH="/usr/local/etc/docker/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # run trap command on exit
-trap 'retVal=$?;[ "$SERVICE_IS_RUNNING" != "true" ] && [ -f "/run/init.d/$EXEC_CMD_BIN.pid" ] && rm -Rf "/run/init.d/$EXEC_CMD_BIN.pid";exit $retVal' SIGINT SIGTERM EXIT
+trap 'retVal=$?;[ "$SERVICE_IS_RUNNING" != "true" ] && [ -f "$SERVICE_PID_FILE" ] && rm -Rf "$SERVICE_PID_FILE";exit $retVal' SIGINT SIGTERM EXIT
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # import the functions file
 if [ -f "/usr/local/etc/docker/functions/entrypoint.sh" ]; then
@@ -22,70 +24,89 @@ done
 # Custom functions
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Predifined variables
-WORKDIR=""                                # set working directory
-
+# Predefined variables
+WORKDIR=""                                                      # set working directory
+DATA_DIR="/data"                                                # set data directory
+WWW_DIR="/data/www"                                             # set the web root
+ETC_DIR="/etc/GEN_SCRIPT_REPLACE_APPNAME"                       # set etc directory
+CONF_DIR="/config/GEN_SCRIPT_REPLACE_APPNAME"                   # set data directory
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Script variables
-SERVICE_PORT=""                           # port which service is listening on
-PRE_EXEC_MESSAGE=""                       # Show message before execute
-
+SERVICE_PORT=""                                                 # port which service is listening on
+PRE_EXEC_MESSAGE=""                                             # Show message before execute
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute command variables
-SERVICE_UID="0"                           # set the user id
-SERVICE_USER="root"                       # execute command as another user
-EXEC_CMD_BIN="GEN_SCRIPT_REPLACE_APPNAME" # command to execute
-EXEC_CMD_ARGS=" "                         # command arguments
+SERVICE_UID="0"                                                 # set the user id
+SERVICE_USER="root"                                             # execute command as another user
+EXEC_CMD_BIN="GEN_SCRIPT_REPLACE_APPNAME"                       # command to execute
+EXEC_CMD_ARGS=" "                                               # command arguments
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # use this function to update config files - IE: change port
 __update_conf_files() {
+  local exitCode=0
 
-  return 0
+  return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # use this function to setup ssl support
 __update_ssl_conf() {
+  local exitCode=0
 
-  return 0
+  return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # function to run before executing
 __pre_execute() {
+  local exitCode=0
 
-  return 0
+  return $exitCode
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # script to start server
 __run_start_script() {
+  local user="${SERVICE_USER:-}"
   local workdir="${WORKDIR:-$HOME}"
   local cmd="$EXEC_CMD_BIN $EXEC_CMD_ARGS"
-  local user="${SERVICE_USER:-root}"
   local lc_type="${LC_ALL:-${LC_CTYPE:-$LANG}}"
-  local home="${workdir//\/root/\/home\/docker}"
+  local home="${workdir//\/root/\/tmp\/docker}"
   local path="/usr/local/bin:/usr/bin:/bin:/usr/sbin"
+  mkdir -p "$home" && __cd "$home"
   case "$1" in
   check) shift 1 && __pgrep $EXEC_CMD_BIN || return 5 ;;
   *) su_cmd env -i PWD="$home" HOME="$home" LC_CTYPE="$lc_type" PATH="$path" USER="$user" sh -c "$cmd" || return 10 ;;
   esac
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# simple cd function
+__cd() { su_cmd mkdir -p "$1" && su_cmd \cd "$1" || exit 1; }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # process check functions
 __pcheck() { [ -n "$(type -P pgrep 2>/dev/null)" ] && pgrep -x "$1" &>/dev/null && return 0 || return 10; }
 __pgrep() { __pcheck "${1:-EXEC_CMD_BIN}" || __ps aux 2>/dev/null | grep -Fw " ${1:-$EXEC_CMD_BIN}" | grep -qv ' grep' | grep '^' && return 0 || return 10; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Allow ENV_ variable
-[ -f "/config/env/$EXEC_CMD_BIN.sh" ] && "/config/env/$EXEC_CMD_BIN.sh" # Import env file
+# Allow ENV_ variable - Import env file
+[ -f "/config/env/$EXEC_CMD_BIN.sh" ] && "/config/env/$EXEC_CMD_BIN.sh"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-WORKDIR="${ENV_WORKDIR:-$WORKDIR}"                            # change to directory
-SERVICE_USER="${ENV_SERVICE_USER:-$SERVICE_USER}"             # execute command as another user
-SERVICE_UID="${ENV_SERVICE_UID:-$SERVICE_UID}"                # set the user id
-SERVICE_PORT="${ENV_SERVICE_PORT:-$SERVICE_PORT}"             # port which service is listening on
-EXEC_CMD_BIN="${ENV_EXEC_CMD_BIN:-$EXEC_CMD_BIN}"             # command to execute
-EXEC_CMD_ARGS="${ENV_EXEC_CMD_ARGS:-$EXEC_CMD_ARGS}"          # command arguments
-PRE_EXEC_MESSAGE="${ENV_PRE_EXEC_MESSAGE:-$PRE_EXEC_MESSAGE}" # Show message before execute
-SERVICE_EXIT_CODE=0                                           # default exit code
+SERVICE_EXIT_CODE=0                                             # default exit code
+WORKDIR="${ENV_WORKDIR:-$WORKDIR}"                              # change to directory
+WWW_DIR="${ENV_WWW_DIR:-$WWW_DIR}"                              # set default web dir
+ETC_DIR="${ENV_ETC_DIR:-$ETC_DIR}"                              # set default etc dir
+DATA_DIR="${ENV_DATA_DIR:-$DATA_DIR}"                           # set default data dir
+CONF_DIR="${ENV_CONF_DIR:-$CONF_DIR}"                           # set default config dir
+SERVICE_USER="${ENV_SERVICE_USER:-$SERVICE_USER}"               # execute command as another user
+SERVICE_UID="${ENV_SERVICE_UID:-$SERVICE_UID}"                  # set the user id
+SERVICE_PORT="${ENV_SERVICE_PORT:-$SERVICE_PORT}"               # port which service is listening on
+PRE_EXEC_MESSAGE="${ENV_PRE_EXEC_MESSAGE:-$PRE_EXEC_MESSAGE}"   # Show message before execute
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-printf '%s\n' "# - - - Attempting to start $EXEC_CMD_BIN - - - #"
+# application specific
+SERVICE_PID_NUMBER="$(__pgrep)"                                 # check if running
+SERVICE_PID_FILE="/run/init.d/$EXEC_CMD_BIN.pid"                # set the pid file location
+EXEC_CMD_BIN="${ENV_EXEC_CMD_BIN:-$EXEC_CMD_BIN}"               # command to execute
+EXEC_CMD_ARGS="${ENV_EXEC_CMD_ARGS:-$EXEC_CMD_ARGS}"            # command arguments
+EXEC_CMD_NAME="$(basename "$EXEC_CMD_BIN")"                     # set the binary name
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Allow variable via imports
+[ -f "/config/env/$EXEC_CMD_BIN.sh" ] && "/config/env/$EXEC_CMD_BIN.sh"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # ensure the command exists
 if [ ! -f "$(type -P "$EXEC_CMD_BIN")" ] && [ -z "$EXEC_CMD_BIN" ]; then
@@ -94,33 +115,20 @@ if [ ! -f "$(type -P "$EXEC_CMD_BIN")" ] && [ -z "$EXEC_CMD_BIN" ]; then
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # check if process is already running
-if __pgrep "$EXEC_CMD_BIN"; then
+if __pgrep "$EXEC_CMD_NAME" || __pgrep "$EXEC_CMD_BIN"; then
   SERVICE_IS_RUNNING="true"
-  echo "$EXEC_CMD_BIN is running"
+  touch "$SERVICE_PID_FILE"
+  echo "$EXEC_CMD_NAME is already running"
   exit 0
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # show message if env exists
 if [ -n "$EXEC_CMD_BIN" ]; then
-  [ -n "$SERVICE_USER" ] && echo "Setting up service to run as $SERVICE_USER"
-  [ -n "$SERVICE_PORT" ] && echo "$EXEC_CMD_BIN will be running on $SERVICE_PORT"
+  [ -n "$SERVICE_USER" ] && echo "Setting up service to run as $SERVICE_USER" || SERVICE_USER="root"
+  [ -n "$SERVICE_PORT" ] && echo "$EXEC_CMD_BIN will be running on $SERVICE_PORT" || SERVICE_PORT=""
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Change to working directory
-[ -n "$WORKDIR" ] && mkdir -p "$WORKDIR" && __cd "$WORKDIR" && echo "Changed to $PWD"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Initialize ssl
-__update_ssl_conf
-__update_ssl_certs
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Updating config files
-__update_conf_files
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# run the pre execute commands
-[ -n "$PRE_EXEC_MESSAGE" ] && echo "$PRE_EXEC_MESSAGE"
-__pre_execute
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-WORKDIR="${WORKDIR:-}"
+# set switch user command
 if [ "$SERVICE_USER" = "root" ] || [ -z "$SERVICE_USER" ]; then
   su_cmd() { eval "$@" || return 1; }
 elif [ "$(builtin type -P gosu)" ]; then
@@ -135,22 +143,33 @@ else
   echo "Can not switch to $SERVICE_USER: attempting to run as root"
   su_cmd() { eval "$@" || return 1; }
 fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Change to working directory
+[ -n "$WORKDIR" ] && __cd "$WORKDIR" && echo "Changed to $PWD"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Initialize ssl
+__update_ssl_conf
+__update_ssl_certs
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Updating config files
+__update_conf_files
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# run the pre execute commands
+[ -n "$PRE_EXEC_MESSAGE" ] && echo "$PRE_EXEC_MESSAGE"
+__pre_execute
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+WORKDIR="${WORKDIR:-}"
 if [ -n "$WORKDIR" ] && [ "${SERVICE_USER:-$USER}" != "root" ]; then
   echo "Fixing file permissions"
   su_cmd chown -Rf $SERVICE_USER $WORKDIR $etc_dir $var_dir $log_dir
 fi
-if __pgrep $EXEC_CMD_BIN && [ -f "/run/init.d/$EXEC_CMD_BIN.pid" ]; then
-  SERVICE_EXIT_CODE=1
-  echo "$EXEC_CMD_BIN" is already running
-else
-  echo "Starting service: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
-  su_cmd touch /run/init.d/$EXEC_CMD_BIN.pid
-  __run_start_script "$@" |& tee -a "/data/logs/entrypoint.log"
-  if [ "$?" -ne 0 ]; then
-    echo "Failed to execute: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
-    SERVICE_EXIT_CODE=10 SERVICE_IS_RUNNING="false"
-    su_cmd rm -Rf "/run/init.d/$EXEC_CMD_BIN.pid"
-  fi
+echo "Starting service: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
+su_cmd touch $SERVICE_PID_FILE
+__run_start_script "$@" |& tee -a "/data/logs/entrypoint.log"
+if [ "$?" -ne 0 ]; then
+  echo "Failed to execute: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
+  SERVICE_EXIT_CODE=10 SERVICE_IS_RUNNING="false"
+  su_cmd rm -Rf "$SERVICE_PID_FILE"
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 exit $SERVICE_EXIT_CODE
