🗃️ Committing everything that changed 🗃️
bin/gen-dockerfile
templates/scripts/functions/docker-entrypoint
templates/scripts/other/docker-entrypoint
templates/scripts/other/start-service

diff --git a/templates/scripts/other/start-service b/templates/scripts/other/start-service
--- a/templates/scripts/other/start-service
+++ b/templates/scripts/other/start-service
@@ -48,6 +48,19 @@ for set_env in "/root/env.sh" "/usr/local/etc/docker/env"/*.sh "/config/env"/*.s
   [ -f "$set_env" ] && . "$set_env"
 done
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Run any pre-execution checks
+__run_pre_execute_checks() {
+  local exitStatus=0
+
+  true
+  exitStatus=$?
+  if [ $exitStatus -ne 0 ]; then
+    echo "The pre-execution check has failed"
+    exit ${exitStatus:-20}
+  fi
+  return $exitStatus
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Custom functions
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -243,6 +256,9 @@ __pre_execute() {
 
   # create user if needed
   # __create_service_user "$user" "${WORK_DIR:-/home/$user}" "$SERVICE_UID" "$SERVICE_GID"
+
+  # Run Custom command
+
   # set user on files/folders
   if [ -n "$user" ] && [ "$user" != "root" ]; then
     if grep -sq "^$user:" "/etc/passwd"; then
@@ -262,6 +278,9 @@ __pre_execute() {
       done
     fi
   fi
+
+  # Run checks
+  __run_pre_execute_checks
 
   # unset unneeded variables
   unset filesperms filename
@@ -350,7 +369,7 @@ __run_start_script() {
   local workdir="${WORK_DIR:-$WORK_DIR}"
   local lc_type="${LC_ALL:-${LC_CTYPE:-$LANG}}"
   local home="${workdir//\/root/\/tmp\/docker}"
-  local path="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"
+  local path="$PATH"
   local sysname="${SERVER_NAME:-$HOSTNAME}" # set hostname
   local message=""
   if [ -z "$cmd" ]; then
