🗃️  Committing everything that changed 🗃️

diff --git a/templates/scripts/other/start-service b/templates/scripts/other/start-service
--- a/templates/scripts/other/start-service
+++ b/templates/scripts/other/start-service
@@ -30,23 +30,21 @@ done
 PRE_EXEC_MESSAGE=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Default predefined variables
-WORKDIR=""       # set working directory
-DATA_DIR="/data" # set data directory
+WORKDIR=""                 # set working directory
+DATA_DIR="/data"           # set data directory
+WWW_DIR="/data/htdocs/www" # set the web root
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ETC_DIR="/etc/GEN_SCRIPT_REPLACE_APPNAME"     # set etc directory
-CONF_DIR="/config/GEN_SCRIPT_REPLACE_APPNAME" # set data directory
+CONF_DIR="/config/GEN_SCRIPT_REPLACE_APPNAME" # set config directory
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 RUN_DIR="/run/init.d"                           # set scripts pid dir
 LOG_DIR="/data/logs/GEN_SCRIPT_REPLACE_APPNAME" # set log directory
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-ROOT_FILE_PREFIX="/config/secure/auth/root" # directory to save password for root user
-USER_FILE_PREFIX="/config/secure/auth/user" # directory to save password for normal user
+ROOT_FILE_PREFIX="/config/secure/auth/root" # directory to save username/password for root user
+USER_FILE_PREFIX="/config/secure/auth/user" # directory to save username/password for normal user
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-WWW_DIR="/data/htdocs/www" # set the web root
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-DATABASE_DIR="/data/db/GEN_SCRIPT_REPLACE_APPNAME" # set the database directory
-# lets use environment for database dir if available
-[ -n "$DATABASE_DIR_GEN_SCRIPT_REPLACE_ENV" ] && DATABASE_DIR="$DATABASE_DIR_GEN_SCRIPT_REPLACE_ENV"
+# set the database directory
+DATABASE_DIR="${DATABASE_DIR_GEN_SCRIPT_REPLACE_ENV:-/data/db/GEN_SCRIPT_REPLACE_APPNAME}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Additional predefined variables
 
@@ -60,20 +58,22 @@ SERVICE_USER="root"                       # execute command as another user
 EXEC_CMD_BIN="GEN_SCRIPT_REPLACE_APPNAME" # command to execute
 EXEC_CMD_ARGS=""                          # command arguments
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Is this service a database server
+# Is this service a web server
 IS_WEB_SERVER="no"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Is this service a database server
 IS_DATABASE_SERVICE="no"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Additional variables
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # usernames
-user_name="${GEN_SCRIPT_REPLACE_ENV_USER_NAME:-}"
-root_user_name="${GEN_SCRIPT_REPLACE_ENV_ROOT_USER_NAME:-}"
+user_name="${GEN_SCRIPT_REPLACE_ENV_USER_NAME:-}"           # normal user name
+root_user_name="${GEN_SCRIPT_REPLACE_ENV_ROOT_USER_NAME:-}" # root user name
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # passwords [password/random]
-user_pass="${GEN_SCRIPT_REPLACE_ENV_USER_PASSWORD:-}"
-root_user_pass="${GEN_SCRIPT_REPLACE_ENV_ROOT_PASSWORD:-}"
+user_pass="${GEN_SCRIPT_REPLACE_ENV_USER_PASS_WORD:-}"      # normal user password
+root_user_pass="${GEN_SCRIPT_REPLACE_ENV_ROOT_PASS_WORD:-}" # root user password
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Overwrite variables from files
 [ -f "${USER_FILE_PREFIX}/${SERVICE_NAME}_name" ] && user_name="$(<"${USER_FILE_PREFIX}/${SERVICE_NAME}_name")"
@@ -222,9 +222,12 @@ __run_start_script() {
   local lc_type="${LC_ALL:-${LC_CTYPE:-$LANG}}"
   local home="${workdir//\/root/\/tmp\/docker}"
   local path="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"
-  if [ -n "$EXEC_CMD_BIN" ]; then
+  if [ -z "$EXEC_CMD_BIN" ]; then
+    echo "Initializing $SCRIPT_NAME has completed"
+    __post_execute 2>"/dev/stderr" |& tee -a "$LOG_DIR/init.txt" &>/dev/null &
+  else
     # ensure the command exists
-    if [ ! -x "$(type -P "$EXEC_CMD_BIN")" ]; then
+    if [ ! -x "$EXEC_CMD_BIN" ]; then
       echo "$EXEC_CMD_NAME is not a valid executable"
       exit 2
     fi
@@ -245,12 +248,9 @@ __run_start_script() {
     else
       echo "Starting service: $EXEC_CMD_NAME $EXEC_CMD_ARGS"
       su_cmd touch "$SERVICE_PID_FILE"
-      __post_execute 2>/dev/stderr 2>&1 |& tee -a "$LOG_DIR/init.txt" &>/dev/null &
+      __post_execute 2>"/dev/stderr" 2>&1 |& tee -a "$LOG_DIR/init.txt" &>/dev/null &
       su_cmd env -i HOME="$home" LC_CTYPE="$lc_type" PATH="$path" USER="$user" sh -c "$cmd" || return 10
     fi
-  else
-    echo "Initializing $SCRIPT_NAME has completed"
-    __post_execute 2>/dev/stderr 2>&1 |& tee -a "$LOG_DIR/init.txt" &>/dev/null &
   fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -311,8 +311,8 @@ SERVICE_PORT="${ENV_SERVICE_PORT:-$SERVICE_PORT}"             # port which servi
 PRE_EXEC_MESSAGE="${ENV_PRE_EXEC_MESSAGE:-$PRE_EXEC_MESSAGE}" # Show message before execute
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # application specific
-EXEC_CMD_BIN="$(type -P "$EXEC_CMD_BIN" || echo "$EXEC_CMD_BIN")" # set full path
 EXEC_CMD_BIN="${ENV_EXEC_CMD_BIN:-$EXEC_CMD_BIN}"                 # command to execute
+EXEC_CMD_BIN="$(type -P "$EXEC_CMD_BIN" || echo "$EXEC_CMD_BIN")" # set full path
 EXEC_CMD_NAME="$(basename "$EXEC_CMD_BIN")"                       # set the binary name
 SERVICE_PID_FILE="/run/init.d/$EXEC_CMD_NAME.pid"                 # set the pid file location
 EXEC_CMD_ARGS="${ENV_EXEC_CMD_ARGS:-$EXEC_CMD_ARGS}"              # command arguments
@@ -332,7 +332,8 @@ SERVICE_PID_NUMBER="$(__pgrep)"                                   # check if run
 user_name="${user_name:-$ENV_USER_NAME}"
 user_pass="${user_pass:-$ENV_USER_PASS}"
 root_user_name="${root_user_name:-$ENV_ROOT_USER_NAME}"
-root_user_pass="${root_user_pass:-$ENV_ROOT_USER_PASS}" # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+root_user_pass="${root_user_pass:-$ENV_ROOT_USER_PASS}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # set password to random if variable is random
 if [ "$user_pass" = "random" ]; then
   user_pass="$(__random_password)"
@@ -354,12 +355,12 @@ fi
 # show message if env exists
 if [ -n "$EXEC_CMD_BIN" ]; then
   [ -n "$SERVICE_USER" ] && echo "Setting up service to run as $SERVICE_USER" || SERVICE_USER="root"
-  [ -n "$SERVICE_PORT" ] && echo "$EXEC_CMD_NAME will be running on $SERVICE_PORT" || SERVICE_PORT=""
+  [ -n "$SERVICE_PORT" ] && echo "${EXEC_CMD_NAME:-$EXEC_CMD_BIN} will be running on $SERVICE_PORT" || SERVICE_PORT=""
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # set switch user command
 if [ "$SERVICE_USER" = "root" ] || [ -z "$SERVICE_USER" ]; then
-  su_cmd() { eval "$@" || return 1; }
+  su_cmd() { eval "$*" || return 1; }
 elif [ "$(builtin type -P gosu)" ]; then
   su_cmd() { gosu $SERVICE_USER "$@" || return 1; }
 elif [ "$(builtin type -P runuser)" ]; then
@@ -370,7 +371,7 @@ elif [ "$(builtin type -P su)" ]; then
   su_cmd() { su -s /bin/sh - $SERVICE_USER -c "$@" || return 1; }
 else
   echo "Can not switch to $SERVICE_USER: attempting to run as root"
-  su_cmd() { eval "$@" || return 1; }
+  su_cmd() { eval "$*" || return 1; }
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Change to working directory
@@ -394,9 +395,10 @@ __run_secure_function
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __run_start_script "$@" |& tee -a "/data/logs/entrypoint.log" &>/dev/null
 if [ "$?" -ne 0 ] && [ -n "$EXEC_CMD_BIN" ]; then
-  echo "Failed to execute: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
-  SERVICE_EXIT_CODE=10 SERVICE_IS_RUNNING="false"
-  su_cmd rm -Rf "$SERVICE_PID_FILE"
+  echo "Failed to execute: $EXEC_CMD_BIN $EXEC_CMD_ARGS" |& tee -a "/data/logs/entrypoint.log" "$LOG_DIR/init.txt"
+  SERVICE_EXIT_CODE=10
+  SERVICE_IS_RUNNING="false"
+  rm -Rf "$SERVICE_PID_FILE"
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 exit $SERVICE_EXIT_CODE
