🗃️ Committing everything that changed 🗃️
templates/scripts/functions/docker-entrypoint
templates/scripts/other/docker-entrypoint
templates/scripts/other/start-service

diff --git a/templates/scripts/other/start-service b/templates/scripts/other/start-service
--- a/templates/scripts/other/start-service
+++ b/templates/scripts/other/start-service
@@ -83,11 +83,9 @@ START_SCRIPT="/usr/local/etc/docker/exec/$SERVICE_NAME"
 # Reset environment before executing service
 RESET_ENV="yes"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Show message before execute
-PRE_EXEC_MESSAGE=""
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set the database root dir
 DATABASE_BASE_DIR="${DATABASE_BASE_DIR:-/data/db}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # set the database directory
 DATABASE_DIR="${DATABASE_DIR_GEN_SCRIPT_REPLACE_ENV:-/data/db/sqlite}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -101,25 +99,15 @@ CONF_DIR="/config/GEN_SCRIPT_REPLACE_APPNAME" # set config directory
 # set the containers etc directory
 ETC_DIR="/etc/GEN_SCRIPT_REPLACE_APPNAME"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-VAR_DIR=""                                      # set the var dir
+# set the var dir
+VAR_DIR=""
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 TMP_DIR="/tmp/GEN_SCRIPT_REPLACE_APPNAME"       # set the temp dir
 RUN_DIR="/run/GEN_SCRIPT_REPLACE_APPNAME"       # set scripts pid dir
 LOG_DIR="/data/logs/GEN_SCRIPT_REPLACE_APPNAME" # set log directory
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set the working dir
-WORK_DIR="" # set working directory
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Where to save passwords to
-ROOT_FILE_PREFIX="/config/secure/auth/root" # directory to save username/password for root user
-USER_FILE_PREFIX="/config/secure/auth/user" # directory to save username/password for normal user
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# root/admin user info password/random]
-root_user_name="${GEN_SCRIPT_REPLACE_ENV_ROOT_USER_NAME:-}" # root user name
-root_user_pass="${GEN_SCRIPT_REPLACE_ENV_ROOT_PASS_WORD:-}" # root user password
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Normal user info [password/random]
-user_name="${GEN_SCRIPT_REPLACE_ENV_USER_NAME:-}"      # normal user name
-user_pass="${GEN_SCRIPT_REPLACE_ENV_USER_PASS_WORD:-}" # normal user password
+WORK_DIR=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # port which service is listening on
 SERVICE_PORT=""
@@ -146,8 +134,26 @@ IS_WEB_SERVER="no"
 # Is this service a database server
 IS_DATABASE_SERVICE="no"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Does this service use a database server
+USES_DATABASE_SERVICE="no"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Show message before execute
+PRE_EXEC_MESSAGE=""
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Update path var
-PATH="./bin:$PATH"
+PATH="$PATH:."
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Where to save passwords to
+ROOT_FILE_PREFIX="/config/secure/auth/root" # directory to save username/password for root user
+USER_FILE_PREFIX="/config/secure/auth/user" # directory to save username/password for normal user
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# root/admin user info password/random]
+root_user_name="${GEN_SCRIPT_REPLACE_ENV_ROOT_USER_NAME:-}" # root user name
+root_user_pass="${GEN_SCRIPT_REPLACE_ENV_ROOT_PASS_WORD:-}" # root user password
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Normal user info [password/random]
+user_name="${GEN_SCRIPT_REPLACE_ENV_USER_NAME:-}"      # normal user name
+user_pass="${GEN_SCRIPT_REPLACE_ENV_USER_PASS_WORD:-}" # normal user password
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Load variables from config
 [ -f "/config/env/GEN_SCRIPT_REPLACE_APPNAME.script.sh" ] && . "/config/env/GEN_SCRIPT_REPLACE_APPNAME.script.sh" # Generated by my dockermgr script
@@ -244,7 +250,7 @@ __pre_execute() {
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # Copy /config to /etc
   for config_2_etc in $CONF_DIR $ADDITIONAL_CONFIG_DIRS; do
-    __initialize_system_etc "$config_2_etc" |& tee -p -a "$LOG_DIR/init.txt" &>/dev/null
+    __initialize_system_etc "$config_2_etc" |& tee -p -a "$LOG_DIR/init.txt"
   done
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # Replace variables
@@ -278,16 +284,16 @@ __post_execute() {
     retVal=$?
     # show exit message
     __banner "$postMessageEnd: Status $retVal"
-  ) 2>"/dev/stderr" | tee -p -a "$LOG_DIR/init.txt" >/dev/null &
+  ) 2>"/dev/stderr" | tee -p -a "$LOG_DIR/init.txt" &
   return
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # use this function to update config files - IE: change port
 __pre_message() {
   local exitCode=0
-  [ -n "$user_name" ] && echo "username:               $user_name" && echo "$user_name" >"${USER_FILE_PREFIX}/${SERVICE_NAME}_name"
+  [ -n "$user_name" ] && __printf_space "40" "username:" "$user_name" && echo "$user_name" >"${USER_FILE_PREFIX}/${SERVICE_NAME}_name"
   [ -n "$user_pass" ] && __printf_space "40" "password:" "saved to ${USER_FILE_PREFIX}/${SERVICE_NAME}_pass" && echo "$user_pass" >"${USER_FILE_PREFIX}/${SERVICE_NAME}_pass"
-  [ -n "$root_user_name" ] && echo "root username:     $root_user_name" && echo "$root_user_name" >"${ROOT_FILE_PREFIX}/${SERVICE_NAME}_name"
+  [ -n "$root_user_name" ] && __printf_space "40" "root username:" "$root_user_name" && echo "$root_user_name" >"${ROOT_FILE_PREFIX}/${SERVICE_NAME}_name"
   [ -n "$root_user_pass" ] && __printf_space "40" "root password:" "saved to ${ROOT_FILE_PREFIX}/${SERVICE_NAME}_pass" && echo "$root_user_pass" >"${ROOT_FILE_PREFIX}/${SERVICE_NAME}_pass"
   [ -n "$PRE_EXEC_MESSAGE" ] && eval echo "$PRE_EXEC_MESSAGE"
   # execute commands
@@ -341,10 +347,10 @@ __run_start_script() {
   local sysname="${SERVER_NAME:-${FULL_DOMAIN_NAME:-$HOSTNAME}}" # set hostname
   [ -f "$CONF_DIR/$SERVICE_NAME.exec_cmd.sh" ] && . "$CONF_DIR/$SERVICE_NAME.exec_cmd.sh"
   #
-  __run_pre_execute_checks 2>/dev/stderr | tee -a -p "/data/logs/entrypoint.log" "$LOG_DIR/init.txt" >/dev/null || return 20
+  __run_pre_execute_checks 2>/dev/stderr | tee -a -p "/data/logs/entrypoint.log" "$LOG_DIR/init.txt" || return 20
   #
   if [ -z "$cmd" ]; then
-    __post_execute 2>"/dev/stderr" | tee -p -a "$LOG_DIR/init.txt" >/dev/null
+    __post_execute 2>"/dev/stderr" | tee -p -a "$LOG_DIR/init.txt"
     retVal=$?
     echo "Initializing $SCRIPT_NAME has completed"
     exit $retVal
@@ -388,7 +394,7 @@ __run_start_script() {
       [ -n "$su_exec" ] && echo "using $su_exec" | tee -a -p "$LOG_DIR/init.txt"
       echo "$message" | tee -a -p "$LOG_DIR/init.txt"
       su_cmd touch "$SERVICE_PID_FILE"
-      __post_execute 2>"/dev/stderr" | tee -p -a "$LOG_DIR/init.txt" >/dev/null &
+      __post_execute 2>"/dev/stderr" | tee -p -a "$LOG_DIR/init.txt" &
       if [ "$RESET_ENV" = "yes" ]; then
         env_command="$(echo "env -i HOME=\"$home\" LC_CTYPE=\"$lc_type\" PATH=\"$path\" HOSTNAME=\"$sysname\" USER=\"${SERVICE_USER:-$RUNAS_USER}\" $extra_env")"
         execute_command="$(__trim "$su_exec $env_command $cmd_exec")"
@@ -451,7 +457,7 @@ __run_secure_function() {
         chmod -Rf 600 "$filesperms"
         chown -Rf $SERVICE_USER:$SERVICE_USER "$filesperms"
       fi
-    done |& tee -p -a "$LOG_DIR/init.txt" &>/dev/null
+    done |& tee -p -a "$LOG_DIR/init.txt"
   fi
   if [ -n "$root_user_name" ] || [ -n "$root_user_pass" ]; then
     for filesperms in "${ROOT_FILE_PREFIX}"/*; do
@@ -459,7 +465,7 @@ __run_secure_function() {
         chmod -Rf 600 "$filesperms"
         chown -Rf $SERVICE_USER:$SERVICE_USER "$filesperms"
       fi
-    done |& tee -p -a "$LOG_DIR/init.txt" &>/dev/null
+    done |& tee -p -a "$LOG_DIR/init.txt"
   fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -505,7 +511,7 @@ EXEC_PRE_SCRIPT="$(type -P "$EXEC_PRE_SCRIPT" || echo "$EXEC_PRE_SCRIPT")" # set
 [ -n "$SERVICE_GROUP" ] || SERVICE_GROUP="${RUNAS_USER:-root}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Database env
-if [ "$IS_DATABASE_SERVICE" = "yes" ]; then
+if [ "$IS_DATABASE_SERVICE" = "yes" ] || [ "$USES_DATABASE_SERVICE" = "yes" ]; then
   RESET_ENV="no"
   DATABASE_CREATE="${ENV_DATABASE_CREATE:-$DATABASE_CREATE}"
   DATABASE_USER="${ENV_DATABASE_USER:-${DATABASE_USER:-$user_name}}"
@@ -591,7 +597,7 @@ __run_secure_function
 # run the pre execute commands
 __pre_execute
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__run_start_script 2>>/dev/stderr | tee -p -a "/data/logs/entrypoint.log" >/dev/null && errorCode=0 || errorCode=10
+__run_start_script 2>>/dev/stderr | tee -p -a "/data/logs/entrypoint.log" && errorCode=0 || errorCode=10
 if [ -n "$EXEC_CMD_BIN" ]; then
   if [ "$errorCode" -ne 0 ]; then
     echo "Failed to execute: ${cmd_exec:-$EXEC_CMD_BIN $EXEC_CMD_ARGS}" | tee -p -a "/data/logs/entrypoint.log" "$LOG_DIR/init.txt"
