🗃️ Committing everything that changed 🗃️
templates/scripts/functions/docker-entrypoint
templates/scripts/other/docker-entrypoint
templates/scripts/other/start-service

diff --git a/templates/scripts/other/start-service b/templates/scripts/other/start-service
--- a/templates/scripts/other/start-service
+++ b/templates/scripts/other/start-service
@@ -64,8 +64,8 @@ DATABASE_DIR="${DATABASE_DIR_GEN_SCRIPT_REPLACE_ENV:-/data/db/GEN_SCRIPT_REPLACE
 WWW_DIR="/var/wwww/htdocs/root"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Default predefined variables
-DATA_DIR="/data"       # set data directory
-CONF_DIR_DIR="/config" # set config directory
+DATA_DIR="/data"   # set data directory
+CONF_DIR="/config" # set config directory
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # set the containers etc directory
 ETC_DIR="/etc/GEN_SCRIPT_REPLACE_APPNAME"
@@ -128,9 +128,10 @@ CMD_ENV=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # use this function to update config files - IE: change port
 __update_conf_files() {
-  local exitCode=0                   # default exit code
-  local user="${SERVICE_USER:-root}" # specifiy different user
-  local runas="root"                 # run as a different user
+  local exitCode=0                          # default exit code
+  local user="${SERVICE_USER:-root}"        # specifiy different user
+  local runas="root"                        # run as a different user
+  local sysname="${SERVER_NAME:-$HOSTNAME}" # set hostname
 
   # delete files
   #__rm ""
@@ -158,14 +159,18 @@ __update_conf_files() {
   # create directories if variable is yes"
   [ "$IS_WEB_SERVER" = "yes" ] && APPLICATION_DIRS="$APPLICATION_DIRS $WWW_DIR" && { [ -d "$WWW_DIR" ] || { (echo "Creating directory $WWW_DIR with permissions 777" && mkdir -p "$WWW_DIR" && chmod -f 777 "$WWW_DIR") |& tee -a "$LOG_DIR/init.txt" &>/dev/null; }; }
   [ "$IS_DATABASE_SERVICE" = "yes" ] && APPLICATION_DIRS="$APPLICATION_DIRS $DATABASE_DIR" && { [ -d "$DATABASE_DIR" ] || { (echo "Creating directory $DATABASE_DIR with permissions 777" && mkdir -p "$DATABASE_DIR" && chmod -f 777 "$DATABASE_DIR") |& tee -a "$LOG_DIR/init.txt" &>/dev/null; }; }
-  # replace variables
-  # __replace "" "" "$CONF_DIR/GEN_SCRIPT_REPLACE_APPNAME.conf"
-  # replace variables recursively
-  # __find_replace "" "" "$CONF_DIR/"
-  # custom commands
 
   # copy config files to system
   __file_copy "$CONF_DIR/." "$ETC_DIR/" |& tee -a "$LOG_DIR/init.txt" &>/dev/null
+
+  # replace variables
+  # __replace "" "" "$ETC_DIR/GEN_SCRIPT_REPLACE_APPNAME.conf"
+  # replace variables recursively
+  # __find_replace "" "" "$ETC_DIR/"
+  # replace defaults in ETC_DIR
+  __initialize_replace_variables "$ETC_DIR"
+  # custom commands
+
   # unset unneeded variables
   unset application_files filedirs
 
@@ -174,9 +179,11 @@ __update_conf_files() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # function to run before executing
 __pre_execute() {
-  local exitCode=0                   # default exit code
-  local user="${SERVICE_USER:-root}" # specifiy different user
-  local runas="root"                 # run as a different user
+  local exitCode=0                          # default exit code
+  local user="${SERVICE_USER:-root}"        # specifiy different user
+  local runas="root"                        # run as a different user
+  local sysname="${SERVER_NAME:-$HOSTNAME}" # set hostname
+
   # define commands
 
   # execute if directories is empty
@@ -202,11 +209,12 @@ __pre_execute() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # function to run after executing
 __post_execute() {
-  local exitCode=0                   # default exit code
-  local user="${SERVICE_USER:-root}" # specifiy different user
-  local runas="root"                 # run as a different user
-  sleep 60                           # how long to wait before executing
-  echo "Running post commands"       # message
+  local exitCode=0                          # default exit code
+  local user="${SERVICE_USER:-root}"        # specifiy different user
+  local runas="root"                        # run as a different user
+  local sysname="${SERVER_NAME:-$HOSTNAME}" # set hostname
+  sleep 60                                  # how long to wait before executing
+  echo "Running post commands"              # message
   # execute commands
 
   return $exitCode
@@ -226,6 +234,7 @@ __pre_message() {
 # use this function to setup ssl support
 __update_ssl_conf() {
   local exitCode=0
+  local sysname="${SERVER_NAME:-$HOSTNAME}" # set hostname
 
   return $exitCode
 }
@@ -265,6 +274,7 @@ __run_start_script() {
   local lc_type="${LC_ALL:-${LC_CTYPE:-$LANG}}"
   local home="${workdir//\/root/\/tmp\/docker}"
   local path="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"
+  local sysname="${SERVER_NAME:-$HOSTNAME}" # set hostname
   local message=""
   if [ -z "$cmd" ]; then
     __post_execute 2>"/dev/stderr" |& tee -a "$LOG_DIR/init.txt" &>/dev/null
@@ -301,7 +311,7 @@ __run_start_script() {
       su_cmd touch "$SERVICE_PID_FILE"
       __post_execute 2>"/dev/stderr" 2>&1 |& tee -a "$LOG_DIR/init.txt" &>/dev/null &
       if [ "$RESET_ENV" = "yes" ]; then
-        su_cmd env -i HOME="$home" LC_CTYPE="$lc_type" PATH="$path" USER="$user" ${CMD_ENV//,/ } sh -c "$cmd_exec" || return 10
+        su_cmd env -i HOME="$home" LC_CTYPE="$lc_type" PATH="$path" HOSTNAME="$sysname" USER="$user" ${CMD_ENV//,/ } sh -c "$cmd_exec" || return 10
       else
         eval "$cmd_exec" || return 10
       fi
