🗃️  Committing everything that changed 🗃️

diff --git a/templates/scripts/other/start-service b/templates/scripts/other/start-service
--- a/templates/scripts/other/start-service
+++ b/templates/scripts/other/start-service
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
+[ "$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x$DEBUGGER_OPTIONS || set -o pipefail
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 printf '%s\n' "# - - - Initializing GEN_SCRIPT_REPLACE_APPNAME - - - #"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 SERVICE_NAME="GEN_SCRIPT_REPLACE_APPNAME"
 SCRIPT_NAME="$(basename "$0" 2>/dev/null)"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
-[ "$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x$DEBUGGER_OPTIONS || set -o pipefail
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 export PATH="/usr/local/etc/docker/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -26,9 +26,10 @@ done
 # Custom functions
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Predefined variables
+# Default predefined variables
 WORKDIR=""                                                        # set working directory
 DATA_DIR="/data"                                                  # set data directory
+RUN_DIR="/run/init.d"                                             # set scripts pid dir
 ETC_DIR="/etc/GEN_SCRIPT_REPLACE_APPNAME"                         # set etc directory
 CONF_DIR="/config/GEN_SCRIPT_REPLACE_APPNAME"                     # set data directory
 LOG_DIR="/data/logs/GEN_SCRIPT_REPLACE_APPNAME"                   # set log directory
@@ -37,12 +38,14 @@ DATABASE_DIR="/data/db/GEN_SCRIPT_REPLACE_APPNAME"                # set the data
 ROOT_FILE_PREFIX="/config/secure/GEN_SCRIPT_REPLACE_APPNAME_root" # where to save password for root user
 USER_FILE_PREFIX="/config/secure/GEN_SCRIPT_REPLACE_APPNAME_user" # where to save password for normal user
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Predefined custom
-
+# Is this service a database server
+IS_WEB_SERVER="no"
+IS_DATABASE_SERVICE="no"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# lets use environment if available
+# lets use environment for database dir if available
 [ -n "$DATABASE_DIR_REPLACE_ENV" ] && DATABASE_DIR="$DATABASE_DIR_REPLACE_ENV"
-
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Additional predefined variables
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # port which service is listening on
 SERVICE_PORT=""
@@ -74,8 +77,21 @@ root_user_pass=""
 # use this function to update config files - IE: change port
 __update_conf_files() {
   local exitCode=0
+
+  # create directories
+  [ -d "$RUN_DIR" ] || mkdir -p "$RUN_DIR"
+  [ -d "$LOG_DIR" ] || mkdir -p "$LOG_DIR"
+  [ -n "$ETC_DIR" ] && [ -d "$CONF_DIR" ] && mkdir -p "$ETC_DIR"
+  # create directories if variable is yes
+  [ "$IS_WEB_SERVER" = "yes" ] && { [ -d "$WWW_DIR" ] || mkdir -p "$WWW_DIR"; }
+  [ "$IS_DATABASE_SERVICE" = "yes" ] && mkdir -p "$DATABASE_DIR" && chmod -f 777 "$DATABASE_DIR"
+  # copy config files
   [ -d "$CONF_DIR" ] && cp -Rf "$CONF_DIR/." "$ETC_DIR/"
-  [ -f "/config/GEN_SCRIPT_REPLACE_APPNAME" ] && cp -Rf "/config/GEN_SCRIPT_REPLACE_APPNAME" "/etc/"
+  # replace variables
+  # __replace "" "" "$CONF_DIR/"
+  # custom commands
+
+  # other
 
   return $exitCode
 }
@@ -83,7 +99,15 @@ __update_conf_files() {
 # function to run before executing
 __pre_execute() {
   local exitCode=0
-  [ -d "$LOG_DIR" ] || mkdir -p "$LOG_DIR"
+
+  # fix permissions
+  chmod -f 777 "$LOG_DIR" "$RUN_DIR"
+  [ -d "$DATABASE_DIR" ] && chmod -f 777 "$DATABASE_DIR"
+  if [ -n "$SERVICE_USER" ] && [ "$SERVICE_USER" != "root" ]; then
+    if grep -s -q "$SERVICE_USER:" "/etc/passwd"; then
+      chown -Rf $SERVICE_USER:$SERVICE_USER "$ETC_DIR" "$WWW_DIR" "$LOG_DIR" && echo "changed ownership to $SERVICE_USER"
+    fi
+  fi
 
   return $exitCode
 }
@@ -200,7 +224,7 @@ EXEC_CMD_ARGS="${ENV_EXEC_CMD_ARGS:-$EXEC_CMD_ARGS}"              # command argu
 EXEC_CMD_NAME="$(basename "$EXEC_CMD_BIN")"                       # set the binary name
 EXEC_CMD_BIN="$(type -P "$EXEC_CMD_BIN" || echo "$EXEC_CMD_BIN")" # set full path
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Allow variable via imports
+# Allow variables via imports - Overwrite existing
 [ -f "/config/env/$EXEC_CMD_BIN.sh" ] && "/config/env/$EXEC_CMD_BIN.sh"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # ensure the command exists
