🗃️ Committing everything that changed 🗃️

diff --git a/templates/scripts/other/start-service b/templates/scripts/other/start-service
--- a/templates/scripts/other/start-service
+++ b/templates/scripts/other/start-service
@@ -54,14 +54,14 @@ __pre_execute() {
 # script to start server
 __run_start_script() {
   local workdir="${WORKDIR:-$HOME}"
-  local home="${workdir//\/root/\/home\/docker}"
-  local path="/usr/local/bin:/usr/bin"
-  local user="${SERVICE_USER//root/daemon}"
-  local lc_type="${LC_ALL:-${LC_CTYPE:-$LANG}}"
   local cmd="$EXEC_CMD_BIN $EXEC_CMD_ARGS"
+  local user="${SERVICE_USER:-root}"
+  local lc_type="${LC_ALL:-${LC_CTYPE:-$LANG}}"
+  local home="${workdir//\/root/\/home\/docker}"
+  local path="/usr/local/bin:/usr/bin:/bin:/usr/sbin"
   case "$1" in
   check) shift 1 && __pgrep $EXEC_CMD_BIN || return 5 ;;
-  *) su_cmd env -i HOME="$home" LC_CTYPE="$lc_type" PATH="$path" USER="$user" bash -c "$cmd" || return 10 ;;
+  *) su_cmd env -i PWD="$home" HOME="$home" LC_CTYPE="$lc_type" PATH="$path" USER="$user" sh -c "$cmd" || return 10 ;;
   esac
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -105,12 +105,12 @@ fi
 # Change to working directory
 [ -n "$WORKDIR" ] && mkdir -p "$WORKDIR" && __cd "$WORKDIR" && echo "Changed to $PWD"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Updating config files
-__update_conf_files
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Initialize ssl
 __update_ssl_conf
 __update_ssl_certs
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Updating config files
+__update_conf_files
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # run the pre execute commands
 [ -n "$PRE_EXEC_MESSAGE" ] && echo "$PRE_EXEC_MESSAGE"
@@ -128,12 +128,12 @@ elif [ "$(builtin type -P sudo)" ]; then
 elif [ "$(builtin type -P su)" ]; then
   su_cmd() { su -s /bin/sh - $SERVICE_USER -c "$@" || return 1; }
 else
-  echo "Can not switch to $SERVICE_USER"
-  exit 10
+  echo "Can not switch to $SERVICE_USER: attempting to run as root"
+  su_cmd() { eval "$@" || return 1; }
 fi
-if [ -n "$WORKDIR" ] && [ -n "$SERVICE_USER" ]; then
+if [ -n "$WORKDIR" ] && [ "${SERVICE_USER:-$USER}" != "root" ]; then
   echo "Fixing file permissions"
-  su_cmd chown -Rf $SERVICE_USER $WORKDIR
+  su_cmd chown -Rf $SERVICE_USER $WORKDIR $etc_dir $var_dir $log_dir
 fi
 if __pgrep $EXEC_CMD_BIN && [ -f "/run/init.d/$EXEC_CMD_BIN.pid" ]; then
   SERVICE_EXIT_CODE=1
@@ -141,8 +141,12 @@ if __pgrep $EXEC_CMD_BIN && [ -f "/run/init.d/$EXEC_CMD_BIN.pid" ]; then
 else
   echo "Starting service: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
   su_cmd touch /run/init.d/$EXEC_CMD_BIN.pid
-  __run_start_script "$@" |& tee -a "/tmp/entrypoint.log" || echo "Failed to execute: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
-  [ "$?" -ne 0 ] && SERVICE_IS_RUNNING="false" && SERVICE_EXIT_CODE=10 && rm -Rf "/run/init.d/$EXEC_CMD_BIN.pid"
+  __run_start_script "$@" |& tee -a "/tmp/entrypoint.log"
+  if [ "$?" -ne 0 ]; then
+    echo "Failed to execute: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
+    SERVICE_EXIT_CODE=10 SERVICE_IS_RUNNING="false"
+    su_cmd rm -Rf "/run/init.d/$EXEC_CMD_BIN.pid"
+  fi
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 exit $SERVICE_EXIT_CODE
