🗃️ Committing everything that changed 🗃️
templates/env/docker/global.sh
templates/env/docker/networking.sh
templates/scripts/functions/docker-entrypoint
templates/scripts/other/start-service

diff --git a/templates/scripts/other/start-service b/templates/scripts/other/start-service
--- a/templates/scripts/other/start-service
+++ b/templates/scripts/other/start-service
@@ -110,16 +110,12 @@ __file_exists_with_content "${ROOT_FILE_PREFIX}/${SERVICE_NAME}_pass" && root_us
 # port which service is listening on
 SERVICE_PORT=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# User to use to launch service
+# User to use to launch service - IE: postgres
 RUNAS_USER="root" # normally root
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # User and group in which the service switches to - IE: nginx,apache,mysql,postgres
 SERVICE_USER="root" # execute command as another user
 SERVICE_GROUP=""    # Set the service group
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# How to set permissions -normally same as $SERVICE_USER $SERVICE_GROUP
-CHANGE_USER=""  # Set user file ownership
-CHANGE_GROUP="" # Set group file ownership
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set user and group ID
 SERVICE_UID="0" # set the user id
@@ -163,13 +159,8 @@ CMD_ENV=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # use this function to update config files - IE: change port
 __update_conf_files() {
-  local exitCode=0                                  # default exit code
-  local runas="${RUNAS_USER:-root}"                 # run as a different user
-  local proc_user="${SERVICE_USER:-${runas:-root}}" # specify different user ownership
-  local proc_group="$SERVICE_GROUP:-$SERVICE_USER}" # specify different group ownership
-  local change_user="${CHANGE_USER:-$proc_user}"    # specify different user ownership
-  local change_group="${CHANGE_GROUP:-$proc_group}" # specify different group ownership
-  local sysname="${SERVER_NAME:-$HOSTNAME}"         # set hostname
+  local exitCode=0                                               # default exit code
+  local sysname="${SERVER_NAME:-${FULL_DOMAIN_NAME:-$HOSTNAME}}" # set hostname
 
   # CD into temp to bybass any permission errors
   cd /tmp || false # lets keep shellcheck happy by adding false
@@ -242,7 +233,8 @@ __update_conf_files() {
   # replace variables
   # __replace "" "" "$ETC_DIR/GEN_SCRIPT_REPLACE_APPNAME.conf"
   # replace variables recursively
-  # __find_replace "" "" "$ETC_DIR/"
+  __find_replace "REPLACE_WWW_USER" "${SERVICE_USER:-root}" "$CONF_DIR"
+  __find_replace "REPLACE_WWW_GROUP" "${SERVICE_GROUP:-root}" "$CONF_DIR"
 
   # execute if directory is empty
   #__is_dir_empty "" && true || false
@@ -257,13 +249,8 @@ __update_conf_files() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # function to run before executing
 __pre_execute() {
-  local exitCode=0                                  # default exit code
-  local runas="${RUNAS_USER:-root}"                 # run as a different user
-  local proc_user="${SERVICE_USER:-${runas:-root}}" # specify different user ownership
-  local proc_group="$SERVICE_GROUP:-$SERVICE_USER}" # specify different group ownership
-  local change_user="${CHANGE_USER:-$proc_user}"    # specify different user ownership
-  local change_group="${CHANGE_GROUP:-$proc_group}" # specify different group ownership
-  local sysname="${SERVER_NAME:-$HOSTNAME}"         # set hostname
+  local exitCode=0                                               # default exit code
+  local sysname="${SERVER_NAME:-${FULL_DOMAIN_NAME:-$HOSTNAME}}" # set hostname
 
   # define commands
 
@@ -278,30 +265,30 @@ __pre_execute() {
   unset config_2_etc ADDITIONAL_CONFIG_DIRS
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # create user if needed
-  __create_service_user "$change_user" "$change_group" "${WORK_DIR:-/home/$change_user}" "${SERVICE_UID:-3000}" "${SERVICE_GID:-3000}"
+  __create_service_user "$SERVICE_USER" "$SERVICE_GROUP" "${WORK_DIR:-/home/$SERVICE_USER}" "${SERVICE_UID:-3000}" "${SERVICE_GID:-3000}"
 
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # Modify user if needed
-  __set_user_group_id $change_user ${SERVICE_UID:-3000} ${SERVICE_GID:-3000}
+  __set_user_group_id $SERVICE_USER ${SERVICE_UID:-3000} ${SERVICE_GID:-3000}
 
   # Run Custom command
 
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # set user on files/folders
-  if [ -n "$change_user" ] && [ "$change_user" != "root" ]; then
-    if grep -sq "^$change_user:" "/etc/passwd"; then
+  if [ -n "$SERVICE_USER" ] && [ "$SERVICE_USER" != "root" ]; then
+    if grep -sq "^$SERVICE_USER:" "/etc/passwd"; then
       for permissions in $ADD_APPLICATION_DIRS $APPLICATION_DIRS; do
         if [ -n "$permissions" ] && [ -e "$permissions" ]; then
-          (chown -Rf $change_user:${change_group:-$change_user} "$permissions" && echo "changed ownership on $permissions to user:$change_user and group:${change_group:-$change_user}") |& tee -a "$LOG_DIR/init.txt" &>/dev/null
+          (chown -Rf $SERVICE_USER:${SERVICE_GROUP:-$SERVICE_USER} "$permissions" && echo "changed ownership on $permissions to user:$SERVICE_USER and group:${SERVICE_GROUP:-$SERVICE_USER}") |& tee -a "$LOG_DIR/init.txt" &>/dev/null
         fi
       done
     fi
   fi
-  if [ -n "$change_group" ] && [ "$change_group" != "root" ]; then
-    if grep -sq "^$change_group:" "/etc/group"; then
+  if [ -n "$SERVICE_GROUP" ] && [ "$SERVICE_GROUP" != "root" ]; then
+    if grep -sq "^$SERVICE_GROUP:" "/etc/group"; then
       for permissions in $ADD_APPLICATION_DIRS $APPLICATION_DIRS; do
         if [ -n "$permissions" ] && [ -e "$permissions" ]; then
-          (chgrp -Rf $change_group "$permissions" && echo "changed group ownership on $permissions to group $change_group") |& tee -a "$LOG_DIR/init.txt" &>/dev/null
+          (chgrp -Rf $SERVICE_GROUP "$permissions" && echo "changed group ownership on $permissions to group $SERVICE_GROUP") |& tee -a "$LOG_DIR/init.txt" &>/dev/null
         fi
       done
     fi
@@ -316,10 +303,8 @@ __pre_execute() {
   __initialize_replace_variables "$ETC_DIR"
   __initialize_replace_variables "$CONF_DIR"
   __initialize_replace_variables "$WWW_ROOT_DIR"
-  __find_replace "REPLACE_WWW_USER" "${change_user:-root}" "$ETC_DIR"
-  __find_replace "REPLACE_WWW_GROUP" "${change_group:-root}" "$ETC_DIR"
-  __find_replace "REPLACE_WWW_USER" "${change_user:-root}" "$CONF_DIR"
-  __find_replace "REPLACE_WWW_GROUP" "${change_group:-root}" "$CONF_DIR"
+  __find_replace "REPLACE_WWW_USER" "${SERVICE_USER:-root}" "$ETC_DIR"
+  __find_replace "REPLACE_WWW_GROUP" "${SERVICE_GROUP:-root}" "$ETC_DIR"
   # unset unneeded variables
   unset filesperms filename
   # Lets wait a few seconds before continuing
@@ -329,13 +314,8 @@ __pre_execute() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # function to run after executing
 __post_execute() {
-  local exitCode=0                                  # default exit code
-  local runas="${RUNAS_USER:-root}"                 # run as a different user
-  local proc_user="${SERVICE_USER:-${runas:-root}}" # specify different user ownership
-  local proc_group="$SERVICE_GROUP:-$SERVICE_USER}" # specify different group ownership
-  local change_user="${CHANGE_USER:-$proc_user}"    # specify different user ownership
-  local change_group="${CHANGE_GROUP:-$proc_group}" # specify different group ownership
-  local sysname="${SERVER_NAME:-$HOSTNAME}"         # set hostname
+  local exitCode=0                                               # default exit code
+  local sysname="${SERVER_NAME:-${FULL_DOMAIN_NAME:-$HOSTNAME}}" # set hostname
 
   sleep 60                     # how long to wait before executing
   echo "Running post commands" # message
@@ -361,7 +341,7 @@ __pre_message() {
 # use this function to setup ssl support
 __update_ssl_conf() {
   local exitCode=0
-  local sysname="${SERVER_NAME:-$HOSTNAME}" # set hostname
+  local sysname="${SERVER_NAME:-${FULL_DOMAIN_NAME:-$HOSTNAME}}" # set hostname
 
   return $exitCode
 }
@@ -404,23 +384,16 @@ EOF
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # script to start server
 __run_start_script() {
-  local runas="${RUNAS_USER:-root}"                            # run as a different user
-  local proc_user="${SERVICE_USER:-${runas:-root}}"            # specify different user ownership
-  local proc_group="$SERVICE_GROUP:-$SERVICE_USER}"            # specify different group ownership
-  local change_user="${CHANGE_USER:-$proc_user}"               # specify different user ownership
-  local change_group="${CHANGE_GROUP:-$proc_group}"            # specify different group ownership
-  local cmd="$(eval echo "${EXEC_CMD_BIN:-}")"                 # expand variables
-  local args="$(eval echo "${EXEC_CMD_ARGS:-}")"               # expand variables
-  local name="$(eval echo "${EXEC_CMD_NAME:-}")"               # expand variables
-  local pre="$(eval echo "${EXEC_PRE_SCRIPT:-}")"              # expand variables
-  local workdir="$(eval echo "${WORK_DIR:-}")"                 # expand variables
-  local lc_type="$(eval echo "${LC_ALL:-${LC_CTYPE:-$LANG}}")" # expand variables
-  local home="$(eval echo "${workdir//\/root/\/tmp\/docker}")" # expand variables
-  local path="$(eval echo "$PATH")"                            # expand variables
-  local message="$(eval echo "")"                              # expand variables
-  local user="$change_user"                                    # Set the user from the change user variable
-  local group="$change_group"                                  # Set the group from the change group variable
-  local sysname="${SERVER_NAME:-$HOSTNAME}"                    # set hostname
+  local cmd="$(eval echo "${EXEC_CMD_BIN:-}")"                   # expand variables
+  local args="$(eval echo "${EXEC_CMD_ARGS:-}")"                 # expand variables
+  local name="$(eval echo "${EXEC_CMD_NAME:-}")"                 # expand variables
+  local pre="$(eval echo "${EXEC_PRE_SCRIPT:-}")"                # expand variables
+  local workdir="$(eval echo "${WORK_DIR:-}")"                   # expand variables
+  local lc_type="$(eval echo "${LC_ALL:-${LC_CTYPE:-$LANG}}")"   # expand variables
+  local home="$(eval echo "${workdir//\/root/\/tmp\/docker}")"   # expand variables
+  local path="$(eval echo "$PATH")"                              # expand variables
+  local message="$(eval echo "")"                                # expand variables
+  local sysname="${SERVER_NAME:-${FULL_DOMAIN_NAME:-$HOSTNAME}}" # set hostname
   [ -f "$CONF_DIR/$SERVICE_NAME.exec_cmd.sh" ] && . "$CONF_DIR/$SERVICE_NAME.exec_cmd.sh"
   if [ -z "$cmd" ]; then
     __post_execute 2>"/dev/stderr" |& tee -a "$LOG_DIR/init.txt" &>/dev/null
@@ -514,8 +487,6 @@ SERVICE_USER="${ENV_SERVICE_USER:-$SERVICE_USER}"             # execute command 
 SERVICE_UID="${ENV_UID:-${ENV_SERVICE_UID:-$SERVICE_UID}}"    # Set UID
 SERVICE_GID="${ENV_GID:-${ENV_SERVICE_GID:-$SERVICE_GID}}"    # Set GID
 SERVICE_PORT="${ENV_SERVICE_PORT:-$SERVICE_PORT}"             # port which service is listening on
-CHANGE_USER="${ENV_CHANGE_USER:-$SERVICE_USER}"               # Set user file ownership
-CHANGE_GROUP="${ENV_CHANGE_GROUP:-$SERVICE_GROUP}"            # Set group file ownership
 RUNAS_USER="${ENV_RUNAS_USER:-$RUNAS_USER}"                   # normally root
 WORK_DIR="${ENV_WORK_DIR:-$WORK_DIR}"                         # change to directory
 WWW_ROOT_DIR="${ENV_WWW_ROOT_DIR:-$WWW_ROOT_DIR}"             # set default web dir
@@ -539,12 +510,6 @@ EXEC_PRE_SCRIPT="$(type -P "$EXEC_PRE_SCRIPT" || echo "$EXEC_PRE_SCRIPT")" # set
 [ -n "$USER_FILE_PREFIX" ] && { [ -d "$USER_FILE_PREFIX" ] || mkdir -p "$USER_FILE_PREFIX"; }
 [ -n "$ROOT_FILE_PREFIX" ] && { [ -d "$ROOT_FILE_PREFIX" ] || mkdir -p "$ROOT_FILE_PREFIX"; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Set USER and GROUP permissions
-[ "$CHANGE_USER" = "" ] && CHANGE_USER="${SERVICE_GROUP:-${SERVICE_USER:-root}}"
-[ "$CHANGE_GROUP" = "" ] && CHANGE_GROUP="${SERVICE_GROUP:-${SERVICE_USER:-root}}"
-[ "$CHANGE_USER" = "root" ] && [ "$SERVICE_USER" != "root" ] && CHANGE_USER="${SERVICE_USER}"
-[ "$CHANGE_GROUP" = "root" ] && [ "$SERVICE_GROUP" != "root" ] && CHANGE_USER="${SERVICE_GROUP:-$SERVICE_USER}"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 [ "$IS_WEB_SERVER" = "yes" ] && RESET_ENV="yes"
 [ "$IS_DATABASE_SERVICE" = "yes" ] && RESET_ENV="no"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -555,10 +520,10 @@ __file_exists_with_content "$ETC_DIR/auth/root/name" && root_user_name="$(<"$ETC
 __file_exists_with_content "$ETC_DIR/auth/root/pass" && root_user_pass="$(<"$ETC_DIR/auth/root/pass")"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Allow setting initial users and passwords via environment
-user_name="${user_name:-$ENV_USER_NAME}"
-user_pass="${user_pass:-$ENV_USER_PASS}"
-root_user_name="${root_user_name:-$ENV_ROOT_USER_NAME}"
-root_user_pass="${root_user_pass:-$ENV_ROOT_USER_PASS}"
+user_name="${ENV_USER_NAME:-$user_name}"
+user_pass="${ENV_USER_PASS:-$user_pass}"
+root_user_name="${ENV_ROOT_USER_NAME:-$root_user_name}"
+root_user_pass="${ENV_ROOT_USER_PASS:-$root_user_pass}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # set password to random if variable is random
 if [ "$user_pass" = "random" ]; then
@@ -580,28 +545,23 @@ fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # show message if env exists
 if [ -n "$EXEC_CMD_BIN" ]; then
-  [ -n "$SERVICE_USER" ] && echo "Setting up service to run as $SERVICE_USER" || SERVICE_USER="root"
+  [ -n "$RUNAS_USER" ] && echo "Setting up service to run as $RUNAS_USER" || SERVICE_USER="root"
   [ -n "$SERVICE_PORT" ] && echo "${EXEC_CMD_NAME:-$EXEC_CMD_BIN} will be running on $SERVICE_PORT" || SERVICE_PORT=""
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # set switch user command
-runas="${RUNAS_USER:-root}"                 # run as a different user
-proc_user="${SERVICE_USER:-${runas:-root}}" # specify different user ownership
-proc_group="$SERVICE_GROUP:-$SERVICE_USER}" # specify different group ownership
-change_user="${CHANGE_USER:-$proc_user}"    # specify different user ownership
-change_group="${CHANGE_GROUP:-$proc_group}" # specify different group ownership
-if [ "$proc_user" = "root" ] || [ -z "$proc_user" ]; then
+if [ "$RUNAS_USER" != "root" ] || [ -z "$RUNAS_USER" ]; then
   su_cmd() { eval "$*" || return 1; }
 elif [ "$(builtin type -P gosu)" ]; then
-  su_cmd() { gosu $runas "$@" || return 1; }
+  su_cmd() { gosu $RUNAS_USER "$@" || return 1; }
 elif [ "$(builtin type -P runuser)" ]; then
-  su_cmd() { runuser -u $runas "$@" || return 1; }
+  su_cmd() { runuser -u $RUNAS_USER "$@" || return 1; }
 elif [ "$(builtin type -P sudo)" ]; then
-  su_cmd() { sudo -u $runas "$@" || return 1; }
+  su_cmd() { sudo -u $RUNAS_USER "$@" || return 1; }
 elif [ "$(builtin type -P su)" ]; then
-  su_cmd() { su -s /bin/sh - $runas -c "$@" || return 1; }
+  su_cmd() { su -s /bin/sh - $RUNAS_USER -c "$@" || return 1; }
 else
-  echo "Can not switch to $runas: attempting to run as root"
+  echo "Can not switch to $RUNAS_USER: attempting to run as root"
   su_cmd() { eval "$*" || return 1; }
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
