🗃️  modified: templates/scripts/bash/build 🗃️

diff --git a/templates/scripts/bash/build b/templates/scripts/bash/build
--- a/templates/scripts/bash/build
+++ b/templates/scripts/bash/build
@@ -101,13 +101,13 @@ __check_log() {
     warnings="$(grep -i 'warning: ' "$BUILD_LOG_FILE" || echo '')"
     if [[ -n "$warnings" ]]; then
       __printf_color "$RED" "The following warnings have occurred:"
-      echo -e "$warnings" | printf_readline "7"
+      echo -e "$warnings" | printf_readline
       __printf_color "$YELLOW" "Log file saved to $BUILD_LOG_FILE"
       exitCode=0
     fi
     if [[ -n "$errors" ]] || [[ "$exitCode" -ne 0 ]]; then
       __printf_color "$RED" "The following errors have occurred:"
-      echo -e "$errors" | printf_readline "7"
+      echo -e "$errors" | printf_readline
       __printf_color "$YELLOW" "Log file saved to $BUILD_LOG_FILE"
       exitCode=1
     else
@@ -164,6 +164,15 @@ __init() {
 __logr() { echo -e "$*" | tee -a "$BUILD_LOG_FILE" &>/dev/null; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __printf_color() { echo -e "\t\t${1:-}${2:-}${NC}"; }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+printf_readline() {
+  local color="$1"
+  set -o pipefail
+  while read line; do
+    echo -e "${color:-$WHITE}$line"
+  done |& tee
+  set +o pipefail
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __help() {
   [[ -z "$ARRAY" ]] || local array="[${ARRAY//,/ }]"
