🗃️  modified: templates/scripts/bash/build 🗃️

diff --git a/templates/scripts/bash/build b/templates/scripts/bash/build
--- a/templates/scripts/bash/build
+++ b/templates/scripts/bash/build
@@ -22,7 +22,7 @@ SRC_DIR="${BASH_SOURCE%/*}"
 # Set bash options
 if [[ "$1" == "--debug" ]]; then shift 1 && set -xo pipefail && export SCRIPT_OPTS="--debug" && export _DEBUG="on"; fi
 trap 'exitCode=${exitCode:-$?};[ -n "$GEN_SCRIPT_REPLACE_ENV_TEMP_FILE" ] && [ -f "$GEN_SCRIPT_REPLACE_ENV_TEMP_FILE" ] && rm -Rf "$GEN_SCRIPT_REPLACE_ENV_TEMP_FILE" &>/dev/null' EXIT
-
+set -eo pipefail
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
 # Set functions
 __help() { printf_color "$BLUE" "Usage: $APPNAME []"; }
@@ -31,12 +31,12 @@ __list_options() { echo "${1:-$ARRAY}" | sed 's|:||g;s|'$2'| '$3'|g' 2>/dev/null
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Additional functions
 printf_color() { echo -e "\t\t${1:-}${2:-}${NC}"; }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Check for needed applications
 type -P bash make &>/dev/null || { echo "Missing: bash" && exit 1; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set variables
+exitCode=10
 NC="$(tput sgr0 2>/dev/null)"
 RESET="$(tput sgr0 2>/dev/null)"
 BLACK="\033[0;30m"
@@ -51,8 +51,6 @@ ORANGE="\033[0;33m"
 LIGHTRED='\033[1;31m'
 BG_GREEN="\[$(tput setab 2 2>/dev/null)\]"
 BG_RED="\[$(tput setab 9 2>/dev/null)\]"
-exitCode=
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Application Folders
 
@@ -114,32 +112,39 @@ else
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Install required packages
-if cmd_exists apt-get; then
-  if cmd_exists pkmgr; then
-    for pkg in libxml2-dev libmenu-cache-dev lxmenu-data libpango1.0-dev librsvg2-dev libcairo2-dev libxrandr-dev build-essential git cmake cmake-data pkg-config python3-sphinx libcairo2-dev libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libxcb-composite0-dev python-xcbgen xcb-proto libxcb-image0-dev libxcb-ewmh-dev libxcb-icccm4-dev; do
-      execute "pkmgr install -y $pkg" "Installing $pkg"
-    done
-  fi
-elif cmd_exists dnf; then
-  if cmd_exists pkmgr; then
-    for pkg in cairo-devel xcb-util-devel libxcb-devel xcb-proto xcb-util-image-devel xcb-util-wm-devel; do
-      execute "pkmgr install -y $pkg" "Installing $pkg"
-    done
-  fi
-elif cmd_exists yum; then
-  if cmd_exists pkmgr; then
-    for pkg in cairo-devel xcb-util-devel libxcb-devel xcb-proto xcb-util-image-devel xcb-util-wm-devel; do
-      execute "pkmgr install -y $pkg" "Installing $pkg"
-    done
-  fi
-fi
+# if cmd_exists apt-get; then
+#   if cmd_exists pkmgr; then
+#     for pkg in LIST; do
+#        printf_color "$CYAN" "Installing $pkg"
+#        pkmgr silent install $pkg &>/dev/null
+#        [[ $? = 0 ]] && printf_color "$GREEN" "Installed $pkg" || printf_color "$RED" "Failed to installed $pkg"
+#     done
+#   fi
+# elif cmd_exists dnf; then
+#   if cmd_exists pkmgr; then
+#     for pkg in LIST; do
+#        printf_color "$CYAN" "Installing $pkg"
+#        pkmgr silent install $pkg &>/dev/null
+#        [[ $? = 0 ]] && printf_color "$GREEN" "Installed $pkg" || printf_color "$RED" "Failed to installed $pkg"
+#     done
+#   fi
+# elif cmd_exists yum; then
+#   if cmd_exists pkmgr; then
+#     for pkg in LIST; do
+#        printf_color "$CYAN" "Installing $pkg"
+#        pkmgr silent install $pkg &>/dev/null
+#        [[ $? = 0 ]] && printf_color "$GREEN" "Installed $pkg" || printf_color "$RED" "Failed to installed $pkg"
+#     done
+#   fi
+# fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main application
 if [[ -d "$BUILD_SRC_DIR" ]]; then
   builtin cd "$BUILD_SRC_DIR" || exit 1
   if [[ -d ".git" ]]; then
     printf_color "$CYAN" "Updating the git repo"
-    git reset --hard &>/dev/null && git pull -q &>/dev/null
+    git reset --hard 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null &&
+      git pull -q 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null
   elif [[ -n "$BUILD_SRC_URL" ]]; then
     printf_color "$CYAN" "Cloning the git repo"
     if ! git clone "$BUILD_SRC_URL" "$BUILD_SRC_DIR"; then
@@ -149,26 +154,37 @@ if [[ -d "$BUILD_SRC_DIR" ]]; then
   fi
   if [[ -f "Makefile" ]]; then
     printf_color "$GREEN" "Updating the git repo"
-    sudo make clean install DESTDIR="$BUILD_DESTDIR" 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null
+    sudo make clean install DESTDIR="$BUILD_DESTDIR" 2>&1 |
+      tee -a "$BUILD_LOG_FILE" &>/dev/null
+    exitCode=$?
   fi
   if [[ -f "$BUILD_LOG_FILE" ]]; then
     errors="$(grep 'fatal error' "$BUILD_LOG_FILE" || echo '')"
-    if [[ -n "$errors" ]]; then
+    if [[ -n "$errors" ]] || [[ "$exitCode" -ne 0 ]]; then
       printf_color "$RED" "The following errors have occurred:"
       echo -e "$errors"
       printf_color "$YELLOW" "Log file saved to $BUILD_LOG_FILE"
-      exit 1
+      exitCode=1
     else
       rm -Rf "$BUILD_LOG_FILE" &>/dev/null
       printf_color "$GREEN" "Build of $BUILD_NAME has completed without error"
+      exitCode=0
     fi
   fi
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # check
-builtin type -P "$BUILD_NAME" &&
-  printf_color "$GRREN" "Successfully installed $BUILD_NAME" ||
-  printf_color "$RED" "Failed to install $BUILD_NAME" # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+if [[ "$exitCode" -eq 0 ]] && builtin type -P "$BUILD_NAME"; then
+  printf_color "$GRREN" "Successfully installed $BUILD_NAME"
+  exitCode=0
+else
+  printf_color "$RED" "Failed to install $BUILD_NAME"
+  exitCode=1
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# End application
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# lets exit with code
 exit ${exitCode:-$?}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
