🗃️  modified: templates/scripts/bash/build 🗃️

diff --git a/templates/scripts/bash/build b/templates/scripts/bash/build
--- a/templates/scripts/bash/build
+++ b/templates/scripts/bash/build
@@ -19,6 +19,7 @@ VERSION="GEN_SCRIPT_REPLACE_VERSION"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
+PATH="${PATH//:./}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set bash options
 if [[ "$1" == "--debug" ]]; then shift 1 && set -xo pipefail && export SCRIPT_OPTS="--debug" && export _DEBUG="on"; fi
@@ -33,26 +34,31 @@ __make_build() {
   local exitCode_configure="0"
   if [[ -f "$BUILD_SRC_DIR/CMakeLists.txt" ]]; then
     mkdir -p "$BUILD_SRC_DIR/build" && cd "$BUILD_SRC_DIR/build" || exit 10
-    cmake .. 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null &&
-      make -j$(nproc) 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null &&
-      sudo make install 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null &&
-      exitCode_cmake="$?"
+    cmake .. 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null || exitCode+=1
+    make -j$(nproc) 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null || exitCode+=1
+    sudo make install DESTDIR="$BUILD_DESTDIR" 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null || exitCode+=1
+    exitCode_cmake="$?"
   elif [[ -f "$BUILD_SRC_DIR/configure" ]]; then
     __printf_color "$GREEN" "Running configure"
     make clean 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null
-    ./configure --prefix="$BUILD_DESTDIR" 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null
+    ./configure \
+      --prefix="$BUILD_DESTDIR" \
+      --with-lx \
+      --with-pmenu 2>&1 |
+      tee -a "$BUILD_LOG_FILE" &>/dev/null
     exitCode_configure="$?"
     if [[ -f "$BUILD_SRC_DIR/Makefile" ]]; then
       __printf_color "$GREEN" "Running make"
-      make -j$(nproc) 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null &&
-        sudo make install DESTDIR="$BUILD_DESTDIR" 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null
+      make -j$(nproc) 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null || exitCode+=1
+      sudo make 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null &&
+        sudo make install
       exitCode_make="$?"
     fi
   elif [[ -f "$BUILD_SRC_DIR/Makefile" ]]; then
     __printf_color "$GREEN" "Running make"
     make clean 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null
-    make -j$(nproc) 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null &&
-      sudo make install DESTDIR="$BUILD_DESTDIR" 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null
+    make -j$(nproc) 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null || exitCode+=1
+    sudo make install DESTDIR="$BUILD_DESTDIR" 2>&1 | tee -a "$BUILD_LOG_FILE" &>/dev/null
     exitCode_make="$?"
   fi
   if [[ "$exitCode_configure" = 0 ]] && [[ "$exitCode_make" = 0 ]] && [[ "$exitCode_cmake" = 0 ]]; then
@@ -95,13 +101,13 @@ __check_log() {
     warnings="$(grep -i 'warning: ' "$BUILD_LOG_FILE" || echo '')"
     if [[ -n "$warnings" ]]; then
       __printf_color "$RED" "The following warnings have occurred:"
-      echo -e "$warnings"
+      echo -e "$warnings" | printf_readline "7"
       __printf_color "$YELLOW" "Log file saved to $BUILD_LOG_FILE"
       exitCode=0
     fi
     if [[ -n "$errors" ]] || [[ "$exitCode" -ne 0 ]]; then
       __printf_color "$RED" "The following errors have occurred:"
-      echo -e "$errors"
+      echo -e "$errors" | printf_readline "7"
       __printf_color "$YELLOW" "Log file saved to $BUILD_LOG_FILE"
       exitCode=1
     else
@@ -143,9 +149,11 @@ __packages() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __init() {
-  if [[ -z "$BUILD_FORCE" ]] && [[ -n "$(type -P "$BUILD_NAME")" ]]; then
-    __printf_color "$RED" "$BUILD_NAME is already installed" 1>&2
+  if [[ -z "$BUILD_FORCE" ]] && [[ -f "$(builtin type -P "$BUILD_NAME" 2>/dev/null)" ]]; then
+    __printf_color "$RED" "$BUILD_NAME is already installed at:" 1>&2
+    __printf_color "$GREEN" "$(builtin type -P "$BUILD_NAME" 2>/dev/null)"
     __printf_color "$YELLOW" "run with --force to rebuild" 1>&2
+    exitCode="0"
     exit 0
   fi
   __printf_color "$PURPLE" "Initializing build script for $BUILD_NAME"
@@ -258,7 +266,7 @@ if [[ -d "$BUILD_SRC_DIR" ]]; then
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # check
-if [[ "$exitCode" -eq 0 ]] && [[ -n "$(builtin type -P "$BUILD_NAME")" ]]; then
+if [[ "$exitCode" -eq 10 || "$exitCode" -eq 0 ]] && [[ -n "$(builtin type -P "$BUILD_NAME")" ]]; then
   __printf_color "$GREEN" "Successfully installed $BUILD_NAME"
   exitCode=0
 else
