🗃️  modified: templates/scripts/bash/docker-entrypoint 🗃️

diff --git a/templates/scripts/bash/docker-entrypoint b/templates/scripts/bash/docker-entrypoint
--- a/templates/scripts/bash/docker-entrypoint
+++ b/templates/scripts/bash/docker-entrypoint
@@ -25,30 +25,49 @@ SRC_DIR="${BASH_SOURCE%/*}"
 if [[ "$1" == "--debug" ]]; then shift 1 && set -xo pipefail && export SCRIPT_OPTS="--debug" && export _DEBUG="on"; fi
 trap 'exit $?' HUP INT QUIT TERM EXIT
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__exec_bash() { [ -n "$1" ] && exec /bin/bash -c "${@:-bash}" || exec /bin/bash || exit 10; }
+# Set functions
+__exec_bash() {
+  [ $# -eq 0 ] &&
+    exec /bin/bash ||
+    exec /bin/bash -c "${@:-bash}" || return 10
+  return $?
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __find() { ls -A "$*" 2>/dev/null; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Define default variables
+BIN_DIR="${BIN_DIR:-/usr/local/bin}"
 DATA_DIR="${DATA_DIR:-$(__find /data/ 2>/dev/null | grep '^' || false)}"
 CONFIG_DIR="${CONFIG_DIR:-$(__find /config/ 2>/dev/null | grep '^' || false)}"
-export TZ="${TZ:-America/New_York}"
-export HOSTNAME="${HOSTNAME:-casjaysdev-GEN_SCRIPT_REPLACE_APPNAME}"
+TZ="${TZ:-America/New_York}"
+HOSTNAME="${HOSTNAME:-casjaysdev-GEN_SCRIPT_REPLACE_APPNAME}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Additional variables
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Export variables
+export TZ HOSTNAME
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set timezone
 [[ -n "${TZ}" ]] && echo "${TZ}" >/etc/timezone
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 [[ -f "/usr/share/zoneinfo/${TZ}" ]] && ln -sf "/usr/share/zoneinfo/${TZ}" "/etc/localtime"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set hostname
 if [[ -n "${HOSTNAME}" ]]; then
   echo "${HOSTNAME}" >/etc/hostname
   echo "127.0.0.1 $HOSTNAME localhost" >/etc/hosts
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-[[ -d "/config/" ]] && rm -Rf "/config/.gitkeep" || { [[ -n "$CONFIG_DIR" ]] && mkdir -p "/config/"; }
-[[ -d "/data/" ]] && rm -Rf "/data/.gitkeep" || { [[ -n "$DATA_DIR" ]] && mkdir -p "/data/"; }
-[[ -d "/bin/" ]] && rm -Rf "/bin/.gitkeep" || { [[ -n "$DATA_DIR" ]] && mkdir -p "/bin/"; }
+# Delete any gitkeep files
+[[ -n "$CONFIG_DIR" ]] && { [[ -d "$CONFIG_DIR" ]] && rm -Rf "$CONFIG_DIR/.gitkeep" || mkdir -p "/config/"; }
+[[ -n "$DATA_DIR" ]] && { [[ -d "$DATA_DIR" ]] && rm -Rf "$DATA_DIR/.gitkeep" || mkdir -p "/data/"; }
+[[ -n "$BIN_DIR" ]] && { [[ -d "$BIN_DIR" ]] && rm -Rf "$BIN_DIR/.gitkeep" || mkdir -p "/bin/"; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Copy config files to /etc
 if [[ -n "$CONFIG_DIR" ]]; then
   for config in $CONFIG_DIR; do
     if [[ -d "/config/$config" ]]; then
+      [[ -d "/etc/$config" ]] || mkdir -p "/etc/$config"
       cp -Rf "/config/$config/." "/etc/$config/"
     elif [[ -f "/config/$config" ]]; then
       cp -Rf "/config/$config" "/etc/$config"
@@ -56,27 +75,34 @@ if [[ -n "$CONFIG_DIR" ]]; then
   done
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Additional commands
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 case "$1" in
---help)
+--help) # Help message
   echo 'Docker container for '$APPNAME''
   echo "Usage: $APPNAME [healthcheck, bash, command]"
+  echo "Failed command with have exit code 10"
   echo
   exitCode=$?
   ;;
-healthcheck)
+
+healthcheck) # Docker healthcheck
   echo "$(uname -s) $(uname -m) is running"
   exitCode=$?
   ;;
-sh | bash | shell | */bin/sh | */bin/bash)
+
+sh | bash | shell | */bin/sh | */bin/bash) # Launch shell
   shift 1
   __exec_bash "$@"
   exitCode=$?
   ;;
-*)
+
+*) # Execute primary command
   __exec_bash "$@"
+  exitCode=$?
   ;;
 esac
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end of entrypoint
 exit ${exitCode:-$?}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-#end
