🗃️  modified: templates/scripts/bash/docker-entrypoint 🗃️

diff --git a/templates/scripts/bash/docker-entrypoint b/templates/scripts/bash/docker-entrypoint
--- a/templates/scripts/bash/docker-entrypoint
+++ b/templates/scripts/bash/docker-entrypoint
@@ -23,24 +23,25 @@ SRC_DIR="${BASH_SOURCE%/*}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set bash options
 if [[ "$1" == "--debug" ]]; then shift 1 && set -xo pipefail && export SCRIPT_OPTS="--debug" && export _DEBUG="on"; fi
-trap 'exit $?' HUP INT QUIT TERM EXIT
+trap 'exit 0' HUP SIGINT SIGTERM QUIT EXIT
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set functions
 __exec_bash() {
   [ $# -eq 0 ] &&
-    exec /bin/bash ||
-    exec /bin/bash -c "${@:-bash}" || return 10
+    eval /bin/bash ||
+    eval "${@:-bash}" || return 10
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __find() { ls -A "$*" 2>/dev/null; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Define default variables
+TZ="${TZ:-America/New_York}"
+HOSTNAME="${HOSTNAME:-casjaysdev-GEN_SCRIPT_REPLACE_APPNAME}"
 BIN_DIR="${BIN_DIR:-/usr/local/bin}"
 DATA_DIR="${DATA_DIR:-$(__find /data/ 2>/dev/null | grep '^' || false)}"
 CONFIG_DIR="${CONFIG_DIR:-$(__find /config/ 2>/dev/null | grep '^' || false)}"
-TZ="${TZ:-America/New_York}"
-HOSTNAME="${HOSTNAME:-casjaysdev-GEN_SCRIPT_REPLACE_APPNAME}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Additional variables
 
@@ -55,17 +56,17 @@ export TZ HOSTNAME
 # Set hostname
 if [[ -n "${HOSTNAME}" ]]; then
   echo "${HOSTNAME}" >/etc/hostname
-  echo "127.0.0.1 $HOSTNAME localhost" >/etc/hosts
+  echo "127.0.0.1 ${HOSTNAME} localhost ${HOSTNAME}.local" >/etc/hosts
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Delete any gitkeep files
-[[ -n "$CONFIG_DIR" ]] && { [[ -d "$CONFIG_DIR" ]] && rm -Rf "$CONFIG_DIR/.gitkeep" || mkdir -p "/config/"; }
-[[ -n "$DATA_DIR" ]] && { [[ -d "$DATA_DIR" ]] && rm -Rf "$DATA_DIR/.gitkeep" || mkdir -p "/data/"; }
-[[ -n "$BIN_DIR" ]] && { [[ -d "$BIN_DIR" ]] && rm -Rf "$BIN_DIR/.gitkeep" || mkdir -p "/bin/"; }
+[[ -n "${CONFIG_DIR}" ]] && { [[ -d "${CONFIG_DIR}" ]] && rm -Rf "${CONFIG_DIR}/.gitkeep" || mkdir -p "/config/"; }
+[[ -n "${DATA_DIR}" ]] && { [[ -d "${DATA_DIR}" ]] && rm -Rf "${DATA_DIR}/.gitkeep" || mkdir -p "/data/"; }
+[[ -n "${BIN_DIR}" ]] && { [[ -d "${BIN_DIR}" ]] && rm -Rf "${BIN_DIR}/.gitkeep" || mkdir -p "/bin/"; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Copy config files to /etc
-if [[ -n "$CONFIG_DIR" ]]; then
-  for config in $CONFIG_DIR; do
+if [[ -n "${CONFIG_DIR}" ]]; then
+  for config in ${CONFIG_DIR}; do
     if [[ -d "/config/$config" ]]; then
       [[ -d "/etc/$config" ]] || mkdir -p "/etc/$config"
       cp -Rf "/config/$config/." "/etc/$config/"
@@ -76,22 +77,24 @@ if [[ -n "$CONFIG_DIR" ]]; then
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Additional commands
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 case "$1" in
 --help) # Help message
   echo 'Docker container for '$APPNAME''
   echo "Usage: $APPNAME [healthcheck, bash, command]"
-  echo "Failed command with have exit code 10"
+  echo "Failed command will have exit code 10"
   echo
   exitCode=$?
   ;;
 
 healthcheck) # Docker healthcheck
   echo "$(uname -s) $(uname -m) is running"
+  echo _other_commands here
   exitCode=$?
   ;;
 
-sh | bash | shell | */bin/sh | */bin/bash) # Launch shell
+*/bin/sh | */bin/bash | bash | shell | sh) # Launch shell
   shift 1
   __exec_bash "$@"
   exitCode=$?
