🐛 FIXED: templates/scripts/bash/case templates/scripts/bash/simple templates/scripts/bash/system templates/scripts/bash/user 🐛

diff --git a/templates/scripts/bash/simple b/templates/scripts/bash/simple
--- a/templates/scripts/bash/simple
+++ b/templates/scripts/bash/simple
@@ -6,7 +6,7 @@ USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-#set opts
+# Set bash options
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ##@Version       : GEN_SCRIPT_REPLACE_VERSION
@@ -23,12 +23,19 @@ SRC_DIR="${BASH_SOURCE%/*}"
 # @Resource      : GEN_SCRIPT_REPLACE_RES
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
 # Set functions
-__help() { printf ''$APPNAME' help  '; }
+__help() { echo ''$APPNAME' help  '; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__list_available() { printf "${1:-$ARRAY}" | sed 's|:||g;s|'$2'| '$3'|g' 2>/dev/null; }
+__list_available() { echo "${1:-$ARRAY}" | sed 's|:||g;s|'$2'| '$3'|g' 2>/dev/null; }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Additional functions
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Check for needed applications
-type -P bash &>/dev/null || printf "Missing: bash"
+type -P bash &>/dev/null || echo "Missing: bash"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set variables
+exitCode=""
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set options
 SETARGS="$*"
@@ -78,9 +85,9 @@ done
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main application
-printf "$APPNAME $ARGS\n"
-printf "Version: $VERSION\n"
+echo "$APPNAME $ARGS"
+echo "Version: $VERSION"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-exit $?
+exit ${exitCode:-$?}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
