🗃️  modified: templates/scripts/bash/simple 🗃️

diff --git a/templates/scripts/bash/simple b/templates/scripts/bash/simple
--- a/templates/scripts/bash/simple
+++ b/templates/scripts/bash/simple
@@ -25,8 +25,12 @@ if [[ "$1" == "--debug" ]]; then shift 1 && set -xo pipefail && export SCRIPT_OP
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
 # Set functions
-__show_raw() { printf '%s' "$1" | sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' | sed '/^\#/d;/^$/d' | sed 's#\t##g' | sed 's###g'; }
 __devnull() { tee "${*:-}" &>/dev/null; }
+__devnull2() { tee "${*:-}" 2>/dev/null; }
+__version() { echo "$VERSION"; }
+printf_color() { echo -e "\t\t${1:-}${2:-}${NC}"; }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__list_options() { echo "${1:-$ARRAY}" | sed 's|:||g;s|'$2'| '$3'|g' |& __devnull2; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __help() {
   # Help function - Align to 50
@@ -60,20 +64,15 @@ __help() {
   exit
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__version() { echo "$VERSION"; }
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__list_options() { echo "${1:-$ARRAY}" | sed 's|:||g;s|'$2'| '$3'|g' 2>/dev/null; }
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Additional functions
-printf_color() { echo -e "\t\t${1:-}${2:-}${NC}"; }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Check for needed applications
-type -P bash &>/dev/null || { echo "Missing: bash" && exit 1; }
+type -P bash |& __devnull || { echo "Missing: bash" && exit 1; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set variables
-NC="$(tput sgr0 2>/dev/null)"
-RESET="$(tput sgr0 2>/dev/null)"
+NC="$(tput sgr0 |& __devnull2)"
+RESET="$(tput sgr0 |& __devnull2)"
 BLACK="\033[0;30m"
 RED="\033[0;31m"
 GREEN="\033[0;32m"
@@ -84,8 +83,8 @@ CYAN="\033[0;36m"
 WHITE="\033[0;37m"
 ORANGE="\033[0;33m"
 LIGHTRED='\033[1;31m'
-BG_GREEN="\[$(tput setab 2 2>/dev/null)\]"
-BG_RED="\[$(tput setab 9 2>/dev/null)\]"
+BG_GREEN="\[$(tput setab 2 |& __devnull2)\]"
+BG_RED="\[$(tput setab 9 |& __devnull2)\]"
 exitCode=
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Application Folders
@@ -101,8 +100,8 @@ LONGOPTS="debug,raw,help,options,version,help"
 ARRAY=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Setup application options
-setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -a -n "$APPNAME" -- "$@" 2>/dev/null)
-eval set -- "${setopts[@]}" 2>/dev/null
+setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -a -n "$APPNAME" -- "$@" |& __devnull2)
+eval set -- "${setopts[@]}" |& __devnull2
 while :; do
   case $1 in
   --help)
@@ -125,9 +124,6 @@ while :; do
     ;;
   --raw)
     export SHOW_RAW="true"
-    unset -f printf_color
-    printf_color() { printf '%b' "$1" | tr -d '\t\t' | sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'; }
-
     ;;
   --)
     shift 1
@@ -135,6 +131,9 @@ while :; do
     ;;
   esac
 done
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Redefine functions based on options
+[ "$SHOW_RAW" = "true" ] && unset -f printf_color && printf_color() { printf '%b' "$1" | tr -d '\t\t' | sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Additional variables
 
