🗃️ Committing everything that changed 🗃️
bin/am_i_online
bin/anime-dl
bin/anonymize
bin/append_path
bin/ask_for_input
bin/ask_for_password
bin/ask_yes_no_question
bin/automate
bin/backupapp
bin/bashtop
bin/blog
bin/buildx
bin/calc
bin/calendar
bin/changeip
bin/cheat.sh
bin/check_app
bin/check-for-updates
bin/clean-system
bin/client-installs
bin/clipboard
bin/cloudflare
bin/cmd_exists
bin/cmdfu
bin/command
bin/config
bin/corona-virus
bin/covid19
bin/currency
bin/decrypt
bin/define
bin/dfmgr
bin/gen-completion
bin/gen-script
bin/pkmgr
bin/real_path
bin/type
bin/volumectl
functions/app-installer.bash
functions/global/colors.bash
functions/global/options.bash
functions/mgr-installers.bash
functions/minimal.bash
functions/system-installer.bash
templates/gen-script/header/raw.tmpl.sh
templates/gen-script/script/system.tmpl.sh
templates/gen-script/script/user.tmpl.sh
templates/scripts/bash/simple
templates/scripts/bash/system
templates/scripts/bash/terminal
templates/scripts/bash/user
templates/scripts/installers/desktopmgr.sh
templates/scripts/installers/devenvmgr.sh
templates/scripts/installers/dfmgr.sh
templates/scripts/installers/dockermgr.sh
templates/scripts/installers/fontmgr.sh
templates/scripts/installers/iconmgr.sh
templates/scripts/installers/mgr-script.system.sh
templates/scripts/installers/mgr-script.user.sh
templates/scripts/installers/personal.sh
templates/scripts/installers/systemmgr.sh
templates/scripts/installers/thememgr.sh
templates/scripts/installers/wallpapermgr.sh
templates/scripts/other/build
templates/scripts/other/docker-entrypoint
templates/scripts/shell/bash
templates/scripts/shell/sh

diff --git a/templates/scripts/bash/simple b/templates/scripts/bash/simple
--- a/templates/scripts/bash/simple
+++ b/templates/scripts/bash/simple
@@ -27,25 +27,35 @@ SRC_DIR="${BASH_SOURCE%/*}"
 # Set bash options
 #if [ ! -t 0 ] && { [[ "$1" = *term ]] || [ $# = 0 ]; }; then { [[ "$1" = *term ]] && shift 1 || true; } && TERMINAL_APP="TRUE" myterminal -e "$APPNAME $*" && exit || exit 1; fi
 [[ "$1" = "--debug" ]] && set -xo pipefail && export SCRIPT_OPTS="--debug" && export _DEBUG="on"
-[[ "$1" = "--raw" ]] && SHOW_RAW="true" && printf_color() { printf '%b' "$1\n" | tr -d '\t\t' | sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'; }
+[[ "$1" = "--raw" ]] && export SHOW_RAW="true"
 set -o pipefail
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
-# Set functions
-__devnull() {
+# Send all output to /dev/null
+devnull() {
   tee &>/dev/null || exitCode=1
   return ${exitCode:-$?}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
-__cmd_exists() {
+# Check for program
+cmd_exists() {
   local exitCode=0
   for cmd in "$@"; do
-    builtin command -v "$cmd" |& __devnull && true || exitCode+=1
+    builtin command -v "$cmd" |& devnull && true || exitCode+=1
   done
   return ${exitCode:-$?}
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Check for internet connection
+am_i_online() {
+  curl -q -LSsfI --max-time 1 --retry 0 "${1:-http://1.1.1.1}" | grep -qi 'server:.*cloudflare' 2>&1 || return 1
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
 # colorization
-printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "\t\t$1\n" "$(tput sgr0 2>/dev/null)"; }
+if [[ "$SHOW_RAW" = "true" ]]; then
+  printf_color() { printf '%b' "$1\n" | tr -d '\t' | sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'; }
+else
+  printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "\t\t$1\n" "$(tput sgr0 2>/dev/null)"; }
+fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # output version
 __version() { printf_color "$VERSION" "2"; }
@@ -113,9 +123,6 @@ __help() {
 # User defined functions
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Defaults
-exitCode=0
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Application Folders
 GEN_SCRIPT_REPLACE_ENV_CONFIG_FILE="${GEN_SCRIPT_REPLACE_ENV_CONFIG_FILE:-settings.conf}"
 GEN_SCRIPT_REPLACE_ENV_CACHE_DIR="${GEN_SCRIPT_REPLACE_ENV_CACHE_DIR:-$HOME/.cache/GEN_SCRIPT_REPLACE_FILENAME}"
@@ -148,9 +155,9 @@ GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_URGENCY="${GEN_SCRIPT_REPLACE_ENV_NOTIFY_CL
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Ensure Directories exist
 [ -d "$GEN_SCRIPT_REPLACE_ENV_LOG_DIR" ] ||
-  mkdir -p "$GEN_SCRIPT_REPLACE_ENV_LOG_DIR" |& __devnull
+  mkdir -p "$GEN_SCRIPT_REPLACE_ENV_LOG_DIR" |& devnull
 [ -d "$GEN_SCRIPT_REPLACE_ENV_TEMP_DIR" ] ||
-  mkdir -p "$GEN_SCRIPT_REPLACE_ENV_TEMP_DIR" |& __devnull
+  mkdir -p "$GEN_SCRIPT_REPLACE_ENV_TEMP_DIR" |& devnull
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Setup notification function
 if [ "$GEN_SCRIPT_REPLACE_ENV_NOTIFY_ENABLED" = "yes" ]; then
@@ -184,17 +191,14 @@ while :; do
   case "$1" in
   --raw)
     shift 1
-    SHOW_RAW="true"
+    export SHOW_RAW="true"
     printf_column() { tee | grep '^'; }
-    printf_color() {
-      printf '%b' "$1\n" | tr -d '\t\t' |
-        sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'
-    }
+    printf_color() { printf '%b' "$1\n" | tr -d '\t' | sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'; }
     ;;
   --debug)
     shift 1
     set -xo pipefail
-    __devnull() {
+    devnull() {
       tee || exitCode=1
       return ${exitCode:-$?}
     }
@@ -236,8 +240,8 @@ done
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Check for required applications/Network check
-cmd_exists --error bash || exit 3 # exit 3 if not found
-#am_i_online --error || exit 4     # exit 4 if no internet
+#cmd_exists bash || exit 3       # exit 3 if not found
+#am_i_online "1.1.1.1" || exit 4 # exit 4 if no internet
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # APP Variables overrides
 
@@ -248,6 +252,9 @@ cmd_exists --error bash || exit 3 # exit 3 if not found
 # begin main app
 printf_color "Name: $APPNAME $ARGS" "2"
 printf_color "Version: $VERSION" "2"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set exit code
+exitCode="${exitCode:-$?}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
diff --git a/templates/scripts/bash/system b/templates/scripts/bash/system
--- a/templates/scripts/bash/system
+++ b/templates/scripts/bash/system
@@ -27,7 +27,7 @@ SRC_DIR="${BASH_SOURCE%/*}"
 # Set bash options
 #if [ ! -t 0 ] && { [[ "$1" = *term ]] || [ $# = 0 ]; }; then { [[ "$1" = *term ]] && shift 1 || true; } && TERMINAL_APP="TRUE" myterminal -e "$APPNAME $*" && exit || exit 1; fi
 [[ "$1" = "--debug" ]] && set -xo pipefail && export SCRIPT_OPTS="--debug" && export _DEBUG="on"
-[[ "$1" = "--raw" ]] && SHOW_RAW="true" && printf_color() { printf '%b' "$1" | tr -d '\t\t' | sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'; }
+[[ "$1" = "--raw" ]] && export SHOW_RAW="true" && printf_color() { printf '%b' "$1" | tr -d '\t' | sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'; }
 set -o pipefail
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Import functions
@@ -45,8 +45,8 @@ else
   exit 1
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Options are: devenvmgr_install dfmgr_install dockermgr_install fontmgr_install iconmgr_install pkmgr_install
-# system_install systemmgr_install thememgr_install user_install wallpapermgr_install
+# Options are: desktopmgr_install devenvmgr_install dfmgr_install dockermgr_install fontmgr_install iconmgr_install
+# pkmgr_install system_install systemmgr_install thememgr_install user_install wallpapermgr_install
 user_install && __options "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set functions
@@ -62,6 +62,11 @@ __cmd_exists() {
   done
   return ${exitCode:-$?}
 }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Disable colorization
+if [[ "$SHOW_RAW" = "true" ]]; then
+  printf_color() { printf '%b' "$1\n" | tr -d '\t' | sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'; }
+fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # output version
 __version() { printf_color "$VERSION" "2"; }
@@ -148,9 +153,6 @@ __help() {
 # User defined functions
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Defaults
-exitCode=0
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Application Folders
 GEN_SCRIPT_REPLACE_ENV_CONFIG_FILE="${GEN_SCRIPT_REPLACE_ENV_CONFIG_FILE:-settings.conf}"
 GEN_SCRIPT_REPLACE_ENV_CONFIG_DIR="${GEN_SCRIPT_REPLACE_ENV_CONFIG_DIR:-$HOME/.config/myscripts/GEN_SCRIPT_REPLACE_FILENAME}"
@@ -231,10 +233,10 @@ while :; do
   case "$1" in
   --raw)
     shift 1
-    SHOW_RAW="true"
+    export SHOW_RAW="true"
     printf_column() { tee | grep '^'; }
     printf_color() {
-      printf '%b' "$1" | tr -d '\t\t' |
+      printf '%b' "$1" | tr -d '\t' |
         sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'
     }
     ;;
@@ -299,7 +301,9 @@ cmd_exists --error bash || exit 3 # exit 3 if not found
 # begin main app
 printf_green "Version:$VERSION"
 printf_green "DIR=$GEN_SCRIPT_REPLACE_ENV_CONFIG_DIR"
-
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set exit code
+exitCode="${exitCode:-$?}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
diff --git a/templates/scripts/bash/user b/templates/scripts/bash/user
--- a/templates/scripts/bash/user
+++ b/templates/scripts/bash/user
@@ -27,7 +27,7 @@ SRC_DIR="${BASH_SOURCE%/*}"
 # Set bash options
 #if [ ! -t 0 ] && { [[ "$1" = *term ]] || [ $# = 0 ]; }; then { [[ "$1" = *term ]] && shift 1 || true; } && TERMINAL_APP="TRUE" myterminal -e "$APPNAME $*" && exit || exit 1; fi
 [[ "$1" = "--debug" ]] && set -xo pipefail && export SCRIPT_OPTS="--debug" && export _DEBUG="on"
-[[ "$1" = "--raw" ]] && SHOW_RAW="true" && printf_color() { printf '%b' "$1" | tr -d '\t\t' | sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'; }
+[[ "$1" = "--raw" ]] && export SHOW_RAW="true" && printf_color() { printf '%b' "$1" | tr -d '\t' | sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'; }
 set -o pipefail
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function file
@@ -55,6 +55,11 @@ __cmd_exists() {
   done
   return ${exitCode:-$?}
 }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Disable colorization
+if [[ "$SHOW_RAW" = "true" ]]; then
+  printf_color() { printf '%b' "$1\n" | tr -d '\t' | sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'; }
+fi
 ## - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # output version
 __version() { printf_color "$VERSION" "2"; }
@@ -82,7 +87,6 @@ GEN_SCRIPT_REPLACE_ENV_OUTPUT_COLOR="${GEN_SCRIPT_REPLACE_ENV_OUTPUT_COLOR:-}"
 GEN_SCRIPT_REPLACE_ENV_OUTPUT_COLOR_2="${GEN_SCRIPT_REPLACE_ENV_OUTPUT_COLOR:-}"
 GEN_SCRIPT_REPLACE_ENV_OUTPUT_COLOR_GOOD="${GEN_SCRIPT_REPLACE_ENV_OUTPUT_COLOR_GOOD:-}"
 GEN_SCRIPT_REPLACE_ENV_OUTPUT_COLOR_ERROR="${GEN_SCRIPT_REPLACE_ENV_OUTPUT_COLOR_ERROR:-}"
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Notification Settings
 GEN_SCRIPT_REPLACE_ENV_NOTIFY_ENABLED="${GEN_SCRIPT_REPLACE_ENV_NOTIFY_ENABLED:-}"
@@ -93,7 +97,6 @@ GEN_SCRIPT_REPLACE_ENV_ERROR_MESSAGE="${GEN_SCRIPT_REPLACE_ENV_ERROR_MESSAGE:-}"
 GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_NAME="${GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_NAME:-}"
 GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_ICON="${GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_ICON:-}"
 GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_URGENCY="${GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_URGENCY:-}"
-
 EOF
   if [ -f "$GEN_SCRIPT_REPLACE_ENV_CONFIG_DIR/$GEN_SCRIPT_REPLACE_ENV_CONFIG_FILE" ]; then
     [[ "$INIT_CONFIG" = "TRUE" ]] || printf_green "Your config file for $APPNAME has been created"
@@ -140,9 +143,6 @@ __help() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # User defined functions
 
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Defaults
-exitCode=0
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Application Folders
 GEN_SCRIPT_REPLACE_ENV_CONFIG_FILE="${GEN_SCRIPT_REPLACE_ENV_CONFIG_FILE:-settings.conf}"
@@ -225,10 +225,10 @@ while :; do
   case "$1" in
   --raw)
     shift 1
-    SHOW_RAW="true"
+    export SHOW_RAW="true"
     printf_column() { tee | grep '^'; }
     printf_color() {
-      printf '%b' "$1" | tr -d '\t\t' |
+      printf '%b' "$1" | tr -d '\t' |
         sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'
     }
     ;;
@@ -293,7 +293,9 @@ cmd_exists --error bash || exit 3 # exit 3 if not found
 # begin main app
 printf_green "Version:$VERSION"
 printf_green "DIR=$GEN_SCRIPT_REPLACE_ENV_CONFIG_DIR"
-
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set exit code
+exitCode="${exitCode:-$?}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
