🗃 Modified: bin/notifications bin/pkmgr templates/scripts/bash/simple templates/scripts/bash/system templates/scripts/bash/user  🗃

diff --git a/templates/scripts/bash/user b/templates/scripts/bash/user
--- a/templates/scripts/bash/user
+++ b/templates/scripts/bash/user
@@ -3,6 +3,7 @@ GEN_SCRIPT_REPLACE_FILENAME_main() {
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   PROG="$(basename "$0")"
   VERSION="GEN_SCRIPT_REPLACE_VERSION"
+  RUN_USER="${SUDO_USER:-${USER}}"
   USER="${SUDO_USER:-${USER}}"
   HOME="${USER_HOME:-${HOME}}"
   SRC_DIR="${BASH_SOURCE%/*}"
@@ -26,13 +27,13 @@ GEN_SCRIPT_REPLACE_FILENAME_main() {
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # Main function file
   if [ -f "$SRC_DIR/functions.bash" ]; then
-    FUNCTIONS_DIR="$SRC_DIR"
+    local FUNCTIONS_DIR="$SRC_DIR"
     . "$FUNCTIONS_DIR/functions.bash"
   elif [ -f "$HOME/.local/bin/functions.bash" ]; then
-    FUNCTIONS_DIR="$HOME/.local/bin"
+    local FUNCTIONS_DIR="$HOME/.local/bin"
     . "$FUNCTIONS_DIR/functions.bash"
   else
-    printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+    printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from ${FUNCTIONS_DIR:-$SRC_DIR}"
     return 1
   fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -57,7 +58,11 @@ GEN_SCRIPT_REPLACE_FILENAME_main() {
       cp -Rf "$GEN_SCRIPT_REPLACE_CONFIG_DIR/$GEN_SCRIPT_REPLACE_CONFIG_FILE" "$GEN_SCRIPT_REPLACE_ENV_CONFIG_BACKUP_DIR/$GEN_SCRIPT_REPLACE_CONFIG_FILE.$$"
     cat <<EOF >"$GEN_SCRIPT_REPLACE_CONFIG_DIR/$GEN_SCRIPT_REPLACE_CONFIG_FILE"
 # Settings for GEN_SCRIPT_REPLACE_FILENAME
-GEN_SCRIPT_REPLACE_ENV_NOTIFY_ENABLED="yes"
+
+# Notification settings
+GEN_SCRIPT_REPLACE_ENV_GOOD_MESSAGE="${GEN_SCRIPT_REPLACE_ENV_GOOD_MESSAGE:-Everything Went OK}"
+GEN_SCRIPT_REPLACE_ENV_ERROR_MESSAGE="${GEN_SCRIPT_REPLACE_ENV_ERROR_MESSAGE:-Well that didn\'t work}"
+GEN_SCRIPT_REPLACE_ENV_NOTIFY_ENABLED="${GEN_SCRIPT_REPLACE_ENV_NOTIFY_ENABLED:-yes}"
 GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_NAME="${NOTIFY_CLIENT_NAME:-$PROG}"
 GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_ICON="${NOTIFY_CLIENT_ICON:-$GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_ICON}"
 
@@ -71,25 +76,36 @@ EOF
     fi
   }
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Set functions
+  __list_available() { printf_custom "$1" "$2: $(echo ${3:-$ARRAY} | __sed 's|:||g;s|'$4'| '$5'|g')" 2>/dev/null; }
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # Defaults
   local exitCode=""
-  local GEN_SCRIPT_REPLACE_ENV_CONFIG_FILE="settings.conf"
-  local GEN_SCRIPT_REPLACE_ENV_CONFIG_DIR="$HOME/.config/misc/GEN_SCRIPT_REPLACE_FILENAME"
-  local GEN_SCRIPT_REPLACE_ENV_CONFIG_BACKUP_DIR="$HOME/.local/share/misc/GEN_SCRIPT_REPLACE_FILENAME/backups"
-  local GEN_SCRIPT_REPLACE_ENV_OPTIONS_DIR="$HOME/.local/share/misc/GEN_SCRIPT_REPLACE_FILENAME/options"
-  local GEN_SCRIPT_REPLACE_ENV_TEMP_FILE="${TMPDIR:-/tmp}/GEN_SCRIPT_REPLACE_FILENAME"
-  local GEN_SCRIPT_REPLACE_ENV_NOTIFY_ENABLED="yes"
+  local GEN_SCRIPT_REPLACE_ENV_CACHE_DIR="${GEN_SCRIPT_REPLACE_ENV_CACHE_DIR:-/$HOME/.cache/GEN_SCRIPT_REPLACE_FILENAME}"
+  local GEN_SCRIPT_REPLACE_ENV_CONFIG_DIR="${GEN_SCRIPT_REPLACE_ENV_CONFIG_DIR:-$HOME/.config/misc/GEN_SCRIPT_REPLACE_FILENAME}"
+  local GEN_SCRIPT_REPLACE_ENV_OPTIONS_DIR="${GEN_SCRIPT_REPLACE_ENV_OPTIONS_DIR:-$HOME/.local/share/misc/GEN_SCRIPT_REPLACE_FILENAME/options}"
+  local GEN_SCRIPT_REPLACE_ENV_CONFIG_BACKUP_DIR="${GEN_SCRIPT_REPLACE_ENV_CONFIG_BACKUP_DIR:-$HOME/.local/share/misc/GEN_SCRIPT_REPLACE_FILENAME/backups}"
+  local GEN_SCRIPT_REPLACE_ENV_TEMP_DIR="${GEN_SCRIPT_REPLACE_ENV_TEMP_DIR/user_scripts:-$HOME/.local/tmp/user_scripts}"
+  local GEN_SCRIPT_REPLACE_ENV_TEMP_FILE="${GEN_SCRIPT_REPLACE_ENV_TEMP_DIR:-$HOME/.local/tmp}/GEN_SCRIPT_REPLACE_FILENAME"
+  local GEN_SCRIPT_REPLACE_ENV_CONFIG_FILE="${GEN_SCRIPT_REPLACE_ENV_CONFIG_FILE:-settings.conf}"
+  local GEN_SCRIPT_REPLACE_ENV_GOOD_MESSAGE="${GEN_SCRIPT_REPLACE_ENV_GOOD_MESSAGE:-Everything Went OK}"
+  local GEN_SCRIPT_REPLACE_ENV_ERROR_MESSAGE="${GEN_SCRIPT_REPLACE_ENV_ERROR_MESSAGE:-Well that didn\'t work}"
+  local GEN_SCRIPT_REPLACE_ENV_NOTIFY_ENABLED="${GEN_SCRIPT_REPLACE_ENV_NOTIFY_ENABLED:-yes}"
   local GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_NAME="${NOTIFY_CLIENT_NAME:-$PROG}"
   local GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_ICON="${NOTIFY_CLIENT_ICON:-$GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_ICON}"
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Ensure Directories exist
+  mkdir -p "$GEN_SCRIPT_REPLACE_ENV_TEMP_DIR" "$GEN_SCRIPT_REPLACE_ENV_CACHE_DIR"
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # Argument/Option settings
   local SETARGS="$*"
-  local SHORTOPTS="c,v,h"
-  local LONGOPTS="options,config,version,help"
+  local SHORTOPTS="c,v,h,z:"
+  local LONGOPTS="options,config,version,help,dir:"
   local ARRAY=""
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # Generate Files
-  [ -f "$GEN_SCRIPT_REPLACE_CONFIG_DIR/$GEN_SCRIPT_REPLACE_CONFIG_FILE" ] || __gen_config &>/dev/null
+  [ -f "$GEN_SCRIPT_REPLACE_CONFIG_DIR/$GEN_SCRIPT_REPLACE_CONFIG_FILE" ] ||
+    __gen_config &>/dev/null
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # Import config
   [ -f "$GEN_SCRIPT_REPLACE_CONFIG_DIR/$GEN_SCRIPT_REPLACE_CONFIG_FILE" ] &&
@@ -126,20 +142,25 @@ EOF
       __gen_config
       exit $?
       ;;
+    -z | --dir)
+      shift 1
+      GEN_SCRIPT_REPLACE_CWD="$1"
+      ;;
     --)
       shift 1
       break
       ;;
-      #*) break ;;
     esac
   done
   #set -- "$SETARGS"
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # Actions based on env
-  export NOTIFY_CLIENT_NAME="${GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_NAME}"
-  export NOTIFY_CLIENT_ICON="${GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_ICON}"
   if [ "$GEN_SCRIPT_REPLACE_ENV_NOTIFY_ENABLED" = "yes" ]; then
     __notifications() {
+      export NOTIFY_GOOD_MESSAGE="${GEN_SCRIPT_REPLACE_ENV_GOOD_MESSAGE}"
+      export NOTIFY_ERROR_MESSAGE="${GEN_SCRIPT_REPLACE_ENV_ERROR_MESSAGE}"
+      export NOTIFY_CLIENT_NAME="${GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_NAME}"
+      export NOTIFY_CLIENT_ICON="${GEN_SCRIPT_REPLACE_ENV_NOTIFY_CLIENT_ICON}"
       notifications "$*" || return 1
     }
   else
@@ -148,8 +169,9 @@ EOF
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # Check for required applications/Network check
   cmd_exists --error bash || exit 1 # exit 1 if not found
+  #am_i_online --error || exit       # exit 1 if no internet
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  # APP Variables
+  # APP Variables overrides
 
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # begin main app
