🗃️ Updated pipes with to tee -p 🗃️
bin/am_i_online
bin/anime-dl
bin/anonymize
bin/append_path
bin/ask_for_input
bin/ask_for_password
bin/ask_yes_no_question
bin/automate
bin/backupapp
bin/bashtop
bin/blog
bin/buildx
bin/calc
bin/calendar
bin/cdd
bin/changeip
bin/cheat.sh
bin/check_app
bin/check-for-updates
bin/clean-system
bin/client-installs
bin/clipboard
bin/cloudflare
bin/cmd_exists
bin/cmdfu
bin/command
bin/config
bin/config-editor
bin/corona-virus
bin/covid19
bin/currency
bin/daysup
bin/decrypt
bin/define
bin/desktopmgr
bin/devenvmgr
bin/devhints
bin/dictionary
bin/diskusage
bin/displayselect
bin/dmenuhandler
bin/dmenurecord
bin/dmenu-usb
bin/dockerignore
bin/dockermgr
bin/dockerrun
bin/dos2unix
bin/duckdns
bin/earthquakes
bin/emojis
bin/encrypt
bin/eslint-config
bin/ex
bin/expandurl
bin/explainshell
bin/findInstallApp
bin/findmydevices
bin/findmypi
bin/findmyroku
bin/gen-apache
bin/gen-caddy
bin/gen-changelog
bin/gen-completion
bin/gen-dns
bin/gen-dockerfile
bin/gen-dockermgr
bin/gen-gitattr
bin/gen-header
bin/gen-html
bin/gen-license
bin/gen-links
bin/gen-network
bin/gen-nginx
bin/gen-passwd
bin/gen-playlist
bin/gen-readme
bin/gen-script
bin/gen-ssl
bin/gen-vars
bin/get_city_id
bin/gitadmin
bin/gitcommit
bin/gitignore
bin/hakmgr
bin/hostnamecli
bin/hue
bin/ifinstalled
bin/ifttt
bin/images
bin/imperial2metric
bin/ix.io
bin/killproc
bin/killzombies
bin/latest-iso
bin/latest-releases
bin/logout-menu
bin/logr
bin/lorem
bin/lsbin
bin/lxcmgr
bin/mailsync
bin/metric2imperial
bin/mpdclient
bin/mpd-notify
bin/multimedia
bin/music
bin/mybluetooth
bin/mybrowser
bin/mydate
bin/myeditor
bin/myemail
bin/myfilemanager
bin/myip
bin/mylocation
bin/mymenu
bin/myps
bin/myshell
bin/myssh
bin/myterminal
bin/mytorrent
bin/myvmmanager
bin/netstatg
bin/netstatl
bin/notes
bin/notflix
bin/notifications
bin/notify-daemon
bin/passmgr
bin/pastebin
bin/pkmgr
bin/port_test
bin/post2social
bin/postit
bin/proxmox-cli
bin/pslist
bin/publishit
bin/pushbullet
bin/radioreference
bin/random-string
bin/randomwallpaper
bin/readme-2-post
bin/real_path
bin/recording
bin/reqpkgs
bin/rmd
bin/roku
bin/run_command
bin/run_in_term
bin/run_options
bin/run_server
bin/scratchpad
bin/screencast
bin/screenshot-menu
bin/search-menu
bin/send-notify
bin/shortenurl
bin/showterm
bin/social
bin/spellcheck
bin/sprunge.us
bin/sshto
bin/ss_screenkey
bin/sudoers
bin/systemmgr
bin/sysusage
bin/tasks
bin/tell-joke
bin/termbin.com
bin/thesaurus
bin/timeis
bin/timer
bin/tldr
bin/tmux-new
bin/todo
bin/tor-site
bin/transfer.sh
bin/translate
bin/trash
bin/tryforever
bin/type
bin/update-ip
bin/update-lecerts
bin/update-motd
bin/update-resolv
bin/urbandict
bin/urlcheck
bin/urldecode
bin/urlencode
bin/usb-writer
bin/venv
bin/videos
bin/virt-check
bin/virtmgr
bin/volumectl
bin/weather
bin/web-notify
bin/wikipedia
bin/xephyr
bin/ytda
bin/ytdv
bin/ytstream
completions/complete_alias
functions/mgr-installers.bash
helpers/obsolete/buildx
helpers/obsolete/gen-dockerfile
helpers/obsolete/gen-env
install.sh
README.md
sources/cheat.sh
sources/tdrop
templates/dockerfiles/ubuntu.template
templates/scripts/bash/mgr-script.system.sh
templates/scripts/bash/mgr-script.user.sh
templates/scripts/bash/simple
templates/scripts/bash/system
templates/scripts/bash/terminal
templates/scripts/bash/user
templates/scripts/functions/docker-entrypoint
templates/scripts/installers/dockermgr.sh
templates/scripts/os/arch.sh
templates/scripts/os/centos.sh
templates/scripts/other/build
templates/scripts/other/start-service

diff --git a/helpers/obsolete/buildx b/helpers/obsolete/buildx
--- a/helpers/obsolete/buildx
+++ b/helpers/obsolete/buildx
@@ -363,11 +363,11 @@ __create_update_docker_daemon_config() {
     __sudo true
     sudo mkdir -p "/etc/docker"
     if [ ! -f "/etc/docker/daemon.json" ]; then
-      printf '{\n  %s\n}' "\"experimental\": true" | sudo tee -a "/etc/docker/daemon.json" &>/dev/null
+      printf '{\n  %s\n}' "\"experimental\": true" | sudo tee -p -a "/etc/docker/daemon.json" &>/dev/null
     elif grep -sq "experimental" "/etc/docker/daemon.json"; then
       sudo sed -i 's|experimental.*e|experimental": true|g' "/etc/docker/daemon.json"
     else
-      echo "{\"experimental\": true}," | sudo tee -a "/etc/docker/daemon.json" &>/dev/null
+      echo "{\"experimental\": true}," | sudo tee -p -a "/etc/docker/daemon.json" &>/dev/null
     fi
   fi
 }
@@ -725,9 +725,9 @@ __docker_init() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __docker_push() {
-  __docker push "$tagged_name" |& tee -a "$logfile" &>/dev/null ||
-    __docker push "$tagged_name" |& tee -a "$logfile" &>/dev/null ||
-    __docker push "$tagged_name" |& tee -a "$logfile" &>/dev/null && true
+  __docker push "$tagged_name" |& tee -p -a "$logfile" &>/dev/null ||
+    __docker push "$tagged_name" |& tee -p -a "$logfile" &>/dev/null ||
+    __docker push "$tagged_name" |& tee -p -a "$logfile" &>/dev/null && true
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -789,16 +789,16 @@ __reinit_buildx() {
   [ "$BUILDX_INIT_RAN" != "true" ] || return 0
   [ "$force_install" = "yes" ] || [ -z "$builder_id" ] || [ -z "$binfmt_id" ] || [ -z "$qemu_id" ] || return 0
   printf_cyan "Reinitializing buildx: $BUILDX_BUILDER_NAME on: $(date)"
-  echo "Reinitializing buildx: $BUILDX_BUILDER_NAME on: $(date)" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+  echo "Reinitializing buildx: $BUILDX_BUILDER_NAME on: $(date)" |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
   local force="${force_install:-$BUILDX_CLEAN_FORCE}"
-  [ -z "$builder_id" ] || __docker_init rm -f --volumes $builder_id |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
-  [ -z "$binfmt_id" ] || __docker_init rm -f --volumes "$qemu_imagename" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
-  [ -z "$qemu_id" ] || __docker_init rm -f --volumes "$binfmt_imagename" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
-  __docker_init run -d --name "$qemu_imagename" --privileged multiarch/qemu-user-static --reset -p yes --credential yes |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
-  __docker_init run -d --name "$binfmt_imagename" --privileged tonistiigi/binfmt --install all |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
-  __docker_init buildx create --driver docker-container --driver-opt network=host --driver-opt image=moby/buildkit:master --name ${BUILDX_BUILDER_NAME:-mybuilder} --use |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
-  __docker_init buildx use "$BUILDX_BUILDER_NAME" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
-  __docker_init buildx inspect --bootstrap |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+  [ -z "$builder_id" ] || __docker_init rm -f --volumes $builder_id |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+  [ -z "$binfmt_id" ] || __docker_init rm -f --volumes "$qemu_imagename" |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+  [ -z "$qemu_id" ] || __docker_init rm -f --volumes "$binfmt_imagename" |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+  __docker_init run -d --name "$qemu_imagename" --privileged multiarch/qemu-user-static --reset -p yes --credential yes |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+  __docker_init run -d --name "$binfmt_imagename" --privileged tonistiigi/binfmt --install all |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+  __docker_init buildx create --driver docker-container --driver-opt network=host --driver-opt image=moby/buildkit:master --name ${BUILDX_BUILDER_NAME:-mybuilder} --use |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+  __docker_init buildx use "$BUILDX_BUILDER_NAME" |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+  __docker_init buildx inspect --bootstrap |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
   __buildx_vars "${BUILDX_BUILDER_NAME:-}"
   __create_update_docker_daemon_config
   if [ -n "$builder_id" ] && __is_buildx_installed; then
@@ -806,10 +806,10 @@ __reinit_buildx() {
     BUILDX_INIT_RAN="true"
     BUILDX_FORCE_REINSTALL=""
     printf_cyan "Building for platforms: $BUILDX_DOCKER_PLATFORMS"
-    printf '%s\n' " # Building for platforms: $BUILDX_DOCKER_PLATFORMS" | tee -a "$logfile" &>/dev/null
+    printf '%s\n' " # Building for platforms: $BUILDX_DOCKER_PLATFORMS" | tee -p -a "$logfile" &>/dev/null
     return 0
   else
-    echo "Initializing of buildx failed" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+    echo "Initializing of buildx failed" |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
     printf_yellow "Initializing of buildx failed"
     return 1
   fi
@@ -883,29 +883,29 @@ __buildx_init() {
     printf_cyan "buildx seems to be already setup"
     return 0
   else
-    echo "Starting buildx init for $name on $(date)" |& tee "$HOME/.local/log/buildx/$name.log"
+    echo "Starting buildx init for $name on $(date)" |& tee -p "$HOME/.local/log/buildx/$name.log"
     printf_yellow "Initializing docker build"
     printf_cyan "Setting logfile to: $buildx_log_file"
     if [ "$BUILDX_CLEANUP" = "true" ] || { [ -n "$binfmt" ] && [ -n "$qemu" ]; }; then
       printf_yellow "Removing old containers: $qemu_imagename,$binfmt_imagename"
-      __docker_init rm -f --volumes "$qemu_imagename" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
-      __docker_init rm -f --volumes "$binfmt_imagename" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+      __docker_init rm -f --volumes "$qemu_imagename" |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+      __docker_init rm -f --volumes "$binfmt_imagename" |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
     fi
     __install_buildx
     if [ "$(uname -m)" = "x86_64" ]; then
       # Setup qemu
       # sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
       printf_yellow "Setting up the qemu image - multiarch/qemu-user-static as $qemu_imagename"
-      __docker_init run -d --name "$qemu_imagename" --privileged multiarch/qemu-user-static --reset -p yes --credential yes |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+      __docker_init run -d --name "$qemu_imagename" --privileged multiarch/qemu-user-static --reset -p yes --credential yes |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
       # Setup binfmt
       printf_yellow "Setting up the binfmt image - tonistiigi/binfmt as $binfmt_imagename"
-      __docker_init run -d --name "$binfmt_imagename" --privileged tonistiigi/binfmt --install all |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+      __docker_init run -d --name "$binfmt_imagename" --privileged tonistiigi/binfmt --install all |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
       # setup buildx
       printf_blue "Setting up docker build to use buildx"
-      #__docker_init buildx create --buildkitd-flags '--allow-insecure-entitlement security.insecure' --name "$name" --use |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
-      __docker_init buildx create --driver docker-container --driver-opt network=host --driver-opt image=moby/buildkit:master --name ${name:-mybuilder} --use |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
-      __docker_init buildx use "$name" |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
-      __docker_init buildx inspect --bootstrap |& tee -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+      #__docker_init buildx create --buildkitd-flags '--allow-insecure-entitlement security.insecure' --name "$name" --use |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+      __docker_init buildx create --driver docker-container --driver-opt network=host --driver-opt image=moby/buildkit:master --name ${name:-mybuilder} --use |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+      __docker_init buildx use "$name" |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
+      __docker_init buildx inspect --bootstrap |& tee -p -a "$HOME/.local/log/buildx/$name.log" &>/dev/null
     fi
     if [ "$BUILDX_INIT_RAN" != "yes" ]; then
       # create docker daemon file
@@ -978,17 +978,17 @@ __run_docker_script() {
   build_command="$(echo "$set_build_command" | grep '^' | grep -v '^$' | sed 's|,,| \\\n|g')"
   set_build_command="${set_build_command//,,/}"
   printf '%b%s: %b%s%b\n' "$GREEN" "Saving the build command to" "$CYAN" "$logscript_file" "$NC"
-  printf 'Saving the build command to: %s\n' "$logscript_file" | tee -a "$logfile" &>/dev/null
+  printf 'Saving the build command to: %s\n' "$logscript_file" | tee -p -a "$logfile" &>/dev/null
   __save_build_script
   printf_blue "Setting default tag to: $set_tag"
-  echo "$BUILDX_GET_VERSION_MESSAGE" | tee -a "$logfile" &>/dev/null
+  echo "$BUILDX_GET_VERSION_MESSAGE" | tee -p -a "$logfile" &>/dev/null
   if [ "$BUILDX_ADD_TAG" = "true" ] || [ -n "$REGISTRY_TAG" ] && [ -n "$ADDITIONAL_PRETTY" ]; then
     printf_blue "Adding tags: $ADDITIONAL_PRETTY"
-    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee -a "$logfile" &>/dev/null
+    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee -p -a "$logfile" &>/dev/null
   fi
   sleep 2
-  printf 'Executing: %s\n' "$set_build_command" | tee -a "$logfile" &>/dev/null
-  eval "$set_build_command" |& tee -a "$logfile" &>/dev/null || false
+  printf 'Executing: %s\n' "$set_build_command" | tee -p -a "$logfile" &>/dev/null
+  eval "$set_build_command" |& tee -p -a "$logfile" &>/dev/null || false
   return $?
 
 }
@@ -1003,16 +1003,16 @@ __run_dockermgr_script() {
   build_command="$(echo "$set_build_command" | grep '^' | grep -v '^$' | sed 's|,,| \\\n|g')"
   set_build_command="${set_build_command//,,/}"
   printf '%b%s: %b%s%b\n' "$GREEN" "Saving the build command to" "$CYAN" "$logscript_file" "$NC"
-  printf 'Saving the build command to: %s\n' "$logscript_file" | tee -a "$logfile" &>/dev/null
+  printf 'Saving the build command to: %s\n' "$logscript_file" | tee -p -a "$logfile" &>/dev/null
   __save_build_script
   printf_blue "Setting default tag to: $set_tag"
   if [ "$BUILDX_ADD_TAG" = "true" ] || [ -n "$REGISTRY_TAG" ] && [ -n "$ADDITIONAL_PRETTY" ]; then
     printf_blue "Adding tags: $ADDITIONAL_PRETTY"
-    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee -a "$logfile" &>/dev/null
+    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee -p -a "$logfile" &>/dev/null
   fi
   sleep 2
-  printf 'Executing: %s\n' "$build_command" | tee -a "$logfile" &>/dev/null
-  eval "$set_build_command" |& tee -a "$logfile" &>/dev/null || false
+  printf 'Executing: %s\n' "$build_command" | tee -p -a "$logfile" &>/dev/null
+  eval "$set_build_command" |& tee -p -a "$logfile" &>/dev/null || false
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -1022,16 +1022,16 @@ __run_buildx_script() {
   build_command="$(echo "$set_build_command" | grep '^' | grep -v '^$' | sed 's|,,| \\\n|g')"
   set_build_command="${set_build_command//,,/}"
   printf '%b%s: %b%s%b\n' "$GREEN" "Saving the build command to" "$CYAN" "$logscript_file" "$NC"
-  printf 'Saving the build command to: %s\n' "$logscript_file" | tee -a "$logfile" &>/dev/null
+  printf 'Saving the build command to: %s\n' "$logscript_file" | tee -p -a "$logfile" &>/dev/null
   __save_build_script
   printf_blue "Setting default tag to: $set_tag"
   if [ "$BUILDX_ADD_TAG" = "true" ] || [ -n "$REGISTRY_TAG" ] && [ -n "$ADDITIONAL_PRETTY" ]; then
     printf_blue "Adding tags: $ADDITIONAL_PRETTY"
-    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee -a "$logfile" &>/dev/null
+    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee -p -a "$logfile" &>/dev/null
   fi
   sleep 2
-  printf 'Executing: %s\n' "$set_build_command" | tee -a "$logfile" &>/dev/null
-  eval "$set_build_command" |& tee -a "$logfile" &>/dev/null || false
+  printf 'Executing: %s\n' "$set_build_command" | tee -p -a "$logfile" &>/dev/null
+  eval "$set_build_command" |& tee -p -a "$logfile" &>/dev/null || false
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -1041,23 +1041,23 @@ __run_build_script() {
   build_command="$(echo "$set_build_command" | grep '^' | grep -v '^$' | sed 's|,,| \\\n|g')"
   set_build_command="${set_build_command//,,/}"
   printf '%b%s: %b%s%b\n' "$GREEN" "Saving the build command to" "$CYAN" "$logscript_file" "$NC"
-  printf 'Saving the build command to: %s\n' "$logscript_file" | tee -a "$logfile" &>/dev/null
+  printf 'Saving the build command to: %s\n' "$logscript_file" | tee -p -a "$logfile" &>/dev/null
   __save_build_script
   printf_blue "Setting default tag to: $set_tag"
   if [ "$BUILDX_ADD_TAG" = "true" ] || [ -n "$REGISTRY_TAG" ] && [ -n "$ADDITIONAL_PRETTY" ]; then
     printf_blue "Adding tags: $ADDITIONAL_PRETTY"
-    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee -a "$logfile" &>/dev/null
+    printf '%s\n' "# Adding tags: $ADDITIONAL_PRETTY" | tee -p -a "$logfile" &>/dev/null
   fi
   sleep 2
-  printf 'Executing: %s\n' "$set_build_command" | tee -a "$logfile" &>/dev/null
-  eval "$set_build_command" |& tee -a "$logfile" &>/dev/null || false
+  printf 'Executing: %s\n' "$set_build_command" | tee -p -a "$logfile" &>/dev/null
+  eval "$set_build_command" |& tee -p -a "$logfile" &>/dev/null || false
   return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __save_build_script() {
   [ -d "$logscript_dir" ] || mkdir -p "$logscript_dir"
-  echo "command: $build_command" |& tee "$logscript_file" &>/dev/null
-  cat <<EOF |& tee "$logscript_file" &>/dev/null
+  echo "command: $build_command" |& tee -p "$logscript_file" &>/dev/null
+  cat <<EOF |& tee -p "$logscript_file" &>/dev/null
 #!/usr/bin/env bash
 # Build command for $tagged_name
 
@@ -1069,10 +1069,10 @@ EOF
   if [ "$BUILDX_GEN_SCRIPT" = "true" ]; then
     if [ -x "$logscript_file" ]; then
       printf_yellow "Your script has been saved: exiting"
-      echo "Your script has been saved: exiting" | tee -a "$logfile" &>/dev/null
+      echo "Your script has been saved: exiting" | tee -p -a "$logfile" &>/dev/null
       exit 0
     else
-      printf_red "Your script failed to save: exiting" | tee -a "$logfile" &>/dev/null
+      printf_red "Your script failed to save: exiting" | tee -p -a "$logfile" &>/dev/null
       exit 1
     fi
   else
@@ -1112,35 +1112,35 @@ __run_docker_build() {
   [ -n "$image_name" ] && tagged_name="$image_name" || tagged_name="$push_tag"
   if [ "$BUILDX_RUN_SCRIPT" = "true" ] && [ -f "$BUILDX_CWD/build.sh" ]; then
     printf_blue "Using $BUILDX_CWD/build.sh to build $tagged_name"
-    printf '%s\n' "# Using Using $BUILDX_CWD/build.sh to build $tagged_name" | tee -a "$logfile" &>/dev/null
+    printf '%s\n' "# Using Using $BUILDX_CWD/build.sh to build $tagged_name" | tee -p -a "$logfile" &>/dev/null
     __run_docker_script
     buildx_status=$?
   elif __is_buildx_installed; then
     printf_blue "Using docker buildx to build $tagged_name"
-    printf '%s\n' "# Using docker buildx to build $tagged_name" | tee -a "$logfile" &>/dev/null
+    printf '%s\n' "# Using docker buildx to build $tagged_name" | tee -p -a "$logfile" &>/dev/null
     __run_buildx_script
     buildx_status=$?
   else
     printf_blue "Using docker build to build $tagged_name"
-    printf '%s\n' "# Using docker build to build $tagged_name" | tee -a "$logfile" &>/dev/null
+    printf '%s\n' "# Using docker build to build $tagged_name" | tee -p -a "$logfile" &>/dev/null
     __run_build_script
     buildx_status=$?
     if [ "$buildx_status" = 0 ]; then
       if __docker_push; then
-        printf '%s\n' "# Pushing of $tagged_name completed on : $(date +'%Y-%m-%d at %H:%M')" | tee -a "$logfile" &>/dev/null
+        printf '%s\n' "# Pushing of $tagged_name completed on : $(date +'%Y-%m-%d at %H:%M')" | tee -p -a "$logfile" &>/dev/null
       else
-        printf '%s\n' "# Pushing of $tagged_name failed on : $(date +'%Y-%m-%d at %H:%M')" | tee -a "$logfile" &>/dev/null
+        printf '%s\n' "# Pushing of $tagged_name failed on : $(date +'%Y-%m-%d at %H:%M')" | tee -p -a "$logfile" &>/dev/null
       fi
     fi
   fi
   if [ $buildx_status = 0 ]; then
-    printf '%s\n' "# Finished building $tagged_name $ADDITIONAL_PRETTY" | tee -a "$logfile" &>/dev/null
+    printf '%s\n' "# Finished building $tagged_name $ADDITIONAL_PRETTY" | tee -p -a "$logfile" &>/dev/null
     buildx_status=0
   else
-    printf '%s\n' "# Building of $tagged_name has failed" | tee -a "$logfile" &>/dev/null
+    printf '%s\n' "# Building of $tagged_name has failed" | tee -p -a "$logfile" &>/dev/null
     buildx_status="${buildx_status:-10}"
   fi
-  printf '\n%s\n' "buildx has Finished on: $(date +'%Y-%m-%d at %H:%M')" | tee -a "$logfile" &>/dev/null
+  printf '\n%s\n' "buildx has Finished on: $(date +'%Y-%m-%d at %H:%M')" | tee -p -a "$logfile" &>/dev/null
   __remove_pid
   return $buildx_status
 }
@@ -1273,14 +1273,14 @@ __execute_buildx() {
     if __docker pull "$push_tag" &>/dev/null; then
       printf_green "Successfully pulled $push_tag"
       notify_message+="Successfully pulled $push_tag|"
-      printf '\n%s\n' "# Successfully pulled $push_tag on : $(date +'%Y-%m-%d at %H:%M')" | tee -a "$logfile" &>/dev/null
+      printf '\n%s\n' "# Successfully pulled $push_tag on : $(date +'%Y-%m-%d at %H:%M')" | tee -p -a "$logfile" &>/dev/null
       __docker rmi "$push_tag" &>/dev/null
       __docker rmi "$pretty_name" &>/dev/null
       buildxexitCode=1
     else
       printf_red "Failed to pull $push_tag" >&2
       notify_message+="Failed to pull $push_tag|"
-      printf '\n%s\n' "# Failed to pull $push_tag on : $(date +'%Y-%m-%d at %H:%M')" | tee -a "$logfile" &>/dev/null
+      printf '\n%s\n' "# Failed to pull $push_tag on : $(date +'%Y-%m-%d at %H:%M')" | tee -p -a "$logfile" &>/dev/null
       buildxexitCode=2
     fi
   else
@@ -1290,8 +1290,8 @@ __execute_buildx() {
   fi
   notify_message="$(echo "$notify_message" | tr '|' '\n')"
   __notifications "${notify_message[@]}" &>/dev/null &
-  printf "# Exit status: %s\n" "$buildxexitCode" | tee -a "$logfile" &>/dev/null
-  printf '###############################################################################\n\n' | tee -a "$logfile" &>/dev/null
+  printf "# Exit status: %s\n" "$buildxexitCode" | tee -p -a "$logfile" &>/dev/null
+  printf '###############################################################################\n\n' | tee -p -a "$logfile" &>/dev/null
   [ -f "$BUILDX_PID_FILE" ] && rm -Rf "$BUILDX_PID_FILE"
   [ "$buildxexitCode" = "1" ] && exitCode=0 || exitCode=$buildxexitCode
   return $exitCode
@@ -1525,7 +1525,7 @@ while :; do
     export SCRIPT_OPTS="--debug"
     export _DEBUG="on"
     __devnull() { tee || return 1; }
-    __devnull2() { eval "$@" |& tee || return 1; }
+    __devnull2() { eval "$@" |& tee -p || return 1; }
     ;;
   --completions)
     if [ "$2" = "short" ]; then
diff --git a/sources/tdrop b/sources/tdrop
--- a/sources/tdrop
+++ b/sources/tdrop
@@ -70,13 +70,13 @@ See man page for more details.
 }
 
 error() {
-  echo >&2 "Error: $*" | tee -a "$LOG_FILE"
+  echo >&2 "Error: $*" | tee -p -a "$LOG_FILE"
   exit 1
 }
 
 debug() {
   if $debug; then
-    echo >&2 "Debug: $*" | tee -a "$LOG_FILE"
+    echo >&2 "Debug: $*" | tee -p -a "$LOG_FILE"
   fi
 }
 
