🗃️ Rewrite gen-dockerfile 🗃️
bin/gen-dockerfile
completions/_gen-dockerfile_completions
man/gen-dockerfile.1
templates/dockerfiles/

diff --git a/completions/_gen-dockerfile_completions b/completions/_gen-dockerfile_completions
--- a/completions/_gen-dockerfile_completions
+++ b/completions/_gen-dockerfile_completions
@@ -1,125 +1,129 @@
 #!/usr/bin/env bash
+# shellcheck shell=bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version           :  202207061337-git
-# @Author            :  Jason Hempstead
-# @Contact           :  jason@casjaysdev.pro
-# @License           :  WTFPL
-# @ReadME            :  gen-dockerfile --help
-# @Copyright         :  Copyright: (c) 2022 Jason Hempstead, Casjays Developments
-# @Created           :  Wednesday, Jul 06, 2022 13:37 EDT
-# @File              :  gen-dockerfile
-# @Description       :
-# @TODO              :
-# @Other             :
-# @Resource          :
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
-_gen-dockerfile() {
-  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${1:-$CONFDIR}'##g' | grep '^' || return 1; }
-  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
-  local cur prev words cword opts split
-  local cur="${COMP_WORDS[$COMP_CWORD]}"
-  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
-  local CONFFILE="settings.conf"
-  local CONFDIR="$HOME/.config/myscripts/gen-dockerfile"
-  local SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/gen-dockerfile}"
-  #local SEARCHCMD="$(___findcmd "$SEARCHDIR/" "d" "1" | sort -u)"
-  local SHOW_COMP_OPTS=""
-  local FILEDIR=""
-  local OPTS=""
-  local LONGOPTS="--completions --config --debug --dir --help --options --raw --version --silent  "
-  local LONGOPTS+="--dockerfile --startup --nogit --template --image --repo --tag --pkmgr --distro-name "
-  local LONGOPTS+="--distro-tag --add-tags --x11 --init --apache --nginx --mysql --postgres --php --application "
-  local SHORTOPTS=""
-  local ARRAY="alpine archlinux debian ubuntu almalinux scratch xorg web"
-
+##@Version           :  202308291821-git
+# @@Author           :  Jason Hempstead
+# @@Contact          :  jason@casjaysdev.pro
+# @@License          :  WTFPL
+# @@ReadME           :  gen-dockerfile --help
+# @@Copyright        :  Copyright: (c) 2023 Jason Hempstead, Casjays Developments
+# @@Created          :  Tuesday, Aug 29, 2023 18:21 EDT
+# @@File             :  gen-dockerfile
+# @@Description      :  Create a Dockerfile
+# @@Changelog        :
+# @@TODO             :  Rewite/Cleanup variables
+# @@Other            :
+# @@Resource         :
+# @@Terminal App     :  no
+# @@sudo/root        :  no
+# @@Template         :  completions/system
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# shellcheck disable=SC2016
+# shellcheck disable=SC2031
+# shellcheck disable=SC2120
+# shellcheck disable=SC2155
+# shellcheck disable=SC2199
+# shellcheck disable=SC2317
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+_gen-dockerfile_completion() {
+  #####################################################################
+  local cur prev words cword opts split CONFDIR="" CONFFILE="" SEARCHDIR=""
+  local SHOW_COMP_OPTS="" NOOPTS="" SHORTOPTS="" LONGOPTS="" ARRAY="" LIST="" SHOW_COMP_OPTS_SEP=""
+  #####################################################################
   _init_completion || return
-
-  if [[ "$SHOW_COMP_OPTS" != "" ]]; then
-    local SHOW_COMP_OPTS_SEP="${SHOW_COMP_OPTS//,/ }"
+  #####################################################################
+  ___jq() { jq -rc "$@" 2>/dev/null; }
+  ___sed_env() { sed 's|"||g;s|.*=||g' 2>/dev/null || false; }
+  ___ls() { ls -A "$1" 2>/dev/null | grep -v '^$' | grep '^' || false; }
+  ___curl() { curl -q -LSsf --max-time 1 --retry 0 "$@" 2>/dev/null || return 1; }
+  ___grep_file() { grep --no-filename -vsR '#' "$@" 2>/dev/null | grep '^' || return 1; }
+  ___find_cmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | grep '^' || return 1; }
+  ___find_rel() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} -printf "%P\n" 2>/dev/null | grep '^' || return 1; }
+  ___grep_env() { GREP_COLORS="" grep -sE '^.*=*..*$' "$1" 2>/dev/null | grep -v '^#' | grep "${2:-^}" | sed 's|"||g' 2>/dev/null | grep '^' || false; }
+  #####################################################################
+  cur="${COMP_WORDS[$COMP_CWORD]}"
+  prev="${COMP_WORDS[$COMP_CWORD - 1]}"
+  #####################################################################
+  CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
+  #####################################################################
+  CONFFILE="settings.conf"
+  CONFDIR="$HOME/.config/myscripts/gen-dockerfile"
+  SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/gen-dockerfile}"
+  #####################################################################
+  SHOW_COMP_OPTS=""
+  #####################################################################
+  SHORTOPTS=""
+  SHORTOPTS+=""
+  #####################################################################
+  LONGOPTS="--completions --config --debug --dir --help --options --raw --version --silent "
+  LONGOPTS+="--dockerfile --startup --nogit --template --image --org --tag --pkmgr --distro-name "
+  LONGOPTS+="--distro-tag --add-tags --x11 --init --apache --nginx --mysql --postgres --php --application "
+  #####################################################################
+  #NOOPTS="--no-* "
+  #####################################################################
+  ARRAY="alpine arch debian ubuntu rhel scratch xorg web"
+  ARRAY+=""
+  #####################################################################
+  LIST=""
+  LIST+=""
+  #####################################################################
+  if [ "$SHOW_COMP_OPTS" != "" ]; then
+    SHOW_COMP_OPTS_SEP="${SHOW_COMP_OPTS//,/ }"
     compopt -o $SHOW_COMP_OPTS_SEP
   fi
-
+  #####################################################################
   if [[ ${cur} == --* ]]; then
     COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
-    return
   elif [[ ${cur} == -* ]]; then
-    COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
-    return
+    if [ -n "$SHORTOPTS" ]; then
+      COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
+    else
+      COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
+    fi
   else
-    case "${COMP_WORDS[1]:-$prev}" in
-    --options)
-      local prev="--options"
-      COMPREPLY=($(compgen -W '' -- "${cur}"))
+    case "${prev:-${COMP_WORDS[1]}}" in
+    --completions)
+      prev=""
+      COMPREPLY=($(compgen -W 'long short list array' -- "$cur"))
       ;;
-
-    --config)
-      local prev="--config"
-      COMPREPLY=($(compgen -W '' -- "${cur}"))
+    --config | --debug | --help | --options | --raw | --version)
+      COMPREPLY=($(compgen -W '${ARRAY} ${LONGOPTS} ${SHORTOPTS}' -- ${cur}))
+      return 0
       ;;
-
-    --help)
-      prev="--help"
-      COMPREPLY=($(compgen -W '' -- "${cur}"))
+    --no-*)
+      COMPREPLY=($(compgen -W '${NOOPTS}' -- "$cur"))
+      return 0
       ;;
-
-    --version)
-      local prev="--version"
-      COMPREPLY=($(compgen -W '' -- "${cur}"))
-      ;;
-
     --dir)
-      local prev="dir"
-      _filedir
-      return
+      prev="dir"
+      [ "$cword" -le 2 ] && _filedir -d || COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
       ;;
-
+    --template)
+      prev="dir"
+      COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
+      ;;
+    --pkmgr)
+      [ "$cword" -le 2 ] && _filedir -d || COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
+      ;;
     *)
-      if [[ -n "$FILEDIR" ]]; then _filedir; fi
-      # if [[ $cword -gt 2 ]]; then
-      #   return
-      # elif [[ $cword == 2 ]]; then
-      #   _filedir
-      #   compopt -o nospace
-      #   return
-      # elif [[ $cword -eq 1 ]]; then
-      #   COMPREPLY=($(compgen -W '{a..z}{a..z}' -- "${cur}"))
-      #   compopt -o nospace
-      #   return
-      if [[ "$ARRAY" = "show__none" ]]; then
-        COMPREPLY=($(compgen -W '' -- "${cur}"))
-      elif [[ "$ARRAY" = "show__filedir" ]]; then
-        _filedir
-      elif [[ "$ARRAY" = "show__commands" ]]; then
-        COMPREPLY=($(compgen -c -- "${cur}"))
-      elif [ "$ARRAY" != "" ]; then
-        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
-      elif [ -n "$OPTS" ]; then
-        COMPREPLY=($(compgen -W '${OPTS}' -- "${cur}"))
-      else
-        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
-      # elif [[ $cword -gt 2 ]]; then
-      #   return
-      # elif [[ $cword == 2 ]]; then
-      #   _filedir
-      #   compopt -o nospace
-      #   return
-      # elif [[ $cword -eq 1 ]]; then
-      #   COMPREPLY=($(compgen -W '{a..z}{a..z}' -- "${cur}"))
-      #   compopt -o nospace
-      #   return
-      fi
+      COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
+      return 0
       ;;
     esac
   fi
   #
-  # [[ ${cword} == 2 ]] && _filedir && compopt -o nospace
-  # [[ $COMP_CWORD -eq 2 ] && COMPREPLY=($(compgen -W '{a..z} {A..Z} {0..9}' -o nospace -- "${cur}"))
-  # [[ $COMP_CWORD -eq 3 ] && COMPREPLY=($(compgen -W '$(_filedir)' -o filenames -o dirnames -- "${cur}"))
-  # [[ $COMP_CWORD -gt 3 ] && COMPREPLY=($(compgen -W '' -- "${cur}"))
-  #prev=""
-  #compopt -o nospace
-  $split && return
+  # [ "${ARRAY}" = "show__filedir" ] && _filedir
+  # [ ${cword} = 2 ] && _filedir && compopt -o nospace
+  # [ "${ARRAY}" != "" ] && COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
+  # [ "${ARRAY}" = "show__none" ] && COMPREPLY=($(compgen -W '' -- "${cur}"))
+  # [ "${ARRAY}" = "show__commands" ] && COMPREPLY=($(compgen -c -- "${cur}"))
+  # [ $COMP_CWORD -eq 2 ] && COMPREPLY=($(compgen -W '{a..z} {A..Z} {0..9}' -o nospace -- "${cur}"))
+  # [ $COMP_CWORD -eq 3 ] && COMPREPLY=($(compgen -W '$(_filedir)' -o filenames -o dirnames -- "${cur}"))
+  # [ $COMP_CWORD -gt 3 ] && COMPREPLY=($(compgen -W '' -- "${cur}"))
+  # compopt -o nospace
 } &&
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # enable completions
-  complete -F _gen-dockerfile gen-dockerfile
+  complete -F _gen-dockerfile_completion -o default gen-dockerfile
+
+# ex: ts=2 sw=2 et filetype=sh
